#pragma once

typedef enum EFactionRelationship {
	FACTION_RELATIONSHIP_NULL,
	FACTION_RELATIONSHIP_ALLY,
	FACTION_RELATIONSHIP_FRIENDLY,
	FACTION_RELATIONSHIP_LIKED,
	FACTION_RELATIONSHIP_NEUTRAL,
	FACTION_RELATIONSHIP_DISLIKED,
	FACTION_RELATIONSHIP_HOSTILE,
	FACTION_RELATIONSHIP_ATWAR
} EFactionRelationship;