Techstorm-rivalry: C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Globals.h File Reference
Globals.h File Reference
#include "raylib.h"
#include "raymath.h"
#include "rlgl.h"
#include <vector>
#include <stdio.h>
#include <stdlib.h>
Classes
struct intVec2
struct intVec3
struct DualVec3
struct CubeVerticies
struct TriVert
Macros
#define AUTHOR MutedTea
#define VERSION "0.0.1"
#define CLITERAL(type) (type)
#define DEFAULT_NEAR_CULL_DISTANCE 0.01
#define DEFAULT_FAR_CULL_DISTANCE 50000.0
#define NUM_FRAMES 3
#define MAX_INSTANCES 10000
#define MAX_SHADERS 10
#define SKYBOX_SIZE 1.0f
#define WORLD_SIZE 100
#define BLOCK_SIZE 1
#define DESPAWN_DISTANCE 1000.0f
#define FILTER_BILINEAR TEXTURE_FILTER_BILINEAR
#define WRAP_CLAMP TEXTURE_WRAP_CLAMP
#define UNIFORM_VEC4 SHADER_UNIFORM_VEC4
#define UNIFORM_VEC3 SHADER_UNIFORM_VEC3
#define UNIFORM_INT SHADER_UNIFORM_INT
#define UNIFORM_FLOAT SHADER_UNIFORM_FLOAT
#define MAP_CUBEMAP SHADER_LOC_MAP_CUBEMAP
#define MAP_IRRADIANCE SHADER_LOC_MAP_IRRADIANCE
#define LOC_VECTOR_VIEW LOC_VECTOR_VIEW
#define LOG_WARN LOG_WARNING
#define GLSL_VERSION 100
Functions
Model GetDefaultModel ()
void SetDefaultModel (Model model)
CubeVerticies CubeVertZero ()
CubeVerticies CubeVertOne ()
Mesh GenMeshCustom (TriVert verts)
TextureCubemap GenTextureCubemap (Shader shader, Texture2D panorama, int size, int format)
bool CheckCollisionRayBox (Ray ray, BoundingBox box, float *outDistance)
Vector3 CameraToWorld (Camera3D camera)
float Mean (const std::vector< float > &data)
Vector3 Vector3RandomControlled (Vector3 start, int minDeviation, int maxDeviation)
float Invert (float Value)
Vector3 Vector3Random (int min, int max)
Vector3 RoundVec3 (Vector3 Target)
Vector3 Vector3MaxPos ()
Vector3 Vector3RandomEx (Vector3 min, Vector3 max)
Macro Definition Documentation
AUTHOR
#define AUTHOR MutedTea
Definition at line 5 of file Globals.h.
BLOCK_SIZE
#define BLOCK_SIZE 1
Definition at line 59 of file Globals.h.
CLITERAL
#define CLITERAL (type) (type)
Definition at line 25 of file Globals.h.
DEFAULT_FAR_CULL_DISTANCE
#define DEFAULT_FAR_CULL_DISTANCE 50000.0
Definition at line 36 of file Globals.h.
DEFAULT_NEAR_CULL_DISTANCE
#define DEFAULT_NEAR_CULL_DISTANCE 0.01
Definition at line 33 of file Globals.h.
DESPAWN_DISTANCE
#define DESPAWN_DISTANCE 1000.0f
Definition at line 62 of file Globals.h.
FILTER_BILINEAR
#define FILTER_BILINEAR TEXTURE_FILTER_BILINEAR
Definition at line 72 of file Globals.h.
GLSL_VERSION
#define GLSL_VERSION 100
Definition at line 89 of file Globals.h.
LOC_VECTOR_VIEW
#define LOC_VECTOR_VIEW LOC_VECTOR_VIEW
Definition at line 82 of file Globals.h.
LOG_WARN
#define LOG_WARN LOG_WARNING
Definition at line 83 of file Globals.h.
MAP_CUBEMAP
#define MAP_CUBEMAP SHADER_LOC_MAP_CUBEMAP
Definition at line 80 of file Globals.h.
MAP_IRRADIANCE
#define MAP_IRRADIANCE SHADER_LOC_MAP_IRRADIANCE
Definition at line 81 of file Globals.h.
MAX_INSTANCES
#define MAX_INSTANCES 10000
Definition at line 42 of file Globals.h.
MAX_SHADERS
#define MAX_SHADERS 10
Definition at line 45 of file Globals.h.
NUM_FRAMES
#define NUM_FRAMES 3
Definition at line 39 of file Globals.h.
SKYBOX_SIZE
#define SKYBOX_SIZE 1.0f
Definition at line 53 of file Globals.h.
UNIFORM_FLOAT
#define UNIFORM_FLOAT SHADER_UNIFORM_FLOAT
Definition at line 79 of file Globals.h.
UNIFORM_INT
#define UNIFORM_INT SHADER_UNIFORM_INT
Definition at line 78 of file Globals.h.
UNIFORM_VEC3
#define UNIFORM_VEC3 SHADER_UNIFORM_VEC3
Definition at line 77 of file Globals.h.
UNIFORM_VEC4
#define UNIFORM_VEC4 SHADER_UNIFORM_VEC4
Definition at line 76 of file Globals.h.
VERSION
#define VERSION "0.0.1"
Definition at line 9 of file Globals.h.
WORLD_SIZE
#define WORLD_SIZE 100
Definition at line 58 of file Globals.h.
WRAP_CLAMP
#define WRAP_CLAMP TEXTURE_WRAP_CLAMP
Definition at line 73 of file Globals.h.
Function Documentation
CameraToWorld()
Vector3 CameraToWorld (Camera3D camera) extern
Definition at line 167 of file Globals.cpp.
{
    float distance;
    // Calculate the ray from the camera to the mouse position
    Vector2 mousePos = GetMousePosition();
    Vector3 mousePos3 = { mousePos.x, mousePos.y, 0 };
    // Get the direction vector of the ray
    Vector3 rayDirection =
        Vector3Normalize(Vector3Subtract(mousePos3, camera.position));
    // Multiply the direction vector with a scalar value to increase the length of
    // the ray
    float rayLength = 40.0f;
    rayDirection = Vector3Scale(rayDirection, rayLength);
    // Create the ray with the modified direction
    Ray ray = { camera.position, rayDirection };
    // Calculate the distance from the camera to the ground plane
    distance = -(camera.position.y / ray.position.y);
    // Calculate the point where the ray intersects the ground plane
    Vector3 groundPoint =
        Vector3Add(camera.position, Vector3Scale(ray.position, distance));
    return groundPoint;
}
References GetMousePosition(), Camera3D::position, Ray::position, ray, Vector3Add(), Vector3Normalize(), Vector3Scale(), Vector3Subtract(), Vector2::x, Vector2::y, and Vector3::y.
CheckCollisionRayBox()
bool CheckCollisionRayBox (Ray ray, BoundingBox box, float * outDistance) extern
Definition at line 80 of file Globals.cpp.
{
    // Compute the inverse of the ray direction
    Vector3 invDir = { 1.0f / ray.direction.x, 1.0f / ray.direction.y,
                      1.0f / ray.direction.z };
    // Compute the sign of the inverse direction
    int signX = (invDir.x < 0.0f) ? 1 : 0;
    int signY = (invDir.y < 0.0f) ? 1 : 0;
    int signZ = (invDir.z < 0.0f) ? 1 : 0;
    // Compute the min and max values for each axis
    float tmin = (box.min.x - ray.position.x) * invDir.x;
    float tmax = (box.max.x - ray.position.x) * invDir.x;
    float tymin = (box.min.y - ray.position.y) * invDir.y;
    float tymax = (box.max.y - ray.position.y) * invDir.y;
    // Swap the min and max values if necessary
    if (tmin > tmax)
    {
        float temp = tmin;
        tmin = tmax;
        tmax = temp;
    }
    if (tymin > tymax)
    {
        float temp = tymin;
        tymin = tymax;
        tymax = temp;
    }
    // Check for a miss
    if ((tmin > tymax) || (tymin > tmax))
    {
        return false;
    }
    // Compute the final min and max values for each axis
    if (tymin > tmin)
    {
        tmin = tymin;
    }
    if (tymax < tmax)
    {
        tmax = tymax;
    }
    float tzmin = (box.min.z - ray.position.z) * invDir.z;
    float tzmax = (box.max.z - ray.position.z) * invDir.z;
    // Swap the min and max values if necessary
    if (tzmin > tzmax)
    {
        float temp = tzmin;
        tzmin = tzmax;
        tzmax = temp;
    }
    // Check for a miss
    if ((tmin > tzmax) || (tzmin > tmax))
    {
        return false;
    }
    // Compute the final min and max values for each axis
    if (tzmin > tmin)
    {
        tmin = tzmin;
    }
    if (tzmax < tmax)
    {
        tmax = tzmax;
    }
    // Store the distance to the box in the output variable
    if (outDistance)
    {
        *outDistance = tmin;
    }
    // The ray intersects the box
    return true;
}
References Ray::direction, BoundingBox::max, BoundingBox::min, Ray::position, ray, Vector3::x, Vector3::y, and Vector3::z.
CubeVertOne()
CubeVerticies CubeVertOne () extern
Definition at line 24 of file Globals.cpp.
{
    return CubeVerticies{ 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };
}
CubeVertZero()
CubeVerticies CubeVertZero () extern
Returns a CubeVerticies object with all coordinates initialized to 0.0f.
Definition at line 19 of file Globals.cpp.
{
    return CubeVerticies{ 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f };
}
GenMeshCustom()
Mesh GenMeshCustom (TriVert verts) extern
Definition at line 34 of file Globals.cpp.
{
    // Initialize a new mesh
    Mesh mesh = { 0 };
    mesh.triangleCount = 1;
    mesh.vertexCount = mesh.triangleCount * 3;
    // Allocate memory for vertices, texture coordinates, and normals
    mesh.vertices = (float*)MemAlloc(mesh.vertexCount * 3 * sizeof(float));  // 3 vertices, 3 coordinates each (x, y, z)
    mesh.texcoords = (float*)MemAlloc(mesh.vertexCount * 2 * sizeof(float));  // 3 vertices, 2 coordinates each (x, y)
    mesh.normals = (float*)MemAlloc(mesh.vertexCount * 3 * sizeof(float));   // 3 vertices, 3 coordinates each (x, y, z)
    // Set vertex data
    mesh.vertices[0] = verts.v1.x;
    mesh.vertices[1] = verts.v2.x;
    mesh.vertices[2] = verts.v3.x;
    mesh.normals[0] = verts.v1.x;
    mesh.normals[1] = verts.v2.x;
    mesh.normals[2] = verts.v3.x;
    mesh.texcoords[0] = 0;
    mesh.texcoords[1] = 0;
    mesh.vertices[3] = verts.v1.y;
    mesh.vertices[4] = verts.v2.y;
    mesh.vertices[5] = verts.v3.y;
    mesh.normals[3] = verts.v1.y;
    mesh.normals[4] = verts.v2.y;
    mesh.normals[5] = verts.v3.y;
    mesh.texcoords[2] = 0.5f;
    mesh.texcoords[3] = 1.0f;
    mesh.vertices[6] = verts.v1.z;
    mesh.vertices[7] = verts.v2.z;
    mesh.vertices[8] = verts.v3.z;
    mesh.normals[6] = verts.v3.z;
    mesh.normals[7] = verts.v3.z;
    mesh.normals[8] = verts.v3.z;
    mesh.texcoords[4] = 1;
    mesh.texcoords[5] = 0;
    // Upload mesh data from CPU (RAM) to GPU (VRAM) memory
    UploadMesh(&mesh, false);
    return mesh;
}
References MemAlloc(), Mesh::normals, Mesh::texcoords, Mesh::triangleCount, UploadMesh(), TriVert::v1, TriVert::v2, TriVert::v3, Mesh::vertexCount, Mesh::vertices, Vector3::x, Vector3::y, and Vector3::z.
GenTextureCubemap()
TextureCubemap GenTextureCubemap (Shader shader, Texture2D panorama, int size, int format) extern
Definition at line 289 of file Globals.cpp.
{
    TextureCubemap cubemap = { 0 };
    rlDisableBackfaceCulling(); // Disable backface culling to render inside the
    // cube
// STEP 1: Setup framebuffer
//------------------------------------------------------------------------------------------
    unsigned int rbo = rlLoadTextureDepth(size, size, true);
    cubemap.id = rlLoadTextureCubemap(0, size, format);
    unsigned int fbo = rlLoadFramebuffer(size, size);
    rlFramebufferAttach(fbo, rbo, RL_ATTACHMENT_DEPTH, RL_ATTACHMENT_RENDERBUFFER,
        0);
    rlFramebufferAttach(fbo, cubemap.id, RL_ATTACHMENT_COLOR_CHANNEL0,
        RL_ATTACHMENT_CUBEMAP_POSITIVE_X, 0);
    // Check if framebuffer is complete with attachments (valid)
    if (rlFramebufferComplete(fbo))
        TraceLog(LOG_INFO, "FBO: [ID %i] Framebuffer object created successfully",
            fbo);
    //------------------------------------------------------------------------------------------
    // STEP 2: Draw to framebuffer
    //------------------------------------------------------------------------------------------
    // NOTE: Shader is used to convert HDR equirectangular environment map to
    // cubemap equivalent (6 faces)
    rlEnableShader(shader.id);
    // Define projection matrix and send it to shader
    Matrix matFboProjection = MatrixPerspective(
        90.0 * DEG2RAD, 1.0, RL_CULL_DISTANCE_NEAR, RL_CULL_DISTANCE_FAR);
    rlSetUniformMatrix(shader.locs[SHADER_LOC_MATRIX_PROJECTION],
        matFboProjection);
    // Define view matrix for every side of the cubemap
    Matrix fboViews[6] = {
        MatrixLookAt(Vector3{0.0f, 0.0f, 0.0f}, Vector3{1.0f, 0.0f, 0.0f},
                     Vector3{0.0f, -1.0f, 0.0f}),
        MatrixLookAt(Vector3{0.0f, 0.0f, 0.0f}, Vector3{-1.0f, 0.0f, 0.0f},
                     Vector3{0.0f, -1.0f, 0.0f}),
        MatrixLookAt(Vector3{0.0f, 0.0f, 0.0f}, Vector3{0.0f, 1.0f, 0.0f},
                     Vector3{0.0f, 0.0f, 1.0f}),
        MatrixLookAt(Vector3{0.0f, 0.0f, 0.0f}, Vector3{0.0f, -1.0f, 0.0f},
                     Vector3{0.0f, 0.0f, -1.0f}),
        MatrixLookAt(Vector3{0.0f, 0.0f, 0.0f}, Vector3{0.0f, 0.0f, 1.0f},
                     Vector3{0.0f, -1.0f, 0.0f}),
        MatrixLookAt(Vector3{0.0f, 0.0f, 0.0f}, Vector3{0.0f, 0.0f, -1.0f},
                     Vector3{0.0f, -1.0f, 0.0f}) };
    rlViewport(0, 0, size, size); // Set viewport to current fbo dimensions
    // Activate and enable texture for drawing to cubemap faces
    rlActiveTextureSlot(0);
    rlEnableTexture(panorama.id);
    for (int i = 0; i < 6; i++)
    {
        // Set the view matrix for the current cube face
        rlSetUniformMatrix(shader.locs[SHADER_LOC_MATRIX_VIEW], fboViews[i]);
        // Select the current cubemap face attachment for the fbo
        // WARNING: This function by default enables->attach->disables fbo!!!
        rlFramebufferAttach(fbo, cubemap.id, RL_ATTACHMENT_COLOR_CHANNEL0,
            RL_ATTACHMENT_CUBEMAP_POSITIVE_X + i, 0);
        rlEnableFramebuffer(fbo);
        // Load and draw a cube, it uses the current enabled texture
        rlClearScreenBuffers();
        rlLoadDrawCube();
        // ALTERNATIVE: Try to use internal batch system to draw the cube instead of
        // rlLoadDrawCube for some reason this method does not work, maybe due to
        // cube triangles definition? normals pointing out?
        // TODO: Investigate this issue...
        // rlSetTexture(panorama.id); // WARNING: It must be called after enabling
        // current framebuffer if using internal batch system!
        // rlClearScreenBuffers();
        // DrawCubeV(Vector3Zero(), Vector3One(), WHITE);
        // rlDrawRenderBatchActive();
    }
    //------------------------------------------------------------------------------------------
    // STEP 3: Unload framebuffer and reset state
    //------------------------------------------------------------------------------------------
    rlDisableShader();        // Unbind shader
    rlDisableTexture();       // Unbind texture
    rlDisableFramebuffer();   // Unbind framebuffer
    rlUnloadFramebuffer(fbo); // Unload framebuffer (and automatically attached
    // depth texture/renderbuffer)
// Reset viewport dimensions to default
    rlViewport(0, 0, rlGetFramebufferWidth(), rlGetFramebufferHeight());
    rlEnableBackfaceCulling();
    //------------------------------------------------------------------------------------------
    cubemap.width = size;
    cubemap.height = size;
    cubemap.mipmaps = 1;
    cubemap.format = format;
    return cubemap;
}
References DEG2RAD, Texture::format, Texture::height, Texture::id, Shader::id, Shader::locs, LOG_INFO, MatrixLookAt(), MatrixPerspective(), Texture::mipmaps, RL_ATTACHMENT_COLOR_CHANNEL0, RL_ATTACHMENT_CUBEMAP_POSITIVE_X, RL_ATTACHMENT_DEPTH, RL_ATTACHMENT_RENDERBUFFER, RL_CULL_DISTANCE_FAR, RL_CULL_DISTANCE_NEAR, rlActiveTextureSlot(), rlClearScreenBuffers(), rlDisableBackfaceCulling(), rlDisableFramebuffer(), rlDisableShader(), rlDisableTexture(), rlEnableBackfaceCulling(), rlEnableFramebuffer(), rlEnableShader(), rlEnableTexture(), rlFramebufferAttach(), rlFramebufferComplete(), rlGetFramebufferHeight(), rlGetFramebufferWidth(), rlLoadDrawCube(), rlLoadFramebuffer(), rlLoadTextureCubemap(), rlLoadTextureDepth(), rlSetUniformMatrix(), rlUnloadFramebuffer(), rlViewport(), SHADER_LOC_MATRIX_PROJECTION, SHADER_LOC_MATRIX_VIEW, TraceLog(), and Texture::width.
GetDefaultModel()
Model GetDefaultModel () extern
Definition at line 7 of file Globals.cpp.
{
    return defaultModel;
}
Invert()
float Invert (float Value) extern
Definition at line 260 of file Globals.cpp.
{
    return -Value;
}
Mean()
float Mean (const std::vector< float > & data) extern
Definition at line 195 of file Globals.cpp.
{
    float result = 0.0;
    for (unsigned int i = 1; i < data.size(); i++)
    {
        result += data[i - 1] + data[i];
    }
    return result / data.size();
}
RoundVec3()
Vector3 RoundVec3 (Vector3 Target) extern
Definition at line 272 of file Globals.cpp.
{
    return Vector3{
        (float)round(Target.x), (float)round(Target.y), (float)round(Target.z) };
}
References Vector3::x, Vector3::y, and Vector3::z.
SetDefaultModel()
void SetDefaultModel (Model model) extern
Definition at line 12 of file Globals.cpp.
{
    defaultModel = model;
}
Vector3MaxPos()
Vector3 Vector3MaxPos () extern
Definition at line 278 of file Globals.cpp.
{
    return Vector3{ WORLD_SIZE, WORLD_SIZE, WORLD_SIZE };
}
References WORLD_SIZE.
Vector3Random()
Vector3 Vector3Random (int min, int max) extern
Definition at line 265 of file Globals.cpp.
{
    return Vector3{ static_cast<float>(GetRandomValue(min, max)),
                     static_cast<float>(GetRandomValue(min, max)),
                     static_cast<float>(GetRandomValue(min, max)) };
}
References GetRandomValue().
Vector3RandomControlled()
Vector3 Vector3RandomControlled (Vector3 start, int minDeviation, int maxDeviation) extern
Definition at line 205 of file Globals.cpp.
{
    Vector3 result = start;
    int roll = GetRandomValue(1, 3);
    int deviationRoll = GetRandomValue(0, 1);
    if (roll == 1)
    {
        result.x += (float)GetRandomValue(minDeviation, maxDeviation) + minDeviation;
        result.y += minDeviation;
        result.z += minDeviation;
        if (deviationRoll == 1)
        {
            result.x += minDeviation;
        }
        else
        {
            result.x -= minDeviation;
        }
    }
    else if (roll == 2)
    {
        result.y += (float)GetRandomValue(minDeviation, maxDeviation);
        result.z += minDeviation;
        if (deviationRoll == 1)
        {
            result.y += minDeviation;
        }
        else
        {
            result.y -= minDeviation;
        }
    }
    else
    {
        result.x += minDeviation;
        result.y += minDeviation;
        result.z += minDeviation;
        if (deviationRoll == 1)
        {
            result.z += (float)GetRandomValue(minDeviation, maxDeviation);
        }
        else
        {
            result.z -= (float)GetRandomValue(minDeviation, maxDeviation);
        }
    }
    return result;
}
References GetRandomValue(), Vector3::x, Vector3::y, and Vector3::z.
Vector3RandomEx()
Vector3 Vector3RandomEx (Vector3 min, Vector3 max) extern
Definition at line 283 of file Globals.cpp.
{
    return Vector3{ (float)GetRandomValue(min.x, max.x), (float)GetRandomValue(min.y, max.y), (float)GetRandomValue(min.z, max.z) };
}
References GetRandomValue(), Vector3::x, Vector3::y, and Vector3::z.