Techstorm-rivalry: ButtonR Class Reference
ButtonR Class Reference
#include <Button.h>
Public Member Functions
ButtonR (string text, float x, float y)
void draw ()
int update ()
void buildBtn ()
void setFontSize (float fontSize)
void setFontSizeNoResize (float fontSize)
void setText (string text)
void setTextNoResize (string text)
void setTextPosition (float x, float y)
void setBtnPosition (float btnX, float btnY)
void setBtnSize (float btnWidth, float btnHeight)
bool IsClicked ()
Public Attributes
Font font = GetFontDefault()
float fontSize = 32
float fontSpacing = 3.0f
Color fontColor = BLACK
bool isRayFont = true
string text = "Button"
Vector2 textSize = MeasureTextEx(font, text.c_str(), fontSize, fontSpacing)
Vector2 oneCharSize = MeasureTextEx(font, "C", fontSize, fontSpacing)
bool txtResizeBtn = true
float btnWidth = (textSize.x + 3.5f * oneCharSize.x)
float btnHeight = textSize.y * (float)(2.0f * (textSize.y / fontSize))
Rectangle rect = { 100, 100, btnWidth, btnHeight }
Color btnLiveColor = { 222, 214, 202, 255 }
Color btnHover = { 135, 195, 74, 100 }
Color btnPressed = { 66, 165, 245, 100 }
Color btnIdle = btnLiveColor
Rectangle border { rect.x, rect.y, btnWidth, btnHeight }
Color borderLiveColor = BLACK
Color borderHover = { 57, 73, 171, 100 }
Color borderPressed = { 0, 105, 92, 100 }
Color borderIdle = borderLiveColor
float borderThickness = (rect.width + rect.height) / 150
bool isBorder = true
double shadowOffset = 0.05
Rectangle shadow { rect.x + 5, rect.y + 5, btnWidth, btnHeight }
Color shadowColor = GRAY
bool isShadow = true
Vector2 textPos
bool m_IsClicked
Vector2 position
Detailed Description
Definition at line 43 of file Button.h.
Constructor & Destructor Documentation
ButtonR()
ButtonR::ButtonR (string text, float x, float y) inline
Definition at line 108 of file Button.h.
    {
        this->text = text;
        this->rect.x = x;
        this->rect.y = y;
        buildBtn();
    }
References buildBtn(), text, Rectangle::x, and Rectangle::y.
Member Function Documentation
buildBtn()
void ButtonR::buildBtn () inline
Definition at line 172 of file Button.h.
    {
        //--- Button size
        /*
            The button size is computed from the font size and length of the text
            See mutators to modify the button’s position,
            the text’s position in the button, and the button’s size.
        */
        float ratioWidth = (isRayFont) ? 3.5f : 4.0f,
            ratioHeight = (isRayFont) ? 2.0f : 1.4f;
        textSize = MeasureTextEx(font, text.c_str(), fontSize, fontSpacing);
        oneCharSize = MeasureTextEx(font, "C", fontSize, fontSpacing);
        if (txtResizeBtn)
        {
            //--- Button size
            rect.width = (textSize.x + ratioWidth * oneCharSize.x);
            rect.height = textSize.y * (float)(ratioHeight * (textSize.y / fontSize));
        }
        //--- Centers text in button
        textPos =
        {
            rect.x + (rect.width - textSize.x) / 2,
            rect.y + (rect.height - textSize.y) / 2 };
        //---- Button border
        border = rect;
        borderThickness = (rect.width + rect.height) / 150;
        //---- Button shadow
        shadow = { rect.x + 5, rect.y + 5, rect.width, rect.height };
    } // build_btn()
References border, borderThickness, font, fontSize, fontSpacing, Rectangle::height, isRayFont, MeasureTextEx(), oneCharSize, rect, shadow, text, textPos, textSize, txtResizeBtn, Rectangle::width, Vector2::x, Rectangle::x, Vector2::y, and Rectangle::y.
draw()
void ButtonR::draw () inline
Definition at line 117 of file Button.h.
    {
        update();
        if (isShadow)
            DrawRectangleRec(shadow, shadowColor);
        DrawRectangleRec(rect, btnLiveColor);
        if (isBorder)
            DrawRectangleLinesEx(border, borderThickness, borderLiveColor);
        DrawTextEx(font, text.c_str(), textPos, fontSize, fontSpacing, fontColor);
    }
References border, borderLiveColor, borderThickness, btnLiveColor, DrawRectangleLinesEx(), DrawRectangleRec(), DrawTextEx(), font, fontColor, fontSize, fontSpacing, isBorder, isShadow, rect, shadow, shadowColor, text, textPos, and update().
IsClicked()
bool ButtonR::IsClicked () inline
Definition at line 255 of file Button.h.
    {
        int result = update();
        Vector2 Mouse = GetMousePosition();
        this->position.x = this->rect.x;
        this->position.y = this->rect.y;
        Vector2 Boundries = { position.x + rect.width,
                             position.y + rect.height
        };
        int Xmargin = rect.width + rect.x;
        int YMargin = rect.height + rect.y;
        int MaxMarginX = Vector2Distance(Vector2Zero(), this->position);
        int MaxMarginY = Vector2Distance(Vector2Zero(), this->position);
        const int ButtonRadiusX = rect.x + rect.width / 2;
        const int ButtonRadiusY = rect.y + rect.height / 2;
        const int MinButtonRadiusX = position.x - (rect.width / 2);
        const int MinButtonRadiusY = position.y - (rect.height / 2);
        float MouseDistanceFromButtonCenter = Vector2Distance(position, Mouse);
        if (Mouse.x >= MinButtonRadiusX && Mouse.x <= ButtonRadiusX && Mouse.y >= MinButtonRadiusY && Mouse.y <= ButtonRadiusY && IsMouseButtonPressed(MOUSE_BUTTON_LEFT)) {
            return true;
        }
        else
        {
            return false;
        }
        return false;
    }
References GetMousePosition(), Rectangle::height, IsMouseButtonPressed(), MOUSE_BUTTON_LEFT, position, rect, update(), Vector2Distance(), Vector2Zero(), Rectangle::width, Vector2::x, Rectangle::x, Vector2::y, and Rectangle::y.
setBtnPosition()
void ButtonR::setBtnPosition (float btnX, float btnY) inline
Definition at line 240 of file Button.h.
    {
        rect.x = btnX;
        rect.y = btnY;
        buildBtn();
    }
References buildBtn(), rect, Rectangle::x, and Rectangle::y.
setBtnSize()
void ButtonR::setBtnSize (float btnWidth, float btnHeight) inline
Definition at line 247 of file Button.h.
    {
        rect.width = btnWidth;
        rect.height = btnHeight;
        txtResizeBtn = false;
        buildBtn();
    }
References btnHeight, btnWidth, buildBtn(), Rectangle::height, rect, txtResizeBtn, and Rectangle::width.
setFontSize()
void ButtonR::setFontSize (float fontSize) inline
Definition at line 206 of file Button.h.
    {
        this->fontSize = fontSize;
        txtResizeBtn = true;
        buildBtn();
    }
References buildBtn(), fontSize, and txtResizeBtn.
setFontSizeNoResize()
void ButtonR::setFontSizeNoResize (float fontSize) inline
Definition at line 213 of file Button.h.
    {
        this->fontSize = fontSize;
        txtResizeBtn = false;
        buildBtn();
    }
References buildBtn(), fontSize, and txtResizeBtn.
setText()
void ButtonR::setText (string text) inline
Definition at line 220 of file Button.h.
    {
        this->text = text;
        txtResizeBtn = true;
        buildBtn();
    }
References buildBtn(), text, and txtResizeBtn.
setTextNoResize()
void ButtonR::setTextNoResize (string text) inline
Definition at line 227 of file Button.h.
    {
        this->text = text;
        txtResizeBtn = false;
        buildBtn();
    }
References buildBtn(), text, and txtResizeBtn.
setTextPosition()
void ButtonR::setTextPosition (float x, float y) inline
Definition at line 234 of file Button.h.
    {
        textPos.x = x;
        textPos.y = y;
    }
References textPos, Vector2::x, and Vector2::y.
update()
int ButtonR::update () inline
Definition at line 129 of file Button.h.
    {
        int result = -1;
        // Mouse position
        Vector2 mouse_pos = GetMousePosition();
        if (CheckCollisionPointRec(mouse_pos, rect))
        {
            if (IsMouseButtonDown(MOUSE_BUTTON_LEFT))
            {
                btnLiveColor = btnPressed;
                borderLiveColor = borderPressed;
                result = MOUSE_BUTTON_LEFT;
            }
            else if (IsMouseButtonDown(MOUSE_BUTTON_RIGHT))
            {
                btnLiveColor = btnPressed;
                borderLiveColor = borderPressed;
                result = MOUSE_BUTTON_RIGHT;
            }
            else if (IsMouseButtonDown(MOUSE_BUTTON_MIDDLE))
            {
                btnLiveColor = btnPressed;
                borderLiveColor = borderPressed;
                result = MOUSE_BUTTON_MIDDLE;
            }
            else
            {
                btnLiveColor = btnHover;
                borderLiveColor = borderHover;
            }
        }
        else
        {
            // state idle
            btnLiveColor = btnIdle;
            borderLiveColor = borderIdle;
        }
        return result;
    } // update()
References borderHover, borderIdle, borderLiveColor, borderPressed, btnHover, btnIdle, btnLiveColor, btnPressed, CheckCollisionPointRec(), GetMousePosition(), IsMouseButtonDown(), MOUSE_BUTTON_LEFT, MOUSE_BUTTON_MIDDLE, MOUSE_BUTTON_RIGHT, and rect.
Member Data Documentation
border
Rectangle ButtonR::border { rect.x, rect.y, btnWidth, btnHeight }
Definition at line 81 of file Button.h.
{ rect.x, rect.y, btnWidth, btnHeight };
borderHover
Color ButtonR::borderHover = { 57, 73, 171, 100 }
Definition at line 85 of file Button.h.
{ 57, 73, 171, 100 },
borderIdle
Color ButtonR::borderIdle = borderLiveColor
Definition at line 87 of file Button.h.
borderLiveColor
Color ButtonR::borderLiveColor = BLACK
Definition at line 83 of file Button.h.
borderPressed
Color ButtonR::borderPressed = { 0, 105, 92, 100 }
Definition at line 86 of file Button.h.
{ 0, 105, 92, 100 },
borderThickness
float ButtonR::borderThickness = (rect.width + rect.height) / 150
Definition at line 88 of file Button.h.
btnHeight
float ButtonR::btnHeight = textSize.y * (float)(2.0f * (textSize.y / fontSize))
Definition at line 65 of file Button.h.
btnHover
Color ButtonR::btnHover = { 135, 195, 74, 100 }
Definition at line 71 of file Button.h.
{ 135, 195, 74, 100 },
btnIdle
Color ButtonR::btnIdle = btnLiveColor
Definition at line 73 of file Button.h.
btnLiveColor
Color ButtonR::btnLiveColor = { 222, 214, 202, 255 }
Definition at line 69 of file Button.h.
{ 222, 214, 202, 255 },
btnPressed
Color ButtonR::btnPressed = { 66, 165, 245, 100 }
Definition at line 72 of file Button.h.
{ 66, 165, 245, 100 },
btnWidth
float ButtonR::btnWidth = (textSize.x + 3.5f * oneCharSize.x)
Definition at line 64 of file Button.h.
font
Font ButtonR::font = GetFontDefault()
Definition at line 46 of file Button.h.
fontColor
Color ButtonR::fontColor = BLACK
Definition at line 49 of file Button.h.
fontSize
float ButtonR::fontSize = 32
Definition at line 47 of file Button.h.
fontSpacing
float ButtonR::fontSpacing = 3.0f
Definition at line 48 of file Button.h.
isBorder
bool ButtonR::isBorder = true
Definition at line 89 of file Button.h.
isRayFont
bool ButtonR::isRayFont = true
Definition at line 50 of file Button.h.
isShadow
bool ButtonR::isShadow = true
Definition at line 100 of file Button.h.
m_IsClicked
bool ButtonR::m_IsClicked
Definition at line 290 of file Button.h.
oneCharSize
Vector2 ButtonR::oneCharSize = MeasureTextEx(font, "C", fontSize, fontSpacing)
Definition at line 55 of file Button.h.
position
Vector2 ButtonR::position
Definition at line 291 of file Button.h.
rect
Rectangle ButtonR::rect = { 100, 100, btnWidth, btnHeight }
Definition at line 66 of file Button.h.
{ 100, 100, btnWidth, btnHeight };
shadow
Rectangle ButtonR::shadow { rect.x + 5, rect.y + 5, btnWidth, btnHeight }
Definition at line 98 of file Button.h.
{ rect.x + 5, rect.y + 5, btnWidth, btnHeight };
shadowColor
Color ButtonR::shadowColor = GRAY
Definition at line 99 of file Button.h.
shadowOffset
double ButtonR::shadowOffset = 0.05
Definition at line 97 of file Button.h.
text
string ButtonR::text = "Button"
Definition at line 53 of file Button.h.
textPos
Vector2 ButtonR::textPos
Initial value:
=
    {
        rect.x + (rect.width - textSize.x) / 2,
        rect.y + (rect.height - textSize.y) / 2 }
Definition at line 103 of file Button.h.
    {
        rect.x + (rect.width - textSize.x) / 2,
        rect.y + (rect.height - textSize.y) / 2 };
textSize
Vector2 ButtonR::textSize = MeasureTextEx(font, text.c_str(), fontSize, fontSpacing)
Definition at line 54 of file Button.h.
txtResizeBtn
bool ButtonR::txtResizeBtn = true
Definition at line 63 of file Button.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Button.h