Techstorm-rivalry: raylib::Font Class Reference
raylib::Font Class Reference
#include <Font.hpp>
Public Member Functions
Font (int baseSize, int glyphCount, int glyphPadding, ::Texture2D texture, ::Rectangle *recs=nullptr, ::GlyphInfo *glyphs=nullptr)
Font ()
Font (const ::Font &font)
Font (const std::string &fileName)
Font (const std::string &fileName, int fontSize, int *fontChars=0, int charCount=0)
Font (const ::Image &image, ::Color key, int firstChar)
Font (const std::string &fileType, const unsigned char *fileData, int dataSize, int fontSize, int *fontChars, int charsCount)
Font (const Font &)=delete
Font (Font &&other)
~Font ()
void Unload ()
int GetBaseSize () const
void SetBaseSize (int value)
int GetGlyphCount () const
void SetGlyphCount (int value)
int GetGlyphPadding () const
void SetGlyphPadding (int value)
::Rectangle * GetRecs () const
void SetRecs (::Rectangle *value)
::GlyphInfo * GetGlyphs () const
void SetGlyphs (::GlyphInfo *value)
TextureUnmanaged GetTexture ()
void SetTexture (const ::Texture &newTexture)
Font & operator= (const ::Font &font)
Font & operator= (const Font &)=delete
Font & operator= (Font &&other) noexcept
void Load (const std::string &fileName)
void Load (const std::string &fileName, int fontSize, int *fontChars, int charCount)
void Load (const ::Image &image, ::Color key, int firstChar)
void Load (const std::string &fileType, const unsigned char *fileData, int dataSize, int fontSize, int *fontChars, int charsCount)
bool IsReady () const
void DrawText (const std::string &text, ::Vector2 position, float fontSize, float spacing, ::Color tint=(Color){ 255, 255, 255, 255 }) const
void DrawText (const std::string &text, int posX, int posY, float fontSize, float spacing, ::Color tint=(Color){ 255, 255, 255, 255 }) const
void DrawText (const std::string &text, ::Vector2 position, ::Vector2 origin, float rotation, float fontSize, float spacing, ::Color tint=(Color){ 255, 255, 255, 255 }) const
void DrawText (int codepoint, ::Vector2 position, float fontSize, ::Color tint={ 255, 255, 255, 255 }) const
void DrawText (const int *codepoints, int count, ::Vector2 position, float fontSize, float spacing, ::Color tint={ 255, 255, 255, 255 }) const
Vector2 MeasureText (const std::string &text, float fontSize, float spacing) const
int GetGlyphIndex (int character) const
inline ::Image ImageText (const std::string &text, float fontSize, float spacing, ::Color tint) const
Public Attributes
int baseSize
int glyphCount
int glyphPadding
Texture2D texture
Rectangle * recs
GlyphInfo * glyphs
Protected Member Functions
void set (const ::Font &font)
Detailed Description
Font type, includes texture and charSet array data
Definition at line 15 of file Font.hpp.
Constructor & Destructor Documentation
Font() [1/9]
raylib::Font::Font (int baseSize, int glyphCount, int glyphPadding, ::Texture2D texture, ::Rectangle * recs = nullptr, ::GlyphInfo * glyphs = nullptr) inline
Definition at line 17 of file Font.hpp.
                                         : ::Font{baseSize, glyphCount, glyphPadding, texture, recs, glyphs} {
        // Nothing.
    }
Font() [2/9]
raylib::Font::Font () inline
Retrieves the default Font.
Definition at line 29 of file Font.hpp.
           {
        set(::GetFontDefault());
    }
References GetFontDefault(), and set().
Font() [3/9]
raylib::Font::Font (const ::Font & font) inline
Definition at line 33 of file Font.hpp.
{
        set(font);
    }
References set().
Font() [4/9]
raylib::Font::Font (const std::string & fileName) inline
Loads a Font from the given file.
Parameters
fileName The file name of the font to load.
Exceptions
raylib::RaylibException Throws if the given font failed to initialize.
Definition at line 44 of file Font.hpp.
{
        Load(fileName);
    }
References Load().
Font() [5/9]
raylib::Font::Font (const std::string & fileName, int fontSize, int * fontChars = 0, int charCount = 0) inline
Loads a Font from the given file, with generation parameters.
Parameters
fileName The file name of the font to load.
Exceptions
raylib::RaylibException Throws if the given font failed to initialize.
See also
LoadFontEx
Definition at line 57 of file Font.hpp.
{
        Load(fileName, fontSize, fontChars, charCount);
    }
References Load().
Font() [6/9]
raylib::Font::Font (const ::Image & image, ::Color key, int firstChar) inline
Loads a Font from the given image with a color key.
Parameters
image The image to load the fond from.
Exceptions
raylib::RaylibException Throws if the given font failed to initialize.
See also
LoadFontFromImage()
Definition at line 70 of file Font.hpp.
{
        Load(image, key, firstChar);
    }
References Load().
Font() [7/9]
raylib::Font::Font (const std::string & fileType, const unsigned char * fileData, int dataSize, int fontSize, int * fontChars, int charsCount) inline
Loads a font from memory, based on the given file type and file data.
Exceptions
raylib::RaylibException Throws if the given font failed to initialize.
See also
LoadFontFromMemory()
Definition at line 81 of file Font.hpp.
{
        Load(fileType, fileData, dataSize, fontSize, fontChars, charsCount);
    }
References Load().
Font() [8/9]
raylib::Font::Font (const Font &) delete
Font() [9/9]
raylib::Font::Font (Font && other) inline
Definition at line 88 of file Font.hpp.
                       {
        set(other);
        other.baseSize = 0;
        other.glyphCount = 0;
        other.glyphPadding = 0;
        other.texture = {};
        other.recs = nullptr;
        other.glyphs = nullptr;
    }
References set().
~Font()
raylib::Font::~Font () inline
Definition at line 99 of file Font.hpp.
            {
        Unload();
    }
References Unload().
Member Function Documentation
DrawText() [1/5]
void raylib::Font::DrawText (const int * codepoints, int count, ::Vector2 position, float fontSize, float spacing, ::Color tint = { 255, 255, 255, 255 }) const inline
Draw multiple character (codepoint)
Definition at line 258 of file Font.hpp.
                         { 255, 255, 255, 255 }) const {
        ::DrawTextCodepoints(*this,
            codepoints, count,
            position, fontSize,
            spacing, tint);
    }
DrawText() [2/5]
void raylib::Font::DrawText (const std::string & text, ::Vector2 position, ::Vector2 origin, float rotation, float fontSize, float spacing, ::Color tint = (Color){ 255, 255, 255, 255 }) const inline
Definition at line 231 of file Font.hpp.
{
        ::DrawTextPro(*this, text.c_str(),
            position, origin,
            rotation, fontSize,
            spacing, tint);
    }
DrawText() [3/5]
void raylib::Font::DrawText (const std::string & text, ::Vector2 position, float fontSize, float spacing, ::Color tint = (Color){ 255, 255, 255, 255 }) const inline
Draw text using font and additional parameters.
Definition at line 216 of file Font.hpp.
{
        ::DrawTextEx(*this, text.c_str(), position,  fontSize,  spacing,  tint);
    }
DrawText() [4/5]
void raylib::Font::DrawText (const std::string & text, int posX, int posY, float fontSize, float spacing, ::Color tint = (Color){ 255, 255, 255, 255 }) const inline
Draw text using font and additional parameters.
Definition at line 224 of file Font.hpp.
{
        ::DrawTextEx(*this, text.c_str(),
            { static_cast<float>(posX), static_cast<float>(posY) },
            fontSize, spacing, tint);
    }
DrawText() [5/5]
void raylib::Font::DrawText (int codepoint, ::Vector2 position, float fontSize, ::Color tint = { 255, 255, 255, 255 }) const inline
Draw one character (codepoint)
Definition at line 248 of file Font.hpp.
                         { 255, 255, 255, 255 }) const {
        ::DrawTextCodepoint(*this, codepoint, position, fontSize, tint);
    }
GetBaseSize()
int raylib::Font::GetBaseSize () const inline
Retrieves the baseSize value for the object.
Returns
The baseSize value of the object.
Definition at line 111 of file Font.hpp.
GetGlyphCount()
int raylib::Font::GetGlyphCount () const inline
Retrieves the glyphCount value for the object.
Returns
The glyphCount value of the object.
Definition at line 112 of file Font.hpp.
GetGlyphIndex()
int raylib::Font::GetGlyphIndex (int character) const inline
Get index position for a unicode character on font
Definition at line 278 of file Font.hpp.
{
        return ::GetGlyphIndex(*this, character);
    }
GetGlyphPadding()
int raylib::Font::GetGlyphPadding () const inline
Retrieves the glyphPadding value for the object.
Returns
The glyphPadding value of the object.
Definition at line 113 of file Font.hpp.
GetGlyphs()
::GlyphInfo * raylib::Font::GetGlyphs () const inline
Retrieves the glyphs value for the object.
Returns
The glyphs value of the object.
Definition at line 115 of file Font.hpp.
GetRecs()
::Rectangle * raylib::Font::GetRecs () const inline
Retrieves the recs value for the object.
Returns
The recs value of the object.
Definition at line 114 of file Font.hpp.
GetTexture()
TextureUnmanaged raylib::Font::GetTexture () inline
Get the texture atlas containing the glyphs.
Definition at line 120 of file Font.hpp.
{
        return texture;
    }
References Font::texture.
ImageText()
inline ::Image raylib::Font::ImageText (const std::string & text, float fontSize, float spacing, ::Color tint) const inline
Create an image from text (custom sprite font)
Definition at line 285 of file Font.hpp.
{
        return ::ImageTextEx(*this, text.c_str(), fontSize, spacing, tint);
    }
IsReady()
bool raylib::Font::IsReady () const inline
Returns if the font is ready to be used.
Definition at line 209 of file Font.hpp.
{
        return ::IsFontReady(*this);
    }
Load() [1/4]
void raylib::Font::Load (const ::Image & image, ::Color key, int firstChar) inline
Definition at line 190 of file Font.hpp.
{
        set(::LoadFontFromImage(image, key, firstChar));
        if (!IsReady()) {
            throw new RaylibException("Failed to load Font with from image");
        }
    }
References IsReady(), LoadFontFromImage(), and set().
Load() [2/4]
void raylib::Font::Load (const std::string & fileName) inline
Loads a font from a given file.
Parameters
fileName The filename of the font to load.
Exceptions
raylib::RaylibException Throws if the given font failed to initialize.
See also
LoadFont()
Definition at line 166 of file Font.hpp.
{
        set(::LoadFont(fileName.c_str()));
        if (!IsReady()) {
            throw new RaylibException("Failed to load Font with from file: " + fileName);
        }
    }
References IsReady(), and set().
Load() [3/4]
void raylib::Font::Load (const std::string & fileName, int fontSize, int * fontChars, int charCount) inline
Loads a font from a given file with generation parameters.
Parameters
fileName The filename of the font to load.
fontSize The desired size of the font.
Exceptions
raylib::RaylibException Throws if the given font failed to initialize.
See also
LoadFontEx()
Definition at line 183 of file Font.hpp.
{
        set(::LoadFontEx(fileName.c_str(), fontSize, fontChars, charCount));
        if (!IsReady()) {
            throw new RaylibException("Failed to load Font with from file with font size: " + fileName);
        }
    }
References IsReady(), and set().
Load() [4/4]
void raylib::Font::Load (const std::string & fileType, const unsigned char * fileData, int dataSize, int fontSize, int * fontChars, int charsCount) inline
Definition at line 197 of file Font.hpp.
{
        set(::LoadFontFromMemory(fileType.c_str(), fileData, dataSize, fontSize, fontChars,
            charsCount));
        if (!IsReady()) {
            throw new RaylibException("Failed to load Font " + fileType + " with from file data");
        }
    }
References IsReady(), LoadFontFromMemory(), and set().
MeasureText()
Vector2 raylib::Font::MeasureText (const std::string & text, float fontSize, float spacing) const inline
Measure string size for Font
Definition at line 271 of file Font.hpp.
{
        return ::MeasureTextEx(*this, text.c_str(), fontSize, spacing);
    }
operator=() [1/3]
Font & raylib::Font::operator= (const ::Font & font) inline
Definition at line 131 of file Font.hpp.
{
        Unload();
        set(font);
        return *this;
    }
References set(), and Unload().
operator=() [2/3]
Font & raylib::Font::operator= (const Font &) delete
operator=() [3/3]
Font & raylib::Font::operator= (Font && other) inline noexcept
Definition at line 139 of file Font.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.baseSize = 0;
        other.glyphCount = 0;
        other.glyphPadding = 0;
        other.texture = {};
        other.recs = nullptr;
        other.glyphs = nullptr;
        return *this;
    }
References set(), and Unload().
set()
void raylib::Font::set (const ::Font & font) inline protected
Definition at line 291 of file Font.hpp.
{
        baseSize = font.baseSize;
        glyphCount = font.glyphCount;
        glyphPadding = font.glyphPadding;
        texture = font.texture;
        recs = font.recs;
        glyphs = font.glyphs;
    }
References Font::baseSize, Font::glyphCount, Font::glyphPadding, Font::glyphs, Font::recs, and Font::texture.
SetBaseSize()
void raylib::Font::SetBaseSize (int value) inline
Sets the baseSize value for the object.
Parameters
value The value of which to set baseSize to.
Definition at line 111 of file Font.hpp.
SetGlyphCount()
void raylib::Font::SetGlyphCount (int value) inline
Sets the glyphCount value for the object.
Parameters
value The value of which to set glyphCount to.
Definition at line 112 of file Font.hpp.
SetGlyphPadding()
void raylib::Font::SetGlyphPadding (int value) inline
Sets the glyphPadding value for the object.
Parameters
value The value of which to set glyphPadding to.
Definition at line 113 of file Font.hpp.
SetGlyphs()
void raylib::Font::SetGlyphs (::GlyphInfo * value) inline
Sets the glyphs value for the object.
Parameters
value The value of which to set glyphs to.
Definition at line 115 of file Font.hpp.
SetRecs()
void raylib::Font::SetRecs (::Rectangle * value) inline
Sets the recs value for the object.
Parameters
value The value of which to set recs to.
Definition at line 114 of file Font.hpp.
SetTexture()
void raylib::Font::SetTexture (const ::Texture & newTexture) inline
Set the texture atlas containing the glyphs.
Definition at line 127 of file Font.hpp.
{
        texture = newTexture;
    }
References Font::texture.
Unload()
void raylib::Font::Unload () inline
Definition at line 103 of file Font.hpp.
                  {
        // Protect against calling UnloadFont() twice.
        if (baseSize != 0) {
            UnloadFont(*this);
            baseSize = 0;
        }
    }
References Font::baseSize, and UnloadFont().
Member Data Documentation
baseSize
int Font::baseSize inherited
Definition at line 306 of file raylib.h.
glyphCount
int Font::glyphCount inherited
Definition at line 307 of file raylib.h.
glyphPadding
int Font::glyphPadding inherited
Definition at line 308 of file raylib.h.
glyphs
GlyphInfo* Font::glyphs inherited
Definition at line 311 of file raylib.h.
recs
Rectangle* Font::recs inherited
Definition at line 310 of file raylib.h.
texture
Texture2D Font::texture inherited
Definition at line 309 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Font.hpp