Techstorm-rivalry: raylib::AudioDevice Class Reference
raylib::AudioDevice Class Reference
#include <AudioDevice.hpp>
Public Member Functions
AudioDevice (bool lateInit=false)
~AudioDevice ()
void Init ()
void Close ()
bool IsReady () const
AudioDevice & SetVolume (float volume)
Detailed Description
Audio device management functions.
Definition at line 12 of file AudioDevice.hpp.
Constructor & Destructor Documentation
AudioDevice()
raylib::AudioDevice::AudioDevice (bool lateInit = false) inline
Initialize audio device and context.
Parameters
lateInit Whether or not to post-pone initializing the context.
Exceptions
raylib::RaylibException Throws if the AudioDevice failed to initialize.
Definition at line 21 of file AudioDevice.hpp.
{
        if (!lateInit) {
            Init();
        }
    }
References Init().
~AudioDevice()
raylib::AudioDevice::~AudioDevice () inline
Close the audio device and context.
Definition at line 30 of file AudioDevice.hpp.
                   {
        Close();
    }
References Close().
Member Function Documentation
Close()
void raylib::AudioDevice::Close () inline
Close the audio device and context.
Definition at line 49 of file AudioDevice.hpp.
{
        ::CloseAudioDevice();
    }
References CloseAudioDevice().
Init()
void raylib::AudioDevice::Init () inline
Initialize audio device and context.
Exceptions
raylib::RaylibException Throws if the AudioDevice failed to initialize.
Definition at line 39 of file AudioDevice.hpp.
                       {
        ::InitAudioDevice();
        if (!IsReady()) {
            throw RaylibException("Failed to initialize AudioDevice");
        }
    }
References InitAudioDevice(), and IsReady().
IsReady()
bool raylib::AudioDevice::IsReady () const inline
Check if audio device has been initialized successfully.
Definition at line 56 of file AudioDevice.hpp.
{
        return ::IsAudioDeviceReady();
    }
SetVolume()
AudioDevice & raylib::AudioDevice::SetVolume (float volume) inline
Set master volume (listener).
Parameters
volume The desired volume to set.
Definition at line 65 of file AudioDevice.hpp.
{
        ::SetMasterVolume(volume);
        return *this;
    }
References SetMasterVolume().
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/AudioDevice.hpp