Techstorm-rivalry: raylib::Shader Class Reference
raylib::Shader Class Reference
#include <Shader.hpp>
Public Member Functions
Shader (const ::Shader &shader)
Shader (unsigned int id, int *locs=nullptr)
Shader (const std::string &vsFileName, const std::string &fsFileName)
Shader (const char *vsFileName, const char *fsFileName)
Shader (const Shader &)=delete
Shader (Shader &&other)
unsigned int GetId () const
void SetId (unsigned int value)
int * GetLocs () const
void SetLocs (int *value)
Shader & operator= (const ::Shader &shader)
Shader & operator= (const Shader &)=delete
Shader & operator= (Shader &&other) noexcept
~Shader ()
void Unload ()
Shader & BeginMode ()
Shader & EndMode ()
int GetLocation (const std::string &uniformName) const
int GetLocationAttrib (const std::string &attribName) const
Shader & SetValue (int uniformLoc, const void *value, int uniformType)
Shader & SetValue (int uniformLoc, const void *value, int uniformType, int count)
Shader & SetValue (int uniformLoc, const ::Matrix &mat)
Shader & SetValue (int uniformLoc, const ::Texture2D &texture)
bool IsReady () const
Static Public Member Functions
::Shader Load (const std::string &vsFileName, const std::string &fsFileName)
::Shader Load (const char *vsFileName, const char *fsFileName)
::Shader LoadFromMemory (const std::string &vsCode, const std::string &fsCode)
::Shader LoadFromMemory (const char *vsCode, const char *fsCode)
Public Attributes
unsigned int id
int * locs
Protected Member Functions
void set (const ::Shader &shader)
Detailed Description
Shader type (generic)
Definition at line 14 of file Shader.hpp.
Constructor & Destructor Documentation
Shader() [1/6]
raylib::Shader::Shader (const ::Shader & shader) inline
Definition at line 16 of file Shader.hpp.
{
        set(shader);
    }
References set().
Shader() [2/6]
raylib::Shader::Shader (unsigned int id, int * locs = nullptr) inline
Definition at line 20 of file Shader.hpp.
: ::Shader{id, locs} {}
Shader() [3/6]
raylib::Shader::Shader (const std::string & vsFileName, const std::string & fsFileName) inline
Definition at line 22 of file Shader.hpp.
{
        set(::LoadShader(vsFileName.c_str(), fsFileName.c_str()));
    }
References LoadShader(), and set().
Shader() [4/6]
raylib::Shader::Shader (const char * vsFileName, const char * fsFileName) inline
Definition at line 26 of file Shader.hpp.
{
        set(::LoadShader(vsFileName, fsFileName));
    }
References LoadShader(), and set().
Shader() [5/6]
raylib::Shader::Shader (const Shader &) delete
Shader() [6/6]
raylib::Shader::Shader (Shader && other) inline
Definition at line 32 of file Shader.hpp.
{
        set(other);
        other.id = 0;
        other.locs = nullptr;
    }
References set().
~Shader()
raylib::Shader::~Shader () inline
Unload shader from GPU memory (VRAM)
Definition at line 92 of file Shader.hpp.
              {
        Unload();
    }
References Unload().
Member Function Documentation
BeginMode()
Shader & raylib::Shader::BeginMode () inline
Begin custom shader drawing.
Definition at line 108 of file Shader.hpp.
{
        ::BeginShaderMode(*this);
        return *this;
    }
References BeginShaderMode().
EndMode()
Shader & raylib::Shader::EndMode () inline
End custom shader drawing (use default shader).
Definition at line 116 of file Shader.hpp.
{
        ::EndShaderMode();
        return *this;
    }
References EndShaderMode().
GetId()
unsigned int raylib::Shader::GetId () const inline
Retrieves the id value for the object.
Returns
The id value of the object.
Definition at line 65 of file Shader.hpp.
GetLocation()
int raylib::Shader::GetLocation (const std::string & uniformName) const inline
Get shader uniform location
See also
GetShaderLocation()
Definition at line 126 of file Shader.hpp.
{
        return ::GetShaderLocation(*this, uniformName.c_str());
    }
GetLocationAttrib()
int raylib::Shader::GetLocationAttrib (const std::string & attribName) const inline
Get shader attribute location
See also
GetShaderLocationAttrib()
Definition at line 135 of file Shader.hpp.
{
        return ::GetShaderLocationAttrib(*this, attribName.c_str());
    }
GetLocs()
int * raylib::Shader::GetLocs () const inline
Retrieves the locs value for the object.
Returns
The locs value of the object.
Definition at line 66 of file Shader.hpp.
IsReady()
bool raylib::Shader::IsReady () const inline
Retrieves whether or not the shader is ready.
Definition at line 182 of file Shader.hpp.
{
        return id != 0 && locs != nullptr;
    }
References Shader::locs.
Load() [1/2]
::Shader raylib::Shader::Load (const char * vsFileName, const char * fsFileName) inline static
Definition at line 48 of file Shader.hpp.
{
        return ::LoadShader(vsFileName, fsFileName);
    }
Load() [2/2]
::Shader raylib::Shader::Load (const std::string & vsFileName, const std::string & fsFileName) inline static
Load shader from files and bind default locations.
See also
LoadShader
Definition at line 44 of file Shader.hpp.
{
        return ::LoadShader(vsFileName.c_str(), fsFileName.c_str());
    }
LoadFromMemory() [1/2]
::Shader raylib::Shader::LoadFromMemory (const char * vsCode, const char * fsCode) inline static
Definition at line 61 of file Shader.hpp.
{
        return ::LoadShaderFromMemory(vsCode, fsCode);
    }
LoadFromMemory() [2/2]
::Shader raylib::Shader::LoadFromMemory (const std::string & vsCode, const std::string & fsCode) inline static
Load a shader from memory.
See also
LoadShaderFromMemory
Definition at line 57 of file Shader.hpp.
{
        return ::LoadShaderFromMemory(vsCode.c_str(), fsCode.c_str());
    }
operator=() [1/3]
Shader & raylib::Shader::operator= (const ::Shader & shader) inline
Definition at line 68 of file Shader.hpp.
{
        set(shader);
        return *this;
    }
References set().
operator=() [2/3]
Shader & raylib::Shader::operator= (const Shader &) delete
operator=() [3/3]
Shader & raylib::Shader::operator= (Shader && other) inline noexcept
Definition at line 75 of file Shader.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.id = 0;
        other.locs = nullptr;
        return *this;
    }
References set(), and Unload().
set()
void raylib::Shader::set (const ::Shader & shader) inline protected
Definition at line 187 of file Shader.hpp.
{
        id = shader.id;
        locs = shader.locs;
    }
References Shader::locs.
SetId()
void raylib::Shader::SetId (unsigned int value) inline
Sets the id value for the object.
Parameters
value The value of which to set id to.
Definition at line 65 of file Shader.hpp.
SetLocs()
void raylib::Shader::SetLocs (int * value) inline
Sets the locs value for the object.
Parameters
value The value of which to set locs to.
Definition at line 66 of file Shader.hpp.
SetValue() [1/4]
Shader & raylib::Shader::SetValue (int uniformLoc, const ::Matrix & mat) inline
Set shader uniform value (matrix 4x4)
See also
SetShaderValueMatrix()
Definition at line 164 of file Shader.hpp.
{
        ::SetShaderValueMatrix(*this, uniformLoc, mat);
        return *this;
    }
References SetShaderValueMatrix().
SetValue() [2/4]
Shader & raylib::Shader::SetValue (int uniformLoc, const ::Texture2D & texture) inline
Set shader uniform value for texture
See also
SetShaderValueTexture()
Definition at line 174 of file Shader.hpp.
{
        ::SetShaderValueTexture(*this, uniformLoc, texture);
        return *this;
    }
References SetShaderValueTexture().
SetValue() [3/4]
Shader & raylib::Shader::SetValue (int uniformLoc, const void * value, int uniformType) inline
Set shader uniform value
See also
SetShaderValue()
Definition at line 144 of file Shader.hpp.
{
        ::SetShaderValue(*this, uniformLoc, value, uniformType);
        return *this;
    }
References SetShaderValue().
SetValue() [4/4]
Shader & raylib::Shader::SetValue (int uniformLoc, const void * value, int uniformType, int count) inline
Set shader uniform value vector
See also
SetShaderValueV()
Definition at line 154 of file Shader.hpp.
{
        ::SetShaderValueV(*this, uniformLoc, value, uniformType, count);
        return *this;
    }
References SetShaderValueV().
Unload()
void raylib::Shader::Unload () inline
Unload shader from GPU memory (VRAM)
Definition at line 99 of file Shader.hpp.
                  {
        if (locs != nullptr) {
            ::UnloadShader(*this);
        }
    }
References Shader::locs, and UnloadShader().
Member Data Documentation
id
unsigned int Shader::id inherited
Definition at line 360 of file raylib.h.
locs
int* Shader::locs inherited
Definition at line 361 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Shader.hpp