Techstorm-rivalry: toml::v3::path_component Class Reference
toml::v3::path_component Class Reference
#include <toml.h>
Public Member Functions
path_component ()
path_component (size_t index) noexcept
path_component (std::string_view key)
path_component (const path_component &pc)
path_component (path_component &&pc) noexcept
path_component & operator= (const path_component &rhs)
path_component & operator= (path_component &&rhs) noexcept
path_component & operator= (size_t new_index) noexcept
path_component & operator= (std::string_view new_key)
~path_component () noexcept
size_t index () const noexcept
operator size_t () const noexcept
const std::string & key () const noexcept
operator const std::string & () const noexcept
path_component_type type () const noexcept
Friends
bool operator== (const path_component &lhs, const path_component &rhs) noexcept
bool operator!= (const path_component &lhs, const path_component &rhs) noexcept
Detailed Description
Definition at line 2797 of file toml.h.
Constructor & Destructor Documentation
path_component() [1/5]
toml::v3::path_component::path_component () inline
Definition at line 10751 of file toml.h.
        : type_{ path_component_type::key }
    {
        store_key("", value_storage_);
    }
path_component() [2/5]
toml::v3::path_component::path_component (size_t index) inline noexcept
Definition at line 10758 of file toml.h.
        : type_(path_component_type::array_index)
    {
        store_index(index, value_storage_);
    }
path_component() [3/5]
toml::v3::path_component::path_component (std::string_view key) inline
Definition at line 10765 of file toml.h.
        : type_(path_component_type::key)
    {
        store_key(key, value_storage_);
    }
path_component() [4/5]
toml::v3::path_component::path_component (const path_component & pc) inline
Definition at line 10781 of file toml.h.
        : type_{ pc.type_ }
    {
        if (type_ == path_component_type::array_index)
            store_index(pc.index(), value_storage_);
        else
            store_key(pc.key(), value_storage_);
    }
References toml::v3::array_index, index(), and key().
path_component() [5/5]
toml::v3::path_component::path_component (path_component && pc) inline noexcept
Definition at line 10791 of file toml.h.
        : type_{ pc.type_ }
    {
        if (type_ == path_component_type::array_index)
            store_index(pc.index_ref(), value_storage_);
        else
            store_key(std::move(pc.key_ref()), value_storage_);
    }
~path_component()
toml::v3::path_component::~path_component () inline noexcept
Definition at line 2902 of file toml.h.
        {
            destroy();
        }
Member Function Documentation
index()
size_t toml::v3::path_component::index () const inline noexcept
Definition at line 2908 of file toml.h.
        {
            TOML_ASSERT_ASSUME(type_ == path_component_type::array_index);
            return *get_as<const size_t>(value_storage_);
        }
References TOML_ASSERT_ASSUME.
key()
const std::string & toml::v3::path_component::key () const inline noexcept
Definition at line 2921 of file toml.h.
        {
            TOML_ASSERT_ASSUME(type_ == path_component_type::key);
            return *get_as<const std::string>(value_storage_);
        }
References TOML_ASSERT_ASSUME.
operator const std::string &()
toml::v3::path_component::operator const std::string & () const inline explicit noexcept
Definition at line 2928 of file toml.h.
        {
            return key();
        }
operator size_t()
toml::v3::path_component::operator size_t () const inline explicit noexcept
Definition at line 2915 of file toml.h.
        {
            return index();
        }
operator=() [1/4]
path_component & toml::v3::path_component::operator= (const path_component & rhs) inline
Definition at line 10801 of file toml.h.
    {
        if (type_ != rhs.type_)
        {
            destroy();
            type_ = rhs.type_;
            if (type_ == path_component_type::array_index)
                store_index(rhs.index(), value_storage_);
            else
                store_key(rhs.key(), value_storage_);
        }
        else
        {
            if (type_ == path_component_type::array_index)
                index_ref() = rhs.index();
            else
                key_ref() = rhs.key();
        }
        return *this;
    }
References toml::v3::array_index, index(), and key().
operator=() [2/4]
path_component & toml::v3::path_component::operator= (path_component && rhs) inline noexcept
Definition at line 10824 of file toml.h.
    {
        if (type_ != rhs.type_)
        {
            destroy();
            type_ = rhs.type_;
            if (type_ == path_component_type::array_index)
                store_index(rhs.index(), value_storage_);
            else
                store_key(std::move(rhs.key_ref()), value_storage_);
        }
        else
        {
            if (type_ == path_component_type::array_index)
                index_ref() = rhs.index();
            else
                key_ref() = std::move(rhs.key_ref());
        }
        return *this;
    }
References toml::v3::array_index.
operator=() [3/4]
path_component & toml::v3::path_component::operator= (size_t new_index) inline noexcept
Definition at line 10861 of file toml.h.
    {
        // If currently a key, string will need to be destroyed regardless
        destroy();
        type_ = path_component_type::array_index;
        store_index(new_index, value_storage_);
        return *this;
    }
References toml::v3::array_index.
operator=() [4/4]
path_component & toml::v3::path_component::operator= (std::string_view new_key) inline
Definition at line 10873 of file toml.h.
    {
        if (type_ == path_component_type::key)
            key_ref() = new_key;
        else
        {
            type_ = path_component_type::key;
            store_key(new_key, value_storage_);
        }
        return *this;
    }
References toml::v3::key.
type()
path_component_type toml::v3::path_component::type () const inline noexcept
Definition at line 2934 of file toml.h.
        {
            return type_;
        }
Friends And Related Symbol Documentation
operator!=
bool operator!= (const path_component & lhs, const path_component & rhs) friend
Definition at line 2946 of file toml.h.
        {
            return !equal(lhs, rhs);
        }
operator==
bool operator== (const path_component & lhs, const path_component & rhs) friend
Definition at line 2940 of file toml.h.
        {
            return equal(lhs, rhs);
        }
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/toml.h