Techstorm-rivalry: raylib::Rectangle Class Reference
raylib::Rectangle Class Reference
#include <Rectangle.hpp>
Public Member Functions
Rectangle (const ::Rectangle &rect)
Rectangle (float x, float y, float width, float height)
Rectangle (float x, float y, float width)
Rectangle (float x, float y)
Rectangle (float x)
Rectangle ()
Rectangle (::Vector2 position, ::Vector2 size)
Rectangle (::Vector2 size)
Rectangle (::Vector4 rect)
float GetX () const
void SetX (float value)
float GetY () const
void SetY (float value)
float GetWidth () const
void SetWidth (float value)
float GetHeight () const
void SetHeight (float value)
Rectangle & operator= (const ::Rectangle &rect)
inline ::Vector4 ToVector4 ()
operator::Vector4 () const
void Draw (::Color color) const
void Draw (::Vector2 origin, float rotation, ::Color color) const
void DrawGradientV (::Color color1, ::Color color2) const
void DrawGradientH (::Color color1, ::Color color2) const
void DrawGradient (::Color col1, ::Color col2, ::Color col3, ::Color col4) const
void DrawLines (::Color color) const
void DrawLines (::Color color, float lineThick) const
void DrawRounded (float roundness, int segments, ::Color color) const
void DrawRoundedLines (float roundness, int segments, float lineThick, ::Color color) const
bool CheckCollision (::Rectangle rec2) const
inline ::Rectangle GetCollision (::Rectangle rec2) const
bool CheckCollision (::Vector2 point) const
bool CheckCollision (::Vector2 center, float radius) const
Vector2 GetSize () const
Rectangle & SetSize (float newWidth, float newHeight)
Rectangle & SetSize (const ::Vector2 &size)
Rectangle & SetShapesTexture (const ::Texture2D &texture)
Vector2 GetPosition () const
Rectangle & SetPosition (float newX, float newY)
Rectangle & SetPosition (const ::Vector2 &position)
Public Attributes
float x
float y
float width
float height
Protected Member Functions
void set (const ::Rectangle &rect)
Detailed Description
Rectangle type
Definition at line 12 of file Rectangle.hpp.
Constructor & Destructor Documentation
Rectangle() [1/9]
raylib::Rectangle::Rectangle (const ::Rectangle & rect) inline
Definition at line 14 of file Rectangle.hpp.
: ::Rectangle{rect.x, rect.y, rect.width, rect.height} {}
Rectangle() [2/9]
raylib::Rectangle::Rectangle (float x, float y, float width, float height) inline
Definition at line 16 of file Rectangle.hpp.
: ::Rectangle{x, y, width, height} {}
Rectangle() [3/9]
raylib::Rectangle::Rectangle (float x, float y, float width) inline
Definition at line 17 of file Rectangle.hpp.
: ::Rectangle{x, y, width, 0} {}
Rectangle() [4/9]
raylib::Rectangle::Rectangle (float x, float y) inline
Definition at line 18 of file Rectangle.hpp.
: ::Rectangle{x, y, 0, 0} {}
Rectangle() [5/9]
raylib::Rectangle::Rectangle (float x) inline
Definition at line 19 of file Rectangle.hpp.
: ::Rectangle{x, 0, 0, 0} {}
Rectangle() [6/9]
raylib::Rectangle::Rectangle () inline
Definition at line 20 of file Rectangle.hpp.
: ::Rectangle{0, 0, 0, 0} {}
Rectangle() [7/9]
raylib::Rectangle::Rectangle (::Vector2 position, ::Vector2 size) inline
Definition at line 22 of file Rectangle.hpp.
            : ::Rectangle{position.x, position.y, size.x, size.y} {}
Rectangle() [8/9]
raylib::Rectangle::Rectangle (::Vector2 size) inline
Definition at line 24 of file Rectangle.hpp.
: ::Rectangle{0, 0, size.x, size.y} {}
Rectangle() [9/9]
raylib::Rectangle::Rectangle (::Vector4 rect) inline
Definition at line 25 of file Rectangle.hpp.
: ::Rectangle{rect.x, rect.y, rect.z, rect.w} {}
Member Function Documentation
CheckCollision() [1/3]
bool raylib::Rectangle::CheckCollision (::Rectangle rec2) const inline
Check collision between two rectangles
Definition at line 91 of file Rectangle.hpp.
{
        return ::CheckCollisionRecs(*this, rec2);
    }
CheckCollision() [2/3]
bool raylib::Rectangle::CheckCollision (::Vector2 center, float radius) const inline
Check collision between circle and rectangle
Definition at line 112 of file Rectangle.hpp.
{
        return ::CheckCollisionCircleRec(center, radius, *this);
    }
CheckCollision() [3/3]
bool raylib::Rectangle::CheckCollision (::Vector2 point) const inline
Check if point is inside rectangle
Definition at line 105 of file Rectangle.hpp.
{
        return ::CheckCollisionPointRec(point, *this);
    }
Draw() [1/2]
void raylib::Rectangle::Draw (::Color color) const inline
Draw a color-filled rectangle
Definition at line 48 of file Rectangle.hpp.
{
        ::DrawRectangleRec(*this, color);
    }
References DrawRectangleRec().
Draw() [2/2]
void raylib::Rectangle::Draw (::Vector2 origin, float rotation, ::Color color) const inline
Definition at line 52 of file Rectangle.hpp.
{
        ::DrawRectanglePro(*this, origin, rotation, color);
    }
References DrawRectanglePro().
DrawGradient()
void raylib::Rectangle::DrawGradient (::Color col1, ::Color col2, ::Color col3, ::Color col4) const inline
Definition at line 66 of file Rectangle.hpp.
{
        ::DrawRectangleGradientEx(*this, col1, col2, col3, col4);
    }
References DrawRectangleGradientEx().
DrawGradientH()
void raylib::Rectangle::DrawGradientH (::Color color1, ::Color color2) const inline
Definition at line 61 of file Rectangle.hpp.
{
        ::DrawRectangleGradientH(static_cast<int>(x), static_cast<int>(y), static_cast<int>(width),
            static_cast<int>(height), color1, color2);
    }
References DrawRectangleGradientH(), Rectangle::height, Rectangle::width, Rectangle::x, and Rectangle::y.
DrawGradientV()
void raylib::Rectangle::DrawGradientV (::Color color1, ::Color color2) const inline
Definition at line 56 of file Rectangle.hpp.
{
        ::DrawRectangleGradientV(static_cast<int>(x), static_cast<int>(y), static_cast<int>(width),
            static_cast<int>(height), color1, color2);
    }
References DrawRectangleGradientV(), Rectangle::height, Rectangle::width, Rectangle::x, and Rectangle::y.
DrawLines() [1/2]
void raylib::Rectangle::DrawLines (::Color color) const inline
Definition at line 70 of file Rectangle.hpp.
{
        ::DrawRectangleLines(static_cast<int>(x), static_cast<int>(y), static_cast<int>(width),
            static_cast<int>(height), color);
    }
References DrawRectangleLines(), Rectangle::height, Rectangle::width, Rectangle::x, and Rectangle::y.
DrawLines() [2/2]
void raylib::Rectangle::DrawLines (::Color color, float lineThick) const inline
Definition at line 75 of file Rectangle.hpp.
{
        ::DrawRectangleLinesEx(*this, lineThick, color);
    }
References DrawRectangleLinesEx().
DrawRounded()
void raylib::Rectangle::DrawRounded (float roundness, int segments, ::Color color) const inline
Definition at line 79 of file Rectangle.hpp.
{
        ::DrawRectangleRounded(*this, roundness, segments, color);
    }
References DrawRectangleRounded().
DrawRoundedLines()
void raylib::Rectangle::DrawRoundedLines (float roundness, int segments, float lineThick, ::Color color) const inline
Definition at line 83 of file Rectangle.hpp.
{
        ::DrawRectangleRoundedLines(*this, roundness, segments, lineThick, color);
    }
References DrawRectangleRoundedLines().
GetCollision()
inline ::Rectangle raylib::Rectangle::GetCollision (::Rectangle rec2) const inline
Get collision rectangle for two rectangles collision
Definition at line 98 of file Rectangle.hpp.
{
        return ::GetCollisionRec(*this, rec2);
    }
GetHeight()
float raylib::Rectangle::GetHeight () const inline
Retrieves the height value for the object.
Returns
The height value of the object.
Definition at line 30 of file Rectangle.hpp.
GetPosition()
Vector2 raylib::Rectangle::GetPosition () const inline
Definition at line 135 of file Rectangle.hpp.
{
        return {x, y};
    }
References Rectangle::x, and Rectangle::y.
GetSize()
Vector2 raylib::Rectangle::GetSize () const inline
Definition at line 116 of file Rectangle.hpp.
{
        return {width, height};
    }
References Rectangle::height, and Rectangle::width.
GetWidth()
float raylib::Rectangle::GetWidth () const inline
Retrieves the width value for the object.
Returns
The width value of the object.
Definition at line 29 of file Rectangle.hpp.
GetX()
float raylib::Rectangle::GetX () const inline
Retrieves the x value for the object.
Returns
The x value of the object.
Definition at line 27 of file Rectangle.hpp.
GetY()
float raylib::Rectangle::GetY () const inline
Retrieves the y value for the object.
Returns
The y value of the object.
Definition at line 28 of file Rectangle.hpp.
operator::Vector4()
raylib::Rectangle::operator::Vector4 () const inline
Definition at line 41 of file Rectangle.hpp.
{
        return {x, y, width, height};
    }
References Rectangle::height, Rectangle::width, Rectangle::x, and Rectangle::y.
operator=()
Rectangle & raylib::Rectangle::operator= (const ::Rectangle & rect) inline
Definition at line 32 of file Rectangle.hpp.
{
        set(rect);
        return *this;
    }
References set().
set()
void raylib::Rectangle::set (const ::Rectangle & rect) inline protected
Definition at line 150 of file Rectangle.hpp.
{
        x = rect.x;
        y = rect.y;
        width = rect.width;
        height = rect.height;
    }
References Rectangle::height, Rectangle::width, Rectangle::x, and Rectangle::y.
SetHeight()
void raylib::Rectangle::SetHeight (float value) inline
Sets the height value for the object.
Parameters
value The value of which to set height to.
Definition at line 30 of file Rectangle.hpp.
SetPosition() [1/2]
Rectangle & raylib::Rectangle::SetPosition (const ::Vector2 & position) inline
Definition at line 145 of file Rectangle.hpp.
{
        return SetPosition(position.x, position.y);
    }
References SetPosition().
SetPosition() [2/2]
Rectangle & raylib::Rectangle::SetPosition (float newX, float newY) inline
Definition at line 139 of file Rectangle.hpp.
{
        x = newX;
        y = newY;
        return *this;
    }
References Rectangle::x, and Rectangle::y.
SetShapesTexture()
Rectangle & raylib::Rectangle::SetShapesTexture (const ::Texture2D & texture) inline
Definition at line 130 of file Rectangle.hpp.
{
        ::SetShapesTexture(texture, *this);
        return *this;
    }
References SetShapesTexture().
SetSize() [1/2]
Rectangle & raylib::Rectangle::SetSize (const ::Vector2 & size) inline
Definition at line 126 of file Rectangle.hpp.
{
        return SetSize(size.x, size.y);
    }
References SetSize().
SetSize() [2/2]
Rectangle & raylib::Rectangle::SetSize (float newWidth, float newHeight) inline
Definition at line 120 of file Rectangle.hpp.
{
        width = newWidth;
        height = newHeight;
        return *this;
    }
References Rectangle::height, and Rectangle::width.
SetWidth()
void raylib::Rectangle::SetWidth (float value) inline
Sets the width value for the object.
Parameters
value The value of which to set width to.
Definition at line 29 of file Rectangle.hpp.
SetX()
void raylib::Rectangle::SetX (float value) inline
Sets the x value for the object.
Parameters
value The value of which to set x to.
Definition at line 27 of file Rectangle.hpp.
SetY()
void raylib::Rectangle::SetY (float value) inline
Sets the y value for the object.
Parameters
value The value of which to set y to.
Definition at line 28 of file Rectangle.hpp.
ToVector4()
inline ::Vector4 raylib::Rectangle::ToVector4 () inline
Definition at line 37 of file Rectangle.hpp.
{
        return {x, y, width, height};
    }
References Rectangle::height, Rectangle::width, Rectangle::x, and Rectangle::y.
Member Data Documentation
height
float Rectangle::height inherited
Definition at line 248 of file raylib.h.
width
float Rectangle::width inherited
Definition at line 247 of file raylib.h.
x
float Rectangle::x inherited
Definition at line 245 of file raylib.h.
y
float Rectangle::y inherited
Definition at line 246 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Rectangle.hpp