Techstorm-rivalry: raylib::Gamepad Class Reference
raylib::Gamepad Class Reference
#include <Gamepad.hpp>
Public Member Functions
Gamepad (int gamepadNumber=0)
int GetNumber () const
void SetNumber (int value)
Gamepad & operator= (const Gamepad &gamepad)
Gamepad & operator= (int gamepadNumber)
operator int () const
bool IsAvailable () const
std::string GetName () const
operator std::string () const
bool IsButtonPressed (int button) const
bool IsButtonDown (int button) const
bool IsButtonReleased (int button) const
bool IsButtonUp (int button) const
int GetButtonPressed () const
int GetAxisCount () const
float GetAxisMovement (int axis) const
int SetMappings (const std::string &mappings)
Static Public Member Functions
static bool IsAvailable (int number)
Public Attributes
int number
Protected Member Functions
void set (int gamepadNumber)
Detailed Description
Input-related functions: gamepads
Definition at line 13 of file Gamepad.hpp.
Constructor & Destructor Documentation
Gamepad()
raylib::Gamepad::Gamepad (int gamepadNumber = 0) inline
Definition at line 15 of file Gamepad.hpp.
{
        set(gamepadNumber);
    }
References set().
Member Function Documentation
GetAxisCount()
int raylib::Gamepad::GetAxisCount () const inline
Return gamepad axis count for a gamepad
Definition at line 100 of file Gamepad.hpp.
{
        return ::GetGamepadAxisCount(number);
    }
References number.
GetAxisMovement()
float raylib::Gamepad::GetAxisMovement (int axis) const inline
Return axis movement value for a gamepad axis
Definition at line 107 of file Gamepad.hpp.
{
        return ::GetGamepadAxisMovement(number, axis);
    }
References number.
GetButtonPressed()
int raylib::Gamepad::GetButtonPressed () const inline
Get the last gamepad button pressed
Definition at line 93 of file Gamepad.hpp.
{
        return ::GetGamepadButtonPressed();
    }
GetName()
std::string raylib::Gamepad::GetName () const inline
Return gamepad internal name id
Definition at line 51 of file Gamepad.hpp.
{
        return ::GetGamepadName(number);
    }
References number.
GetNumber()
int raylib::Gamepad::GetNumber () const inline
Retrieves the number value for the object.
Returns
The number value of the object.
Definition at line 20 of file Gamepad.hpp.
IsAvailable() [1/2]
bool raylib::Gamepad::IsAvailable () const inline
Detect if a gamepad is available
Definition at line 37 of file Gamepad.hpp.
{
        return ::IsGamepadAvailable(number);
    }
References number.
IsAvailable() [2/2]
static bool raylib::Gamepad::IsAvailable (int number) inline static
Detect if a gamepad is available
Definition at line 44 of file Gamepad.hpp.
{
        return ::IsGamepadAvailable(number);
    }
References number.
IsButtonDown()
bool raylib::Gamepad::IsButtonDown (int button) const inline
Detect if a gamepad button is being pressed
Definition at line 72 of file Gamepad.hpp.
{
        return ::IsGamepadButtonDown(number, button);
    }
References number.
IsButtonPressed()
bool raylib::Gamepad::IsButtonPressed (int button) const inline
Detect if a gamepad button has been pressed once
Definition at line 65 of file Gamepad.hpp.
{
        return ::IsGamepadButtonPressed(number, button);
    }
References number.
IsButtonReleased()
bool raylib::Gamepad::IsButtonReleased (int button) const inline
Detect if a gamepad button has been released once
Definition at line 79 of file Gamepad.hpp.
{
        return ::IsGamepadButtonReleased(number, button);
    }
References number.
IsButtonUp()
bool raylib::Gamepad::IsButtonUp (int button) const inline
Detect if a gamepad button is NOT being pressed
Definition at line 86 of file Gamepad.hpp.
{
        return ::IsGamepadButtonUp(number, button);
    }
References number.
operator int()
raylib::Gamepad::operator int () const inline
Definition at line 32 of file Gamepad.hpp.
{ return number; }
References number.
operator std::string()
raylib::Gamepad::operator std::string () const inline
Return gamepad internal name id
Definition at line 58 of file Gamepad.hpp.
{
        return GetName();
    }
References GetName().
operator=() [1/2]
Gamepad & raylib::Gamepad::operator= (const Gamepad & gamepad) inline
Definition at line 22 of file Gamepad.hpp.
{
        set(gamepad);
        return *this;
    }
References set().
operator=() [2/2]
Gamepad & raylib::Gamepad::operator= (int gamepadNumber) inline
Definition at line 27 of file Gamepad.hpp.
{
        set(gamepadNumber);
        return *this;
    }
References set().
set()
void raylib::Gamepad::set (int gamepadNumber) inline protected
Definition at line 116 of file Gamepad.hpp.
{
        number = gamepadNumber;
    }
References number.
SetMappings()
int raylib::Gamepad::SetMappings (const std::string & mappings) inline
Definition at line 111 of file Gamepad.hpp.
{
        return SetGamepadMappings(mappings.c_str());
    }
References SetGamepadMappings().
SetNumber()
void raylib::Gamepad::SetNumber (int value) inline
Sets the number value for the object.
Parameters
value The value of which to set number to.
Definition at line 20 of file Gamepad.hpp.
Member Data Documentation
number
int raylib::Gamepad::number
Definition at line 18 of file Gamepad.hpp.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Gamepad.hpp