Techstorm-rivalry: raylib::Vector4 Class Reference
raylib::Vector4 Class Reference
#include <Vector4.hpp>
Public Member Functions
Vector4 (const ::Vector4 &vec)
Vector4 (float x, float y, float z, float w)
Vector4 (float x, float y, float z)
Vector4 (float x, float y)
Vector4 (float x)
Vector4 ()
Vector4 (::Rectangle rectangle)
Vector4 (::Color color)
float GetX () const
void SetX (float value)
float GetY () const
void SetY (float value)
float GetZ () const
void SetZ (float value)
float GetW () const
void SetW (float value)
Vector4 & operator= (const ::Vector4 &vector4)
bool operator== (const ::Vector4 &other) const
bool operator!= (const ::Vector4 &other) const
inline ::Rectangle ToRectangle () const
operator::Rectangle () const
std::string ToString () const
operator std::string () const
Vector4 Multiply (const ::Vector4 &vector4) const
Vector4 operator* (const ::Vector4 &vector4) const
Vector4 Lerp (const ::Vector4 &vector4, float amount) const
Vector4 Nlerp (const ::Vector4 &vector4, float amount) const
Vector4 Slerp (const ::Vector4 &vector4, float amount) const
Matrix ToMatrix () const
float Length () const
Vector4 Normalize () const
Vector4 Invert () const
void ToAxisAngle (::Vector3 *outAxis, float *outAngle) const
std::pair< Vector3, float > ToAxisAngle () const
Vector4 Transform (const ::Matrix &matrix) const
Vector3 ToEuler () const
Color ColorFromNormalized () const
operator Color () const
Static Public Member Functions
static Vector4 Identity ()
static Vector4 FromVector3ToVector3 (const ::Vector3 &from, const ::Vector3 &to)
static Vector4 FromMatrix (const ::Matrix &matrix)
static Vector4 FromAxisAngle (const ::Vector3 &axis, const float angle)
static Vector4 FromEuler (const float pitch, const float yaw, const float roll)
static Vector4 FromEuler (const ::Vector3 &vector3)
Public Attributes
float x
float y
float z
float w
Protected Member Functions
void set (const ::Vector4 &vec4)
Detailed Description
Vector4 type
Definition at line 19 of file Vector4.hpp.
Constructor & Destructor Documentation
Vector4() [1/8]
raylib::Vector4::Vector4 (const ::Vector4 & vec) inline
Definition at line 21 of file Vector4.hpp.
: ::Vector4{vec.x, vec.y, vec.z, vec.w} {}
Vector4() [2/8]
raylib::Vector4::Vector4 (float x, float y, float z, float w) inline
Definition at line 23 of file Vector4.hpp.
: ::Vector4{x, y, z, w} {}
Vector4() [3/8]
raylib::Vector4::Vector4 (float x, float y, float z) inline
Definition at line 24 of file Vector4.hpp.
: ::Vector4{x, y, z, 0} {}
Vector4() [4/8]
raylib::Vector4::Vector4 (float x, float y) inline
Definition at line 25 of file Vector4.hpp.
: ::Vector4{x, y, 0, 0} {}
Vector4() [5/8]
raylib::Vector4::Vector4 (float x) inline
Definition at line 26 of file Vector4.hpp.
: ::Vector4{x, 0, 0, 0} {}
Vector4() [6/8]
raylib::Vector4::Vector4 () inline
Definition at line 27 of file Vector4.hpp.
: ::Vector4{0, 0, 0, 0} {}
Vector4() [7/8]
raylib::Vector4::Vector4 (::Rectangle rectangle) inline
Definition at line 28 of file Vector4.hpp.
: ::Vector4{rectangle.x, rectangle.y, rectangle.width, rectangle.height} {}
Vector4() [8/8]
raylib::Vector4::Vector4 (::Color color) inline
Definition at line 30 of file Vector4.hpp.
{
        set(ColorNormalize(color));
    }
References ColorNormalize(), and set().
Member Function Documentation
ColorFromNormalized()
Color raylib::Vector4::ColorFromNormalized () const inline
Definition at line 156 of file Vector4.hpp.
{
        return ::ColorFromNormalized(*this);
    }
FromAxisAngle()
static Vector4 raylib::Vector4::FromAxisAngle (const ::Vector3 & axis, const float angle) inline static
Definition at line 139 of file Vector4.hpp.
{
        return ::QuaternionFromAxisAngle(axis, angle);
    }
FromEuler() [1/2]
static Vector4 raylib::Vector4::FromEuler (const ::Vector3 & vector3) inline static
Definition at line 147 of file Vector4.hpp.
{
        return ::QuaternionFromEuler(vector3.x, vector3.y, vector3.z);
    }
FromEuler() [2/2]
static Vector4 raylib::Vector4::FromEuler (const float pitch, const float yaw, const float roll) inline static
Definition at line 143 of file Vector4.hpp.
{
        return ::QuaternionFromEuler(pitch, yaw, roll);
    }
FromMatrix()
static Vector4 raylib::Vector4::FromMatrix (const ::Matrix & matrix) inline static
Definition at line 135 of file Vector4.hpp.
{
        return ::QuaternionFromMatrix(matrix);
    }
FromVector3ToVector3()
static Vector4 raylib::Vector4::FromVector3ToVector3 (const ::Vector3 & from, const ::Vector3 & to) inline static
Definition at line 131 of file Vector4.hpp.
{
        return ::QuaternionFromVector3ToVector3(from , to);
    }
GetW()
float raylib::Vector4::GetW () const inline
Retrieves the w value for the object.
Returns
The w value of the object.
Definition at line 37 of file Vector4.hpp.
GetX()
float raylib::Vector4::GetX () const inline
Retrieves the x value for the object.
Returns
The x value of the object.
Definition at line 34 of file Vector4.hpp.
GetY()
float raylib::Vector4::GetY () const inline
Retrieves the y value for the object.
Returns
The y value of the object.
Definition at line 35 of file Vector4.hpp.
GetZ()
float raylib::Vector4::GetZ () const inline
Retrieves the z value for the object.
Returns
The z value of the object.
Definition at line 36 of file Vector4.hpp.
Identity()
static Vector4 raylib::Vector4::Identity () inline static
Definition at line 127 of file Vector4.hpp.
{
        return ::QuaternionIdentity();
    }
Invert()
Vector4 raylib::Vector4::Invert () const inline
Definition at line 104 of file Vector4.hpp.
{
        return QuaternionInvert(*this);
    }
References QuaternionInvert().
Length()
float raylib::Vector4::Length () const inline
Definition at line 96 of file Vector4.hpp.
{
        return QuaternionLength(*this);
    }
References QuaternionLength().
Lerp()
Vector4 raylib::Vector4::Lerp (const ::Vector4 & vector4, float amount) const inline
Definition at line 80 of file Vector4.hpp.
{
        return QuaternionLerp(*this, vector4, amount);
    }
References QuaternionLerp().
Multiply()
Vector4 raylib::Vector4::Multiply (const ::Vector4 & vector4) const inline
Definition at line 72 of file Vector4.hpp.
{
        return QuaternionMultiply(*this, vector4);
    }
References QuaternionMultiply().
Nlerp()
Vector4 raylib::Vector4::Nlerp (const ::Vector4 & vector4, float amount) const inline
Definition at line 84 of file Vector4.hpp.
{
        return QuaternionNlerp(*this, vector4, amount);
    }
References QuaternionNlerp().
Normalize()
Vector4 raylib::Vector4::Normalize () const inline
Definition at line 100 of file Vector4.hpp.
{
        return QuaternionNormalize(*this);
    }
References QuaternionNormalize().
operator Color()
raylib::Vector4::operator Color () const inline
Definition at line 160 of file Vector4.hpp.
{
        return ColorFromNormalized();
    }
References ColorFromNormalized().
operator std::string()
raylib::Vector4::operator std::string () const inline
Definition at line 67 of file Vector4.hpp.
{
        return ToString();
    }
References ToString().
operator!=()
bool raylib::Vector4::operator!= (const ::Vector4 & other) const inline
Definition at line 51 of file Vector4.hpp.
{
        return !(*this == other);
    }
operator*()
Vector4 raylib::Vector4::operator* (const ::Vector4 & vector4) const inline
Definition at line 76 of file Vector4.hpp.
{
        return QuaternionMultiply(*this, vector4);
    }
References QuaternionMultiply().
operator::Rectangle()
raylib::Vector4::operator::Rectangle () const inline
Definition at line 59 of file Vector4.hpp.
{
        return {x, y, z, w};
    }
References Vector4::w, Vector4::x, Vector4::y, and Vector4::z.
operator=()
Vector4 & raylib::Vector4::operator= (const ::Vector4 & vector4) inline
Definition at line 39 of file Vector4.hpp.
{
        set(vector4);
        return *this;
    }
References set().
operator==()
bool raylib::Vector4::operator== (const ::Vector4 & other) const inline
Definition at line 44 of file Vector4.hpp.
{
        return x == other.x
            && y == other.y
            && z == other.z
            && w == other.w;
    }
References Vector4::w, Vector4::x, Vector4::y, and Vector4::z.
set()
void raylib::Vector4::set (const ::Vector4 & vec4) inline protected
Definition at line 165 of file Vector4.hpp.
{
        x = vec4.x;
        y = vec4.y;
        z = vec4.z;
        w = vec4.w;
    }
References Vector4::w, Vector4::x, Vector4::y, and Vector4::z.
SetW()
void raylib::Vector4::SetW (float value) inline
Sets the w value for the object.
Parameters
value The value of which to set w to.
Definition at line 37 of file Vector4.hpp.
SetX()
void raylib::Vector4::SetX (float value) inline
Sets the x value for the object.
Parameters
value The value of which to set x to.
Definition at line 34 of file Vector4.hpp.
SetY()
void raylib::Vector4::SetY (float value) inline
Sets the y value for the object.
Parameters
value The value of which to set y to.
Definition at line 35 of file Vector4.hpp.
SetZ()
void raylib::Vector4::SetZ (float value) inline
Sets the z value for the object.
Parameters
value The value of which to set z to.
Definition at line 36 of file Vector4.hpp.
Slerp()
Vector4 raylib::Vector4::Slerp (const ::Vector4 & vector4, float amount) const inline
Definition at line 88 of file Vector4.hpp.
{
        return QuaternionSlerp(*this, vector4, amount);
    }
References QuaternionSlerp().
ToAxisAngle() [1/2]
std::pair< Vector3, float > raylib::Vector4::ToAxisAngle () const inline
Get the rotation angle and axis for a given quaternion
Definition at line 115 of file Vector4.hpp.
{
        Vector3 outAxis;
        float outAngle;
        QuaternionToAxisAngle(*this, &outAxis, &outAngle);
        return std::pair<Vector3, float>(outAxis, outAngle);
    }
References QuaternionToAxisAngle().
ToAxisAngle() [2/2]
void raylib::Vector4::ToAxisAngle (::Vector3 * outAxis, float * outAngle) const inline
Definition at line 108 of file Vector4.hpp.
{
        QuaternionToAxisAngle(*this, outAxis, outAngle);
    }
References QuaternionToAxisAngle().
ToEuler()
Vector3 raylib::Vector4::ToEuler () const inline
Definition at line 151 of file Vector4.hpp.
{
        return ::QuaternionToEuler(*this);
    }
ToMatrix()
Matrix raylib::Vector4::ToMatrix () const inline
Definition at line 92 of file Vector4.hpp.
{
        return QuaternionToMatrix(*this);
    }
References QuaternionToMatrix().
ToRectangle()
inline ::Rectangle raylib::Vector4::ToRectangle () const inline
Definition at line 55 of file Vector4.hpp.
{
        return {x, y, z, w};
    }
References Vector4::w, Vector4::x, Vector4::y, and Vector4::z.
ToString()
std::string raylib::Vector4::ToString () const inline
Definition at line 63 of file Vector4.hpp.
{
        return TextFormat("Vector4(%f, %f, %f, %f)", x, y, z, w);
    }
References TextFormat(), Vector4::w, Vector4::x, Vector4::y, and Vector4::z.
Transform()
Vector4 raylib::Vector4::Transform (const ::Matrix & matrix) const inline
Definition at line 123 of file Vector4.hpp.
{
        return ::QuaternionTransform(*this, matrix);
    }
Member Data Documentation
w
float Vector4::w inherited
Definition at line 221 of file raylib.h.
x
float Vector4::x inherited
Definition at line 218 of file raylib.h.
y
float Vector4::y inherited
Definition at line 219 of file raylib.h.
z
float Vector4::z inherited
Definition at line 220 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Vector4.hpp