Techstorm-rivalry: toml::v3::noex::parse_result Class Reference
toml::v3::noex::parse_result Class Reference
#include <toml.h>
Public Types
using iterator = table_iterator
using const_iterator = const_table_iterator
Public Member Functions
parse_result () noexcept
parse_result (toml::table &&tbl) noexcept
parse_result (parse_error &&err) noexcept
parse_result (parse_result &&res) noexcept
parse_result & operator= (parse_result &&rhs) noexcept
~parse_result () noexcept
bool succeeded () const noexcept
bool failed () const noexcept
operator bool () const noexcept
toml::table & table () &noexcept
toml::table && table () &&noexcept
const toml::table & table () const &noexcept
operator toml::table & () noexcept
operator toml::table && () noexcept
operator const toml::table & () const noexcept
parse_error & error () &noexcept
parse_error && error () &&noexcept
const parse_error & error () const &noexcept
operator parse_error & () noexcept
operator parse_error && () noexcept
operator const parse_error & () const noexcept
table_iterator begin () noexcept
const_table_iterator begin () const noexcept
const_table_iterator cbegin () const noexcept
table_iterator end () noexcept
const_table_iterator end () const noexcept
const_table_iterator cend () const noexcept
node_view< node > at_path (std::string_view path) noexcept
node_view< const node > at_path (std::string_view path) const noexcept
node_view< node > at_path (const toml::path &path) noexcept
node_view< const node > at_path (const toml::path &path) const noexcept
node_view< node > operator[] (const toml::path &path) noexcept
node_view< const node > operator[] (const toml::path &path) const noexcept
node_view< node > operator[] (std::string_view key) noexcept
node_view< const node > operator[] (std::string_view key) const noexcept
Friends
std::ostream & operator<< (std::ostream &os, const parse_result &result)
Detailed Description
Definition at line 8796 of file toml.h.
Member Typedef Documentation
const_iterator
using toml::v3::noex::parse_result::const_iterator = const_table_iterator
Definition at line 8985 of file toml.h.
iterator
using toml::v3::noex::parse_result::iterator = table_iterator
Definition at line 8983 of file toml.h.
Constructor & Destructor Documentation
parse_result() [1/4]
toml::v3::noex::parse_result::parse_result () inline noexcept
Definition at line 8831 of file toml.h.
            : err_{ true }
        {
            ::new (static_cast<void*>(storage_.bytes)) parse_error{ std::string{}, source_region{} };
        }
parse_result() [2/4]
toml::v3::noex::parse_result::parse_result (toml::table && tbl) inline explicit noexcept
Definition at line 8838 of file toml.h.
            : err_{ false }
        {
            ::new (static_cast<void*>(storage_.bytes)) toml::table{ std::move(tbl) };
        }
parse_result() [3/4]
toml::v3::noex::parse_result::parse_result (parse_error && err) inline explicit noexcept
Definition at line 8845 of file toml.h.
            : err_{ true }
        {
            ::new (static_cast<void*>(storage_.bytes)) parse_error{ std::move(err) };
        }
parse_result() [4/4]
toml::v3::noex::parse_result::parse_result (parse_result && res) inline noexcept
Definition at line 8852 of file toml.h.
            : err_{ res.err_ }
        {
            if (err_)
                ::new (static_cast<void*>(storage_.bytes)) parse_error{ std::move(res).error() };
            else
                ::new (static_cast<void*>(storage_.bytes)) toml::table{ std::move(res).table() };
        }
~parse_result()
toml::v3::noex::parse_result::~parse_result () inline noexcept
Definition at line 8882 of file toml.h.
        {
            destroy();
        }
Member Function Documentation
at_path() [1/4]
node_view< const node > toml::v3::noex::parse_result::at_path (const toml::path & path) const inline noexcept
Definition at line 9042 of file toml.h.
                    {
                        return err_ ? node_view<const node>{} : table().at_path(path);
                    }
References toml::v3::node::at_path().
at_path() [2/4]
node_view< node > toml::v3::noex::parse_result::at_path (const toml::path & path) inline noexcept
Definition at line 9036 of file toml.h.
                    {
                        return err_ ? node_view<node>{} : table().at_path(path);
                    }
References toml::v3::node::at_path().
at_path() [3/4]
node_view< const node > toml::v3::noex::parse_result::at_path (std::string_view path) const inline noexcept
Definition at line 9030 of file toml.h.
                    {
                        return err_ ? node_view<const node>{} : table().at_path(path);
                    }
References toml::v3::node::at_path().
at_path() [4/4]
node_view< node > toml::v3::noex::parse_result::at_path (std::string_view path) inline noexcept
Definition at line 9024 of file toml.h.
                    {
                        return err_ ? node_view<node>{} : table().at_path(path);
                    }
References toml::v3::node::at_path().
begin() [1/2]
const_table_iterator toml::v3::noex::parse_result::begin () const inline noexcept
Definition at line 8994 of file toml.h.
                    {
                        return err_ ? const_table_iterator{} : table().begin();
                    }
References toml::v3::table::begin().
begin() [2/2]
table_iterator toml::v3::noex::parse_result::begin () inline noexcept
Definition at line 8988 of file toml.h.
                    {
                        return err_ ? table_iterator{} : table().begin();
                    }
References toml::v3::table::begin().
cbegin()
const_table_iterator toml::v3::noex::parse_result::cbegin () const inline noexcept
Definition at line 9000 of file toml.h.
                    {
                        return err_ ? const_table_iterator{} : table().cbegin();
                    }
References toml::v3::table::cbegin().
cend()
const_table_iterator toml::v3::noex::parse_result::cend () const inline noexcept
Definition at line 9018 of file toml.h.
                    {
                        return err_ ? const_table_iterator{} : table().cend();
                    }
References toml::v3::table::cend().
end() [1/2]
const_table_iterator toml::v3::noex::parse_result::end () const inline noexcept
Definition at line 9012 of file toml.h.
                    {
                        return err_ ? const_table_iterator{} : table().end();
                    }
References toml::v3::table::end().
end() [2/2]
table_iterator toml::v3::noex::parse_result::end () inline noexcept
Definition at line 9006 of file toml.h.
                    {
                        return err_ ? table_iterator{} : table().end();
                    }
References toml::v3::table::end().
error() [1/3]
parse_error && toml::v3::noex::parse_result::error () && inline noexcept
Definition at line 8952 of file toml.h.
                    {
                        TOML_ASSERT_ASSUME(err_);
                        return static_cast<parse_error&&>(*get_as<parse_error>(storage_));
                    }
References TOML_ASSERT_ASSUME.
error() [2/3]
parse_error & toml::v3::noex::parse_result::error () & inline noexcept
Definition at line 8945 of file toml.h.
                    {
                        TOML_ASSERT_ASSUME(err_);
                        return *get_as<parse_error>(storage_);
                    }
References TOML_ASSERT_ASSUME.
error() [3/3]
const parse_error & toml::v3::noex::parse_result::error () const & inline noexcept
Definition at line 8959 of file toml.h.
                    {
                        TOML_ASSERT_ASSUME(err_);
                        return *get_as<const parse_error>(storage_);
                    }
References TOML_ASSERT_ASSUME.
failed()
bool toml::v3::noex::parse_result::failed () const inline noexcept
Definition at line 8894 of file toml.h.
        {
            return err_;
        }
operator bool()
toml::v3::noex::parse_result::operator bool () const inline explicit noexcept
Definition at line 8900 of file toml.h.
        {
            return !err_;
        }
operator const parse_error &()
toml::v3::noex::parse_result::operator const parse_error & () const inline explicit noexcept
Definition at line 8978 of file toml.h.
                    {
                        return error();
                    }
operator const toml::table &()
toml::v3::noex::parse_result::operator const toml::table & () const inline noexcept
Definition at line 8939 of file toml.h.
                    {
                        return table();
                    }
operator parse_error &()
toml::v3::noex::parse_result::operator parse_error & () inline explicit noexcept
Definition at line 8966 of file toml.h.
                    {
                        return error();
                    }
operator parse_error &&()
toml::v3::noex::parse_result::operator parse_error && () inline explicit noexcept
Definition at line 8972 of file toml.h.
                    {
                        return std::move(error());
                    }
operator toml::table &()
toml::v3::noex::parse_result::operator toml::table & () inline noexcept
Definition at line 8927 of file toml.h.
            {
                return table();
            }
operator toml::table &&()
toml::v3::noex::parse_result::operator toml::table && () inline noexcept
Definition at line 8933 of file toml.h.
                {
                    return std::move(table());
                }
operator=()
parse_result & toml::v3::noex::parse_result::operator= (parse_result && rhs) inline noexcept
Definition at line 8861 of file toml.h.
        {
            if (err_ != rhs.err_)
            {
                destroy();
                err_ = rhs.err_;
                if (err_)
                    ::new (static_cast<void*>(storage_.bytes)) parse_error{ std::move(rhs).error() };
                else
                    ::new (static_cast<void*>(storage_.bytes)) toml::table{ std::move(rhs).table() };
            }
            else
            {
                if (err_)
                    error() = std::move(rhs).error();
                else
                    table() = std::move(rhs).table();
            }
            return *this;
        }
operator[]() [1/4]
node_view< const node > toml::v3::noex::parse_result::operator[] (const toml::path & path) const inline noexcept
Definition at line 9070 of file toml.h.
                    {
                        return err_ ? node_view<const node>{} : table()[path];
                    }
operator[]() [2/4]
node_view< node > toml::v3::noex::parse_result::operator[] (const toml::path & path) inline noexcept
Definition at line 9064 of file toml.h.
                    {
                        return err_ ? node_view<node>{} : table()[path];
                    }
operator[]() [3/4]
node_view< const node > toml::v3::noex::parse_result::operator[] (std::string_view key) const inline noexcept
Definition at line 9082 of file toml.h.
                    {
                        return err_ ? node_view<const node>{} : table()[key];
                    }
operator[]() [4/4]
node_view< node > toml::v3::noex::parse_result::operator[] (std::string_view key) inline noexcept
Definition at line 9076 of file toml.h.
                    {
                        return err_ ? node_view<node>{} : table()[key];
                    }
succeeded()
bool toml::v3::noex::parse_result::succeeded () const inline noexcept
Definition at line 8888 of file toml.h.
        {
            return !err_;
        }
table() [1/3]
toml::table && toml::v3::noex::parse_result::table () && inline noexcept
Definition at line 8913 of file toml.h.
        {
            TOML_ASSERT_ASSUME(!err_);
            return static_cast<toml::table&&>(*get_as<toml::table>(storage_));
        }
References TOML_ASSERT_ASSUME.
table() [2/3]
toml::table & toml::v3::noex::parse_result::table () & inline noexcept
Definition at line 8906 of file toml.h.
        {
            TOML_ASSERT_ASSUME(!err_);
            return *get_as<toml::table>(storage_);
        }
References TOML_ASSERT_ASSUME.
table() [3/3]
const toml::table & toml::v3::noex::parse_result::table () const & inline noexcept
Definition at line 8920 of file toml.h.
        {
            TOML_ASSERT_ASSUME(!err_);
            return *get_as<const toml::table>(storage_);
        }
References TOML_ASSERT_ASSUME.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const parse_result & result) friend
Definition at line 9105 of file toml.h.
                    {
                        return result.err_ ? (os << result.error()) : (os << result.table());
                    }
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/toml.h