Techstorm-rivalry: toml::v3::array Class Reference
toml::v3::array Class Reference
#include <toml.h>
Public Types
using value_type = node
using size_type = size_t
using difference_type = ptrdiff_t
using reference = node&
using const_reference = const node&
using iterator = array_iterator
using const_iterator = const_array_iterator
Public Member Functions
array () noexcept
~array () noexcept
array (const array &)
array (array &&other) noexcept
template<typename ElemType , typename... ElemTypes, typename std::enable_if<((sizeof...(ElemTypes) > 0||!std::is_same_v< impl::remove_cvref< ElemType >, array >)), int >::type = 0>
array (ElemType &&val, ElemTypes &&... vals)
array & operator= (const array &)
array & operator= (array &&rhs) noexcept
node_type type () const noexcept final
bool is_homogeneous (node_type ntype) const noexcept final
bool is_homogeneous (node_type ntype, node *&first_nonmatch) noexcept final
bool is_homogeneous (node_type ntype, const node *&first_nonmatch) const noexcept final
template<typename ElemType = void>
bool is_homogeneous () const noexcept
bool is_table () const noexcept final
bool is_array () const noexcept final
bool is_array_of_tables () const noexcept final
bool is_value () const noexcept final
bool is_string () const noexcept final
bool is_integer () const noexcept final
bool is_floating_point () const noexcept final
bool is_number () const noexcept final
bool is_boolean () const noexcept final
bool is_date () const noexcept final
bool is_time () const noexcept final
bool is_date_time () const noexcept final
table * as_table () noexcept final
array * as_array () noexcept final
toml::value< std::string > * as_string () noexcept final
toml::value< int64_t > * as_integer () noexcept final
toml::value< double > * as_floating_point () noexcept final
toml::value< bool > * as_boolean () noexcept final
toml::value< date > * as_date () noexcept final
toml::value< time > * as_time () noexcept final
toml::value< date_time > * as_date_time () noexcept final
const table * as_table () const noexcept final
const array * as_array () const noexcept final
const toml::value< std::string > * as_string () const noexcept final
const toml::value< int64_t > * as_integer () const noexcept final
const toml::value< double > * as_floating_point () const noexcept final
const toml::value< bool > * as_boolean () const noexcept final
const toml::value< date > * as_date () const noexcept final
const toml::value< time > * as_time () const noexcept final
const toml::value< date_time > * as_date_time () const noexcept final
node * get (size_t index) noexcept
const node * get (size_t index) const noexcept
template<typename ElemType >
impl::wrap_node< ElemType > * get_as (size_t index) noexcept
template<typename ElemType >
const impl::wrap_node< ElemType > * get_as (size_t index) const noexcept
node & operator[] (size_t index) noexcept
const node & operator[] (size_t index) const noexcept
node & at (size_t index)
const node & at (size_t index) const
node & front () noexcept
const node & front () const noexcept
node & back () noexcept
const node & back () const noexcept
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cend () const noexcept
template<typename Func >
array & for_each (Func &&visitor) &noexcept(for_each_is_nothrow< Func &&, array & >)
template<typename Func >
array && for_each (Func &&visitor) &&noexcept(for_each_is_nothrow< Func &&, array && >)
template<typename Func >
const array & for_each (Func &&visitor) const &noexcept(for_each_is_nothrow< Func &&, const array & >)
template<typename Func >
const array && for_each (Func &&visitor) const &&noexcept(for_each_is_nothrow< Func &&, const array && >)
bool empty () const noexcept
size_t size () const noexcept
size_t max_size () const noexcept
size_t capacity () const noexcept
void reserve (size_t new_capacity)
void shrink_to_fit ()
void truncate (size_t new_size)
template<typename ElemType >
void resize (size_t new_size, ElemType &&default_init_val, value_flags default_init_flags=preserve_source_value_flags)
iterator erase (const_iterator pos) noexcept
iterator erase (const_iterator first, const_iterator last) noexcept
array & flatten () &
array && flatten () &&
array & prune (bool recursive=true) &noexcept
array && prune (bool recursive=true) &&noexcept
void pop_back () noexcept
void clear () noexcept
template<typename ElemType >
iterator insert (const_iterator pos, ElemType &&val, value_flags flags=preserve_source_value_flags)
template<typename ElemType >
iterator insert (const_iterator pos, size_t count, ElemType &&val, value_flags flags=preserve_source_value_flags)
template<typename Iter >
iterator insert (const_iterator pos, Iter first, Iter last, value_flags flags=preserve_source_value_flags)
template<typename ElemType >
iterator insert (const_iterator pos, std::initializer_list< ElemType > ilist, value_flags flags=preserve_source_value_flags)
template<typename ElemType = void, typename... Args>
iterator emplace (const_iterator pos, Args &&... args)
template<typename ElemType >
iterator replace (const_iterator pos, ElemType &&val, value_flags flags=preserve_source_value_flags)
template<typename ElemType >
void push_back (ElemType &&val, value_flags flags=preserve_source_value_flags)
template<typename ElemType = void, typename... Args>
decltype(auto) emplace_back (Args &&... args)
template<typename T >
bool is () const noexcept
template<typename T >
impl::wrap_node< T > * as () noexcept
template<typename T >
const impl::wrap_node< T > * as () const noexcept
template<typename T >
optional< T > value_exact () const noexcept(impl::value_retrieval_is_nothrow< T >)
template<typename T >
optional< T > value () const noexcept(impl::value_retrieval_is_nothrow< T >)
template<typename T >
auto value_or (T &&default_value) const noexcept(impl::value_retrieval_is_nothrow< T >)
template<typename T >
decltype(auto) ref () &noexcept
template<typename T >
decltype(auto) ref () &&noexcept
template<typename T >
decltype(auto) ref () const &noexcept
template<typename T >
decltype(auto) ref () const &&noexcept
const source_region & source () const noexcept
template<typename Func >
decltype(auto) visit (Func &&visitor) &noexcept(visit_is_nothrow< Func &&, node & >)
template<typename Func >
decltype(auto) visit (Func &&visitor) &&noexcept(visit_is_nothrow< Func &&, node && >)
template<typename Func >
decltype(auto) visit (Func &&visitor) const &noexcept(visit_is_nothrow< Func &&, const node & >)
template<typename Func >
decltype(auto) visit (Func &&visitor) const &&noexcept(visit_is_nothrow< Func &&, const node && >)
operator node_view< node > () noexcept
operator node_view< const node > () const noexcept
node_view< node > at_path (std::string_view path) noexcept
node_view< const node > at_path (std::string_view path) const noexcept
node_view< node > at_path (const toml::path &path) noexcept
node_view< const node > at_path (const toml::path &path) const noexcept
node_view< node > operator[] (const toml::path &path) noexcept
node_view< const node > operator[] (const toml::path &path) const noexcept
Protected Types
template<typename T , typename N >
using ref_cast_type_
template<typename T , typename N >
using ref_cast_type
Protected Member Functions
template<typename T >
ref_cast_type< T, node & > ref_cast () &noexcept
template<typename T >
ref_cast_type< T, node && > ref_cast () &&noexcept
template<typename T >
ref_cast_type< T, const node & > ref_cast () const &noexcept
template<typename T >
ref_cast_type< T, const node && > ref_cast () const &&noexcept
Friends
bool operator== (const array &lhs, const array &rhs) noexcept
bool operator!= (const array &lhs, const array &rhs) noexcept
template<typename T >
bool operator== (const array &lhs, const std::initializer_list< T > &rhs) noexcept
template<typename T >
bool operator== (const std::initializer_list< T > &rhs, const array &lhs) noexcept
template<typename T >
bool operator!= (const array &lhs, const std::initializer_list< T > &rhs) noexcept
template<typename T >
bool operator!= (const std::initializer_list< T > &rhs, const array &lhs) noexcept
template<typename T >
bool operator== (const array &lhs, const std::vector< T > &rhs) noexcept
template<typename T >
bool operator== (const std::vector< T > &rhs, const array &lhs) noexcept
template<typename T >
bool operator!= (const array &lhs, const std::vector< T > &rhs) noexcept
template<typename T >
bool operator!= (const std::vector< T > &rhs, const array &lhs) noexcept
std::ostream & operator<< (std::ostream &lhs, const array &rhs)
Detailed Description
Definition at line 5962 of file toml.h.
Member Typedef Documentation
const_iterator
using toml::v3::array::const_iterator = const_array_iterator
Definition at line 6331 of file toml.h.
const_reference
using toml::v3::array::const_reference = const node&
Definition at line 6012 of file toml.h.
difference_type
using toml::v3::array::difference_type = ptrdiff_t
Definition at line 6010 of file toml.h.
iterator
using toml::v3::array::iterator = array_iterator
Definition at line 6329 of file toml.h.
ref_cast_type
template<typename T , typename N > using toml::v3::node::ref_cast_type protected inherited
Initial value:
 std::conditional_t<
            std::is_reference_v<N>,
            ref_cast_type_<T, N>,
            ref_cast_type_<T, std::add_lvalue_reference_t<N>>
            >
Definition at line 3458 of file toml.h.
ref_cast_type_
template<typename T , typename N > using toml::v3::node::ref_cast_type_ protected inherited
Initial value:
 std::conditional_t<
            std::is_reference_v<T>,
            impl::copy_ref<impl::copy_cv<impl::wrap_node<T>, std::remove_reference_t<N>>, T>,
            impl::copy_cvref<impl::wrap_node<T>, N>
            >
Definition at line 3451 of file toml.h.
reference
using toml::v3::array::reference = node&
Definition at line 6011 of file toml.h.
size_type
using toml::v3::array::size_type = size_t
Definition at line 6009 of file toml.h.
value_type
using toml::v3::array::value_type = node
Definition at line 6008 of file toml.h.
Constructor & Destructor Documentation
array() [1/4]
toml::v3::array::array () inline noexcept
Definition at line 11243 of file toml.h.
    {
#if TOML_LIFETIME_HOOKS
        TOML_ARRAY_CREATED;
#endif
    }
~array()
toml::v3::array::~array () inline noexcept
Definition at line 11251 of file toml.h.
    {
#if TOML_LIFETIME_HOOKS
        TOML_ARRAY_DESTROYED;
#endif
    }
array() [2/4]
toml::v3::array::array (const array & other) inline
Definition at line 11290 of file toml.h.
        : node(other)
    {
        elems_.reserve(other.elems_.size());
        for (const auto& elem : other)
            elems_.emplace_back(impl::make_node(elem));
#if TOML_LIFETIME_HOOKS
        TOML_ARRAY_CREATED;
#endif
    }
References toml::v3::impl::make_node().
array() [3/4]
toml::v3::array::array (array && other) inline noexcept
Definition at line 11303 of file toml.h.
        : node(std::move(other)),
          elems_(std::move(other.elems_))
    {
#if TOML_LIFETIME_HOOKS
        TOML_ARRAY_CREATED;
#endif
    }
array() [4/4]
template<typename ElemType , typename... ElemTypes, typename std::enable_if<((sizeof...(ElemTypes) > 0||!std::is_same_v< impl::remove_cvref< ElemType >, array >)), int >::type = 0> toml::v3::array::array (ElemType && val, ElemTypes &&... vals) inline explicit
Definition at line 6033 of file toml.h.
            : array{ std::false_type{},
                     std::initializer_list<impl::array_init_elem>{ static_cast<ElemType&&>(val),
                                                                   static_cast<ElemTypes&&>(vals)... } }
        {}
Member Function Documentation
as() [1/2]
template<typename T > const impl::wrap_node< T > * toml::v3::node::as () const inline noexcept inherited
Definition at line 3676 of file toml.h.
        {
            using unwrapped_type = impl::unwrap_node<impl::remove_cvref<T>>;
            static_assert(toml::is_value<unwrapped_type> || toml::is_container<unwrapped_type>,
                          "The template type argument of node::as() must be one of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
            if constexpr (std::is_same_v<unwrapped_type, table>)
                return as_table();
            else if constexpr (std::is_same_v<unwrapped_type, array>)
                return as_array();
            else if constexpr (std::is_same_v<unwrapped_type, std::string>)
                return as_string();
            else if constexpr (std::is_same_v<unwrapped_type, int64_t>)
                return as_integer();
            else if constexpr (std::is_same_v<unwrapped_type, double>)
                return as_floating_point();
            else if constexpr (std::is_same_v<unwrapped_type, bool>)
                return as_boolean();
            else if constexpr (std::is_same_v<unwrapped_type, date>)
                return as_date();
            else if constexpr (std::is_same_v<unwrapped_type, time>)
                return as_time();
            else if constexpr (std::is_same_v<unwrapped_type, date_time>)
                return as_date_time();
        }
References TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
as() [2/2]
template<typename T > impl::wrap_node< T > * toml::v3::node::as () inline noexcept inherited
Definition at line 3648 of file toml.h.
        {
            using unwrapped_type = impl::unwrap_node<impl::remove_cvref<T>>;
            static_assert(toml::is_value<unwrapped_type> || toml::is_container<unwrapped_type>,
                          "The template type argument of node::as() must be one of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
            if constexpr (std::is_same_v<unwrapped_type, table>)
                return as_table();
            else if constexpr (std::is_same_v<unwrapped_type, array>)
                return as_array();
            else if constexpr (std::is_same_v<unwrapped_type, std::string>)
                return as_string();
            else if constexpr (std::is_same_v<unwrapped_type, int64_t>)
                return as_integer();
            else if constexpr (std::is_same_v<unwrapped_type, double>)
                return as_floating_point();
            else if constexpr (std::is_same_v<unwrapped_type, bool>)
                return as_boolean();
            else if constexpr (std::is_same_v<unwrapped_type, date>)
                return as_date();
            else if constexpr (std::is_same_v<unwrapped_type, time>)
                return as_time();
            else if constexpr (std::is_same_v<unwrapped_type, date_time>)
                return as_date_time();
        }
References TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
as_array() [1/2]
const array * toml::v3::array::as_array () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6207 of file toml.h.
        {
            return this;
        }
as_array() [2/2]
array * toml::v3::array::as_array () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6153 of file toml.h.
        {
            return this;
        }
as_boolean() [1/2]
const toml::value< bool > * toml::v3::array::as_boolean () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6231 of file toml.h.
        {
            return nullptr;
        }
as_boolean() [2/2]
toml::value< bool > * toml::v3::array::as_boolean () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6177 of file toml.h.
        {
            return nullptr;
        }
as_date() [1/2]
const toml::value< date > * toml::v3::array::as_date () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6237 of file toml.h.
        {
            return nullptr;
        }
as_date() [2/2]
toml::value< date > * toml::v3::array::as_date () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6183 of file toml.h.
        {
            return nullptr;
        }
as_date_time() [1/2]
const toml::value< date_time > * toml::v3::array::as_date_time () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6249 of file toml.h.
        {
            return nullptr;
        }
as_date_time() [2/2]
toml::value< date_time > * toml::v3::array::as_date_time () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6195 of file toml.h.
        {
            return nullptr;
        }
as_floating_point() [1/2]
const toml::value< double > * toml::v3::array::as_floating_point () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6225 of file toml.h.
        {
            return nullptr;
        }
as_floating_point() [2/2]
toml::value< double > * toml::v3::array::as_floating_point () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6171 of file toml.h.
        {
            return nullptr;
        }
as_integer() [1/2]
const toml::value< int64_t > * toml::v3::array::as_integer () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6219 of file toml.h.
        {
            return nullptr;
        }
as_integer() [2/2]
toml::value< int64_t > * toml::v3::array::as_integer () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6165 of file toml.h.
        {
            return nullptr;
        }
as_string() [1/2]
const toml::value< std::string > * toml::v3::array::as_string () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6213 of file toml.h.
        {
            return nullptr;
        }
as_string() [2/2]
toml::value< std::string > * toml::v3::array::as_string () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6159 of file toml.h.
        {
            return nullptr;
        }
as_table() [1/2]
const table * toml::v3::array::as_table () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6201 of file toml.h.
        {
            return nullptr;
        }
as_table() [2/2]
table * toml::v3::array::as_table () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6147 of file toml.h.
        {
            return nullptr;
        }
as_time() [1/2]
const toml::value< time > * toml::v3::array::as_time () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6243 of file toml.h.
        {
            return nullptr;
        }
as_time() [2/2]
toml::value< time > * toml::v3::array::as_time () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6189 of file toml.h.
        {
            return nullptr;
        }
at() [1/2]
node & toml::v3::array::at (size_t index) inline
Definition at line 11416 of file toml.h.
    {
#if TOML_COMPILER_HAS_EXCEPTIONS
        return *elems_.at(index);
#else
        auto n = get(index);
        TOML_ASSERT_ASSUME(n && "element index not found in array!");
        return *n;
#endif
    }
References get(), and TOML_ASSERT_ASSUME.
at() [2/2]
const node & toml::v3::array::at (size_t index) const inline
Definition at line 6300 of file toml.h.
        {
            return const_cast<array&>(*this).at(index);
        }
References at().
at_path() [1/4]
node_view< const node > toml::v3::node::at_path (const toml::path & path) const noexcept inherited
at_path() [2/4]
node_view< node > toml::v3::node::at_path (const toml::path & path) noexcept inherited
at_path() [3/4]
node_view< const node > toml::v3::node::at_path (std::string_view path) const inline noexcept inherited
Definition at line 10363 of file toml.h.
    {
        return toml::at_path(*this, path);
    }
at_path() [4/4]
node_view< node > toml::v3::node::at_path (std::string_view path) inline noexcept inherited
Definition at line 10357 of file toml.h.
    {
        return toml::at_path(*this, path);
    }
back() [1/2]
const node & toml::v3::array::back () const inline noexcept
Definition at line 6324 of file toml.h.
        {
            return *elems_.back();
        }
back() [2/2]
node & toml::v3::array::back () inline noexcept
Definition at line 6318 of file toml.h.
        {
            return *elems_.back();
        }
begin() [1/2]
const_iterator toml::v3::array::begin () const inline noexcept
Definition at line 6340 of file toml.h.
        {
            return const_iterator{ elems_.cbegin() };
        }
begin() [2/2]
iterator toml::v3::array::begin () inline noexcept
Definition at line 6334 of file toml.h.
        {
            return iterator{ elems_.begin() };
        }
capacity()
size_t toml::v3::array::capacity () const inline noexcept
Definition at line 6551 of file toml.h.
        {
            return elems_.capacity();
        }
cbegin()
const_iterator toml::v3::array::cbegin () const inline noexcept
Definition at line 6346 of file toml.h.
        {
            return const_iterator{ elems_.cbegin() };
        }
cend()
const_iterator toml::v3::array::cend () const inline noexcept
Definition at line 6364 of file toml.h.
        {
            return const_iterator{ elems_.cend() };
        }
clear()
void toml::v3::array::clear () inline noexcept
Definition at line 11574 of file toml.h.
    {
        elems_.clear();
    }
emplace()
template<typename ElemType = void, typename... Args> iterator toml::v3::array::emplace (const_iterator pos, Args &&... args) inline
Definition at line 6696 of file toml.h.
        {
            using raw_elem_type = impl::remove_cvref<ElemType>;
            using elem_type = std::conditional_t<std::is_void_v<raw_elem_type>, //
                                                 impl::emplaced_type_of<Args&&...>,
                                                 raw_elem_type>;
            using type = impl::remove_cvref<impl::unwrap_node<elem_type>>;
            static_assert(impl::is_native<type> || impl::is_one_of<type, table, array>,
                          "Emplacement type parameter must be one of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
            return iterator{ insert_at(const_vector_iterator{ pos },
                                       impl::node_ptr{ new impl::wrap_node<type>{ static_cast<Args&&>(args)... } }) };
        }
References TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
emplace_back()
template<typename ElemType = void, typename... Args> decltype(auto) toml::v3::array::emplace_back (Args &&... args) inline
Definition at line 6734 of file toml.h.
        {
            using raw_elem_type = impl::remove_cvref<ElemType>;
            using elem_type = std::conditional_t<std::is_void_v<raw_elem_type>, //
                                                 impl::emplaced_type_of<Args&&...>,
                                                 raw_elem_type>;
            static constexpr auto moving_node_ptr = std::is_same_v<elem_type, impl::node_ptr> //
                                                 && sizeof...(Args) == 1u                     //
                                                 && impl::first_is_same<impl::node_ptr&&, Args&&...>;
            using unwrapped_type = impl::remove_cvref<impl::unwrap_node<elem_type>>;
            static_assert(
                moving_node_ptr                                       //
                    || impl::is_native<unwrapped_type>                //
                    || impl::is_one_of<unwrapped_type, table, array>, //
                "ElemType argument of array::emplace_back() must be one of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
            if constexpr (moving_node_ptr)
            {
                insert_at_back(static_cast<Args&&>(args)...);
                return *elems_.back();
            }
            else
            {
                auto ptr = new impl::wrap_node<unwrapped_type>{ static_cast<Args&&>(args)... };
                insert_at_back(impl::node_ptr{ ptr });
                return *ptr;
            }
        }
References TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
empty()
bool toml::v3::array::empty () const inline noexcept
Definition at line 6533 of file toml.h.
        {
            return elems_.empty();
        }
end() [1/2]
const_iterator toml::v3::array::end () const inline noexcept
Definition at line 6358 of file toml.h.
        {
            return const_iterator{ elems_.cend() };
        }
end() [2/2]
iterator toml::v3::array::end () inline noexcept
Definition at line 6352 of file toml.h.
        {
            return iterator{ elems_.end() };
        }
erase() [1/2]
array::iterator toml::v3::array::erase (const_iterator first, const_iterator last) inline noexcept
Definition at line 11457 of file toml.h.
    {
        return iterator{ elems_.erase(const_vector_iterator{ first }, const_vector_iterator{ last }) };
    }
erase() [2/2]
array::iterator toml::v3::array::erase (const_iterator pos) inline noexcept
Definition at line 11451 of file toml.h.
    {
        return iterator{ elems_.erase(const_vector_iterator{ pos }) };
    }
flatten() [1/2]
array & toml::v3::array::flatten () & inline
Definition at line 11492 of file toml.h.
    {
        if (elems_.empty())
            return *this;
        bool requires_flattening = false;
        size_t size_after_flattening = elems_.size();
        for (size_t i = elems_.size(); i-- > 0u;)
        {
            auto arr = elems_[i]->as_array();
            if (!arr)
                continue;
            size_after_flattening--; // discount the array itself
            const auto leaf_count = arr->total_leaf_count();
            if (leaf_count > 0u)
            {
                requires_flattening = true;
                size_after_flattening += leaf_count;
            }
            else
                elems_.erase(elems_.cbegin() + static_cast<ptrdiff_t>(i));
        }
        if (!requires_flattening)
            return *this;
        elems_.reserve(size_after_flattening);
        size_t i = 0;
        while (i < elems_.size())
        {
            auto arr = elems_[i]->as_array();
            if (!arr)
            {
                i++;
                continue;
            }
            impl::node_ptr arr_storage = std::move(elems_[i]);
            const auto leaf_count = arr->total_leaf_count();
            if (leaf_count > 1u)
                preinsertion_resize(i + 1u, leaf_count - 1u);
            flatten_child(std::move(*arr), i); // increments i
        }
        return *this;
    }
References size().
flatten() [2/2]
array && toml::v3::array::flatten () && inline
Definition at line 6590 of file toml.h.
        {
            return static_cast<toml::array&&>(this->flatten());
        }
for_each() [1/4]
template<typename Func > array && toml::v3::array::for_each (Func && visitor) && inline noexcept
Definition at line 6512 of file toml.h.
        {
            do_for_each(static_cast<Func&&>(visitor), static_cast<array&&>(*this));
            return static_cast<array&&>(*this);
        }
for_each() [2/4]
template<typename Func > array & toml::v3::array::for_each (Func && visitor) & inline noexcept
Definition at line 6505 of file toml.h.
        {
            do_for_each(static_cast<Func&&>(visitor), *this);
            return *this;
        }
for_each() [3/4]
template<typename Func > const array && toml::v3::array::for_each (Func && visitor) const && inline noexcept
Definition at line 6526 of file toml.h.
        {
            do_for_each(static_cast<Func&&>(visitor), static_cast<const array&&>(*this));
            return static_cast<const array&&>(*this);
        }
for_each() [4/4]
template<typename Func > const array & toml::v3::array::for_each (Func && visitor) const & inline noexcept
Definition at line 6519 of file toml.h.
        {
            do_for_each(static_cast<Func&&>(visitor), *this);
            return *this;
        }
front() [1/2]
const node & toml::v3::array::front () const inline noexcept
Definition at line 6312 of file toml.h.
        {
            return *elems_.front();
        }
front() [2/2]
node & toml::v3::array::front () inline noexcept
Definition at line 6306 of file toml.h.
        {
            return *elems_.front();
        }
get() [1/2]
const node * toml::v3::array::get (size_t index) const inline noexcept
Definition at line 6261 of file toml.h.
        {
            return const_cast<array&>(*this).get(index);
        }
References get().
get() [2/2]
node * toml::v3::array::get (size_t index) inline noexcept
Definition at line 6255 of file toml.h.
        {
            return index < elems_.size() ? elems_[index].get() : nullptr;
        }
get_as() [1/2]
template<typename ElemType > const impl::wrap_node< ElemType > * toml::v3::array::get_as (size_t index) const inline noexcept
Definition at line 6277 of file toml.h.
        {
            return const_cast<array&>(*this).template get_as<ElemType>(index);
        }
get_as() [2/2]
template<typename ElemType > impl::wrap_node< ElemType > * toml::v3::array::get_as (size_t index) inline noexcept
Definition at line 6268 of file toml.h.
        {
            if (auto val = get(index))
                return val->template as<ElemType>();
            return nullptr;
        }
insert() [1/4]
template<typename ElemType > iterator toml::v3::array::insert (const_iterator pos, ElemType && val, value_flags flags = preserve_source_value_flags) inline
Definition at line 6610 of file toml.h.
        {
            if constexpr (is_node_view<ElemType>)
            {
                if (!val)
                    return end();
            }
            return iterator{ insert_at(const_vector_iterator{ pos },
                                       impl::make_node(static_cast<ElemType&&>(val), flags)) };
        }
insert() [2/4]
template<typename Iter > iterator toml::v3::array::insert (const_iterator pos, Iter first, Iter last, value_flags flags = preserve_source_value_flags) inline
Definition at line 6651 of file toml.h.
        {
            const auto distance = std::distance(first, last);
            if (distance <= 0)
                return iterator{ elems_.begin() + (const_vector_iterator{ pos } - elems_.cbegin()) };
            else
            {
                auto count = distance;
                using deref_type = decltype(*first);
                if constexpr (is_node_view<deref_type>)
                {
                    for (auto it = first; it != last; it++)
                        if (!(*it))
                            count--;
                    if (!count)
                        return iterator{ elems_.begin() + (const_vector_iterator{ pos } - elems_.cbegin()) };
                }
                const auto start_idx = static_cast<size_t>(const_vector_iterator{ pos } - elems_.cbegin());
                preinsertion_resize(start_idx, static_cast<size_t>(count));
                size_t i = start_idx;
                for (auto it = first; it != last; it++)
                {
                    if constexpr (is_node_view<deref_type>)
                    {
                        if (!(*it))
                            continue;
                    }
                    if constexpr (std::is_rvalue_reference_v<deref_type>)
                        elems_[i++] = impl::make_node(std::move(*it), flags);
                    else
                        elems_[i++] = impl::make_node(*it, flags);
                }
                return iterator{ elems_.begin() + static_cast<ptrdiff_t>(start_idx) };
            }
        }
insert() [3/4]
template<typename ElemType > iterator toml::v3::array::insert (const_iterator pos, size_t count, ElemType && val, value_flags flags = preserve_source_value_flags) inline
Definition at line 6622 of file toml.h.
        {
            if constexpr (is_node_view<ElemType>)
            {
                if (!val)
                    return end();
            }
            switch (count)
            {
                case 0: return iterator{ elems_.begin() + (const_vector_iterator{ pos } - elems_.cbegin()) };
                case 1: return insert(pos, static_cast<ElemType&&>(val), flags);
                default:
                {
                    const auto start_idx = static_cast<size_t>(const_vector_iterator{ pos } - elems_.cbegin());
                    preinsertion_resize(start_idx, count);
                    size_t i = start_idx;
                    for (size_t e = start_idx + count - 1u; i < e; i++)
                        elems_[i] = impl::make_node(val, flags);
                    elems_[i] = impl::make_node(static_cast<ElemType&&>(val), flags);
                    return iterator{ elems_.begin() + static_cast<ptrdiff_t>(start_idx) };
                }
            }
        }
insert() [4/4]
template<typename ElemType > iterator toml::v3::array::insert (const_iterator pos, std::initializer_list< ElemType > ilist, value_flags flags = preserve_source_value_flags) inline
Definition at line 6688 of file toml.h.
        {
            return insert(pos, ilist.begin(), ilist.end(), flags);
        }
is()
template<typename T > bool toml::v3::node::is () const inline noexcept inherited
Definition at line 3566 of file toml.h.
        {
            using type = impl::remove_cvref<impl::unwrap_node<T>>;
            static_assert(toml::is_value<type> || toml::is_container<type>,
                          "The template type argument of node::is() must be one of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
            if constexpr (std::is_same_v<type, table>)
                return is_table();
            else if constexpr (std::is_same_v<type, array>)
                return is_array();
            else if constexpr (std::is_same_v<type, std::string>)
                return is_string();
            else if constexpr (std::is_same_v<type, int64_t>)
                return is_integer();
            else if constexpr (std::is_same_v<type, double>)
                return is_floating_point();
            else if constexpr (std::is_same_v<type, bool>)
                return is_boolean();
            else if constexpr (std::is_same_v<type, date>)
                return is_date();
            else if constexpr (std::is_same_v<type, time>)
                return is_time();
            else if constexpr (std::is_same_v<type, date_time>)
                return is_date_time();
        }
References TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
is_array()
bool toml::v3::array::is_array () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6081 of file toml.h.
        {
            return true;
        }
is_array_of_tables()
bool toml::v3::array::is_array_of_tables () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6087 of file toml.h.
        {
            return is_homogeneous(node_type::table);
        }
is_boolean()
bool toml::v3::array::is_boolean () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6123 of file toml.h.
        {
            return false;
        }
is_date()
bool toml::v3::array::is_date () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6129 of file toml.h.
        {
            return false;
        }
is_date_time()
bool toml::v3::array::is_date_time () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6141 of file toml.h.
        {
            return false;
        }
is_floating_point()
bool toml::v3::array::is_floating_point () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6111 of file toml.h.
        {
            return false;
        }
is_homogeneous() [1/4]
template<typename ElemType = void> bool toml::v3::array::is_homogeneous () const inline noexcept
Definition at line 6065 of file toml.h.
        {
            using type = impl::remove_cvref<impl::unwrap_node<ElemType>>;
            static_assert(std::is_void_v<type> || toml::is_value<type> || toml::is_container<type>,
                          "The template type argument of array::is_homogeneous() must be void or one "
                          "of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
            return is_homogeneous(impl::node_type_of<type>);
        }
References TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
is_homogeneous() [2/4]
bool toml::v3::array::is_homogeneous (node_type ntype) const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 11368 of file toml.h.
    {
        if (elems_.empty())
            return false;
        if (ntype == node_type::none)
            ntype = elems_[0]->type();
        for (const auto& val : elems_)
            if (val->type() != ntype)
                return false;
        return true;
    }
References toml::v3::none.
is_homogeneous() [3/4]
bool toml::v3::array::is_homogeneous (node_type ntype, const node *& first_nonmatch) const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 11407 of file toml.h.
    {
        node* fnm = nullptr;
        const auto result = const_cast<array&>(*this).is_homogeneous(ntype, fnm);
        first_nonmatch = fnm;
        return result;
    }
References is_homogeneous().
is_homogeneous() [4/4]
bool toml::v3::array::is_homogeneous (node_type ntype, node *& first_nonmatch) inline final virtual noexcept
Implements toml::v3::node.
Definition at line 11385 of file toml.h.
    {
        if (elems_.empty())
        {
            first_nonmatch = {};
            return false;
        }
        if (ntype == node_type::none)
            ntype = elems_[0]->type();
        for (const auto& val : elems_)
        {
            if (val->type() != ntype)
            {
                first_nonmatch = val.get();
                return false;
            }
        }
        return true;
    }
References toml::v3::none.
is_integer()
bool toml::v3::array::is_integer () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6105 of file toml.h.
        {
            return false;
        }
is_number()
bool toml::v3::array::is_number () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6117 of file toml.h.
        {
            return false;
        }
is_string()
bool toml::v3::array::is_string () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6099 of file toml.h.
        {
            return false;
        }
is_table()
bool toml::v3::array::is_table () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6075 of file toml.h.
        {
            return false;
        }
is_time()
bool toml::v3::array::is_time () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6135 of file toml.h.
        {
            return false;
        }
is_value()
bool toml::v3::array::is_value () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6093 of file toml.h.
        {
            return false;
        }
max_size()
size_t toml::v3::array::max_size () const inline noexcept
Definition at line 6545 of file toml.h.
        {
            return elems_.max_size();
        }
operator node_view< const node >()
toml::v3::node::operator node_view< const node > () const inline explicit noexcept inherited
Definition at line 4489 of file toml.h.
    {
        return node_view<const node>{ this };
    }
operator node_view< node >()
toml::v3::node::operator node_view< node > () inline explicit noexcept inherited
Definition at line 4484 of file toml.h.
    {
        return node_view<node>{ this };
    }
operator=() [1/2]
array & toml::v3::array::operator= (array && rhs) inline noexcept
Definition at line 11327 of file toml.h.
    {
        if (&rhs != this)
        {
            node::operator=(std::move(rhs));
            elems_ = std::move(rhs.elems_);
        }
        return *this;
    }
References toml::v3::node::operator=().
operator=() [2/2]
array & toml::v3::array::operator= (const array & rhs) inline
Definition at line 11313 of file toml.h.
    {
        if (&rhs != this)
        {
            node::operator=(rhs);
            elems_.clear();
            elems_.reserve(rhs.elems_.size());
            for (const auto& elem : rhs)
                elems_.emplace_back(impl::make_node(elem));
        }
        return *this;
    }
References toml::v3::impl::make_node(), and toml::v3::node::operator=().
operator[]() [1/4]
node_view< const node > toml::v3::node::operator[] (const toml::path & path) const noexcept inherited
operator[]() [2/4]
node_view< node > toml::v3::node::operator[] (const toml::path & path) noexcept inherited
operator[]() [3/4]
const node & toml::v3::array::operator[] (size_t index) const inline noexcept
Definition at line 6290 of file toml.h.
        {
            return *elems_[index];
        }
operator[]() [4/4]
node & toml::v3::array::operator[] (size_t index) inline noexcept
Definition at line 6284 of file toml.h.
        {
            return *elems_[index];
        }
pop_back()
void toml::v3::array::pop_back () inline noexcept
Definition at line 11568 of file toml.h.
    {
        elems_.pop_back();
    }
prune() [1/2]
array && toml::v3::array::prune (bool recursive = true) && inline noexcept
Definition at line 6598 of file toml.h.
        {
            return static_cast<toml::array&&>(this->prune(recursive));
        }
prune() [2/2]
array & toml::v3::array::prune (bool recursive = true) & inline noexcept
Definition at line 11541 of file toml.h.
    {
        if (elems_.empty())
            return *this;
        for (size_t i = elems_.size(); i-- > 0u;)
        {
            if (auto arr = elems_[i]->as_array())
            {
                if (recursive)
                    arr->prune(true);
                if (arr->empty())
                    elems_.erase(elems_.cbegin() + static_cast<ptrdiff_t>(i));
            }
            else if (auto tbl = elems_[i]->as_table())
            {
                if (recursive)
                    tbl->prune(true);
                if (tbl->empty())
                    elems_.erase(elems_.cbegin() + static_cast<ptrdiff_t>(i));
            }
        }
        return *this;
    }
References erase(), and prune().
push_back()
template<typename ElemType > void toml::v3::array::push_back (ElemType && val, value_flags flags = preserve_source_value_flags) inline
Definition at line 6728 of file toml.h.
        {
            emplace_back_if_not_empty_view(static_cast<ElemType&&>(val), flags);
        }
ref() [1/4]
template<typename T > decltype(auto) toml::v3::node::ref () && inline noexcept inherited
Definition at line 3723 of file toml.h.
        {
            return do_ref<T>(std::move(*this));
        }
ref() [2/4]
template<typename T > decltype(auto) toml::v3::node::ref () & inline noexcept inherited
Definition at line 3716 of file toml.h.
        {
            return do_ref<T>(*this);
        }
ref() [3/4]
template<typename T > decltype(auto) toml::v3::node::ref () const && inline noexcept inherited
Definition at line 3737 of file toml.h.
        {
            return do_ref<T>(std::move(*this));
        }
ref() [4/4]
template<typename T > decltype(auto) toml::v3::node::ref () const & inline noexcept inherited
Definition at line 3730 of file toml.h.
        {
            return do_ref<T>(*this);
        }
ref_cast() [1/4]
template<typename T > ref_cast_type< T, node && > toml::v3::node::ref_cast () && inline protected noexcept inherited
Definition at line 3475 of file toml.h.
        {
            using out_ref = ref_cast_type<T, node&&>;
            using out_type = std::remove_reference_t<out_ref>;
            return static_cast<out_ref>(*reinterpret_cast<out_type*>(this));
        }
ref_cast() [2/4]
template<typename T > ref_cast_type< T, node & > toml::v3::node::ref_cast () & inline protected noexcept inherited
Definition at line 3466 of file toml.h.
        {
            using out_ref = ref_cast_type<T, node&>;
            using out_type = std::remove_reference_t<out_ref>;
            return static_cast<out_ref>(*reinterpret_cast<out_type*>(this));
        }
ref_cast() [3/4]
template<typename T > ref_cast_type< T, const node && > toml::v3::node::ref_cast () const && inline protected noexcept inherited
Definition at line 3493 of file toml.h.
        {
            using out_ref = ref_cast_type<T, const node&&>;
            using out_type = std::remove_reference_t<out_ref>;
            return static_cast<out_ref>(*reinterpret_cast<out_type*>(this));
        }
ref_cast() [4/4]
template<typename T > ref_cast_type< T, const node & > toml::v3::node::ref_cast () const & inline protected noexcept inherited
Definition at line 3484 of file toml.h.
        {
            using out_ref = ref_cast_type<T, const node&>;
            using out_type = std::remove_reference_t<out_ref>;
            return static_cast<out_ref>(*reinterpret_cast<out_type*>(this));
        }
replace()
template<typename ElemType > iterator toml::v3::array::replace (const_iterator pos, ElemType && val, value_flags flags = preserve_source_value_flags) inline
Definition at line 6712 of file toml.h.
        {
            TOML_ASSERT(pos >= cbegin() && pos < cend());
            if constexpr (is_node_view<ElemType>)
            {
                if (!val)
                    return end();
            }
            const auto it = elems_.begin() + (const_vector_iterator{ pos } - elems_.cbegin());
            *it = impl::make_node(static_cast<ElemType&&>(val), flags);
            return iterator{ it };
        }
References TOML_ASSERT.
reserve()
void toml::v3::array::reserve (size_t new_capacity) inline
Definition at line 11432 of file toml.h.
    {
        elems_.reserve(new_capacity);
    }
resize()
template<typename ElemType > void toml::v3::array::resize (size_t new_size, ElemType && default_init_val, value_flags default_init_flags = preserve_source_value_flags) inline
Definition at line 6566 of file toml.h.
        {
            static_assert(!is_node_view<ElemType>,
                          "The default element type argument to toml::array::resize may not be toml::node_view.");
            if (!new_size)
                clear();
            else if (new_size > elems_.size())
                insert(cend(), new_size - elems_.size(), static_cast<ElemType&&>(default_init_val), default_init_flags);
            else
                truncate(new_size);
        }
shrink_to_fit()
void toml::v3::array::shrink_to_fit () inline
Definition at line 11438 of file toml.h.
    {
        elems_.shrink_to_fit();
    }
size()
size_t toml::v3::array::size () const inline noexcept
Definition at line 6539 of file toml.h.
        {
            return elems_.size();
        }
source()
const source_region & toml::v3::node::source () const inline noexcept inherited
Definition at line 3743 of file toml.h.
        {
            return source_;
        }
truncate()
void toml::v3::array::truncate (size_t new_size) inline
Definition at line 11444 of file toml.h.
    {
        if (new_size < elems_.size())
            elems_.resize(new_size);
    }
type()
node_type toml::v3::array::type () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 6046 of file toml.h.
        {
            return node_type::array;
        }
value()
template<typename T > optional< T > toml::v3::node::value () const inline noexcept inherited
Definition at line 5363 of file toml.h.
    {
        using namespace impl;
        static_assert(!is_wide_string<T> || TOML_ENABLE_WINDOWS_COMPAT,
                      "Retrieving values as wide-character strings with node::value() is only "
                      "supported on Windows with TOML_ENABLE_WINDOWS_COMPAT enabled.");
        static_assert((is_native<T> || can_represent_native<T> || can_partially_represent_native<T>) && !is_cvref<T>,
                      TOML_SA_VALUE_FUNC_MESSAGE("return type of node::value()"));
        // when asking for strings, dates, times and date_times there's no 'fuzzy' conversion
        // semantics to be mindful of so the exact retrieval is enough.
        if constexpr (is_natively_one_of<T, std::string, time, date, date_time>)
        {
            if (type() == node_type_of<T>)
                return { this->get_value_exact<T>() };
            else
                return {};
        }
        // everything else requires a bit of logicking.
        else
        {
            switch (type())
            {
                // int -> *
                case node_type::integer:
                {
                    // int -> int
                    if constexpr (is_natively_one_of<T, int64_t>)
                    {
                        if constexpr (is_native<T> || can_represent_native<T>)
                            return static_cast<T>(*ref_cast<int64_t>());
                        else
                            return node_integer_cast<T>(*ref_cast<int64_t>());
                    }
                    // int -> float
                    else if constexpr (is_natively_one_of<T, double>)
                    {
                        const int64_t val = *ref_cast<int64_t>();
                        if constexpr (std::numeric_limits<T>::digits < 64)
{
                            constexpr auto largest_whole_float = (int64_t{ 1 } << std::numeric_limits<T>::digits);
                            if (val < -largest_whole_float || val > largest_whole_float)
                                return {};
                        }
                        return static_cast<T>(val);
                    }
                    // int -> bool
                    else if constexpr (is_natively_one_of<T, bool>)
                        return static_cast<bool>(*ref_cast<int64_t>());
                    // int -> anything else
                    else
                        return {};
                }
                // float -> *
                case node_type::floating_point:
                {
                    // float -> float
                    if constexpr (is_natively_one_of<T, double>)
                    {
                        if constexpr (is_native<T> || can_represent_native<T>)
                            return { static_cast<T>(*ref_cast<double>()) };
                        else
{
                            const double val = *ref_cast<double>();
                            if (impl::fpclassify(val) == fp_class::ok
                                && (val < (std::numeric_limits<T>::lowest)() || val >(std::numeric_limits<T>::max)()))
                                return {};
                            return { static_cast<T>(val) };
                        }
                    }
                    // float -> int
                    else if constexpr (is_natively_one_of<T, int64_t>)
                    {
                        const double val = *ref_cast<double>();
                        if (impl::fpclassify(val) == fp_class::ok
                            && static_cast<double>(static_cast<int64_t>(val)) == val)
                            return node_integer_cast<T>(static_cast<int64_t>(val));
                        else
                            return {};
                    }
                    // float -> anything else
                    else
                        return {};
                }
                // bool -> *
                case node_type::boolean:
                {
                    // bool -> bool
                    if constexpr (is_natively_one_of<T, bool>)
                        return { *ref_cast<bool>() };
                    // bool -> int
                    else if constexpr (is_natively_one_of<T, int64_t>)
                        return { static_cast<T>(*ref_cast<bool>()) };
                    // bool -> anything else
                    else
                        return {};
                }
            }
            // non-values, or 'exact' types covered above
            return {};
        }
    }
References TOML_ENABLE_WINDOWS_COMPAT, and TOML_SA_VALUE_FUNC_MESSAGE.
value_exact()
template<typename T > optional< T > toml::v3::node::value_exact () const inline noexcept inherited
Definition at line 5340 of file toml.h.
    {
        using namespace impl;
        static_assert(!is_wide_string<T> || TOML_ENABLE_WINDOWS_COMPAT,
                      "Retrieving values as wide-character strings with node::value_exact() is only "
                      "supported on Windows with TOML_ENABLE_WINDOWS_COMPAT enabled.");
        static_assert((is_native<T> || can_represent_native<T>) && !is_cvref<T>,
                      TOML_SA_VALUE_EXACT_FUNC_MESSAGE("return type of node::value_exact()"));
        // prevent additional compiler error spam when the static_assert fails by gating behind if constexpr
        if constexpr ((is_native<T> || can_represent_native<T>) && !is_cvref<T>)
        {
            if (type() == node_type_of<T>)
                return { this->get_value_exact<T>() };
            else
                return {};
        }
    }
References TOML_ENABLE_WINDOWS_COMPAT, and TOML_SA_VALUE_EXACT_FUNC_MESSAGE.
value_or()
template<typename T > auto toml::v3::node::value_or (T && default_value) const inline noexcept inherited
Definition at line 5480 of file toml.h.
    {
        using namespace impl;
        static_assert(!is_wide_string<T> || TOML_ENABLE_WINDOWS_COMPAT,
                      "Retrieving values as wide-character strings with node::value_or() is only "
                      "supported on Windows with TOML_ENABLE_WINDOWS_COMPAT enabled.");
        if constexpr (is_wide_string<T>)
        {
#if TOML_ENABLE_WINDOWS_COMPAT
            if (type() == node_type::string)
                return widen(*ref_cast<std::string>());
            return std::wstring{ static_cast<T&&>(default_value) };
#else
            static_assert(dependent_false<T>, "Evaluated unreachable branch!");
#endif
        }
        else
        {
            using value_type =
                std::conditional_t<std::is_pointer_v<std::decay_t<T>>,
                                   std::add_pointer_t<std::add_const_t<std::remove_pointer_t<std::decay_t<T>>>>,
                                   std::decay_t<T>>;
            using traits = value_traits<value_type>;
            // clang-format off
            static_assert(
                traits::is_native || traits::can_represent_native || traits::can_partially_represent_native,
                "The default value type of node::value_or() must be one of:"
                TOML_SA_LIST_NEW "A native TOML value type"
                TOML_SA_NATIVE_VALUE_TYPE_LIST
                TOML_SA_LIST_NXT "A non-view type capable of losslessly representing a native TOML value type"
                TOML_SA_LIST_BEG "std::string"
                #if TOML_ENABLE_WINDOWS_COMPAT
                TOML_SA_LIST_SEP "std::wstring"
                #endif
                TOML_SA_LIST_SEP "any signed integer type >= 64 bits"
                TOML_SA_LIST_SEP "any floating-point type >= 64 bits"
                TOML_SA_LIST_END
                TOML_SA_LIST_NXT "A non-view type capable of (reasonably) representing a native TOML value type"
                TOML_SA_LIST_BEG "any other integer type"
                TOML_SA_LIST_SEP "any floating-point type"
                TOML_SA_LIST_END
                TOML_SA_LIST_NXT "A compatible view type"
                TOML_SA_LIST_BEG "std::string_view"
                #if TOML_HAS_CHAR8
                TOML_SA_LIST_SEP "std::u8string_view"
                #endif
                #if TOML_ENABLE_WINDOWS_COMPAT
                TOML_SA_LIST_SEP "std::wstring_view"
                #endif
                TOML_SA_LIST_SEP "const char*"
                #if TOML_HAS_CHAR8
                TOML_SA_LIST_SEP "const char8_t*"
                #endif
                #if TOML_ENABLE_WINDOWS_COMPAT
                TOML_SA_LIST_SEP "const wchar_t*"
                #endif
                TOML_SA_LIST_END
            );
            // clang-format on
            // prevent additional compiler error spam when the static_assert fails by gating behind if constexpr
            if constexpr (traits::is_native || traits::can_represent_native || traits::can_partially_represent_native)
            {
                if constexpr (traits::is_native)
                {
                    if (type() == node_type_of<value_type>)
                        return *ref_cast<typename traits::native_type>();
                }
                if (auto val = this->value<value_type>())
                    return *val;
                if constexpr (std::is_pointer_v<value_type>)
                    return value_type{ default_value };
                else
                    return static_cast<T&&>(default_value);
            }
        }
    }
References TOML_ENABLE_WINDOWS_COMPAT, TOML_SA_LIST_BEG, TOML_SA_LIST_END, TOML_SA_LIST_NEW, TOML_SA_LIST_NXT, TOML_SA_LIST_SEP, and TOML_SA_NATIVE_VALUE_TYPE_LIST.
visit() [1/4]
template<typename Func > decltype(auto) toml::v3::node::visit (Func && visitor) && inline noexcept inherited
Definition at line 3907 of file toml.h.
        {
            return do_visit(static_cast<Func&&>(visitor), static_cast<node&&>(*this));
        }
visit() [2/4]
template<typename Func > decltype(auto) toml::v3::node::visit (Func && visitor) & inline noexcept inherited
Definition at line 3901 of file toml.h.
        {
            return do_visit(static_cast<Func&&>(visitor), *this);
        }
visit() [3/4]
template<typename Func > decltype(auto) toml::v3::node::visit (Func && visitor) const && inline noexcept inherited
Definition at line 3919 of file toml.h.
        {
            return do_visit(static_cast<Func&&>(visitor), static_cast<const node&&>(*this));
        }
visit() [4/4]
template<typename Func > decltype(auto) toml::v3::node::visit (Func && visitor) const & inline noexcept inherited
Definition at line 3913 of file toml.h.
        {
            return do_visit(static_cast<Func&&>(visitor), *this);
        }
Friends And Related Symbol Documentation
operator!= [1/5]
bool operator!= (const array & lhs, const array & rhs) friend
Definition at line 6805 of file toml.h.
        {
            return !equal(lhs, rhs);
        }
operator!= [2/5]
template<typename T > bool operator!= (const array & lhs, const std::initializer_list< T > & rhs) friend
Definition at line 6816 of file toml.h.
operator!= [3/5]
template<typename T > bool operator!= (const array & lhs, const std::vector< T > & rhs) friend
Definition at line 6824 of file toml.h.
operator!= [4/5]
template<typename T > bool operator!= (const std::initializer_list< T > & rhs, const array & lhs) friend
Definition at line 6816 of file toml.h.
operator!= [5/5]
template<typename T > bool operator!= (const std::vector< T > & rhs, const array & lhs) friend
Definition at line 6824 of file toml.h.
operator<<
std::ostream & operator<< (std::ostream & lhs, const array & rhs) friend
Definition at line 6828 of file toml.h.
        {
            impl::print_to_stream(lhs, rhs);
            return lhs;
        }
operator== [1/5]
bool operator== (const array & lhs, const array & rhs) friend
Definition at line 6799 of file toml.h.
        {
            return equal(lhs, rhs);
        }
operator== [2/5]
template<typename T > bool operator== (const array & lhs, const std::initializer_list< T > & rhs) friend
Definition at line 6812 of file toml.h.
        {
            return equal_to_container(lhs, rhs);
        }
operator== [3/5]
template<typename T > bool operator== (const array & lhs, const std::vector< T > & rhs) friend
Definition at line 6820 of file toml.h.
        {
            return equal_to_container(lhs, rhs);
        }
operator== [4/5]
template<typename T > bool operator== (const std::initializer_list< T > & rhs, const array & lhs) friend
Definition at line 6816 of file toml.h.
operator== [5/5]
template<typename T > bool operator== (const std::vector< T > & rhs, const array & lhs) friend
Definition at line 6824 of file toml.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/toml.h