Techstorm-rivalry: raylib::Model Class Reference
raylib::Model Class Reference
#include <Model.hpp>
Public Member Functions
Model ()
Model (const ::Model &model)
Model (const std::string &fileName)
Model (const ::Mesh &mesh)
~Model ()
Model (const Model &)=delete
Model (Model &&other)
::Matrix GetTransform () const
void SetTransform (::Matrix value)
int GetMeshCount () const
void SetMeshCount (int value)
int GetMaterialCount () const
void SetMaterialCount (int value)
::Mesh * GetMeshes () const
void SetMeshes (::Mesh *value)
::Material * GetMaterials () const
void SetMaterials (::Material *value)
int * GetMeshMaterial () const
void SetMeshMaterial (int *value)
int GetBoneCount () const
void SetBoneCount (int value)
::BoneInfo * GetBones () const
void SetBones (::BoneInfo *value)
::Transform * GetBindPose () const
void SetBindPose (::Transform *value)
Model & operator= (const ::Model &model)
Model & operator= (const Model &)=delete
Model & operator= (Model &&other) noexcept
void Unload ()
Model & SetMeshMaterial (int meshId, int materialId)
Model & UpdateAnimation (const ::ModelAnimation &anim, int frame)
bool IsModelAnimationValid (const ::ModelAnimation &anim) const
void Draw (::Vector3 position, float scale=1.0f, ::Color tint={255, 255, 255, 255}) const
void Draw (::Vector3 position, ::Vector3 rotationAxis, float rotationAngle=0.0f, ::Vector3 scale={1.0f, 1.0f, 1.0f}, ::Color tint={255, 255, 255, 255}) const
void DrawWires (::Vector3 position, float scale=1.0f, ::Color tint={255, 255, 255, 255}) const
void DrawWires (::Vector3 position, ::Vector3 rotationAxis, float rotationAngle=0.0f, ::Vector3 scale={1.0f, 1.0f, 1.0f}, ::Color tint={255, 255, 255, 255}) const
BoundingBox GetBoundingBox () const
operator BoundingBox () const
bool IsReady () const
void Load (const std::string &fileName)
void Load (const ::Mesh &mesh)
Public Attributes
Matrix transform
int meshCount
int materialCount
Mesh * meshes
Material * materials
int * meshMaterial
int boneCount
BoneInfo * bones
Transform * bindPose
Protected Member Functions
void set (const ::Model &model)
Detailed Description
Model type
Definition at line 15 of file Model.hpp.
Constructor & Destructor Documentation
Model() [1/6]
raylib::Model::Model () inline
Definition at line 17 of file Model.hpp.
            {
        // Nothing.
    }
Model() [2/6]
raylib::Model::Model (const ::Model & model) inline
Definition at line 24 of file Model.hpp.
{
        set(model);
    }
References set().
Model() [3/6]
raylib::Model::Model (const std::string & fileName) inline
Definition at line 33 of file Model.hpp.
{
        Load(fileName);
    }
References Load().
Model() [4/6]
raylib::Model::Model (const ::Mesh & mesh) inline
Definition at line 42 of file Model.hpp.
{
        Load(mesh);
    }
References Load().
~Model()
raylib::Model::~Model () inline
Definition at line 46 of file Model.hpp.
             {
        Unload();
    }
References Unload().
Model() [5/6]
raylib::Model::Model (const Model &) delete
Model() [6/6]
raylib::Model::Model (Model && other) inline
Definition at line 52 of file Model.hpp.
{
        set(other);
        other.meshCount = 0;
        other.materialCount = 0;
        other.meshes = nullptr;
        other.materials = nullptr;
        other.meshMaterial = nullptr;
        other.boneCount = 0;
        other.bones = nullptr;
        other.bindPose = nullptr;
    }
References set().
Member Function Documentation
Draw() [1/2]
void raylib::Model::Draw (::Vector3 position, ::Vector3 rotationAxis, float rotationAngle = 0.0f, ::Vector3 scale = {1.0f, 1.0f, 1.0f}, ::Color tint = {255, 255, 255, 255}) const inline
Draw a model with extended parameters
Definition at line 148 of file Model.hpp.
                            {1.0f, 1.0f, 1.0f},
            ::Color tint = {255, 255, 255, 255}) const {
        ::DrawModelEx(*this, position, rotationAxis, rotationAngle, scale, tint);
    }
Draw() [2/2]
void raylib::Model::Draw (::Vector3 position, float scale = 1.0f, ::Color tint = {255, 255, 255, 255}) const inline
Draw a model (with texture if set)
Definition at line 139 of file Model.hpp.
                         {255, 255, 255, 255}) const {
        ::DrawModel(*this, position, scale, tint);
    }
DrawWires() [1/2]
void raylib::Model::DrawWires (::Vector3 position, ::Vector3 rotationAxis, float rotationAngle = 0.0f, ::Vector3 scale = {1.0f, 1.0f, 1.0f}, ::Color tint = {255, 255, 255, 255}) const inline
Draw a model wires (with texture if set) with extended parameters
Definition at line 169 of file Model.hpp.
                            {1.0f, 1.0f, 1.0f},
            ::Color tint = {255, 255, 255, 255}) const {
        ::DrawModelWiresEx(*this, position, rotationAxis, rotationAngle, scale, tint);
    }
DrawWires() [2/2]
void raylib::Model::DrawWires (::Vector3 position, float scale = 1.0f, ::Color tint = {255, 255, 255, 255}) const inline
Draw a model wires (with texture if set)
Definition at line 160 of file Model.hpp.
                         {255, 255, 255, 255}) const {
        ::DrawModelWires(*this, position, scale, tint);
    }
GetBindPose()
::Transform * raylib::Model::GetBindPose () const inline
Retrieves the bindPose value for the object.
Returns
The bindPose value of the object.
Definition at line 73 of file Model.hpp.
GetBoneCount()
int raylib::Model::GetBoneCount () const inline
Retrieves the boneCount value for the object.
Returns
The boneCount value of the object.
Definition at line 71 of file Model.hpp.
GetBones()
::BoneInfo * raylib::Model::GetBones () const inline
Retrieves the bones value for the object.
Returns
The bones value of the object.
Definition at line 72 of file Model.hpp.
GetBoundingBox()
BoundingBox raylib::Model::GetBoundingBox () const inline
Compute model bounding box limits (considers all meshes)
Definition at line 181 of file Model.hpp.
{
        return ::GetModelBoundingBox(*this);
    }
GetMaterialCount()
int raylib::Model::GetMaterialCount () const inline
Retrieves the materialCount value for the object.
Returns
The materialCount value of the object.
Definition at line 67 of file Model.hpp.
GetMaterials()
::Material * raylib::Model::GetMaterials () const inline
Retrieves the materials value for the object.
Returns
The materials value of the object.
Definition at line 69 of file Model.hpp.
GetMeshCount()
int raylib::Model::GetMeshCount () const inline
Retrieves the meshCount value for the object.
Returns
The meshCount value of the object.
Definition at line 66 of file Model.hpp.
GetMeshes()
::Mesh * raylib::Model::GetMeshes () const inline
Retrieves the meshes value for the object.
Returns
The meshes value of the object.
Definition at line 68 of file Model.hpp.
GetMeshMaterial()
int * raylib::Model::GetMeshMaterial () const inline
Retrieves the meshMaterial value for the object.
Returns
The meshMaterial value of the object.
Definition at line 70 of file Model.hpp.
GetTransform()
::Matrix raylib::Model::GetTransform () const inline
Retrieves the transform value for the object.
Returns
The transform value of the object.
Definition at line 65 of file Model.hpp.
IsModelAnimationValid()
bool raylib::Model::IsModelAnimationValid (const ::ModelAnimation & anim) const inline
Check model animation skeleton match
Definition at line 132 of file Model.hpp.
{
        return ::IsModelAnimationValid(*this, anim);
    }
IsReady()
bool raylib::Model::IsReady () const inline
Determines whether or not the Model has data in it.
Definition at line 195 of file Model.hpp.
{
        return ::IsModelReady(*this);
    }
Load() [1/2]
void raylib::Model::Load (const ::Mesh & mesh) inline
Loads a Model from the given Mesh.
Exceptions
raylib::RaylibException Throws if failed to load the Modal.
Definition at line 216 of file Model.hpp.
{
        set(::LoadModelFromMesh(mesh));
        if (!IsReady()) {
            throw RaylibException("Failed to load Model from Mesh");
        }
    }
References IsReady(), LoadModelFromMesh(), and set().
Load() [2/2]
void raylib::Model::Load (const std::string & fileName) inline
Loads a Model from the given file.
Exceptions
raylib::RaylibException Throws if failed to load the Modal.
Definition at line 204 of file Model.hpp.
{
        set(::LoadModel(fileName.c_str()));
        if (!IsReady()) {
            throw RaylibException("Failed to load Model from " + fileName);
        }
    }
References IsReady(), LoadModel(), and set().
operator BoundingBox()
raylib::Model::operator BoundingBox () const inline
Compute model bounding box limits (considers all meshes)
Definition at line 188 of file Model.hpp.
{
        return ::GetModelBoundingBox(*this);
    }
operator=() [1/3]
Model & raylib::Model::operator= (const ::Model & model) inline
Definition at line 75 of file Model.hpp.
{
        set(model);
        return *this;
    }
References set().
operator=() [2/3]
Model & raylib::Model::operator= (const Model &) delete
operator=() [3/3]
Model & raylib::Model::operator= (Model && other) inline noexcept
Definition at line 82 of file Model.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.meshCount = 0;
        other.materialCount = 0;
        other.meshes = nullptr;
        other.materials = nullptr;
        other.meshMaterial = nullptr;
        other.boneCount = 0;
        other.bones = nullptr;
        other.bindPose = nullptr;
        return *this;
    }
References set(), and Unload().
set()
void raylib::Model::set (const ::Model & model) inline protected
Definition at line 224 of file Model.hpp.
{
        transform = model.transform;
        meshCount = model.meshCount;
        materialCount = model.materialCount;
        meshes = model.meshes;
        materials = model.materials;
        meshMaterial = model.meshMaterial;
        boneCount = model.boneCount;
        bones = model.bones;
        bindPose = model.bindPose;
    }
References Model::bindPose, Model::boneCount, Model::bones, Model::materialCount, Model::materials, Model::meshCount, Model::meshes, Model::meshMaterial, and Model::transform.
SetBindPose()
void raylib::Model::SetBindPose (::Transform * value) inline
Sets the bindPose value for the object.
Parameters
value The value of which to set bindPose to.
Definition at line 73 of file Model.hpp.
SetBoneCount()
void raylib::Model::SetBoneCount (int value) inline
Sets the boneCount value for the object.
Parameters
value The value of which to set boneCount to.
Definition at line 71 of file Model.hpp.
SetBones()
void raylib::Model::SetBones (::BoneInfo * value) inline
Sets the bones value for the object.
Parameters
value The value of which to set bones to.
Definition at line 72 of file Model.hpp.
SetMaterialCount()
void raylib::Model::SetMaterialCount (int value) inline
Sets the materialCount value for the object.
Parameters
value The value of which to set materialCount to.
Definition at line 67 of file Model.hpp.
SetMaterials()
void raylib::Model::SetMaterials (::Material * value) inline
Sets the materials value for the object.
Parameters
value The value of which to set materials to.
Definition at line 69 of file Model.hpp.
SetMeshCount()
void raylib::Model::SetMeshCount (int value) inline
Sets the meshCount value for the object.
Parameters
value The value of which to set meshCount to.
Definition at line 66 of file Model.hpp.
SetMeshes()
void raylib::Model::SetMeshes (::Mesh * value) inline
Sets the meshes value for the object.
Parameters
value The value of which to set meshes to.
Definition at line 68 of file Model.hpp.
SetMeshMaterial() [1/2]
void raylib::Model::SetMeshMaterial (int * value) inline
Sets the meshMaterial value for the object.
Parameters
value The value of which to set meshMaterial to.
Definition at line 70 of file Model.hpp.
SetMeshMaterial() [2/2]
Model & raylib::Model::SetMeshMaterial (int meshId, int materialId) inline
Set material for a mesh
Definition at line 116 of file Model.hpp.
{
        ::SetModelMeshMaterial(this, meshId, materialId);
        return *this;
    }
References SetModelMeshMaterial().
SetTransform()
void raylib::Model::SetTransform (::Matrix value) inline
Sets the transform value for the object.
Parameters
value The value of which to set transform to.
Definition at line 65 of file Model.hpp.
Unload()
void raylib::Model::Unload () inline
Unload model (including meshes) from memory (RAM and/or VRAM)
Definition at line 105 of file Model.hpp.
{
        if (meshes != nullptr || materials != nullptr) {
            ::UnloadModel(*this);
            meshes = nullptr;
            materials = nullptr;
        }
    }
References Model::materials, Model::meshes, and UnloadModel().
UpdateAnimation()
Model & raylib::Model::UpdateAnimation (const ::ModelAnimation & anim, int frame) inline
Update model animation pose
Definition at line 124 of file Model.hpp.
{
        ::UpdateModelAnimation(*this, anim, frame);
        return *this;
    }
References UpdateModelAnimation().
Member Data Documentation
bindPose
Transform* Model::bindPose inherited
Definition at line 404 of file raylib.h.
boneCount
int Model::boneCount inherited
Definition at line 402 of file raylib.h.
bones
BoneInfo* Model::bones inherited
Definition at line 403 of file raylib.h.
materialCount
int Model::materialCount inherited
Definition at line 396 of file raylib.h.
materials
Material* Model::materials inherited
Definition at line 398 of file raylib.h.
meshCount
int Model::meshCount inherited
Definition at line 395 of file raylib.h.
meshes
Mesh* Model::meshes inherited
Definition at line 397 of file raylib.h.
meshMaterial
int* Model::meshMaterial inherited
Definition at line 399 of file raylib.h.
transform
Matrix Model::transform inherited
Definition at line 393 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Model.hpp