Techstorm-rivalry: ConfigRegistry Class Reference
ConfigRegistry Class Reference
The ConfigRegistry class manages a registry of configuration files.
#include <Configman.h>
Public Member Functions
ConfigRegistry ()
Constructor for ConfigRegistry.
~ConfigRegistry ()
Destructor for ConfigRegistry.
bool IsFileRegistered (const char *FileName)
Check if a file is registered in the registry.
ConfigFile GetFile (const char *FileName)
Get a configuration file from the registry.
void RegisterFile (const char *FileName)
Register a configuration file into the registry.
int Flush ()
Flush the registry, WILL NOT SAVE!
Public Attributes
ConfigRegistrySecretary * ConfigSecretary = new ConfigRegistrySecretary()
Detailed Description
The ConfigRegistry class manages a registry of configuration files.
Definition at line 243 of file Configman.h.
Constructor & Destructor Documentation
ConfigRegistry()
ConfigRegistry::ConfigRegistry () inline
Constructor for ConfigRegistry.
Definition at line 249 of file Configman.h.
                     {
    }
~ConfigRegistry()
ConfigRegistry::~ConfigRegistry () inline
Destructor for ConfigRegistry.
Definition at line 255 of file Configman.h.
                      {
        delete ConfigSecretary;
    }
References ConfigSecretary.
Member Function Documentation
Flush()
int ConfigRegistry::Flush () inline
Flush the registry, WILL NOT SAVE!
Returns
1 if the registry is empty, 0 otherwise.
Definition at line 292 of file Configman.h.
    {
        ConfigFile::Flush();
        bool issuccessful = registry.empty();
        return issuccessful;
    }
References ConfigFile::Flush().
GetFile()
ConfigFile ConfigRegistry::GetFile (const char * FileName) inline
Get a configuration file from the registry.
Parameters
FileName The name of the file to get.
Returns
The configuration file.
Definition at line 274 of file Configman.h.
    {
        return ConfigSecretary->FindFile(registry, FileName);
    }
References ConfigSecretary, and ConfigRegistrySecretary::FindFile().
IsFileRegistered()
bool ConfigRegistry::IsFileRegistered (const char * FileName) inline
Check if a file is registered in the registry.
Parameters
FileName The name of the file to check.
Returns
True if the file is registered, false otherwise.
Definition at line 264 of file Configman.h.
    {
        return ConfigSecretary->DoesFileExist(registry, FileName);
    }
References ConfigSecretary, and ConfigRegistrySecretary::DoesFileExist().
RegisterFile()
void ConfigRegistry::RegisterFile (const char * FileName) inline
Register a configuration file into the registry.
Parameters
FileName The name of the file to register.
Definition at line 283 of file Configman.h.
    {
        registry.push_back(ConfigFile(FileName));
    }
Member Data Documentation
ConfigSecretary
ConfigRegistrySecretary* ConfigRegistry::ConfigSecretary = new ConfigRegistrySecretary()
Definition at line 299 of file Configman.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Configman.h