Techstorm-rivalry: raylib::Window Class Reference
raylib::Window Class Reference
#include <Window.hpp>
Public Member Functions
Window ()
Window (int width, int height, const std::string &title="raylib", unsigned int flags=0)
~Window ()
void Init (int width=800, int height=450, const std::string &title="raylib", unsigned int flags=0)
bool ShouldClose () const
void Close ()
bool IsCursorOnScreen () const
bool IsFullscreen () const
bool IsHidden () const
bool IsMinimized () const
bool IsMaximized () const
bool IsFocused () const
bool IsResized () const
bool IsState (unsigned int flag) const
Window & SetState (unsigned int flag)
Window & ClearState (unsigned int flag)
Window & ClearBackground (const ::Color &color=(Color){ 0, 0, 0, 255 })
Window & ToggleFullscreen ()
Window & SetFullscreen (bool fullscreen)
Window & ToggleBorderless ()
Window & Maximize ()
Window & Minimize ()
Window & Restore ()
Window & SetIcon (const ::Image &image)
Window & SetIcons (Image *images, int count)
Window & SetTitle (const std::string &title)
Window & SetPosition (int x, int y)
Window & SetPosition (const ::Vector2 &position)
Window & SetMonitor (int monitor)
Window & SetMinSize (int width, int height)
Window & SetMinSize (const ::Vector2 &size)
Window & SetSize (int width, int height)
Window & SetOpacity (float opacity)
Window & SetFocused ()
Window & SetSize (const ::Vector2 &size)
Vector2 GetSize () const
void * GetHandle () const
Window & BeginDrawing ()
Window & EndDrawing ()
int GetWidth () const
int GetHeight () const
int GetRenderWidth () const
int GetRenderHeight () const
Vector2 GetPosition () const
Vector2 GetScaleDPI () const
void SetClipboardText (const std::string &text)
const std::string GetClipboardText ()
Window & SetTargetFPS (int fps)
int GetFPS () const
void DrawFPS (int posX=10, int posY=10) const
float GetFrameTime () const
double GetTime () const
void SetConfigFlags (unsigned int flags)
Static Public Member Functions
static bool IsReady ()
Detailed Description
Window and Graphics Device Functions.
Definition at line 14 of file Window.hpp.
Constructor & Destructor Documentation
Window() [1/2]
raylib::Window::Window () inline
Build a Window object, but defer the initialization. Ensure you call Init() manually.
See also
Init()
Definition at line 21 of file Window.hpp.
             {
        // Nothing.
    }
Window() [2/2]
raylib::Window::Window (int width, int height, const std::string & title = "raylib", unsigned int flags = 0) inline
Initialize window and OpenGL context.
Parameters
width The width of the window.
height The height of the window.
title The desired title of the window.
flags The ConfigFlags to set prior to initializing the window. See SetConfigFlags for more details.
See also
SetConfigFlags()
ConfigFlags
Exceptions
raylib::RaylibException Thrown if the window failed to initiate.
Definition at line 38 of file Window.hpp.
{
        Init(width, height, title, flags);
    }
References Init().
~Window()
raylib::Window::~Window () inline
Close window and unload OpenGL context
Definition at line 45 of file Window.hpp.
              {
        Close();
    }
References Close().
Member Function Documentation
BeginDrawing()
Window & raylib::Window::BeginDrawing () inline
Setup canvas (framebuffer) to start drawing
Definition at line 336 of file Window.hpp.
{
        ::BeginDrawing();
        return *this;
    }
References BeginDrawing().
ClearBackground()
Window & raylib::Window::ClearBackground (const ::Color & color = (Color){ 0, 0, 0, 255 }) inline
Clear window with given color.
Definition at line 163 of file Window.hpp.
{
        ::ClearBackground(color);
        return *this;
    }
References ClearBackground().
ClearState()
Window & raylib::Window::ClearState (unsigned int flag) inline
Clear window configuration state flags
Definition at line 155 of file Window.hpp.
{
        ::ClearWindowState(flag);
        return *this;
    }
References ClearWindowState().
Close()
void raylib::Window::Close () inline
Close window and unload OpenGL context
Definition at line 82 of file Window.hpp.
{
        if (::IsWindowReady()) {
            ::CloseWindow();
        }
    }
References CloseWindow(), and IsWindowReady().
DrawFPS()
void raylib::Window::DrawFPS (int posX = 10, int posY = 10) const inline
Draw current FPS
Definition at line 423 of file Window.hpp.
{
        ::DrawFPS(posX, posY);
    }
References DrawFPS().
EndDrawing()
Window & raylib::Window::EndDrawing () inline
End canvas drawing and swap buffers (double buffering)
Definition at line 344 of file Window.hpp.
{
        ::EndDrawing();
        return *this;
    }
References EndDrawing().
GetClipboardText()
const std::string raylib::Window::GetClipboardText () inline
Get clipboard text content
Definition at line 401 of file Window.hpp.
{
        return ::GetClipboardText();
    }
GetFPS()
int raylib::Window::GetFPS () const inline
Returns current FPS
Definition at line 416 of file Window.hpp.
{
        return ::GetFPS();
    }
GetFrameTime()
float raylib::Window::GetFrameTime () const inline
Returns time in seconds for last frame drawn
Definition at line 430 of file Window.hpp.
{
        return ::GetFrameTime();
    }
GetHandle()
void * raylib::Window::GetHandle () const inline
Get native window handle
Definition at line 329 of file Window.hpp.
{
        return ::GetWindowHandle();
    }
GetHeight()
int raylib::Window::GetHeight () const inline
Get current screen height
Definition at line 359 of file Window.hpp.
{
        return ::GetScreenHeight();
    }
GetPosition()
Vector2 raylib::Window::GetPosition () const inline
Get window position XY on monitor
Definition at line 380 of file Window.hpp.
{
        return ::GetWindowPosition();
    }
GetRenderHeight()
int raylib::Window::GetRenderHeight () const inline
Get current render height (it considers HiDPI)
Definition at line 373 of file Window.hpp.
{
        return ::GetRenderHeight();
    }
GetRenderWidth()
int raylib::Window::GetRenderWidth () const inline
Get current render width (it considers HiDPI)
Definition at line 366 of file Window.hpp.
{
        return ::GetRenderWidth();
    }
GetScaleDPI()
Vector2 raylib::Window::GetScaleDPI () const inline
Get window scale DPI factor
Definition at line 387 of file Window.hpp.
{
        return ::GetWindowScaleDPI();
    }
GetSize()
Vector2 raylib::Window::GetSize () const inline
Get the screen's width and height.
Definition at line 322 of file Window.hpp.
{
        return {static_cast<float>(GetWidth()), static_cast<float>(GetHeight())};
    }
References GetHeight(), and GetWidth().
GetTime()
double raylib::Window::GetTime () const inline
Returns elapsed time in seconds since InitWindow()
Definition at line 437 of file Window.hpp.
{
        return ::GetTime();
    }
GetWidth()
int raylib::Window::GetWidth () const inline
Get current screen width
Definition at line 352 of file Window.hpp.
{
        return ::GetScreenWidth();
    }
Init()
void raylib::Window::Init (int width = 800, int height = 450, const std::string & title = "raylib", unsigned int flags = 0) inline
Initializes the window.
Parameters
width The width of the window.
height The height of the window.
title The desired title of the window.
flags The ConfigFlags to set prior to initializing the window. See SetConfigFlags for more details.
See also
SetConfigFlags()
ConfigFlags
Exceptions
raylib::RaylibException Thrown if the window failed to initiate.
Definition at line 62 of file Window.hpp.
{
        if (flags != 0) {
            ::SetConfigFlags(flags);
        }
        ::InitWindow(width, height, title.c_str());
        if (!::IsWindowReady()) {
            throw RaylibException("Failed to create Window");
        }
    }
References IsWindowReady(), and SetConfigFlags().
IsCursorOnScreen()
bool raylib::Window::IsCursorOnScreen () const inline
Check if cursor is on the current screen
Definition at line 91 of file Window.hpp.
{
        return ::IsCursorOnScreen();
    }
IsFocused()
bool raylib::Window::IsFocused () const inline
Check if window is currently focused
Definition at line 126 of file Window.hpp.
{
        return ::IsWindowFocused();
    }
IsFullscreen()
bool raylib::Window::IsFullscreen () const inline
Check if window is currently fullscreen
Definition at line 98 of file Window.hpp.
{
        return ::IsWindowFullscreen();
    }
IsHidden()
bool raylib::Window::IsHidden () const inline
Check if window is currently hidden
Definition at line 105 of file Window.hpp.
{
        return ::IsWindowHidden();
    }
IsMaximized()
bool raylib::Window::IsMaximized () const inline
Check if window is currently minimized
Definition at line 119 of file Window.hpp.
{
        return ::IsWindowMaximized();
    }
IsMinimized()
bool raylib::Window::IsMinimized () const inline
Check if window is currently minimized
Definition at line 112 of file Window.hpp.
{
        return ::IsWindowMinimized();
    }
IsReady()
static bool raylib::Window::IsReady () inline static
Check if window has been initialized successfully
Definition at line 444 of file Window.hpp.
{
        return ::IsWindowReady();
    }
IsResized()
bool raylib::Window::IsResized () const inline
Check if window has been resized last frame
Definition at line 133 of file Window.hpp.
{
        return ::IsWindowResized();
    }
IsState()
bool raylib::Window::IsState (unsigned int flag) const inline
Check if one specific window flag is enabled
Definition at line 140 of file Window.hpp.
{
        return ::IsWindowState(flag);
    }
Maximize()
Window & raylib::Window::Maximize () inline
Set window state: maximized, if resizable (only PLATFORM_DESKTOP)
Definition at line 204 of file Window.hpp.
{
        ::MaximizeWindow();
        return *this;
    }
References MaximizeWindow().
Minimize()
Window & raylib::Window::Minimize () inline
Set window state: minimized, if resizable (only PLATFORM_DESKTOP)
Definition at line 212 of file Window.hpp.
{
        ::MinimizeWindow();
        return *this;
    }
References MinimizeWindow().
Restore()
Window & raylib::Window::Restore () inline
Set window state: not minimized/maximized (only PLATFORM_DESKTOP)
Definition at line 220 of file Window.hpp.
{
        ::RestoreWindow();
        return *this;
    }
References RestoreWindow().
SetClipboardText()
void raylib::Window::SetClipboardText (const std::string & text) inline
Set clipboard text content
Definition at line 394 of file Window.hpp.
{
        ::SetClipboardText(text.c_str());
    }
References SetClipboardText().
SetConfigFlags()
void raylib::Window::SetConfigFlags (unsigned int flags) inline
Sets the configuration flags for raylib.
Parameters
flags The ConfigFlags to apply to the configuration.
See also
SetConfigFlags
Definition at line 455 of file Window.hpp.
{
        ::SetConfigFlags(flags);
    }
References SetConfigFlags().
SetFocused()
Window & raylib::Window::SetFocused () inline
Set window focused (only PLATFORM_DESKTOP)
Definition at line 307 of file Window.hpp.
{
        ::SetWindowFocused();
        return *this;
    }
References SetWindowFocused().
SetFullscreen()
Window & raylib::Window::SetFullscreen (bool fullscreen) inline
Set whether or not the application should be fullscreen.
Definition at line 179 of file Window.hpp.
{
        if (fullscreen) {
            if (!IsFullscreen()) {
                ToggleFullscreen();
            }
        } else {
            if (IsFullscreen()) {
                ToggleFullscreen();
            }
        }
        return *this;
    }
References IsFullscreen(), and ToggleFullscreen().
SetIcon()
Window & raylib::Window::SetIcon (const ::Image & image) inline
Set icon for window
Definition at line 228 of file Window.hpp.
{
        ::SetWindowIcon(image);
        return *this;
    }
References SetWindowIcon().
SetIcons()
Window & raylib::Window::SetIcons (Image * images, int count) inline
Set icon for window (multiple images, RGBA 32bit, only PLATFORM_DESKTOP)
Definition at line 236 of file Window.hpp.
{
        ::SetWindowIcons(images, count);
        return *this;
    }
References SetWindowIcons().
SetMinSize() [1/2]
Window & raylib::Window::SetMinSize (const ::Vector2 & size) inline
Set window minimum dimensions
Definition at line 283 of file Window.hpp.
{
        ::SetWindowMinSize(static_cast<int>(size.x), static_cast<int>(size.y));
        return *this;
    }
References SetWindowMinSize().
SetMinSize() [2/2]
Window & raylib::Window::SetMinSize (int width, int height) inline
Set window minimum dimensions
Definition at line 275 of file Window.hpp.
{
        ::SetWindowMinSize(width, height);
        return *this;
    }
References SetWindowMinSize().
SetMonitor()
Window & raylib::Window::SetMonitor (int monitor) inline
Set monitor for the current window
Definition at line 267 of file Window.hpp.
{
        ::SetWindowMonitor(monitor);
        return *this;
    }
References SetWindowMonitor().
SetOpacity()
Window & raylib::Window::SetOpacity (float opacity) inline
Set window opacity [0.0f..1.0f] (only PLATFORM_DESKTOP)
Definition at line 299 of file Window.hpp.
{
        ::SetWindowOpacity(opacity);
        return *this;
    }
References SetWindowOpacity().
SetPosition() [1/2]
Window & raylib::Window::SetPosition (const ::Vector2 & position) inline
Set window position on screen
Definition at line 260 of file Window.hpp.
{
        return SetPosition(static_cast<int>(position.x), static_cast<int>(position.y));
    }
References SetPosition().
SetPosition() [2/2]
Window & raylib::Window::SetPosition (int x, int y) inline
Set window position on screen
Definition at line 252 of file Window.hpp.
{
        ::SetWindowPosition(x, y);
        return *this;
    }
References SetWindowPosition().
SetSize() [1/2]
Window & raylib::Window::SetSize (const ::Vector2 & size) inline
Set window dimensions
Definition at line 315 of file Window.hpp.
{
        return SetSize(static_cast<int>(size.x), static_cast<int>(size.y));
    }
References SetSize().
SetSize() [2/2]
Window & raylib::Window::SetSize (int width, int height) inline
Set window dimensions
Definition at line 291 of file Window.hpp.
{
        ::SetWindowSize(width, height);
        return *this;
    }
References SetWindowSize().
SetState()
Window & raylib::Window::SetState (unsigned int flag) inline
Set window configuration state using flags
Definition at line 147 of file Window.hpp.
{
        ::SetWindowState(flag);
        return *this;
    }
References SetWindowState().
SetTargetFPS()
Window & raylib::Window::SetTargetFPS (int fps) inline
Set target FPS (maximum)
Definition at line 408 of file Window.hpp.
{
        ::SetTargetFPS(fps);
        return *this;
    }
References SetTargetFPS().
SetTitle()
Window & raylib::Window::SetTitle (const std::string & title) inline
Set title for window
Definition at line 244 of file Window.hpp.
{
        ::SetWindowTitle(title.c_str());
        return *this;
    }
ShouldClose()
bool raylib::Window::ShouldClose () const inline
Check if KEY_ESCAPE pressed or Close icon pressed
Definition at line 75 of file Window.hpp.
{
        return ::WindowShouldClose();
    }
ToggleBorderless()
Window & raylib::Window::ToggleBorderless () inline
Toggle window state: borderless/windowed
Definition at line 196 of file Window.hpp.
{
        ::ToggleBorderlessWindowed();
        return *this;
    }
References ToggleBorderlessWindowed().
ToggleFullscreen()
Window & raylib::Window::ToggleFullscreen () inline
Toggle window state: fullscreen/windowed
Definition at line 171 of file Window.hpp.
{
        ::ToggleFullscreen();
        return *this;
    }
References ToggleFullscreen().
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Window.hpp