Techstorm-rivalry: raylib::RayCollision Class Reference
raylib::RayCollision Class Reference
#include <RayCollision.hpp>
Public Member Functions
RayCollision (const ::RayCollision &ray)
RayCollision (bool hit, float distance, ::Vector3 point, ::Vector3 normal)
RayCollision (const ::Ray &ray, const ::BoundingBox &box)
RayCollision (const ::Ray &ray, const ::Mesh &mesh, const ::Matrix &transform)
RayCollision (const ::Ray &ray, ::Vector3 p1, ::Vector3 p2, ::Vector3 p3, ::Vector3 p4)
RayCollision (const ::Ray &ray, ::Vector3 center, float radius)
RayCollision (const ::Ray &ray, ::Vector3 p1, ::Vector3 p2, ::Vector3 p3)
RayCollision & operator= (const ::RayCollision &ray)
bool GetHit () const
void SetHit (bool value)
float GetDistance () const
void SetDistance (float value)
::Vector3 GetPosition () const
void SetPosition (::Vector3 value)
::Vector3 GetNormal () const
void SetNormal (::Vector3 value)
Public Attributes
bool hit
float distance
Vector3 point
Vector3 normal
Protected Member Functions
void set (const ::RayCollision &ray)
Detailed Description
Raycast hit information
Definition at line 11 of file RayCollision.hpp.
Constructor & Destructor Documentation
RayCollision() [1/7]
raylib::RayCollision::RayCollision (const ::RayCollision & ray) inline
Definition at line 13 of file RayCollision.hpp.
{
        set(ray);
    }
References ray, and set().
RayCollision() [2/7]
raylib::RayCollision::RayCollision (bool hit, float distance, ::Vector3 point, ::Vector3 normal) inline
Definition at line 17 of file RayCollision.hpp.
                                       : ::RayCollision{hit, distance, point, normal} {
        // Nothing.
    }
RayCollision() [3/7]
raylib::RayCollision::RayCollision (const ::Ray & ray, const ::BoundingBox & box) inline
Get collision info between ray and bounding box
Definition at line 25 of file RayCollision.hpp.
{
        set(::GetRayCollisionBox(ray, box));
    }
References GetRayCollisionBox(), ray, and set().
RayCollision() [4/7]
raylib::RayCollision::RayCollision (const ::Ray & ray, const ::Mesh & mesh, const ::Matrix & transform) inline
Get collision info between ray and mesh
Definition at line 32 of file RayCollision.hpp.
{
        set(::GetRayCollisionMesh(ray, mesh, transform));
    }
References GetRayCollisionMesh(), ray, and set().
RayCollision() [5/7]
raylib::RayCollision::RayCollision (const ::Ray & ray, ::Vector3 p1, ::Vector3 p2, ::Vector3 p3, ::Vector3 p4) inline
Get collision info between ray and quad
Definition at line 39 of file RayCollision.hpp.
{
        set(::GetRayCollisionQuad(ray, p1, p2, p3, p4));
    }
References GetRayCollisionQuad(), ray, and set().
RayCollision() [6/7]
raylib::RayCollision::RayCollision (const ::Ray & ray, ::Vector3 center, float radius) inline
Get collision info between ray and sphere
Definition at line 46 of file RayCollision.hpp.
{
        set(::GetRayCollisionSphere(ray, center, radius));
    }
References GetRayCollisionSphere(), ray, and set().
RayCollision() [7/7]
raylib::RayCollision::RayCollision (const ::Ray & ray, ::Vector3 p1, ::Vector3 p2, ::Vector3 p3) inline
Get collision info between ray and triangle
Definition at line 53 of file RayCollision.hpp.
{
        set(::GetRayCollisionTriangle(ray, p1, p2, p3));
    }
References GetRayCollisionTriangle(), ray, and set().
Member Function Documentation
GetDistance()
float raylib::RayCollision::GetDistance () const inline
Retrieves the distance value for the object.
Returns
The distance value of the object.
Definition at line 63 of file RayCollision.hpp.
GetHit()
bool raylib::RayCollision::GetHit () const inline
Retrieves the hit value for the object.
Returns
The hit value of the object.
Definition at line 62 of file RayCollision.hpp.
GetNormal()
::Vector3 raylib::RayCollision::GetNormal () const inline
Retrieves the normal value for the object.
Returns
The normal value of the object.
Definition at line 65 of file RayCollision.hpp.
GetPosition()
::Vector3 raylib::RayCollision::GetPosition () const inline
Retrieves the point value for the object.
Returns
The point value of the object.
Definition at line 64 of file RayCollision.hpp.
operator=()
RayCollision & raylib::RayCollision::operator= (const ::RayCollision & ray) inline
Definition at line 57 of file RayCollision.hpp.
{
        set(ray);
        return *this;
    }
References ray, and set().
set()
void raylib::RayCollision::set (const ::RayCollision & ray) inline protected
Definition at line 68 of file RayCollision.hpp.
{
        hit = ray.hit;
        distance = ray.distance;
        point = ray.point;
        normal = ray.normal;
    }
References RayCollision::distance, RayCollision::hit, RayCollision::normal, RayCollision::point, and ray.
SetDistance()
void raylib::RayCollision::SetDistance (float value) inline
Sets the distance value for the object.
Parameters
value The value of which to set distance to.
Definition at line 63 of file RayCollision.hpp.
SetHit()
void raylib::RayCollision::SetHit (bool value) inline
Sets the hit value for the object.
Parameters
value The value of which to set hit to.
Definition at line 62 of file RayCollision.hpp.
SetNormal()
void raylib::RayCollision::SetNormal (::Vector3 value) inline
Sets the normal value for the object.
Parameters
value The value of which to set normal to.
Definition at line 65 of file RayCollision.hpp.
SetPosition()
void raylib::RayCollision::SetPosition (::Vector3 value) inline
Sets the point value for the object.
Parameters
value The value of which to set point to.
Definition at line 64 of file RayCollision.hpp.
Member Data Documentation
distance
float RayCollision::distance inherited
Definition at line 425 of file raylib.h.
hit
bool RayCollision::hit inherited
Definition at line 424 of file raylib.h.
normal
Vector3 RayCollision::normal inherited
Definition at line 427 of file raylib.h.
point
Vector3 RayCollision::point inherited
Definition at line 426 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/RayCollision.hpp