Techstorm-rivalry: raylib::Matrix Class Reference
raylib::Matrix Class Reference
#include <Matrix.hpp>
Public Member Functions
Matrix (const ::Matrix &mat)
Matrix (float m0=0, float m4=0, float m8=0, float m12=0, float m1=0, float m5=0, float m9=0, float m13=0, float m2=0, float m6=0, float m10=0, float m14=0, float m3=0, float m7=0, float m11=0, float m15=0)
float GetM0 () const
void SetM0 (float value)
float GetM1 () const
void SetM1 (float value)
float GetM2 () const
void SetM2 (float value)
float GetM3 () const
void SetM3 (float value)
float GetM4 () const
void SetM4 (float value)
float GetM5 () const
void SetM5 (float value)
float GetM6 () const
void SetM6 (float value)
float GetM7 () const
void SetM7 (float value)
float GetM8 () const
void SetM8 (float value)
float GetM9 () const
void SetM9 (float value)
float GetM10 () const
void SetM10 (float value)
float GetM11 () const
void SetM11 (float value)
float GetM12 () const
void SetM12 (float value)
float GetM13 () const
void SetM13 (float value)
float GetM14 () const
void SetM14 (float value)
float GetM15 () const
void SetM15 (float value)
Matrix & operator= (const ::Matrix &matrix)
Matrix & operator= (const Matrix &matrix)
bool operator== (const ::Matrix &other)
bool operator!= (const ::Matrix &other)
float Trace () const
Matrix Transpose () const
Matrix Invert () const
Matrix Add (const ::Matrix &right)
Matrix operator+ (const ::Matrix &matrix)
Matrix Subtract (const ::Matrix &right)
Matrix operator- (const ::Matrix &matrix)
Matrix Multiply (const ::Matrix &right) const
Matrix operator* (const ::Matrix &matrix)
float16 ToFloatV () const
operator float16 ()
Matrix & SetShaderValue (const ::Shader &shader, int uniformLoc)
Static Public Member Functions
static Matrix Identity ()
static Matrix Translate (float x, float y, float z)
static Matrix Rotate (Vector3 axis, float angle)
static Matrix RotateXYZ (Vector3 angle)
static Matrix RotateX (float angle)
static Matrix RotateY (float angle)
static Matrix RotateZ (float angle)
static Matrix Scale (float x, float y, float z)
static Matrix Frustum (double left, double right, double bottom, double top, double near, double far)
static Matrix Perspective (double fovy, double aspect, double near, double far)
static Matrix Ortho (double left, double right, double bottom, double top, double near, double far)
static Matrix LookAt (Vector3 eye, Vector3 target, Vector3 up)
static Matrix GetCamera (const ::Camera &camera)
static Matrix GetCamera (const ::Camera2D &camera)
Public Attributes
float m0
float m4
float m8
float m12
float m1
float m5
float m9
float m13
float m2
float m6
float m10
float m14
float m3
float m7
float m11
float m15
Protected Member Functions
void set (const ::Matrix &mat)
Detailed Description
Matrix type (OpenGL style 4x4 - right handed, column major)
Definition at line 16 of file Matrix.hpp.
Constructor & Destructor Documentation
Matrix() [1/2]
raylib::Matrix::Matrix (const ::Matrix & mat) inline
Definition at line 18 of file Matrix.hpp.
                              : ::Matrix{
            mat.m0, mat.m4, mat.m8, mat.m12,
            mat.m1, mat.m5, mat.m9, mat.m13,
            mat.m2, mat.m6, mat.m10, mat.m14,
            mat.m3, mat.m7, mat.m11, mat.m15} {
        // Nothing.
    }
Matrix() [2/2]
raylib::Matrix::Matrix (float m0 = 0, float m4 = 0, float m8 = 0, float m12 = 0, float m1 = 0, float m5 = 0, float m9 = 0, float m13 = 0, float m2 = 0, float m6 = 0, float m10 = 0, float m14 = 0, float m3 = 0, float m7 = 0, float m11 = 0, float m15 = 0) inline
Definition at line 26 of file Matrix.hpp.
                                                                      :
        ::Matrix{
            m0, m4, m8, m12,
            m1, m5, m9, m13,
            m2, m6, m10, m14,
            m3, m7, m11, m15} {
        // Nothing.
    }
Member Function Documentation
Add()
Matrix raylib::Matrix::Add (const ::Matrix & right) inline
Definition at line 112 of file Matrix.hpp.
{
        return ::MatrixAdd(*this, right);
    }
Frustum()
static Matrix raylib::Matrix::Frustum (double left, double right, double bottom, double top, double near, double far) inline static
Definition at line 164 of file Matrix.hpp.
{
        return ::MatrixFrustum(left, right, bottom, top, near, far);
    }
GetCamera() [1/2]
static Matrix raylib::Matrix::GetCamera (const ::Camera & camera) inline static
Definition at line 198 of file Matrix.hpp.
{
        return ::GetCameraMatrix(camera);
    }
GetCamera() [2/2]
static Matrix raylib::Matrix::GetCamera (const ::Camera2D & camera) inline static
Definition at line 202 of file Matrix.hpp.
{
        return ::GetCameraMatrix2D(camera);
    }
GetM0()
float raylib::Matrix::GetM0 () const inline
Retrieves the m0 value for the object.
Returns
The m0 value of the object.
Definition at line 39 of file Matrix.hpp.
GetM1()
float raylib::Matrix::GetM1 () const inline
Retrieves the m1 value for the object.
Returns
The m1 value of the object.
Definition at line 40 of file Matrix.hpp.
GetM10()
float raylib::Matrix::GetM10 () const inline
Retrieves the m10 value for the object.
Returns
The m10 value of the object.
Definition at line 49 of file Matrix.hpp.
GetM11()
float raylib::Matrix::GetM11 () const inline
Retrieves the m11 value for the object.
Returns
The m11 value of the object.
Definition at line 50 of file Matrix.hpp.
GetM12()
float raylib::Matrix::GetM12 () const inline
Retrieves the m12 value for the object.
Returns
The m12 value of the object.
Definition at line 51 of file Matrix.hpp.
GetM13()
float raylib::Matrix::GetM13 () const inline
Retrieves the m13 value for the object.
Returns
The m13 value of the object.
Definition at line 52 of file Matrix.hpp.
GetM14()
float raylib::Matrix::GetM14 () const inline
Retrieves the m14 value for the object.
Returns
The m14 value of the object.
Definition at line 53 of file Matrix.hpp.
GetM15()
float raylib::Matrix::GetM15 () const inline
Retrieves the m15 value for the object.
Returns
The m15 value of the object.
Definition at line 54 of file Matrix.hpp.
GetM2()
float raylib::Matrix::GetM2 () const inline
Retrieves the m2 value for the object.
Returns
The m2 value of the object.
Definition at line 41 of file Matrix.hpp.
GetM3()
float raylib::Matrix::GetM3 () const inline
Retrieves the m3 value for the object.
Returns
The m3 value of the object.
Definition at line 42 of file Matrix.hpp.
GetM4()
float raylib::Matrix::GetM4 () const inline
Retrieves the m4 value for the object.
Returns
The m4 value of the object.
Definition at line 43 of file Matrix.hpp.
GetM5()
float raylib::Matrix::GetM5 () const inline
Retrieves the m5 value for the object.
Returns
The m5 value of the object.
Definition at line 44 of file Matrix.hpp.
GetM6()
float raylib::Matrix::GetM6 () const inline
Retrieves the m6 value for the object.
Returns
The m6 value of the object.
Definition at line 45 of file Matrix.hpp.
GetM7()
float raylib::Matrix::GetM7 () const inline
Retrieves the m7 value for the object.
Returns
The m7 value of the object.
Definition at line 46 of file Matrix.hpp.
GetM8()
float raylib::Matrix::GetM8 () const inline
Retrieves the m8 value for the object.
Returns
The m8 value of the object.
Definition at line 47 of file Matrix.hpp.
GetM9()
float raylib::Matrix::GetM9 () const inline
Retrieves the m9 value for the object.
Returns
The m9 value of the object.
Definition at line 48 of file Matrix.hpp.
Identity()
static Matrix raylib::Matrix::Identity () inline static
Definition at line 108 of file Matrix.hpp.
{
        return ::MatrixIdentity();
    }
Invert()
Matrix raylib::Matrix::Invert () const inline
Definition at line 104 of file Matrix.hpp.
{
        return ::MatrixInvert(*this);
    }
LookAt()
static Matrix raylib::Matrix::LookAt (Vector3 eye, Vector3 target, Vector3 up) inline static
Definition at line 178 of file Matrix.hpp.
{
        return ::MatrixLookAt(eye, target, up);
    }
Multiply()
Matrix raylib::Matrix::Multiply (const ::Matrix & right) const inline
Definition at line 156 of file Matrix.hpp.
{
        return ::MatrixMultiply(*this, right);
    }
operator float16()
raylib::Matrix::operator float16 () inline
Definition at line 186 of file Matrix.hpp.
                       {
        return ToFloatV();
    }
References ToFloatV().
operator!=()
bool raylib::Matrix::operator!= (const ::Matrix & other) inline
Definition at line 85 of file Matrix.hpp.
{
        return !(*this == other);
    }
operator*()
Matrix raylib::Matrix::operator* (const ::Matrix & matrix) inline
Definition at line 160 of file Matrix.hpp.
{
        return ::MatrixMultiply(*this, matrix);
    }
operator+()
Matrix raylib::Matrix::operator+ (const ::Matrix & matrix) inline
Definition at line 116 of file Matrix.hpp.
{
            return ::MatrixAdd(*this, matrix);
    }
operator-()
Matrix raylib::Matrix::operator- (const ::Matrix & matrix) inline
Definition at line 124 of file Matrix.hpp.
{
        return ::MatrixSubtract(*this, matrix);
    }
operator=() [1/2]
Matrix & raylib::Matrix::operator= (const ::Matrix & matrix) inline
Definition at line 56 of file Matrix.hpp.
{
        set(matrix);
        return *this;
    }
References set().
operator=() [2/2]
Matrix & raylib::Matrix::operator= (const Matrix & matrix) inline
Definition at line 61 of file Matrix.hpp.
{
        set(matrix);
        return *this;
    }
References set().
operator==()
bool raylib::Matrix::operator== (const ::Matrix & other) inline
Definition at line 66 of file Matrix.hpp.
{
        return m0 == other.m0
            && m1 == other.m1
            && m2 == other.m2
            && m3 == other.m3
            && m4 == other.m4
            && m5 == other.m5
            && m6 == other.m6
            && m7 == other.m7
            && m8 == other.m8
            && m9 == other.m9
            && m10 == other.m10
            && m11 == other.m11
            && m12 == other.m12
            && m13 == other.m13
            && m14 == other.m14
            && m15 == other.m15;
    }
References Matrix::m0, Matrix::m1, Matrix::m10, Matrix::m11, Matrix::m12, Matrix::m13, Matrix::m14, Matrix::m15, Matrix::m2, Matrix::m3, Matrix::m4, Matrix::m5, Matrix::m6, Matrix::m7, Matrix::m8, and Matrix::m9.
Ortho()
static Matrix raylib::Matrix::Ortho (double left, double right, double bottom, double top, double near, double far) inline static
Definition at line 173 of file Matrix.hpp.
{
        return ::MatrixOrtho(left, right, bottom, top, near, far);
    }
Perspective()
static Matrix raylib::Matrix::Perspective (double fovy, double aspect, double near, double far) inline static
Definition at line 169 of file Matrix.hpp.
{
        return ::MatrixPerspective(fovy, aspect, near, far);
    }
Rotate()
static Matrix raylib::Matrix::Rotate (Vector3 axis, float angle) inline static
Definition at line 132 of file Matrix.hpp.
{
        return ::MatrixRotate(axis, angle);
    }
RotateX()
static Matrix raylib::Matrix::RotateX (float angle) inline static
Definition at line 140 of file Matrix.hpp.
{
        return ::MatrixRotateX(angle);
    }
RotateXYZ()
static Matrix raylib::Matrix::RotateXYZ (Vector3 angle) inline static
Definition at line 136 of file Matrix.hpp.
{
        return ::MatrixRotateXYZ(angle);
    }
RotateY()
static Matrix raylib::Matrix::RotateY (float angle) inline static
Definition at line 144 of file Matrix.hpp.
{
        return ::MatrixRotateY(angle);
    }
RotateZ()
static Matrix raylib::Matrix::RotateZ (float angle) inline static
Definition at line 148 of file Matrix.hpp.
{
        return ::MatrixRotateZ(angle);
    }
Scale()
static Matrix raylib::Matrix::Scale (float x, float y, float z) inline static
Definition at line 152 of file Matrix.hpp.
{
        return ::MatrixScale(x, y, z);
    }
set()
void raylib::Matrix::set (const ::Matrix & mat) inline protected
Definition at line 209 of file Matrix.hpp.
{
        m0 = mat.m0;
        m1 = mat.m1;
        m2 = mat.m2;
        m3 = mat.m3;
        m4 = mat.m4;
        m5 = mat.m5;
        m6 = mat.m6;
        m7 = mat.m7;
        m8 = mat.m8;
        m9 = mat.m9;
        m10 = mat.m10;
        m11 = mat.m11;
        m12 = mat.m12;
        m13 = mat.m13;
        m14 = mat.m14;
        m15 = mat.m15;
    }
References Matrix::m0, Matrix::m1, Matrix::m10, Matrix::m11, Matrix::m12, Matrix::m13, Matrix::m14, Matrix::m15, Matrix::m2, Matrix::m3, Matrix::m4, Matrix::m5, Matrix::m6, Matrix::m7, Matrix::m8, and Matrix::m9.
SetM0()
void raylib::Matrix::SetM0 (float value) inline
Sets the m0 value for the object.
Parameters
value The value of which to set m0 to.
Definition at line 39 of file Matrix.hpp.
SetM1()
void raylib::Matrix::SetM1 (float value) inline
Sets the m1 value for the object.
Parameters
value The value of which to set m1 to.
Definition at line 40 of file Matrix.hpp.
SetM10()
void raylib::Matrix::SetM10 (float value) inline
Sets the m10 value for the object.
Parameters
value The value of which to set m10 to.
Definition at line 49 of file Matrix.hpp.
SetM11()
void raylib::Matrix::SetM11 (float value) inline
Sets the m11 value for the object.
Parameters
value The value of which to set m11 to.
Definition at line 50 of file Matrix.hpp.
SetM12()
void raylib::Matrix::SetM12 (float value) inline
Sets the m12 value for the object.
Parameters
value The value of which to set m12 to.
Definition at line 51 of file Matrix.hpp.
SetM13()
void raylib::Matrix::SetM13 (float value) inline
Sets the m13 value for the object.
Parameters
value The value of which to set m13 to.
Definition at line 52 of file Matrix.hpp.
SetM14()
void raylib::Matrix::SetM14 (float value) inline
Sets the m14 value for the object.
Parameters
value The value of which to set m14 to.
Definition at line 53 of file Matrix.hpp.
SetM15()
void raylib::Matrix::SetM15 (float value) inline
Sets the m15 value for the object.
Parameters
value The value of which to set m15 to.
Definition at line 54 of file Matrix.hpp.
SetM2()
void raylib::Matrix::SetM2 (float value) inline
Sets the m2 value for the object.
Parameters
value The value of which to set m2 to.
Definition at line 41 of file Matrix.hpp.
SetM3()
void raylib::Matrix::SetM3 (float value) inline
Sets the m3 value for the object.
Parameters
value The value of which to set m3 to.
Definition at line 42 of file Matrix.hpp.
SetM4()
void raylib::Matrix::SetM4 (float value) inline
Sets the m4 value for the object.
Parameters
value The value of which to set m4 to.
Definition at line 43 of file Matrix.hpp.
SetM5()
void raylib::Matrix::SetM5 (float value) inline
Sets the m5 value for the object.
Parameters
value The value of which to set m5 to.
Definition at line 44 of file Matrix.hpp.
SetM6()
void raylib::Matrix::SetM6 (float value) inline
Sets the m6 value for the object.
Parameters
value The value of which to set m6 to.
Definition at line 45 of file Matrix.hpp.
SetM7()
void raylib::Matrix::SetM7 (float value) inline
Sets the m7 value for the object.
Parameters
value The value of which to set m7 to.
Definition at line 46 of file Matrix.hpp.
SetM8()
void raylib::Matrix::SetM8 (float value) inline
Sets the m8 value for the object.
Parameters
value The value of which to set m8 to.
Definition at line 47 of file Matrix.hpp.
SetM9()
void raylib::Matrix::SetM9 (float value) inline
Sets the m9 value for the object.
Parameters
value The value of which to set m9 to.
Definition at line 48 of file Matrix.hpp.
SetShaderValue()
Matrix & raylib::Matrix::SetShaderValue (const ::Shader & shader, int uniformLoc) inline
Set shader uniform value (matrix 4x4)
Definition at line 193 of file Matrix.hpp.
{
        ::SetShaderValueMatrix(shader, uniformLoc, *this);
        return *this;
    }
References SetShaderValueMatrix().
Subtract()
Matrix raylib::Matrix::Subtract (const ::Matrix & right) inline
Definition at line 120 of file Matrix.hpp.
{
        return ::MatrixSubtract(*this, right);
    }
ToFloatV()
float16 raylib::Matrix::ToFloatV () const inline
Definition at line 182 of file Matrix.hpp.
{
        return ::MatrixToFloatV(*this);
    }
Trace()
float raylib::Matrix::Trace () const inline
Returns the trace of the matrix (sum of the values along the diagonal)
Definition at line 93 of file Matrix.hpp.
{
        return ::MatrixTrace(*this);
    }
Translate()
static Matrix raylib::Matrix::Translate (float x, float y, float z) inline static
Definition at line 128 of file Matrix.hpp.
{
        return ::MatrixTranslate(x, y, z);
    }
Transpose()
Matrix raylib::Matrix::Transpose () const inline
Transposes provided matrix
Definition at line 100 of file Matrix.hpp.
{
        return ::MatrixTranspose(*this);
    }
Member Data Documentation
m0
float Matrix::m0 inherited
Definition at line 229 of file raylib.h.
m1
float Matrix::m1 inherited
Definition at line 230 of file raylib.h.
m10
float Matrix::m10 inherited
Definition at line 231 of file raylib.h.
m11
float Matrix::m11 inherited
Definition at line 232 of file raylib.h.
m12
float Matrix::m12 inherited
Definition at line 229 of file raylib.h.
m13
float Matrix::m13 inherited
Definition at line 230 of file raylib.h.
m14
float Matrix::m14 inherited
Definition at line 231 of file raylib.h.
m15
float Matrix::m15 inherited
Definition at line 232 of file raylib.h.
m2
float Matrix::m2 inherited
Definition at line 231 of file raylib.h.
m3
float Matrix::m3 inherited
Definition at line 232 of file raylib.h.
m4
float Matrix::m4 inherited
Definition at line 229 of file raylib.h.
m5
float Matrix::m5 inherited
Definition at line 230 of file raylib.h.
m6
float Matrix::m6 inherited
Definition at line 231 of file raylib.h.
m7
float Matrix::m7 inherited
Definition at line 232 of file raylib.h.
m8
float Matrix::m8 inherited
Definition at line 229 of file raylib.h.
m9
float Matrix::m9 inherited
Definition at line 230 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Matrix.hpp