Techstorm-rivalry: raylib::RenderTexture Class Reference
raylib::RenderTexture Class Reference
#include <RenderTexture.hpp>
Public Member Functions
RenderTexture ()
RenderTexture (const ::RenderTexture &renderTexture)
RenderTexture (unsigned int id, const ::Texture &texture, const ::Texture &depth)
RenderTexture (int width, int height)
RenderTexture (const RenderTexture &)=delete
RenderTexture (RenderTexture &&other)
unsigned int GetId () const
void SetId (unsigned int value)
TextureUnmanaged GetTexture ()
void SetTexture (const ::Texture &newTexture)
TextureUnmanaged GetDepth ()
void SetDepth (const ::Texture &newDepth)
RenderTexture & operator= (const ::RenderTexture &texture)
RenderTexture & operator= (const RenderTexture &)=delete
RenderTexture & operator= (RenderTexture &&other) noexcept
~RenderTexture ()
void Unload ()
RenderTexture & BeginMode ()
RenderTexture & EndMode ()
bool IsReady () const
Static Public Member Functions
static RenderTexture Load (int width, int height)
Public Attributes
unsigned int id
Texture texture
Texture depth
Protected Member Functions
void set (const ::RenderTexture &renderTexture)
Detailed Description
RenderTexture type, for texture rendering
Definition at line 13 of file RenderTexture.hpp.
Constructor & Destructor Documentation
RenderTexture() [1/6]
raylib::RenderTexture::RenderTexture () inline
Default constructor to build an empty RenderTexture.
Definition at line 18 of file RenderTexture.hpp.
                    {
        id = 0;
    }
RenderTexture() [2/6]
raylib::RenderTexture::RenderTexture (const ::RenderTexture & renderTexture) inline
Definition at line 22 of file RenderTexture.hpp.
{
        set(renderTexture);
    }
References set().
RenderTexture() [3/6]
raylib::RenderTexture::RenderTexture (unsigned int id, const ::Texture & texture, const ::Texture & depth) inline
Definition at line 26 of file RenderTexture.hpp.
                                                                                 :
        ::RenderTexture{id, texture, depth} {}
RenderTexture() [4/6]
raylib::RenderTexture::RenderTexture (int width, int height) inline
Load texture for rendering (framebuffer)
Definition at line 32 of file RenderTexture.hpp.
{
        set(::LoadRenderTexture(width, height));
    }
References LoadRenderTexture(), and set().
RenderTexture() [5/6]
raylib::RenderTexture::RenderTexture (const RenderTexture &) delete
RenderTexture() [6/6]
raylib::RenderTexture::RenderTexture (RenderTexture && other) inline
Definition at line 38 of file RenderTexture.hpp.
{
        set(other);
        other.id = 0;
        other.texture = {};
        other.depth = {};
    }
References set().
~RenderTexture()
raylib::RenderTexture::~RenderTexture () inline
Definition at line 92 of file RenderTexture.hpp.
                     {
        Unload();
    }
References Unload().
Member Function Documentation
BeginMode()
RenderTexture & raylib::RenderTexture::BeginMode () inline
Initializes render texture for drawing
Definition at line 103 of file RenderTexture.hpp.
{
        ::BeginTextureMode(*this);
        return *this;
    }
References BeginTextureMode().
EndMode()
RenderTexture & raylib::RenderTexture::EndMode () inline
Ends drawing to render texture
Definition at line 111 of file RenderTexture.hpp.
{
        ::EndTextureMode();
        return *this;
    }
References EndTextureMode().
GetDepth()
TextureUnmanaged raylib::RenderTexture::GetDepth () inline
Depth buffer attachment texture
Definition at line 62 of file RenderTexture.hpp.
{
        return depth;
    }
References RenderTexture::depth.
GetId()
unsigned int raylib::RenderTexture::GetId () const inline
Retrieves the id value for the object.
Returns
The id value of the object.
Definition at line 46 of file RenderTexture.hpp.
GetTexture()
TextureUnmanaged raylib::RenderTexture::GetTexture () inline
Get the color buffer attachment texture.
Definition at line 51 of file RenderTexture.hpp.
{
        return texture;
    }
References RenderTexture::texture.
IsReady()
bool raylib::RenderTexture::IsReady () const inline
Retrieves whether or not the render texture is ready.
Definition at line 126 of file RenderTexture.hpp.
{
        return ::IsRenderTextureReady(*this);
    }
Load()
static RenderTexture raylib::RenderTexture::Load (int width, int height) inline static
Load texture for rendering (framebuffer)
Definition at line 119 of file RenderTexture.hpp.
{
        return ::LoadRenderTexture(width, height);
    }
operator=() [1/3]
RenderTexture & raylib::RenderTexture::operator= (const ::RenderTexture & texture) inline
Definition at line 70 of file RenderTexture.hpp.
{
        set(texture);
        return *this;
    }
References set(), and RenderTexture::texture.
operator=() [2/3]
RenderTexture & raylib::RenderTexture::operator= (const RenderTexture &) delete
operator=() [3/3]
RenderTexture & raylib::RenderTexture::operator= (RenderTexture && other) inline noexcept
Definition at line 77 of file RenderTexture.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.id = 0;
        other.texture = {};
        other.depth = {};
        return *this;
    }
References set(), and Unload().
set()
void raylib::RenderTexture::set (const ::RenderTexture & renderTexture) inline protected
Definition at line 131 of file RenderTexture.hpp.
{
        id = renderTexture.id;
        texture = renderTexture.texture;
        depth = renderTexture.depth;
    }
References RenderTexture::depth, and RenderTexture::texture.
SetDepth()
void raylib::RenderTexture::SetDepth (const ::Texture & newDepth) inline
Definition at line 66 of file RenderTexture.hpp.
{
        depth = newDepth;
    }
References RenderTexture::depth.
SetId()
void raylib::RenderTexture::SetId (unsigned int value) inline
Sets the id value for the object.
Parameters
value The value of which to set id to.
Definition at line 46 of file RenderTexture.hpp.
SetTexture()
void raylib::RenderTexture::SetTexture (const ::Texture & newTexture) inline
Definition at line 55 of file RenderTexture.hpp.
{
        texture = newTexture;
    }
References RenderTexture::texture.
Unload()
void raylib::RenderTexture::Unload () inline
Definition at line 96 of file RenderTexture.hpp.
{
        UnloadRenderTexture(*this);
    }
References UnloadRenderTexture().
Member Data Documentation
depth
Texture RenderTexture::depth inherited
Definition at line 279 of file raylib.h.
id
unsigned int RenderTexture::id inherited
Definition at line 277 of file raylib.h.
texture
Texture RenderTexture::texture inherited
Definition at line 278 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/RenderTexture.hpp