Techstorm-rivalry: raylib::Sound Class Reference
raylib::Sound Class Reference
#include <Sound.hpp>
Public Member Functions
Sound (const Sound &)=delete
Sound & operator= (const Sound &)=delete
Sound ()
Sound (::AudioStream stream, unsigned int frameCount)
Sound (Sound &&other)
Sound (const std::string &fileName)
Sound (const ::Wave &wave)
~Sound ()
unsigned int GetFrameCount () const
void SetFrameCount (unsigned int value)
::AudioStream GetStream () const
void SetStream (::AudioStream value)
Sound & operator= (Sound &&other) noexcept
Sound & Update (const void *data, int samplesCount)
Sound & Update (const void *data)
void Unload ()
Sound & Play ()
Sound & Stop ()
Sound & Pause ()
Sound & Resume ()
bool IsPlaying () const
Sound & SetVolume (float volume)
Sound & SetPitch (float pitch)
Sound & SetPan (float pan=0.5f)
void Load (const std::string &fileName)
void Load (const ::Wave &wave)
bool IsReady () const
Public Attributes
AudioStream stream
unsigned int frameCount
Protected Member Functions
void set (const ::Sound &sound)
Detailed Description
Wave/Sound management functions
raylib::Sound boom("boom.wav");
boom.Play();
Definition at line 19 of file Sound.hpp.
Constructor & Destructor Documentation
Sound() [1/6]
raylib::Sound::Sound (const Sound &) delete
Sound() [2/6]
raylib::Sound::Sound () inline
Definition at line 24 of file Sound.hpp.
            {
        stream = { nullptr, nullptr, 0, 0, 0 };
        frameCount = 0;
    }
References Sound::frameCount, and Sound::stream.
Sound() [3/6]
raylib::Sound::Sound (::AudioStream stream, unsigned int frameCount) inline
Definition at line 29 of file Sound.hpp.
                                                       : ::Sound{stream, frameCount} {
        // Nothing.
    }
Sound() [4/6]
raylib::Sound::Sound (Sound && other) inline
Definition at line 33 of file Sound.hpp.
{
        set(other);
        other.stream = { nullptr, nullptr, 0, 0, 0 };
        other.frameCount = 0;
    }
References set().
Sound() [5/6]
raylib::Sound::Sound (const std::string & fileName) inline
Loads a sound from the given file.
Exceptions
raylib::RaylibException Throws if the Sound failed to load.
Definition at line 45 of file Sound.hpp.
{
        Load(fileName);
    }
References Load().
Sound() [6/6]
raylib::Sound::Sound (const ::Wave & wave) inline
Loads a sound from the given Wave.
Exceptions
raylib::RaylibException Throws if the Sound failed to load.
Definition at line 54 of file Sound.hpp.
{
        Load(wave);
    }
References Load().
~Sound()
raylib::Sound::~Sound () inline
Definition at line 58 of file Sound.hpp.
             {
        Unload();
    }
References Unload().
Member Function Documentation
GetFrameCount()
unsigned int raylib::Sound::GetFrameCount () const inline
Retrieves the frameCount value for the object.
Returns
The frameCount value of the object.
Definition at line 62 of file Sound.hpp.
GetStream()
::AudioStream raylib::Sound::GetStream () const inline
Retrieves the stream value for the object.
Returns
The stream value of the object.
Definition at line 63 of file Sound.hpp.
IsPlaying()
bool raylib::Sound::IsPlaying () const inline
Check if a sound is currently playing
Definition at line 140 of file Sound.hpp.
{
        return ::IsSoundPlaying(*this);
    }
IsReady()
bool raylib::Sound::IsReady () const inline
Retrieve whether or not the Sound buffer is loaded.
Returns
True or false depending on whether the Sound buffer is loaded.
Definition at line 197 of file Sound.hpp.
{
        return ::IsSoundReady(*this);
    }
Load() [1/2]
void raylib::Sound::Load (const ::Wave & wave) inline
Loads the given Wave object into the Sound.
Exceptions
raylib::RaylibException Throws if the Sound failed to load.
Definition at line 185 of file Sound.hpp.
{
        set(::LoadSoundFromWave(wave));
        if (!IsReady()) {
            throw new RaylibException("Failed to load Wave");
        }
    }
References IsReady(), LoadSoundFromWave(), and set().
Load() [2/2]
void raylib::Sound::Load (const std::string & fileName) inline
Load a sound from the given file.
Exceptions
raylib::RaylibException Throws if the Sound failed to load.
Definition at line 173 of file Sound.hpp.
{
        set(::LoadSound(fileName.c_str()));
        if (!IsReady()) {
            throw new RaylibException("Failed to load Sound from file");
        }
    }
References IsReady(), LoadSound(), and set().
operator=() [1/2]
Sound & raylib::Sound::operator= (const Sound &) delete
operator=() [2/2]
Sound & raylib::Sound::operator= (Sound && other) inline noexcept
Definition at line 65 of file Sound.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.frameCount = 0;
        other.stream = { nullptr, nullptr, 0, 0, 0 };
        return *this;
    }
References set(), and Unload().
Pause()
Sound & raylib::Sound::Pause () inline
Pause a sound
Definition at line 124 of file Sound.hpp.
{
        ::PauseSound(*this);
        return *this;
    }
References PauseSound().
Play()
Sound & raylib::Sound::Play () inline
Play a sound
Definition at line 108 of file Sound.hpp.
{
        ::PlaySound(*this);
        return *this;
    }
References PlaySound().
Resume()
Sound & raylib::Sound::Resume () inline
Resume a paused sound
Definition at line 132 of file Sound.hpp.
{
        ::ResumeSound(*this);
        return *this;
    }
References ResumeSound().
set()
void raylib::Sound::set (const ::Sound & sound) inline protected
Definition at line 202 of file Sound.hpp.
{
        frameCount = sound.frameCount;
        stream = sound.stream;
    }
References Sound::frameCount, and Sound::stream.
SetFrameCount()
void raylib::Sound::SetFrameCount (unsigned int value) inline
Sets the frameCount value for the object.
Parameters
value The value of which to set frameCount to.
Definition at line 62 of file Sound.hpp.
SetPan()
Sound & raylib::Sound::SetPan (float pan = 0.5f) inline
Set pan for a sound (0.5 is center)
Definition at line 163 of file Sound.hpp.
{
        ::SetSoundPan(*this, pan);
        return *this;
    }
References SetSoundPan().
SetPitch()
Sound & raylib::Sound::SetPitch (float pitch) inline
Set pitch for a sound (1.0 is base level)
Definition at line 155 of file Sound.hpp.
{
        ::SetSoundPitch(*this, pitch);
        return *this;
    }
References SetSoundPitch().
SetStream()
void raylib::Sound::SetStream (::AudioStream value) inline
Sets the stream value for the object.
Parameters
value The value of which to set stream to.
Definition at line 63 of file Sound.hpp.
SetVolume()
Sound & raylib::Sound::SetVolume (float volume) inline
Set volume for a sound (1.0 is max level)
Definition at line 147 of file Sound.hpp.
{
        ::SetSoundVolume(*this, volume);
        return *this;
    }
References SetSoundVolume().
Stop()
Sound & raylib::Sound::Stop () inline
Stop playing a sound
Definition at line 116 of file Sound.hpp.
{
        ::StopSound(*this);
        return *this;
    }
References StopSound().
Unload()
void raylib::Sound::Unload () inline
Unload sound
Definition at line 97 of file Sound.hpp.
{
        // Protect against calling UnloadSound() twice.
        if (frameCount != 0) {
            ::UnloadSound(*this);
            frameCount = 0;
        }
    }
References Sound::frameCount, and UnloadSound().
Update() [1/2]
Sound & raylib::Sound::Update (const void * data) inline
Update sound buffer with new data, assuming it's the same sample count.
Definition at line 89 of file Sound.hpp.
{
        ::UpdateSound(*this, data, static_cast<int>(frameCount));
        return *this;
    }
References Sound::frameCount, and UpdateSound().
Update() [2/2]
Sound & raylib::Sound::Update (const void * data, int samplesCount) inline
Update sound buffer with new data
Definition at line 81 of file Sound.hpp.
{
        ::UpdateSound(*this, data, samplesCount);
        return *this;
    }
References UpdateSound().
Member Data Documentation
frameCount
unsigned int Sound::frameCount inherited
Definition at line 463 of file raylib.h.
stream
AudioStream Sound::stream inherited
Definition at line 462 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Sound.hpp