Techstorm-rivalry: raylib::Image Class Reference
raylib::Image Class Reference
#include <Image.hpp>
Public Member Functions
Image (void *data=nullptr, int width=0, int height=0, int mipmaps=1, int format=PIXELFORMAT_UNCOMPRESSED_R8G8B8A8)
Image (const ::Image &image)
Image (const std::string &fileName)
Image (const std::string &fileName, int width, int height, int format, int headerSize=0)
Image (const std::string &fileName, int *frames)
Image (const std::string &fileType, const unsigned char *fileData, int dataSize)
Image (const ::Texture2D &texture)
Image (int width, int height, ::Color color={255, 255, 255, 255})
Image (const std::string &text, int fontSize, ::Color color={255, 255, 255, 255})
Image (const ::Font &font, const std::string &text, float fontSize, float spacing, ::Color tint={255, 255, 255, 255})
Image (const Image &other)
Image (Image &&other)
~Image ()
Image & operator= (const ::Image &image)
Image & operator= (const Image &other)
Image & operator= (Image &&other) noexcept
void Load (const std::string &fileName)
void Load (const std::string &fileName, int width, int height, int format, int headerSize)
void Load (const std::string &fileName, int *frames)
void Load (const std::string &fileType, const unsigned char *fileData, int dataSize)
void Load (const ::Texture2D &texture)
void Unload ()
void Export (const std::string &fileName) const
unsigned char * ExportToMemory (const char *fileType, int *fileSize)
void ExportAsCode (const std::string &fileName) const
void * GetData () const
void SetData (void *value)
int GetWidth () const
void SetWidth (int value)
int GetHeight () const
void SetHeight (int value)
int GetMipmaps () const
void SetMipmaps (int value)
int GetFormat () const
void SetFormat (int value)
inline ::Vector2 GetSize () const
inline ::Image Copy () const
inline ::Image FromImage (::Rectangle rec) const
Image & Format (int newFormat)
Image & ToPOT (::Color fillColor)
Image & Crop (::Rectangle crop)
Image & AlphaCrop (float threshold)
Image & AlphaClear (::Color color, float threshold)
Image & AlphaMask (const ::Image &alphaMask)
Image & AlphaPremultiply ()
Image & Crop (int newWidth, int newHeight)
Image & Crop (::Vector2 size)
Image & Crop (int offsetX, int offsetY, int newWidth, int newHeight)
Image & Resize (int newWidth, int newHeight)
Image & ResizeNN (int newWidth, int newHeight)
Image & ResizeCanvas (int newWidth, int newHeight, int offsetX=0, int offsetY=0, ::Color color={255, 255, 255, 255})
Image & Mipmaps ()
Image & Dither (int rBpp, int gBpp, int bBpp, int aBpp)
Image & FlipVertical ()
Image & FlipHorizontal ()
Image & Rotate (int degrees)
Image & RotateCW ()
Image & RotateCCW ()
Image & ColorTint (::Color color={255, 255, 255, 255})
Image & ColorInvert ()
Image & ColorGrayscale ()
Image & ColorContrast (float contrast)
Image & ColorBrightness (int brightness)
Image & ColorReplace (::Color color, ::Color replace)
Rectangle GetAlphaBorder (float threshold) const
raylib::Color GetColor (int x=0, int y=0) const
raylib::Color GetColor (::Vector2 position) const
Image & ClearBackground (::Color color={0, 0, 0, 255})
void DrawPixel (int posX, int posY, ::Color color={255, 255, 255, 255})
void DrawPixel (::Vector2 position, ::Color color={255, 255, 255, 255})
void DrawLine (int startPosX, int startPosY, int endPosX, int endPosY, ::Color color={255, 255, 255, 255})
void DrawLine (::Vector2 start, ::Vector2 end, ::Color color={255, 255, 255, 255})
void DrawCircle (int centerX, int centerY, int radius, ::Color color={255, 255, 255, 255})
void DrawCircle (::Vector2 center, int radius, ::Color color={255, 255, 255, 255})
void DrawRectangle (int posX, int posY, int width, int height, ::Color color={255, 255, 255, 255})
void DrawRectangle (Vector2 position, Vector2 size, ::Color color={255, 255, 255, 255})
void DrawRectangle (::Rectangle rec, ::Color color={255, 255, 255, 255})
void DrawRectangleLines (::Rectangle rec, int thick=1, ::Color color={255, 255, 255, 255})
void Draw (const ::Image &src, ::Rectangle srcRec, ::Rectangle dstRec, ::Color tint={255, 255, 255, 255})
void DrawText (const std::string &text, ::Vector2 position, int fontSize, ::Color color={255, 255, 255, 255})
void DrawText (const std::string &text, int x, int y, int fontSize, ::Color color={255, 255, 255, 255})
void DrawText (const ::Font &font, const std::string &text, ::Vector2 position, float fontSize, float spacing, ::Color tint={255, 255, 255, 255})
inline ::Color * LoadColors () const
inline ::Color * LoadPalette (int maxPaletteSize, int *colorsCount) const
void UnloadColors (::Color *colors) const
void UnloadPalette (::Color *colors) const
inline ::Texture2D LoadTexture () const
operator::Texture2D ()
int GetPixelDataSize () const
bool IsReady () const
Static Public Member Functions
::Image Text (const std::string &text, int fontSize, ::Color color={255, 255, 255, 255})
::Image Text (const ::Font &font, const std::string &text, float fontSize, float spacing, ::Color tint={255, 255, 255, 255})
::Image LoadFromScreen ()
::Image Color (int width, int height, ::Color color={255, 255, 255, 255})
::Image GradientLinear (int width, int height, int direction, ::Color start, ::Color end)
::Image GradientRadial (int width, int height, float density, ::Color inner, ::Color outer)
::Image Checked (int width, int height, int checksX, int checksY, ::Color col1={255, 255, 255, 255}, ::Color col2={0, 0, 0, 255})
::Image WhiteNoise (int width, int height, float factor)
::Image Cellular (int width, int height, int tileSize)
static int GetPixelDataSize (int width, int height, int format=PIXELFORMAT_UNCOMPRESSED_R32G32B32A32)
Public Attributes
void * data
int width
int height
int mipmaps
int format
Protected Member Functions
void set (const ::Image &image)
Detailed Description
Image type, bpp always RGBA (32bit)
Data stored in CPU memory (RAM)
Definition at line 17 of file Image.hpp.
Constructor & Destructor Documentation
Image() [1/12]
raylib::Image::Image (void * data = nullptr, int width = 0, int height = 0, int mipmaps = 1, int format = PIXELFORMAT_UNCOMPRESSED_R8G8B8A8) inline
Definition at line 19 of file Image.hpp.
                                                            : ::Image{data, width, height, mipmaps, format} {
        // Nothing.
    }
Image() [2/12]
raylib::Image::Image (const ::Image & image) inline
Definition at line 27 of file Image.hpp.
{
        set(image);
    }
References set().
Image() [3/12]
raylib::Image::Image (const std::string & fileName) inline
Load an image from the given file.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
See also
Load()
Definition at line 38 of file Image.hpp.
{
        Load(fileName);
    }
References Load().
Image() [4/12]
raylib::Image::Image (const std::string & fileName, int width, int height, int format, int headerSize = 0) inline
Load a raw image from the given file, with the provided width, height, and formats.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
See also
LoadRaw()
Definition at line 49 of file Image.hpp.
{
        Load(fileName, width, height, format, headerSize);
    }
References Image::format, Image::height, Load(), and Image::width.
Image() [5/12]
raylib::Image::Image (const std::string & fileName, int * frames) inline
Load an animation image from the given file.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
See also
LoadAnim()
Definition at line 60 of file Image.hpp.
{
        Load(fileName, frames);
    }
References Load().
Image() [6/12]
raylib::Image::Image (const std::string & fileType, const unsigned char * fileData, int dataSize) inline
Load an image from the given file.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
Definition at line 69 of file Image.hpp.
{
        Load(fileType, fileData, dataSize);
    }
References Load().
Image() [7/12]
raylib::Image::Image (const ::Texture2D & texture) inline
Load an image from the given file.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
Definition at line 78 of file Image.hpp.
{
        Load(texture);
    }
References Load().
Image() [8/12]
raylib::Image::Image (int width, int height, ::Color color = {255, 255, 255, 255}) inline
Definition at line 82 of file Image.hpp.
                                               {255, 255, 255, 255}) {
        set(::GenImageColor(width, height, color));
    }
Image() [9/12]
raylib::Image::Image (const std::string & text, int fontSize, ::Color color = {255, 255, 255, 255}) inline
Definition at line 86 of file Image.hpp.
                                                             {255, 255, 255, 255}) {
        set(::ImageText(text.c_str(), fontSize, color));
    }
Image() [10/12]
raylib::Image::Image (const ::Font & font, const std::string & text, float fontSize, float spacing, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 90 of file Image.hpp.
                         {255, 255, 255, 255}) {
        set(::ImageTextEx(font, text.c_str(), fontSize, spacing, tint));
    }
Image() [11/12]
raylib::Image::Image (const Image & other) inline
Definition at line 95 of file Image.hpp.
{
        set(other.Copy());
    }
References Copy(), and set().
Image() [12/12]
raylib::Image::Image (Image && other) inline
Definition at line 99 of file Image.hpp.
{
        set(other);
        other.data = nullptr;
        other.width = 0;
        other.height = 0;
        other.mipmaps = 0;
        other.format = 0;
    }
References set().
~Image()
raylib::Image::~Image () inline
Definition at line 170 of file Image.hpp.
             {
        Unload();
    }
References Unload().
Member Function Documentation
AlphaClear()
Image & raylib::Image::AlphaClear (::Color color, float threshold) inline
Clear alpha channel to desired color
Definition at line 381 of file Image.hpp.
{
        ::ImageAlphaClear(this, color, threshold);
        return *this;
    }
References ImageAlphaClear().
AlphaCrop()
Image & raylib::Image::AlphaCrop (float threshold) inline
Crop image depending on alpha value
Definition at line 373 of file Image.hpp.
{
        ::ImageAlphaCrop(this, threshold);
        return *this;
    }
References ImageAlphaCrop().
AlphaMask()
Image & raylib::Image::AlphaMask (const ::Image & alphaMask) inline
Apply alpha mask to image
Definition at line 389 of file Image.hpp.
{
        ::ImageAlphaMask(this, alphaMask);
        return *this;
    }
References ImageAlphaMask().
AlphaPremultiply()
Image & raylib::Image::AlphaPremultiply () inline
Premultiply alpha channel
Definition at line 397 of file Image.hpp.
{
        ::ImageAlphaPremultiply(this);
        return *this;
    }
References ImageAlphaPremultiply().
Cellular()
::Image raylib::Image::Cellular (int width, int height, int tileSize) inline static
Generate image: cellular algorithm. Bigger tileSize means bigger cells
Definition at line 166 of file Image.hpp.
{
        return ::GenImageCellular(width, height, tileSize);
    }
References Image::height, and Image::width.
Checked()
::Image raylib::Image::Checked (int width, int height, int checksX, int checksY, ::Color col1 = {255, 255, 255, 255}, ::Color col2 = {0, 0, 0, 255}) inline static
Generate image: checked
Definition at line 151 of file Image.hpp.
                         {255, 255, 255, 255}, ::Color col2 = {0, 0, 0, 255}) {
        return ::GenImageChecked(width, height, checksX, checksY, col1, col2);
    }
ClearBackground()
Image & raylib::Image::ClearBackground (::Color color = {0, 0, 0, 255}) inline
Clear image background with given color
Definition at line 589 of file Image.hpp.
                                                {0, 0, 0, 255}) {
        ::ImageClearBackground(this, color);
        return *this;
    }
Color()
::Image raylib::Image::Color (int width, int height, ::Color color = {255, 255, 255, 255}) inline static
Generate image: plain color
Definition at line 129 of file Image.hpp.
                                                            {255, 255, 255, 255}) {
        return ::GenImageColor(width, height, color);
    }
ColorBrightness()
Image & raylib::Image::ColorBrightness (int brightness) inline
Modify image color: brightness
Parameters
brightness Brightness values between -255 and 255
Definition at line 550 of file Image.hpp.
{
        ::ImageColorBrightness(this, brightness);
        return *this;
    }
References ImageColorBrightness().
ColorContrast()
Image & raylib::Image::ColorContrast (float contrast) inline
Modify image color: contrast
Parameters
contrast Contrast values between -100 and 100
Definition at line 540 of file Image.hpp.
{
        ::ImageColorContrast(this, contrast);
        return *this;
    }
References ImageColorContrast().
ColorGrayscale()
Image & raylib::Image::ColorGrayscale () inline
Modify image color: grayscale
Definition at line 530 of file Image.hpp.
{
        ::ImageColorGrayscale(this);
        return *this;
    }
References ImageColorGrayscale().
ColorInvert()
Image & raylib::Image::ColorInvert () inline
Modify image color: invert
Definition at line 522 of file Image.hpp.
{
        ::ImageColorInvert(this);
        return *this;
    }
References ImageColorInvert().
ColorReplace()
Image & raylib::Image::ColorReplace (::Color color, ::Color replace) inline
Modify image color: replace color
Definition at line 558 of file Image.hpp.
{
        ::ImageColorReplace(this, color, replace);
        return *this;
    }
References ImageColorReplace().
ColorTint()
Image & raylib::Image::ColorTint (::Color color = {255, 255, 255, 255}) inline
Modify image color: tint
Definition at line 514 of file Image.hpp.
                                          {255, 255, 255, 255}) {
        ::ImageColorTint(this, color);
        return *this;
    }
Copy()
inline ::Image raylib::Image::Copy () const inline
Create an image duplicate (useful for transformations)
Definition at line 335 of file Image.hpp.
{
        return ::ImageCopy(*this);
    }
Crop() [1/4]
Image & raylib::Image::Crop (::Rectangle crop) inline
Crop an image to area defined by a rectangle
Definition at line 365 of file Image.hpp.
{
        ::ImageCrop(this, crop);
        return *this;
    }
References ImageCrop().
Crop() [2/4]
Image & raylib::Image::Crop (::Vector2 size) inline
Crop an image to a new given width and height based on a vector.
Definition at line 412 of file Image.hpp.
{
        return Crop(0, 0, static_cast<int>(size.x), static_cast<int>(size.y));
    }
References Crop(), Vector2::x, and Vector2::y.
Crop() [3/4]
Image & raylib::Image::Crop (int newWidth, int newHeight) inline
Crop an image to a new given width and height.
Definition at line 405 of file Image.hpp.
{
        return Crop(0, 0, newWidth, newHeight);
    }
References Crop().
Crop() [4/4]
Image & raylib::Image::Crop (int offsetX, int offsetY, int newWidth, int newHeight) inline
Crop an image to area defined by a rectangle
Definition at line 419 of file Image.hpp.
{
        ::Rectangle rect{
            static_cast<float>(offsetX),
            static_cast<float>(offsetY),
            static_cast<float>(newWidth),
            static_cast<float>(newHeight)
        };
        ::ImageCrop(this, rect);
        return *this;
    }
References ImageCrop().
Dither()
Image & raylib::Image::Dither (int rBpp, int gBpp, int bBpp, int aBpp) inline
Dither image data to 16bpp or lower (Floyd-Steinberg dithering)
Definition at line 466 of file Image.hpp.
{
        ::ImageDither(this, rBpp, gBpp, bBpp, aBpp);
        return *this;
    }
References ImageDither().
Draw()
void raylib::Image::Draw (const ::Image & src, ::Rectangle srcRec, ::Rectangle dstRec, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 643 of file Image.hpp.
                         {255, 255, 255, 255}) {
        ::ImageDraw(this, src, srcRec, dstRec, tint);
    }
DrawCircle() [1/2]
void raylib::Image::DrawCircle (::Vector2 center, int radius, ::Color color = {255, 255, 255, 255}) inline
Definition at line 619 of file Image.hpp.
                          {255, 255, 255, 255}) {
        ::ImageDrawCircleV(this, center, radius, color);
    }
DrawCircle() [2/2]
void raylib::Image::DrawCircle (int centerX, int centerY, int radius, ::Color color = {255, 255, 255, 255}) inline
Definition at line 614 of file Image.hpp.
                          {255, 255, 255, 255}) {
        ::ImageDrawCircle(this, centerX, centerY, radius, color);
    }
DrawLine() [1/2]
void raylib::Image::DrawLine (::Vector2 start, ::Vector2 end, ::Color color = {255, 255, 255, 255}) inline
Definition at line 610 of file Image.hpp.
                                                                   {255, 255, 255, 255}) {
        ::ImageDrawLineV(this, start, end, color);
    }
DrawLine() [2/2]
void raylib::Image::DrawLine (int startPosX, int startPosY, int endPosX, int endPosY, ::Color color = {255, 255, 255, 255}) inline
Definition at line 605 of file Image.hpp.
                          {255, 255, 255, 255}) {
        ::ImageDrawLine(this, startPosX, startPosY, endPosX, endPosY, color);
    }
DrawPixel() [1/2]
void raylib::Image::DrawPixel (::Vector2 position, ::Color color = {255, 255, 255, 255}) inline
Definition at line 601 of file Image.hpp.
                                                          {255, 255, 255, 255}) {
        ::ImageDrawPixelV(this, position, color);
    }
DrawPixel() [2/2]
void raylib::Image::DrawPixel (int posX, int posY, ::Color color = {255, 255, 255, 255}) inline
Draw pixel within an image
Definition at line 597 of file Image.hpp.
                                                            {255, 255, 255, 255}) {
        ::ImageDrawPixel(this, posX, posY, color);
    }
DrawRectangle() [1/3]
void raylib::Image::DrawRectangle (::Rectangle rec, ::Color color = {255, 255, 255, 255}) inline
Definition at line 634 of file Image.hpp.
                                                           {255, 255, 255, 255}) {
        ::ImageDrawRectangleRec(this, rec, color);
    }
DrawRectangle() [2/3]
void raylib::Image::DrawRectangle (int posX, int posY, int width, int height, ::Color color = {255, 255, 255, 255}) inline
Definition at line 624 of file Image.hpp.
                          {255, 255, 255, 255}) {
        ::ImageDrawRectangle(this, posX, posY, width, height, color);
    }
DrawRectangle() [3/3]
void raylib::Image::DrawRectangle (Vector2 position, Vector2 size, ::Color color = {255, 255, 255, 255}) inline
Definition at line 629 of file Image.hpp.
                          {255, 255, 255, 255}) {
        ::ImageDrawRectangleV(this, position, size, color);
    }
DrawRectangleLines()
void raylib::Image::DrawRectangleLines (::Rectangle rec, int thick = 1, ::Color color = {255, 255, 255, 255}) inline
Definition at line 638 of file Image.hpp.
                          {255, 255, 255, 255}) {
        ::ImageDrawRectangleLines(this, rec, thick, color);
    }
DrawText() [1/3]
void raylib::Image::DrawText (const ::Font & font, const std::string & text, ::Vector2 position, float fontSize, float spacing, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 663 of file Image.hpp.
                                                        {255, 255, 255, 255}) {
        ::ImageDrawTextEx(this, font, text.c_str(), position, fontSize, spacing, tint);
    }
DrawText() [2/3]
void raylib::Image::DrawText (const std::string & text, ::Vector2 position, int fontSize, ::Color color = {255, 255, 255, 255}) inline
Definition at line 648 of file Image.hpp.
                          {255, 255, 255, 255}) {
        ::ImageDrawText(this,
            text.c_str(),
            static_cast<int>(position.x),
            static_cast<int>(position.y),
            fontSize,
            color);
    }
DrawText() [3/3]
void raylib::Image::DrawText (const std::string & text, int x, int y, int fontSize, ::Color color = {255, 255, 255, 255}) inline
Definition at line 658 of file Image.hpp.
                          {255, 255, 255, 255}) {
        ::ImageDrawText(this, text.c_str(), x, y, fontSize, color);
    }
Export()
void raylib::Image::Export (const std::string & fileName) const inline
Export image data to file, returns true on success
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
Definition at line 295 of file Image.hpp.
{
        if (!::ExportImage(*this, fileName.c_str())) {
            throw RaylibException(TextFormat("Failed to export Image to file: %s", fileName.c_str()));
        }
    }
References TextFormat().
ExportAsCode()
void raylib::Image::ExportAsCode (const std::string & fileName) const inline
Export image as code file defining an array of bytes, returns true on success
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
Definition at line 313 of file Image.hpp.
{
        if (!::ExportImageAsCode(*this, fileName.c_str())) {
            throw RaylibException(TextFormat("Failed to export Image code to file: %s", fileName.c_str()));
        }
    }
References TextFormat().
ExportToMemory()
unsigned char * raylib::Image::ExportToMemory (const char * fileType, int * fileSize) inline
Export image to memory buffer
Definition at line 304 of file Image.hpp.
{
        return ::ExportImageToMemory(*this, fileType, fileSize);
    }
FlipHorizontal()
Image & raylib::Image::FlipHorizontal () inline
Flip image horizontally
Definition at line 482 of file Image.hpp.
{
        ::ImageFlipHorizontal(this);
        return *this;
    }
References ImageFlipHorizontal().
FlipVertical()
Image & raylib::Image::FlipVertical () inline
Flip image vertically
Definition at line 474 of file Image.hpp.
{
        ::ImageFlipVertical(this);
        return *this;
    }
References ImageFlipVertical().
Format()
Image & raylib::Image::Format (int newFormat) inline
Convert image data to desired format
Definition at line 349 of file Image.hpp.
{
        ::ImageFormat(this, newFormat);
        return *this;
    }
References ImageFormat().
FromImage()
inline ::Image raylib::Image::FromImage (::Rectangle rec) const inline
Create an image from another image piece
Definition at line 342 of file Image.hpp.
{
        return ::ImageFromImage(*this, rec);
    }
GetAlphaBorder()
Rectangle raylib::Image::GetAlphaBorder (float threshold) const inline
Get image alpha border rectangle
Parameters
threshold Threshold is defined as a percentatge: 0.0f -> 1.0f
Definition at line 568 of file Image.hpp.
{
        return ::GetImageAlphaBorder(*this, threshold);
    }
GetColor() [1/2]
raylib::Color raylib::Image::GetColor (::Vector2 position) const inline
Get image pixel color at vector position
Definition at line 582 of file Image.hpp.
{
        return ::GetImageColor(*this, static_cast<int>(position.x), static_cast<int>(position.y));
    }
References Vector2::x, and Vector2::y.
GetColor() [2/2]
raylib::Color raylib::Image::GetColor (int x = 0, int y = 0) const inline
Get image pixel color at (x, y) position
Definition at line 575 of file Image.hpp.
{
        return ::GetImageColor(*this, x, y);
    }
GetData()
void * raylib::Image::GetData () const inline
Retrieves the data value for the object.
Returns
The data value of the object.
Definition at line 319 of file Image.hpp.
GetFormat()
int raylib::Image::GetFormat () const inline
Retrieves the format value for the object.
Returns
The format value of the object.
Definition at line 323 of file Image.hpp.
GetHeight()
int raylib::Image::GetHeight () const inline
Retrieves the height value for the object.
Returns
The height value of the object.
Definition at line 321 of file Image.hpp.
GetMipmaps()
int raylib::Image::GetMipmaps () const inline
Retrieves the mipmaps value for the object.
Returns
The mipmaps value of the object.
Definition at line 322 of file Image.hpp.
GetPixelDataSize() [1/2]
int raylib::Image::GetPixelDataSize () const inline
Returns the pixel data size based on the current image.
Returns
The pixel data size of the image.
Definition at line 724 of file Image.hpp.
{
        return ::GetPixelDataSize(width, height, format);
    }
References Image::format, Image::height, and Image::width.
GetPixelDataSize() [2/2]
static int raylib::Image::GetPixelDataSize (int width, int height, int format = PIXELFORMAT_UNCOMPRESSED_R32G32B32A32) inline static
Get pixel data size in bytes for certain format
Definition at line 715 of file Image.hpp.
{
        return ::GetPixelDataSize(width, height, format);
    }
References Image::format, Image::height, and Image::width.
GetSize()
inline ::Vector2 raylib::Image::GetSize () const inline
Retrieve the width and height of the image.
Definition at line 328 of file Image.hpp.
{
        return {static_cast<float>(width), static_cast<float>(height)};
    }
References Image::height, and Image::width.
GetWidth()
int raylib::Image::GetWidth () const inline
Retrieves the width value for the object.
Returns
The width value of the object.
Definition at line 320 of file Image.hpp.
GradientLinear()
::Image raylib::Image::GradientLinear (int width, int height, int direction, ::Color start, ::Color end) inline static
Generate image: linear gradient
Definition at line 136 of file Image.hpp.
{
        return ::GenImageGradientLinear(width, height, direction, start, end);
    }
References Image::height, and Image::width.
GradientRadial()
::Image raylib::Image::GradientRadial (int width, int height, float density, ::Color inner, ::Color outer) inline static
Generate image: radial gradient
Definition at line 143 of file Image.hpp.
{
        return ::GenImageGradientRadial(width, height, density, inner, outer);
    }
References Image::height, and Image::width.
IsReady()
bool raylib::Image::IsReady () const inline
Retrieve whether or not the Image has been loaded.
Returns
True or false depending on whether the Image has been loaded.
Definition at line 733 of file Image.hpp.
{
        return ::IsImageReady(*this);
    }
Load() [1/5]
void raylib::Image::Load (const ::Texture2D & texture) inline
Load an image from the given file.
Exceptions
raylib::RaylibException Thrown if the image animation to load from the file.
See also
LoadImageFromTexture()
Definition at line 273 of file Image.hpp.
{
        set(::LoadImageFromTexture(texture));
        if (!IsReady()) {
            throw RaylibException("Failed to load Image from texture.");
        }
    }
References IsReady(), LoadImageFromTexture(), and set().
Load() [2/5]
void raylib::Image::Load (const std::string & fileName) inline
Load image from file into CPU memory (RAM)
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
See also
LoadImage()
Definition at line 214 of file Image.hpp.
{
        set(::LoadImage(fileName.c_str()));
        if (!IsReady()) {
            throw RaylibException("Failed to load Image from file: " + fileName);
        }
    }
References IsReady(), and set().
Load() [3/5]
void raylib::Image::Load (const std::string & fileName, int * frames) inline
Load image sequence from file (frames appended to image.data).
Exceptions
raylib::RaylibException Thrown if the image animation to load from the file.
See also
LoadImageAnim()
Definition at line 242 of file Image.hpp.
{
        set(::LoadImageAnim(fileName.c_str(), frames));
        if (!IsReady()) {
            throw RaylibException("Failed to load Image from file: " + fileName);
        }
    }
References IsReady(), and set().
Load() [4/5]
void raylib::Image::Load (const std::string & fileName, int width, int height, int format, int headerSize) inline
Load image from RAW file data.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
See also
LoadImageRaw()
Definition at line 228 of file Image.hpp.
{
        set(::LoadImageRaw(fileName.c_str(), width, height, format, headerSize));
        if (!IsReady()) {
            throw RaylibException("Failed to load Image from file: " + fileName);
        }
    }
References Image::format, Image::height, IsReady(), set(), and Image::width.
Load() [5/5]
void raylib::Image::Load (const std::string & fileType, const unsigned char * fileData, int dataSize) inline
Load image from memory buffer, fileType refers to extension: i.e. "png".
Exceptions
raylib::RaylibException Thrown if the image animation to load from the file.
See also
LoadImageFromMemory()
Definition at line 256 of file Image.hpp.
{
        set(::LoadImageFromMemory(fileType.c_str(), fileData, dataSize));
        if (!IsReady()) {
            throw RaylibException("Failed to load Image data with file type: " + fileType);
        }
    }
References IsReady(), and set().
LoadColors()
inline ::Color * raylib::Image::LoadColors () const inline
Load color data from image as a Color array (RGBA - 32bit)
Definition at line 671 of file Image.hpp.
{
        return ::LoadImageColors(*this);
    }
LoadFromScreen()
::Image raylib::Image::LoadFromScreen () inline static
Get pixel data from screen buffer and return an Image (screenshot)
Definition at line 122 of file Image.hpp.
{
        return ::LoadImageFromScreen();
    }
LoadPalette()
inline ::Color * raylib::Image::LoadPalette (int maxPaletteSize, int * colorsCount) const inline
Load colors palette from image as a Color array (RGBA - 32bit)
Definition at line 678 of file Image.hpp.
{
        return ::LoadImagePalette(*this, maxPaletteSize, colorsCount);
    }
LoadTexture()
inline ::Texture2D raylib::Image::LoadTexture () const inline
Load texture from image data.
Definition at line 699 of file Image.hpp.
{
        return ::LoadTextureFromImage(*this);
    }
Mipmaps()
Image & raylib::Image::Mipmaps () inline
Generate all mipmap levels for a provided image
Definition at line 458 of file Image.hpp.
{
        ::ImageMipmaps(this);
        return *this;
    }
References ImageMipmaps().
operator::Texture2D()
raylib::Image::operator::Texture2D () inline
Loads a texture from the image data.
See also
LoadTexture()
Definition at line 708 of file Image.hpp.
{
        return LoadTexture();
    }
References LoadTexture().
operator=() [1/3]
Image & raylib::Image::operator= (const ::Image & image) inline
Definition at line 174 of file Image.hpp.
{
        set(image);
        return *this;
    }
References set().
operator=() [2/3]
Image & raylib::Image::operator= (const Image & other) inline
Definition at line 179 of file Image.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other.Copy());
        return *this;
    }
References Copy(), set(), and Unload().
operator=() [3/3]
Image & raylib::Image::operator= (Image && other) inline noexcept
Definition at line 190 of file Image.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.data = nullptr;
        other.width = 0;
        other.height = 0;
        other.mipmaps = 0;
        other.format = 0;
        return *this;
    }
References set(), and Unload().
Resize()
Image & raylib::Image::Resize (int newWidth, int newHeight) inline
Resize and image to new size
Definition at line 433 of file Image.hpp.
{
        ::ImageResize(this, newWidth, newHeight);
        return *this;
    }
References ImageResize().
ResizeCanvas()
Image & raylib::Image::ResizeCanvas (int newWidth, int newHeight, int offsetX = 0, int offsetY = 0, ::Color color = {255, 255, 255, 255}) inline
Resize canvas and fill with color
Definition at line 449 of file Image.hpp.
                          {255, 255, 255, 255}) {
        ::ImageResizeCanvas(this, newWidth, newHeight, offsetX, offsetY, color);
        return *this;
    }
ResizeNN()
Image & raylib::Image::ResizeNN (int newWidth, int newHeight) inline
Resize and image to new size using Nearest-Neighbor scaling algorithm
Definition at line 441 of file Image.hpp.
{
        ::ImageResizeNN(this, newWidth, newHeight);
        return *this;
    }
References ImageResizeNN().
Rotate()
Image & raylib::Image::Rotate (int degrees) inline
Rotate image by input angle in degrees (-359 to 359)
Definition at line 490 of file Image.hpp.
{
        ::ImageRotate(this, degrees);
        return *this;
    }
References ImageRotate().
RotateCCW()
Image & raylib::Image::RotateCCW () inline
Rotate image counter-clockwise 90deg
Definition at line 506 of file Image.hpp.
{
        ::ImageRotateCCW(this);
        return *this;
    }
References ImageRotateCCW().
RotateCW()
Image & raylib::Image::RotateCW () inline
Rotate image clockwise 90deg
Definition at line 498 of file Image.hpp.
{
        ::ImageRotateCW(this);
        return *this;
    }
References ImageRotateCW().
set()
void raylib::Image::set (const ::Image & image) inline protected
Definition at line 738 of file Image.hpp.
{
        data = image.data;
        width = image.width;
        height = image.height;
        mipmaps = image.mipmaps;
        format = image.format;
    }
References Image::data, Image::format, Image::height, Image::mipmaps, and Image::width.
SetData()
void raylib::Image::SetData (void * value) inline
Sets the data value for the object.
Parameters
value The value of which to set data to.
Definition at line 319 of file Image.hpp.
SetFormat()
void raylib::Image::SetFormat (int value) inline
Sets the format value for the object.
Parameters
value The value of which to set format to.
Definition at line 323 of file Image.hpp.
SetHeight()
void raylib::Image::SetHeight (int value) inline
Sets the height value for the object.
Parameters
value The value of which to set height to.
Definition at line 321 of file Image.hpp.
SetMipmaps()
void raylib::Image::SetMipmaps (int value) inline
Sets the mipmaps value for the object.
Parameters
value The value of which to set mipmaps to.
Definition at line 322 of file Image.hpp.
SetWidth()
void raylib::Image::SetWidth (int value) inline
Sets the width value for the object.
Parameters
value The value of which to set width to.
Definition at line 320 of file Image.hpp.
Text() [1/2]
::Image raylib::Image::Text (const ::Font & font, const std::string & text, float fontSize, float spacing, ::Color tint = {255, 255, 255, 255}) inline static
Definition at line 114 of file Image.hpp.
                         {255, 255, 255, 255}) {
        return ::ImageTextEx(font, text.c_str(), fontSize, spacing, tint);
    }
Text() [2/2]
::Image raylib::Image::Text (const std::string & text, int fontSize, ::Color color = {255, 255, 255, 255}) inline static
Definition at line 109 of file Image.hpp.
                          {255, 255, 255, 255}) {
        return ::ImageText(text.c_str(), fontSize, color);
    }
ToPOT()
Image & raylib::Image::ToPOT (::Color fillColor) inline
Convert image to POT (power-of-two)
Definition at line 357 of file Image.hpp.
{
        ::ImageToPOT(this, fillColor);
        return *this;
    }
References ImageToPOT().
Unload()
void raylib::Image::Unload () inline
Unload image from CPU memory (RAM)
Definition at line 283 of file Image.hpp.
{
        if (data != nullptr) {
            ::UnloadImage(*this);
            data = nullptr;
        }
    }
References Image::data, and UnloadImage().
UnloadColors()
void raylib::Image::UnloadColors (::Color * colors) const inline
Unload color data loaded with LoadImageColors()
Definition at line 685 of file Image.hpp.
{
        ::UnloadImageColors(colors);
    }
References UnloadImageColors().
UnloadPalette()
void raylib::Image::UnloadPalette (::Color * colors) const inline
Unload colors palette loaded with LoadImagePalette()
Definition at line 692 of file Image.hpp.
{
        ::UnloadImagePalette(colors);
    }
References UnloadImagePalette().
WhiteNoise()
::Image raylib::Image::WhiteNoise (int width, int height, float factor) inline static
Generate image: white noise
Definition at line 159 of file Image.hpp.
{
        return ::GenImageWhiteNoise(width, height, factor);
    }
References Image::height, and Image::width.
Member Data Documentation
data
void* Image::data inherited
Definition at line 253 of file raylib.h.
format
int Image::format inherited
Definition at line 257 of file raylib.h.
height
int Image::height inherited
Definition at line 255 of file raylib.h.
mipmaps
int Image::mipmaps inherited
Definition at line 256 of file raylib.h.
width
int Image::width inherited
Definition at line 254 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Image.hpp