Techstorm-rivalry: raylib::Color Class Reference
raylib::Color Class Reference
#include <Color.hpp>
Public Member Functions
Color (const ::Color &color)
Color (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha=255)
Color ()
Color (::Vector3 hsv)
Color (unsigned int hexValue)
Color (void *srcPtr, int format)
int ToInt () const
operator int () const
std::string ToString () const
operator std::string () const
Color Fade (float alpha) const
Vector4 Normalize () const
Color (::Vector4 normalized)
Vector3 ToHSV () const
unsigned char GetR () const
void SetR (unsigned char value)
unsigned char GetG () const
void SetG (unsigned char value)
unsigned char GetB () const
void SetB (unsigned char value)
unsigned char GetA () const
void SetA (unsigned char value)
Color & operator= (const ::Color &color)
Color & ClearBackground ()
void DrawPixel (int x, int y) const
void DrawPixel (::Vector2 pos) const
void DrawLine (int startPosX, int startPosY, int endPosX, int endPosY) const
void DrawLine (::Vector2 startPos, ::Vector2 endPos) const
void DrawLine (::Vector2 startPos, ::Vector2 endPos, float thick) const
void DrawLineBezier (::Vector2 startPos, ::Vector2 endPos, float thick=1.0f) const
void DrawLineStrip (::Vector2 *points, int numPoints) const
void DrawText (const std::string &text, int posX=0, int posY=0, int fontSize=10.0f) const
void DrawText (const ::Font &font, const std::string &text, ::Vector2 position, float fontSize, float spacing) const
void DrawText (const ::Font &font, const std::string &text, ::Vector2 position, ::Vector2 origin, float rotation, float fontSize, float spacing) const
void DrawRectangle (int posX, int posY, int width, int height) const
void DrawRectangle (::Vector2 position, ::Vector2 size) const
void DrawRectangle (::Rectangle rec) const
void DrawRectangle (::Rectangle rec, ::Vector2 origin, float rotation) const
void DrawRectangleLines (int posX, int posY, int width, int height) const
void DrawRectangleLines (::Rectangle rec, float lineThick) const
Color Tint (::Color tint)
Color Brightness (float factor)
Color Contrast (float contrast)
Color Alpha (float alpha) const
Color AlphaBlend (::Color dst, ::Color tint) const
Static Public Member Functions
::Color FromHSV (float hue, float saturation, float value)
static Color LightGray ()
static Color Gray ()
static Color DarkGray ()
static Color Yellow ()
static Color Gold ()
static Color Orange ()
static Color Pink ()
static Color Red ()
static Color Maroon ()
static Color Green ()
static Color Lime ()
static Color DarkGreen ()
static Color SkyBlue ()
static Color Blue ()
static Color DarkBlue ()
static Color Purple ()
static Color Violet ()
static Color DarkPurple ()
static Color Beige ()
static Color Brown ()
static Color DarkBrown ()
static Color White ()
static Color Black ()
static Color Blank ()
static Color Magenta ()
static Color RayWhite ()
Public Attributes
unsigned char r
unsigned char g
unsigned char b
unsigned char a
Protected Member Functions
void set (const ::Color &color)
Detailed Description
Color type, RGBA (32bit)
Definition at line 14 of file Color.hpp.
Constructor & Destructor Documentation
Color() [1/7]
raylib::Color::Color (const ::Color & color) inline
Definition at line 16 of file Color.hpp.
: ::Color{color.r, color.g, color.b, color.a} {}
Color() [2/7]
raylib::Color::Color (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha = 255) inline
Definition at line 18 of file Color.hpp.
                                       : ::Color{red, green, blue, alpha} {};
Color() [3/7]
raylib::Color::Color () inline
Black.
Definition at line 27 of file Color.hpp.
: ::Color{0, 0, 0, 255} {};
Color() [4/7]
raylib::Color::Color (::Vector3 hsv) inline
Returns a Color from HSV values
Definition at line 32 of file Color.hpp.
                       {
        set(::ColorFromHSV(hsv.x, hsv.y, hsv.z));
    }
References ColorFromHSV(), set(), Vector3::x, Vector3::y, and Vector3::z.
Color() [5/7]
raylib::Color::Color (unsigned int hexValue) inline
Get Color structure from hexadecimal value
Definition at line 46 of file Color.hpp.
{
        set(::GetColor(hexValue));
    }
References GetColor(), and set().
Color() [6/7]
raylib::Color::Color (void * srcPtr, int format) inline
Definition at line 50 of file Color.hpp.
{
        set(::GetPixelColor(srcPtr, format));
    }
References GetPixelColor(), and set().
Color() [7/7]
raylib::Color::Color (::Vector4 normalized) inline
Returns Color from normalized values [0..1]
Definition at line 93 of file Color.hpp.
{
        set(::ColorFromNormalized(normalized));
    }
References ColorFromNormalized(), and set().
Member Function Documentation
Alpha()
Color raylib::Color::Alpha (float alpha) const inline
Returns color with alpha applied, alpha goes from 0.0f to 1.0f
Definition at line 230 of file Color.hpp.
{
        return ::ColorAlpha(*this, alpha);
    }
AlphaBlend()
Color raylib::Color::AlphaBlend (::Color dst, ::Color tint) const inline
Returns src alpha-blended into dst color with tint
Definition at line 237 of file Color.hpp.
{
        return ::ColorAlphaBlend(dst, *this, tint);
    }
Beige()
static Color raylib::Color::Beige () inline static
Definition at line 259 of file Color.hpp.
{ return BEIGE; }
References BEIGE.
Black()
static Color raylib::Color::Black () inline static
Definition at line 263 of file Color.hpp.
{ return BLACK; }
References BLACK.
Blank()
static Color raylib::Color::Blank () inline static
Definition at line 264 of file Color.hpp.
{ return BLANK; }
References BLANK.
Blue()
static Color raylib::Color::Blue () inline static
Definition at line 254 of file Color.hpp.
{ return BLUE; }
References BLUE.
Brightness()
Color raylib::Color::Brightness (float factor) inline
Get color with brightness correction, brightness factor goes from -1.0f to 1.0f
Definition at line 216 of file Color.hpp.
{
        return ::ColorBrightness(*this, factor);
    }
Brown()
static Color raylib::Color::Brown () inline static
Definition at line 260 of file Color.hpp.
{ return BROWN; }
References BROWN.
ClearBackground()
Color & raylib::Color::ClearBackground () inline
Set background color (framebuffer clear color)
Definition at line 117 of file Color.hpp.
{
        ::ClearBackground(*this);
        return *this;
    }
References ClearBackground().
Contrast()
Color raylib::Color::Contrast (float contrast) inline
Get color with contrast correction, contrast values between -1.0f and 1.0f
Definition at line 223 of file Color.hpp.
{
        return ::ColorContrast(*this, contrast);
    }
DarkBlue()
static Color raylib::Color::DarkBlue () inline static
Definition at line 255 of file Color.hpp.
{ return DARKBLUE; }
References DARKBLUE.
DarkBrown()
static Color raylib::Color::DarkBrown () inline static
Definition at line 261 of file Color.hpp.
{ return DARKBROWN; }
References DARKBROWN.
DarkGray()
static Color raylib::Color::DarkGray () inline static
Definition at line 243 of file Color.hpp.
{ return DARKGRAY; }
References DARKGRAY.
DarkGreen()
static Color raylib::Color::DarkGreen () inline static
Definition at line 252 of file Color.hpp.
{ return DARKGREEN; }
References DARKGREEN.
DarkPurple()
static Color raylib::Color::DarkPurple () inline static
Definition at line 258 of file Color.hpp.
{ return DARKPURPLE; }
References DARKPURPLE.
DrawLine() [1/3]
void raylib::Color::DrawLine (::Vector2 startPos, ::Vector2 endPos) const inline
Draw a line using Vector points
Definition at line 143 of file Color.hpp.
{
        ::DrawLineV(startPos, endPos, *this);
    }
References DrawLineV().
DrawLine() [2/3]
void raylib::Color::DrawLine (::Vector2 startPos, ::Vector2 endPos, float thick) const inline
Draw a line using Vector points, with a given thickness
Definition at line 150 of file Color.hpp.
{
        ::DrawLineEx(startPos, endPos, thick, *this);
    }
References DrawLineEx().
DrawLine() [3/3]
void raylib::Color::DrawLine (int startPosX, int startPosY, int endPosX, int endPosY) const inline
Draw a line
Definition at line 136 of file Color.hpp.
{
        ::DrawLine(startPosX, startPosY, endPosX, endPosY, *this);
    }
References DrawLine().
DrawLineBezier()
void raylib::Color::DrawLineBezier (::Vector2 startPos, ::Vector2 endPos, float thick = 1.0f) const inline
Definition at line 154 of file Color.hpp.
{
        ::DrawLineBezier(startPos, endPos, thick, *this);
    }
References DrawLineBezier().
DrawLineStrip()
void raylib::Color::DrawLineStrip (::Vector2 * points, int numPoints) const inline
Definition at line 158 of file Color.hpp.
{
        ::DrawLineStrip(points, numPoints, *this);
    }
References DrawLineStrip().
DrawPixel() [1/2]
void raylib::Color::DrawPixel (::Vector2 pos) const inline
Draw a pixel
Definition at line 129 of file Color.hpp.
{
        ::DrawPixelV(pos, *this);
    }
References DrawPixelV().
DrawPixel() [2/2]
void raylib::Color::DrawPixel (int x, int y) const inline
Definition at line 122 of file Color.hpp.
{
        ::DrawPixel(x, y, *this);
    }
References DrawPixel().
DrawRectangle() [1/4]
void raylib::Color::DrawRectangle (::Rectangle rec) const inline
Definition at line 190 of file Color.hpp.
{
        ::DrawRectangleRec(rec, *this);
    }
References DrawRectangleRec().
DrawRectangle() [2/4]
void raylib::Color::DrawRectangle (::Rectangle rec, ::Vector2 origin, float rotation) const inline
Definition at line 194 of file Color.hpp.
{
        ::DrawRectanglePro(rec, origin, rotation, *this);
    }
References DrawRectanglePro().
DrawRectangle() [3/4]
void raylib::Color::DrawRectangle (::Vector2 position, ::Vector2 size) const inline
Definition at line 186 of file Color.hpp.
{
        ::DrawRectangleV(position, size, *this);
    }
References DrawRectangleV().
DrawRectangle() [4/4]
void raylib::Color::DrawRectangle (int posX, int posY, int width, int height) const inline
Definition at line 182 of file Color.hpp.
{
        ::DrawRectangle(posX, posY, width, height, *this);
    }
References DrawRectangle().
DrawRectangleLines() [1/2]
void raylib::Color::DrawRectangleLines (::Rectangle rec, float lineThick) const inline
Definition at line 202 of file Color.hpp.
{
        ::DrawRectangleLinesEx(rec, lineThick, *this);
    }
References DrawRectangleLinesEx().
DrawRectangleLines() [2/2]
void raylib::Color::DrawRectangleLines (int posX, int posY, int width, int height) const inline
Definition at line 198 of file Color.hpp.
{
        ::DrawRectangleLines(posX, posY, width, height, *this);
    }
References DrawRectangleLines().
DrawText() [1/3]
void raylib::Color::DrawText (const ::Font & font, const std::string & text, ::Vector2 position, ::Vector2 origin, float rotation, float fontSize, float spacing) const inline
Definition at line 171 of file Color.hpp.
{
        ::DrawTextPro(font, text.c_str(), position, origin, rotation, fontSize, spacing, *this);
    }
DrawText() [2/3]
void raylib::Color::DrawText (const ::Font & font, const std::string & text, ::Vector2 position, float fontSize, float spacing) const inline
Definition at line 166 of file Color.hpp.
{
        ::DrawTextEx(font, text.c_str(), position, fontSize, spacing, *this);
    }
DrawText() [3/3]
void raylib::Color::DrawText (const std::string & text, int posX = 0, int posY = 0, int fontSize = 10.0f) const inline
Definition at line 162 of file Color.hpp.
{
        ::DrawText(text.c_str(), posX, posY, fontSize, *this);
    }
References DrawText().
Fade()
Color raylib::Color::Fade (float alpha) const inline
Returns color with alpha applied, alpha goes from 0.0f to 1.0f
Definition at line 79 of file Color.hpp.
{
        return ::Fade(*this, alpha);
    }
FromHSV()
::Color raylib::Color::FromHSV (float hue, float saturation, float value) inline static
Returns a Color from HSV values
Definition at line 39 of file Color.hpp.
{
        return ::ColorFromHSV(hue, saturation, value);
    }
GetA()
unsigned char raylib::Color::GetA () const inline
Retrieves the a value for the object.
Returns
The a value of the object.
Definition at line 107 of file Color.hpp.
GetB()
unsigned char raylib::Color::GetB () const inline
Retrieves the b value for the object.
Returns
The b value of the object.
Definition at line 106 of file Color.hpp.
GetG()
unsigned char raylib::Color::GetG () const inline
Retrieves the g value for the object.
Returns
The g value of the object.
Definition at line 105 of file Color.hpp.
GetR()
unsigned char raylib::Color::GetR () const inline
Retrieves the r value for the object.
Returns
The r value of the object.
Definition at line 104 of file Color.hpp.
Gold()
static Color raylib::Color::Gold () inline static
Definition at line 245 of file Color.hpp.
{ return GOLD; }
References GOLD.
Gray()
static Color raylib::Color::Gray () inline static
Definition at line 242 of file Color.hpp.
{ return GRAY; }
References GRAY.
Green()
static Color raylib::Color::Green () inline static
Definition at line 250 of file Color.hpp.
{ return GREEN; }
References GREEN.
LightGray()
static Color raylib::Color::LightGray () inline static
Definition at line 241 of file Color.hpp.
{ return LIGHTGRAY; }
References LIGHTGRAY.
Lime()
static Color raylib::Color::Lime () inline static
Definition at line 251 of file Color.hpp.
{ return LIME; }
References LIME.
Magenta()
static Color raylib::Color::Magenta () inline static
Definition at line 265 of file Color.hpp.
{ return MAGENTA; }
References MAGENTA.
Maroon()
static Color raylib::Color::Maroon () inline static
Definition at line 249 of file Color.hpp.
{ return MAROON; }
References MAROON.
Normalize()
Vector4 raylib::Color::Normalize () const inline
Returns Color normalized as float [0..1]
Definition at line 86 of file Color.hpp.
{
        return ::ColorNormalize(*this);
    }
operator int()
raylib::Color::operator int () const inline
Returns hexadecimal value for a Color
Definition at line 64 of file Color.hpp.
{
        return ::ColorToInt(*this);
    }
operator std::string()
raylib::Color::operator std::string () const inline
Definition at line 72 of file Color.hpp.
{
        return ToString();
    }
References ToString().
operator=()
Color & raylib::Color::operator= (const ::Color & color) inline
Definition at line 109 of file Color.hpp.
{
        set(color);
        return *this;
    }
References set().
Orange()
static Color raylib::Color::Orange () inline static
Definition at line 246 of file Color.hpp.
{ return ORANGE; }
References ORANGE.
Pink()
static Color raylib::Color::Pink () inline static
Definition at line 247 of file Color.hpp.
{ return PINK; }
References PINK.
Purple()
static Color raylib::Color::Purple () inline static
Definition at line 256 of file Color.hpp.
{ return PURPLE; }
References PURPLE.
RayWhite()
static Color raylib::Color::RayWhite () inline static
Definition at line 266 of file Color.hpp.
{ return RAYWHITE; }
References RAYWHITE.
Red()
static Color raylib::Color::Red () inline static
Definition at line 248 of file Color.hpp.
{ return RED; }
References RED.
set()
void raylib::Color::set (const ::Color & color) inline protected
Definition at line 269 of file Color.hpp.
{
        r = color.r;
        g = color.g;
        b = color.b;
        a = color.a;
    }
References Color::a, Color::b, Color::g, and Color::r.
SetA()
void raylib::Color::SetA (unsigned char value) inline
Sets the a value for the object.
Parameters
value The value of which to set a to.
Definition at line 107 of file Color.hpp.
SetB()
void raylib::Color::SetB (unsigned char value) inline
Sets the b value for the object.
Parameters
value The value of which to set b to.
Definition at line 106 of file Color.hpp.
SetG()
void raylib::Color::SetG (unsigned char value) inline
Sets the g value for the object.
Parameters
value The value of which to set g to.
Definition at line 105 of file Color.hpp.
SetR()
void raylib::Color::SetR (unsigned char value) inline
Sets the r value for the object.
Parameters
value The value of which to set r to.
Definition at line 104 of file Color.hpp.
SkyBlue()
static Color raylib::Color::SkyBlue () inline static
Definition at line 253 of file Color.hpp.
{ return SKYBLUE; }
References SKYBLUE.
Tint()
Color raylib::Color::Tint (::Color tint) inline
Get color multiplied with another color
Definition at line 209 of file Color.hpp.
{
        return ::ColorTint(*this, tint);
    }
ToHSV()
Vector3 raylib::Color::ToHSV () const inline
Returns HSV values for a Color
Definition at line 100 of file Color.hpp.
{
        return ::ColorToHSV(*this);
    }
ToInt()
int raylib::Color::ToInt () const inline
Returns hexadecimal value for a Color
Definition at line 57 of file Color.hpp.
                      {
        return ::ColorToInt(*this);
    }
ToString()
std::string raylib::Color::ToString () const inline
Definition at line 68 of file Color.hpp.
{
        return TextFormat("Color(%d, %d, %d, %d)", r, g, b, a);
    }
References Color::a, Color::b, Color::g, Color::r, and TextFormat().
Violet()
static Color raylib::Color::Violet () inline static
Definition at line 257 of file Color.hpp.
{ return VIOLET; }
References VIOLET.
White()
static Color raylib::Color::White () inline static
Definition at line 262 of file Color.hpp.
{ return WHITE; }
References WHITE.
Yellow()
static Color raylib::Color::Yellow () inline static
Definition at line 244 of file Color.hpp.
{ return YELLOW; }
References YELLOW.
Member Data Documentation
a
unsigned char Color::a inherited
Definition at line 240 of file raylib.h.
b
unsigned char Color::b inherited
Definition at line 239 of file raylib.h.
g
unsigned char Color::g inherited
Definition at line 238 of file raylib.h.
r
unsigned char Color::r inherited
Definition at line 237 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Color.hpp