Techstorm-rivalry: raylib::Ray Class Reference
raylib::Ray Class Reference
#include <Ray.hpp>
Public Member Functions
Ray (const ::Ray &ray)
Ray (::Vector3 position={0.0f, 0.0f, 0.0f}, ::Vector3 direction={0.0f, 0.0f, 0.0f})
Ray (::Vector2 mousePosition, const ::Camera &camera)
Ray & operator= (const ::Ray &ray)
::Vector3 GetPosition () const
void SetPosition (::Vector3 value)
::Vector3 GetDirection () const
void SetDirection (::Vector3 value)
void Draw (::Color color) const
RayCollision GetCollision (::Vector3 center, float radius) const
RayCollision GetCollision (const ::BoundingBox &box) const
RayCollision GetCollision (const ::Mesh &mesh, const ::Matrix &transform) const
RayCollision GetCollision (::Vector3 p1, ::Vector3 p2, ::Vector3 p3) const
RayCollision GetCollision (::Vector3 p1, ::Vector3 p2, ::Vector3 p3, ::Vector3 p4) const
Static Public Member Functions
static Ray GetMouse (::Vector2 mousePosition, const ::Camera &camera)
static Ray GetMouse (const ::Camera &camera)
Public Attributes
Vector3 position
Vector3 direction
Protected Member Functions
void set (const ::Ray &ray)
Detailed Description
Ray type (useful for raycast)
Definition at line 12 of file Ray.hpp.
Constructor & Destructor Documentation
Ray() [1/3]
raylib::Ray::Ray (const ::Ray & ray) inline
Definition at line 14 of file Ray.hpp.
{
        set(ray);
    }
References ray, and set().
Ray() [2/3]
raylib::Ray::Ray (::Vector3 position = {0.0f, 0.0f, 0.0f}, ::Vector3 direction = {0.0f, 0.0f, 0.0f}) inline
Definition at line 18 of file Ray.hpp.
                           {0.0f, 0.0f, 0.0f}, ::Vector3 direction = {0.0f, 0.0f, 0.0f}) :
            ::Ray{position, direction} {
        // Nothing.
    }
Ray() [3/3]
raylib::Ray::Ray (::Vector2 mousePosition, const ::Camera & camera) inline
Definition at line 23 of file Ray.hpp.
{
        set(::GetMouseRay(mousePosition, camera));
    }
References GetMouseRay(), and set().
Member Function Documentation
Draw()
void raylib::Ray::Draw (::Color color) const inline
Draw a ray line
Definition at line 38 of file Ray.hpp.
{
        DrawRay(*this, color);
    }
References DrawRay().
GetCollision() [1/5]
RayCollision raylib::Ray::GetCollision (::Vector3 center, float radius) const inline
Get collision information between ray and sphere
Definition at line 45 of file Ray.hpp.
{
        return ::GetRayCollisionSphere(*this, center, radius);
    }
GetCollision() [2/5]
RayCollision raylib::Ray::GetCollision (::Vector3 p1, ::Vector3 p2, ::Vector3 p3) const inline
Get collision info between ray and triangle
Definition at line 66 of file Ray.hpp.
{
        return ::GetRayCollisionTriangle(*this, p1, p2, p3);
    }
GetCollision() [3/5]
RayCollision raylib::Ray::GetCollision (::Vector3 p1, ::Vector3 p2, ::Vector3 p3, ::Vector3 p4) const inline
Get collision info between ray and quad
Definition at line 73 of file Ray.hpp.
{
        return ::GetRayCollisionQuad(*this, p1, p2, p3, p4);
    }
GetCollision() [4/5]
RayCollision raylib::Ray::GetCollision (const ::BoundingBox & box) const inline
Detect collision between ray and box
Definition at line 52 of file Ray.hpp.
{
        return ::GetRayCollisionBox(*this, box);
    }
GetCollision() [5/5]
RayCollision raylib::Ray::GetCollision (const ::Mesh & mesh, const ::Matrix & transform) const inline
Get collision information between ray and mesh
Definition at line 59 of file Ray.hpp.
{
        return ::GetRayCollisionMesh(*this, mesh, transform);
    }
GetDirection()
::Vector3 raylib::Ray::GetDirection () const inline
Retrieves the direction value for the object.
Returns
The direction value of the object.
Definition at line 33 of file Ray.hpp.
GetMouse() [1/2]
static Ray raylib::Ray::GetMouse (::Vector2 mousePosition, const ::Camera & camera) inline static
Get a ray trace from mouse position
Definition at line 80 of file Ray.hpp.
{
        return ::GetMouseRay(mousePosition, camera);
    }
GetMouse() [2/2]
static Ray raylib::Ray::GetMouse (const ::Camera & camera) inline static
Get a ray trace from mouse position
Definition at line 87 of file Ray.hpp.
{
        return ::GetMouseRay(::GetMousePosition(), camera);
    }
References GetMousePosition().
GetPosition()
::Vector3 raylib::Ray::GetPosition () const inline
Retrieves the position value for the object.
Returns
The position value of the object.
Definition at line 32 of file Ray.hpp.
operator=()
Ray & raylib::Ray::operator= (const ::Ray & ray) inline
Definition at line 27 of file Ray.hpp.
{
        set(ray);
        return *this;
    }
References ray, and set().
set()
void raylib::Ray::set (const ::Ray & ray) inline protected
Definition at line 92 of file Ray.hpp.
{
        position = ray.position;
        direction = ray.direction;
    }
References Ray::direction, Ray::position, and ray.
SetDirection()
void raylib::Ray::SetDirection (::Vector3 value) inline
Sets the direction value for the object.
Parameters
value The value of which to set direction to.
Definition at line 33 of file Ray.hpp.
SetPosition()
void raylib::Ray::SetPosition (::Vector3 value) inline
Sets the position value for the object.
Parameters
value The value of which to set position to.
Definition at line 32 of file Ray.hpp.
Member Data Documentation
direction
Vector3 Ray::direction inherited
Definition at line 419 of file raylib.h.
position
Vector3 Ray::position inherited
Definition at line 418 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Ray.hpp