Techstorm-rivalry: raylib::Texture Class Reference
raylib::Texture Class Reference
#include <Texture.hpp>
Public Member Functions
Texture (const Texture &)=delete
Texture & operator= (const Texture &)=delete
Texture (Texture &&other)
~Texture ()
Texture & operator= (Texture &&other) noexcept
TextureUnmanaged ()
TextureUnmanaged (unsigned int id, int width, int height, int mipmaps=1, int format=PIXELFORMAT_UNCOMPRESSED_R8G8B8A8)
TextureUnmanaged (const ::Texture &texture)
TextureUnmanaged (const ::Image &image)
TextureUnmanaged (const ::Image &image, int layout)
TextureUnmanaged (const std::string &fileName)
TextureUnmanaged (::Texture &&other)
unsigned int GetId () const
void SetId (unsigned int value)
int GetWidth () const
void SetWidth (int value)
int GetHeight () const
void SetHeight (int value)
int GetMipmaps () const
void SetMipmaps (int value)
int GetFormat () const
void SetFormat (int value)
inline ::Vector2 GetSize () const
void Load (const ::Image &image)
void Load (const ::Image &image, int layoutType)
void Load (const std::string &fileName)
void Unload ()
TextureUnmanaged & Update (const void *pixels)
TextureUnmanaged & Update (::Rectangle rec, const void *pixels)
inline ::Image GetData () const
operator Image ()
TextureUnmanaged & GenMipmaps ()
TextureUnmanaged & SetFilter (int filterMode)
TextureUnmanaged & SetWrap (int wrapMode)
void Draw (int posX=0, int posY=0, ::Color tint={255, 255, 255, 255}) const
void Draw (::Vector2 position, ::Color tint={255, 255, 255, 255}) const
void Draw (::Vector2 position, float rotation, float scale=1.0f, ::Color tint={255, 255, 255, 255}) const
void Draw (::Rectangle sourceRec, ::Vector2 position={0, 0}, ::Color tint={255, 255, 255, 255}) const
void Draw (::Rectangle sourceRec, ::Rectangle destRec, ::Vector2 origin={0, 0}, float rotation=0, ::Color tint={255, 255, 255, 255}) const
void Draw (::NPatchInfo nPatchInfo, ::Rectangle destRec, ::Vector2 origin={0, 0}, float rotation=0, ::Color tint={255, 255, 255, 255}) const
void DrawBillboard (const ::Camera &camera, ::Vector3 position, float size, ::Color tint={255, 255, 255, 255}) const
void DrawBillboard (const ::Camera &camera, ::Rectangle source, ::Vector3 position, ::Vector2 size, ::Color tint={255, 255, 255, 255}) const
void DrawBillboard (const ::Camera &camera, ::Rectangle source, Vector3 position, ::Vector3 up, Vector2 size, Vector2 origin, float rotation=0.0f, ::Color tint={255, 255, 255, 255}) const
TextureUnmanaged & SetMaterial (::Material *material, int mapType=MATERIAL_MAP_NORMAL)
TextureUnmanaged & SetMaterial (const ::Material &material, int mapType=MATERIAL_MAP_NORMAL)
TextureUnmanaged & SetShapes (const ::Rectangle &source)
TextureUnmanaged & SetShaderValue (const ::Shader &shader, int locIndex)
bool IsReady () const
Public Attributes
unsigned int id
int width
int height
int mipmaps
int format
Protected Member Functions
void set (const ::Texture &texture)
Detailed Description
Texture type
The texture will be unloaded on object destruction. Use raylib::TextureUnmanaged if you're looking to not unload.
See also
raylib::TextureUnmanaged
Definition at line 14 of file Texture.hpp.
Constructor & Destructor Documentation
Texture() [1/2]
raylib::Texture::Texture (const Texture &) delete
Explicitly forbid the copy constructor.
Texture() [2/2]
raylib::Texture::Texture (Texture && other) inline
Move constructor.
Definition at line 31 of file Texture.hpp.
{
        set(other);
        other.id = 0;
        other.width = 0;
        other.height = 0;
        other.mipmaps = 0;
        other.format = 0;
    }
References raylib::TextureUnmanaged::set().
~Texture()
raylib::Texture::~Texture () inline
On destruction, unload the Texture.
Definition at line 44 of file Texture.hpp.
               {
        Unload();
    }
References raylib::TextureUnmanaged::Unload().
Member Function Documentation
Draw() [1/6]
void raylib::TextureUnmanaged::Draw (::NPatchInfo nPatchInfo, ::Rectangle destRec, ::Vector2 origin = {0, 0}, float rotation = 0, ::Color tint = {255, 255, 255, 255}) const inline inherited
Draws a texture (or part of it) that stretches or shrinks nicely
See also
DrawTextureNPatch()
Definition at line 249 of file TextureUnmanaged.hpp.
                                                                                {0, 0},
            float rotation = 0, ::Color tint = {255, 255, 255, 255}) const {
        ::DrawTextureNPatch(*this, nPatchInfo, destRec, origin, rotation, tint);
    }
Draw() [2/6]
void raylib::TextureUnmanaged::Draw (::Rectangle sourceRec, ::Rectangle destRec, ::Vector2 origin = {0, 0}, float rotation = 0, ::Color tint = {255, 255, 255, 255}) const inline inherited
Draw a part of a texture defined by a rectangle with 'pro' parameters
See also
DrawTexturePro()
Definition at line 239 of file TextureUnmanaged.hpp.
                                                                              {0, 0},
            float rotation = 0, ::Color tint = {255, 255, 255, 255}) const {
        ::DrawTexturePro(*this, sourceRec, destRec, origin, rotation, tint);
    }
Draw() [3/6]
void raylib::TextureUnmanaged::Draw (::Rectangle sourceRec, ::Vector2 position = {0, 0}, ::Color tint = {255, 255, 255, 255}) const inline inherited
Draw a part of a texture defined by a rectangle
See also
DrawTextureRec()
Definition at line 229 of file TextureUnmanaged.hpp.
                                                             {0, 0},
            ::Color tint = {255, 255, 255, 255}) const {
        ::DrawTextureRec(*this, sourceRec, position, tint);
    }
Draw() [4/6]
void raylib::TextureUnmanaged::Draw (::Vector2 position, ::Color tint = {255, 255, 255, 255}) const inline inherited
Draw a Texture2D with position defined as Vector2
See also
DrawTextureV()
Definition at line 210 of file TextureUnmanaged.hpp.
                                                    {255, 255, 255, 255}) const {
        ::DrawTextureV(*this, position, tint);
    }
Draw() [5/6]
void raylib::TextureUnmanaged::Draw (::Vector2 position, float rotation, float scale = 1.0f, ::Color tint = {255, 255, 255, 255}) const inline inherited
Draw a Texture2D with extended parameters
See also
DrawTextureEx()
Definition at line 219 of file TextureUnmanaged.hpp.
                         {255, 255, 255, 255}) const {
        ::DrawTextureEx(*this, position, rotation, scale, tint);
    }
Draw() [6/6]
void raylib::TextureUnmanaged::Draw (int posX = 0, int posY = 0, ::Color tint = {255, 255, 255, 255}) const inline inherited
Draw a Texture2D
See also
DrawTexture()
Definition at line 201 of file TextureUnmanaged.hpp.
                                                              {255, 255, 255, 255}) const {
        ::DrawTexture(*this, posX, posY, tint);
    }
DrawBillboard() [1/3]
void raylib::TextureUnmanaged::DrawBillboard (const ::Camera & camera, ::Rectangle source, ::Vector3 position, ::Vector2 size, ::Color tint = {255, 255, 255, 255}) const inline inherited
Draw a billboard texture defined by source
See also
DrawBillboardRec()
Definition at line 270 of file TextureUnmanaged.hpp.
                         {255, 255, 255, 255}) const {
        DrawBillboardRec(camera, *this, source, position, size, tint);
    }
DrawBillboard() [2/3]
void raylib::TextureUnmanaged::DrawBillboard (const ::Camera & camera, ::Rectangle source, Vector3 position, ::Vector3 up, Vector2 size, Vector2 origin, float rotation = 0.0f, ::Color tint = {255, 255, 255, 255}) const inline inherited
Draw a billboard texture defined by source and rotation
See also
DrawBillboardPro()
Definition at line 281 of file TextureUnmanaged.hpp.
                         {255, 255, 255, 255}) const {
        DrawBillboardPro(camera, *this, source, position, up, size, origin, rotation, tint);
    }
DrawBillboard() [3/3]
void raylib::TextureUnmanaged::DrawBillboard (const ::Camera & camera, ::Vector3 position, float size, ::Color tint = {255, 255, 255, 255}) const inline inherited
Draw a billboard texture
See also
DrawBillboard()
Definition at line 259 of file TextureUnmanaged.hpp.
                         {255, 255, 255, 255}) const {
        ::DrawBillboard(camera, *this, position, size, tint);
    }
GenMipmaps()
TextureUnmanaged & raylib::TextureUnmanaged::GenMipmaps () inline inherited
Generate GPU mipmaps for a texture
Definition at line 175 of file TextureUnmanaged.hpp.
{
        ::GenTextureMipmaps(this);
        return *this;
    }
References GenTextureMipmaps().
GetData()
inline ::Image raylib::TextureUnmanaged::GetData () const inline inherited
Get pixel data from GPU texture and return an Image
Definition at line 161 of file TextureUnmanaged.hpp.
{
        return ::LoadImageFromTexture(*this);
    }
GetFormat()
int raylib::TextureUnmanaged::GetFormat () const inline inherited
Retrieves the format value for the object.
Returns
The format value of the object.
Definition at line 87 of file TextureUnmanaged.hpp.
GetHeight()
int raylib::TextureUnmanaged::GetHeight () const inline inherited
Retrieves the height value for the object.
Returns
The height value of the object.
Definition at line 85 of file TextureUnmanaged.hpp.
GetId()
unsigned int raylib::TextureUnmanaged::GetId () const inline inherited
Retrieves the id value for the object.
Returns
The id value of the object.
Definition at line 83 of file TextureUnmanaged.hpp.
GetMipmaps()
int raylib::TextureUnmanaged::GetMipmaps () const inline inherited
Retrieves the mipmaps value for the object.
Returns
The mipmaps value of the object.
Definition at line 86 of file TextureUnmanaged.hpp.
GetSize()
inline ::Vector2 raylib::TextureUnmanaged::GetSize () const inline inherited
Retrieve the width and height of the texture.
Definition at line 97 of file TextureUnmanaged.hpp.
{
        return {static_cast<float>(width), static_cast<float>(height)};
    }
References Texture::height, and Texture::width.
GetWidth()
int raylib::TextureUnmanaged::GetWidth () const inline inherited
Retrieves the width value for the object.
Returns
The width value of the object.
Definition at line 84 of file TextureUnmanaged.hpp.
IsReady()
bool raylib::TextureUnmanaged::IsReady () const inline inherited
Determines whether or not the Texture has been loaded and is ready.
Returns
True or false depending on whether the Texture has data.
Definition at line 322 of file TextureUnmanaged.hpp.
{
        return id != 0;
    }
Load() [1/3]
void raylib::TextureUnmanaged::Load (const ::Image & image) inline inherited
Load texture from image data
Definition at line 104 of file TextureUnmanaged.hpp.
{
        set(::LoadTextureFromImage(image));
        if (!IsReady()) {
            throw RaylibException("Failed to load Texture from Image");
        }
    }
References raylib::TextureUnmanaged::IsReady(), LoadTextureFromImage(), and raylib::TextureUnmanaged::set().
Load() [2/3]
void raylib::TextureUnmanaged::Load (const ::Image & image, int layoutType) inline inherited
Load cubemap from image, multiple image cubemap layouts supported
Definition at line 114 of file TextureUnmanaged.hpp.
{
        set(::LoadTextureCubemap(image, layoutType));
        if (!IsReady()) {
            throw RaylibException("Failed to load Texture from Cubemap");
        }
    }
References raylib::TextureUnmanaged::IsReady(), LoadTextureCubemap(), and raylib::TextureUnmanaged::set().
Load() [3/3]
void raylib::TextureUnmanaged::Load (const std::string & fileName) inline inherited
Load texture from file into GPU memory (VRAM)
Definition at line 124 of file TextureUnmanaged.hpp.
{
        set(::LoadTexture(fileName.c_str()));
        if (!IsReady()) {
            throw RaylibException("Failed to load Texture from file: " + fileName);
        }
    }
References raylib::TextureUnmanaged::IsReady(), LoadTexture(), and raylib::TextureUnmanaged::set().
operator Image()
raylib::TextureUnmanaged::operator Image () inline inherited
Get pixel data from GPU texture and return an Image
Definition at line 168 of file TextureUnmanaged.hpp.
{
        return GetData();
    }
References raylib::TextureUnmanaged::GetData().
operator=() [1/2]
Texture & raylib::Texture::operator= (const Texture &) delete
Explicitly forbid copy assignment.
operator=() [2/2]
Texture & raylib::Texture::operator= (Texture && other) inline noexcept
Move assignment.
Definition at line 51 of file Texture.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.id = 0;
        other.width = 0;
        other.height = 0;
        other.mipmaps = 0;
        other.format = 0;
        return *this;
    }
References raylib::TextureUnmanaged::set(), and raylib::TextureUnmanaged::Unload().
set()
void raylib::TextureUnmanaged::set (const ::Texture & texture) inline protected inherited
Definition at line 327 of file TextureUnmanaged.hpp.
{
        id = texture.id;
        width = texture.width;
        height = texture.height;
        mipmaps = texture.mipmaps;
        format = texture.format;
    }
References Texture::format, Texture::height, Texture::mipmaps, and Texture::width.
SetFilter()
TextureUnmanaged & raylib::TextureUnmanaged::SetFilter (int filterMode) inline inherited
Set texture scaling filter mode
Definition at line 183 of file TextureUnmanaged.hpp.
{
        ::SetTextureFilter(*this, filterMode);
        return *this;
    }
References SetTextureFilter().
SetFormat()
void raylib::TextureUnmanaged::SetFormat (int value) inline inherited
Sets the format value for the object.
Parameters
value The value of which to set format to.
Definition at line 87 of file TextureUnmanaged.hpp.
SetHeight()
void raylib::TextureUnmanaged::SetHeight (int value) inline inherited
Sets the height value for the object.
Parameters
value The value of which to set height to.
Definition at line 85 of file TextureUnmanaged.hpp.
SetId()
void raylib::TextureUnmanaged::SetId (unsigned int value) inline inherited
Sets the id value for the object.
Parameters
value The value of which to set id to.
Definition at line 83 of file TextureUnmanaged.hpp.
SetMaterial() [1/2]
TextureUnmanaged & raylib::TextureUnmanaged::SetMaterial (::Material * material, int mapType = MATERIAL_MAP_NORMAL) inline inherited
Set texture for a material map type (MAP_DIFFUSE, MAP_SPECULAR...)
Definition at line 291 of file TextureUnmanaged.hpp.
{
        ::SetMaterialTexture(material, mapType, *this);
        return *this;
    }
References SetMaterialTexture().
SetMaterial() [2/2]
TextureUnmanaged & raylib::TextureUnmanaged::SetMaterial (const ::Material & material, int mapType = MATERIAL_MAP_NORMAL) inline inherited
Definition at line 296 of file TextureUnmanaged.hpp.
{
        ::SetMaterialTexture((::Material*)(&material), mapType, *this);
        return *this;
    }
References SetMaterialTexture().
SetMipmaps()
void raylib::TextureUnmanaged::SetMipmaps (int value) inline inherited
Sets the mipmaps value for the object.
Parameters
value The value of which to set mipmaps to.
Definition at line 86 of file TextureUnmanaged.hpp.
SetShaderValue()
TextureUnmanaged & raylib::TextureUnmanaged::SetShaderValue (const ::Shader & shader, int locIndex) inline inherited
Set shader uniform value for texture (sampler2d)
Definition at line 312 of file TextureUnmanaged.hpp.
{
        ::SetShaderValueTexture(shader, locIndex, *this);
        return *this;
    }
References SetShaderValueTexture().
SetShapes()
TextureUnmanaged & raylib::TextureUnmanaged::SetShapes (const ::Rectangle & source) inline inherited
Set texture and rectangle to be used on shapes drawing.
Definition at line 304 of file TextureUnmanaged.hpp.
{
        ::SetShapesTexture(*this, source);
        return *this;
    }
References SetShapesTexture().
SetWidth()
void raylib::TextureUnmanaged::SetWidth (int value) inline inherited
Sets the width value for the object.
Parameters
value The value of which to set width to.
Definition at line 84 of file TextureUnmanaged.hpp.
SetWrap()
TextureUnmanaged & raylib::TextureUnmanaged::SetWrap (int wrapMode) inline inherited
Set texture wrapping mode
Definition at line 191 of file TextureUnmanaged.hpp.
{
        ::SetTextureWrap(*this, wrapMode);
        return *this;
    }
References SetTextureWrap().
TextureUnmanaged() [1/7]
raylib::TextureUnmanaged::TextureUnmanaged () inline
Default texture constructor.
Definition at line 26 of file TextureUnmanaged.hpp.
                       : ::Texture{0, 0, 0, 0, 0} {
        // Nothing.
    }
TextureUnmanaged() [2/7]
raylib::TextureUnmanaged::TextureUnmanaged (::Texture && other) inline
Definition at line 78 of file TextureUnmanaged.hpp.
                                      :
            ::Texture{other.id, other.width, other.height, other.mipmaps, other.format} {
        // Nothing.
    }
TextureUnmanaged() [3/7]
raylib::TextureUnmanaged::TextureUnmanaged (const ::Image & image) inline
Creates a texture from the given Image.
Exceptions
raylib::RaylibException Throws if failed to create the texture from the given image.
Definition at line 54 of file TextureUnmanaged.hpp.
{
        Load(image);
    }
TextureUnmanaged() [4/7]
raylib::TextureUnmanaged::TextureUnmanaged (const ::Image & image, int layout) inline
Load cubemap from image, multiple image cubemap layouts supported.
Exceptions
raylib::RaylibException Throws if failed to create the texture from the given cubemap.
See also
LoadTextureCubemap()
Definition at line 65 of file TextureUnmanaged.hpp.
{
        Load(image, layout);
    }
TextureUnmanaged() [5/7]
raylib::TextureUnmanaged::TextureUnmanaged (const ::Texture & texture) inline
Creates a texture object based on the given Texture struct data.
Definition at line 44 of file TextureUnmanaged.hpp.
                                             :
            ::Texture{texture.id, texture.width, texture.height, texture.mipmaps, texture.format} {
        // Nothing.
    }
TextureUnmanaged() [6/7]
raylib::TextureUnmanaged::TextureUnmanaged (const std::string & fileName) inline
Load texture from file into GPU memory (VRAM)
Exceptions
raylib::RaylibException Throws if failed to create the texture from the given file.
Definition at line 74 of file TextureUnmanaged.hpp.
{
        Load(fileName);
    }
TextureUnmanaged() [7/7]
raylib::TextureUnmanaged::TextureUnmanaged (unsigned int id, int width, int height, int mipmaps = 1, int format = PIXELFORMAT_UNCOMPRESSED_R8G8B8A8) inline
Move/Create a texture structure manually.
Definition at line 33 of file TextureUnmanaged.hpp.
            : ::Texture{id, width, height, mipmaps, format} {
        // Nothing.
    }
Unload()
void raylib::TextureUnmanaged::Unload () inline inherited
Unload texture from GPU memory (VRAM)
Definition at line 134 of file TextureUnmanaged.hpp.
{
        // Protect against calling UnloadTexture() twice.
        if (id != 0) {
            ::UnloadTexture(*this);
            id = 0;
        }
    }
References UnloadTexture().
Update() [1/2]
TextureUnmanaged & raylib::TextureUnmanaged::Update (::Rectangle rec, const void * pixels) inline inherited
Update GPU texture rectangle with new data
Definition at line 153 of file TextureUnmanaged.hpp.
{
        UpdateTextureRec(*this, rec, pixels);
        return *this;
    }
References UpdateTextureRec().
Update() [2/2]
TextureUnmanaged & raylib::TextureUnmanaged::Update (const void * pixels) inline inherited
Update GPU texture with new data
Definition at line 145 of file TextureUnmanaged.hpp.
{
        ::UpdateTexture(*this, pixels);
        return *this;
    }
References UpdateTexture().
Member Data Documentation
format
int Texture::format inherited
Definition at line 266 of file raylib.h.
height
int Texture::height inherited
Definition at line 264 of file raylib.h.
id
unsigned int Texture::id inherited
Definition at line 262 of file raylib.h.
mipmaps
int Texture::mipmaps inherited
Definition at line 265 of file raylib.h.
width
int Texture::width inherited
Definition at line 263 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Texture.hpp