Techstorm-rivalry: Logman Class Reference
Logman Class Reference
#include <Logman.h>
Public Member Functions
Logman ()
~Logman ()
Static Public Member Functions
static void Store (const char *message)
static void Log (const char *message)
static void Error (const char *message)
static void Warn (const char *message)
static void CustomLog (int msgType, const char *text, va_list args=0)
Detailed Description
Definition at line 9 of file Logman.h.
Constructor & Destructor Documentation
Logman()
Logman::Logman () inline
Definition at line 11 of file Logman.h.
             {
        SetTraceLogCallback(this->CustomLog);
    }
References CustomLog(), and SetTraceLogCallback().
~Logman()
Logman::~Logman () inline
Definition at line 15 of file Logman.h.
              {
        delete this;
    }
Member Function Documentation
CustomLog()
static void Logman::CustomLog (int msgType, const char * text, va_list args = 0) inline static
Definition at line 38 of file Logman.h.
    {
        char timeStr[64] = { 0 };
        time_t now = time(NULL);
        struct tm* tm_info = localtime(&now);
        strftime(timeStr, sizeof(timeStr), "%Y-%m-%d %H:%M:%S", tm_info);
        printf("[%s] ", timeStr);
        switch (msgType)
        {
        case LOG_INFO:
            printf("[INFO] : ");
            break;
        case LOG_ERROR:
            printf("[ERROR]: ");
            break;
        case LOG_WARNING:
            printf("[WARN] : ");
            break;
        case LOG_DEBUG:
            printf("[DEBUG]: ");
            break;
        default:
            break;
        }
        vprintf(text, args);
        printf("\n");
    }
References LOG_DEBUG, LOG_ERROR, LOG_INFO, and LOG_WARNING.
Error()
static void Logman::Error (const char * message) inline static
Definition at line 28 of file Logman.h.
{
        CustomLog(LOG_ERROR, message, NULL);
    }
References CustomLog(), and LOG_ERROR.
Log()
static void Logman::Log (const char * message) inline static
Definition at line 24 of file Logman.h.
{
        CustomLog(LOG_INFO, message, NULL);
    }
References CustomLog(), and LOG_INFO.
Store()
static void Logman::Store (const char * message) inline static
Definition at line 20 of file Logman.h.
{
    }
Warn()
static void Logman::Warn (const char * message) inline static
Definition at line 32 of file Logman.h.
{
        CustomLog(LOG_WARNING, message, NULL);
    }
References CustomLog(), and LOG_WARNING.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Logman.h