Techstorm-rivalry: raylib::Mouse Class Reference
raylib::Mouse Class Reference
#include <Mouse.hpp>
Static Public Member Functions
static bool IsButtonPressed (int button)
static bool IsButtonDown (int button)
static bool IsButtonReleased (int button)
static bool IsButtonUp (int button)
static int GetX ()
static int GetY ()
static void SetX (int x)
static void SetY (int y)
static Vector2 GetPosition ()
static void SetPosition (int x, int y)
static void SetPosition (::Vector2 position)
static Vector2 GetDelta ()
static void SetOffset (int offsetX=0, int offsetY=0)
static void SetOffset (::Vector2 offset)
static void SetScale (float scaleX=1.0f, float scaleY=1.0f)
static void SetScale (::Vector2 scale)
static float GetWheelMove ()
static Vector2 GetWheelMoveV ()
static void SetCursor (int cursor=MOUSE_CURSOR_DEFAULT)
static int GetTouchX ()
static int GetTouchY ()
static Vector2 GetTouchPosition (int index)
static Ray GetRay (::Vector2 mousePosition, const ::Camera &camera)
static Ray GetRay (const ::Camera &camera)
Detailed Description
Input-related functions: mouse
Definition at line 11 of file Mouse.hpp.
Member Function Documentation
GetDelta()
static Vector2 raylib::Mouse::GetDelta () inline static
Get mouse delta between frames
Definition at line 69 of file Mouse.hpp.
{
        return ::GetMouseDelta();
    }
GetPosition()
static Vector2 raylib::Mouse::GetPosition () inline static
Definition at line 54 of file Mouse.hpp.
{
        return ::GetMousePosition();
    }
GetRay() [1/2]
static Ray raylib::Mouse::GetRay (::Vector2 mousePosition, const ::Camera & camera) inline static
Get a ray trace from mouse position
Definition at line 138 of file Mouse.hpp.
{
        return ::GetMouseRay(mousePosition, camera);
    }
GetRay() [2/2]
static Ray raylib::Mouse::GetRay (const ::Camera & camera) inline static
Get a ray trace from mouse position
Definition at line 145 of file Mouse.hpp.
{
        return ::GetMouseRay(::GetMousePosition(), camera);
    }
References GetMousePosition().
GetTouchPosition()
static Vector2 raylib::Mouse::GetTouchPosition (int index) inline static
Get touch position XY for a touch point index (relative to screen size)
Definition at line 131 of file Mouse.hpp.
{
        return ::GetTouchPosition(index);
    }
GetTouchX()
static int raylib::Mouse::GetTouchX () inline static
Get touch position X for touch point 0 (relative to screen size)
Definition at line 117 of file Mouse.hpp.
{
        return ::GetTouchX();
    }
GetTouchY()
static int raylib::Mouse::GetTouchY () inline static
Get touch position Y for touch point 0 (relative to screen size)
Definition at line 124 of file Mouse.hpp.
{
        return ::GetTouchY();
    }
GetWheelMove()
static float raylib::Mouse::GetWheelMove () inline static
Get mouse wheel movement for X or Y, whichever is larger
Definition at line 92 of file Mouse.hpp.
{
        return ::GetMouseWheelMove();
    }
GetWheelMoveV()
static Vector2 raylib::Mouse::GetWheelMoveV () inline static
Get mouse wheel movement for both X and Y
See also
GetMouseWheelMoveV()
Definition at line 101 of file Mouse.hpp.
{
        return GetMouseWheelMoveV();
    }
References GetMouseWheelMoveV().
GetX()
static int raylib::Mouse::GetX () inline static
Definition at line 38 of file Mouse.hpp.
{
        return ::GetMouseX();
    }
GetY()
static int raylib::Mouse::GetY () inline static
Definition at line 42 of file Mouse.hpp.
{
        return ::GetMouseY();
    }
IsButtonDown()
static bool raylib::Mouse::IsButtonDown (int button) inline static
Detect if a mouse button is being pressed
Definition at line 23 of file Mouse.hpp.
{
        return ::IsMouseButtonDown(button);
    }
IsButtonPressed()
static bool raylib::Mouse::IsButtonPressed (int button) inline static
Detect if a mouse button has been pressed once
Definition at line 16 of file Mouse.hpp.
{
        return ::IsMouseButtonPressed(button);
    }
IsButtonReleased()
static bool raylib::Mouse::IsButtonReleased (int button) inline static
Detect if a mouse button has been released once
Definition at line 30 of file Mouse.hpp.
{
        return ::IsMouseButtonReleased(button);
    }
IsButtonUp()
static bool raylib::Mouse::IsButtonUp (int button) inline static
Definition at line 34 of file Mouse.hpp.
{
        return ::IsMouseButtonUp(button);
    }
SetCursor()
static void raylib::Mouse::SetCursor (int cursor = MOUSE_CURSOR_DEFAULT) inline static
Sets the current mouse cursor icon.
See also
MouseCursor
Definition at line 110 of file Mouse.hpp.
{
        ::SetMouseCursor(cursor);
    }
References SetMouseCursor().
SetOffset() [1/2]
static void raylib::Mouse::SetOffset (::Vector2 offset) inline static
Definition at line 77 of file Mouse.hpp.
{
        ::SetMouseOffset(static_cast<int>(offset.x), static_cast<int>(offset.y));
    }
References offset, and SetMouseOffset().
SetOffset() [2/2]
static void raylib::Mouse::SetOffset (int offsetX = 0, int offsetY = 0) inline static
Definition at line 73 of file Mouse.hpp.
{
        ::SetMouseOffset(offsetX, offsetY);
    }
References SetMouseOffset().
SetPosition() [1/2]
static void raylib::Mouse::SetPosition (::Vector2 position) inline static
Definition at line 62 of file Mouse.hpp.
{
        ::SetMousePosition(static_cast<int>(position.x), static_cast<int>(position.y));
    }
References SetMousePosition(), Vector2::x, and Vector2::y.
SetPosition() [2/2]
static void raylib::Mouse::SetPosition (int x, int y) inline static
Definition at line 58 of file Mouse.hpp.
{
        ::SetMousePosition(x, y);
    }
References SetMousePosition().
SetScale() [1/2]
static void raylib::Mouse::SetScale (::Vector2 scale) inline static
Definition at line 85 of file Mouse.hpp.
{
        ::SetMouseScale(scale.x, scale.y);
    }
References SetMouseScale(), Vector2::x, and Vector2::y.
SetScale() [2/2]
static void raylib::Mouse::SetScale (float scaleX = 1.0f, float scaleY = 1.0f) inline static
Definition at line 81 of file Mouse.hpp.
{
        ::SetMouseScale(scaleX, scaleY);
    }
References SetMouseScale().
SetX()
static void raylib::Mouse::SetX (int x) inline static
Definition at line 46 of file Mouse.hpp.
{
        ::SetMousePosition(x, GetY());
    }
References GetY(), and SetMousePosition().
SetY()
static void raylib::Mouse::SetY (int y) inline static
Definition at line 50 of file Mouse.hpp.
{
        ::SetMousePosition(GetX(), y);
    }
References GetX(), and SetMousePosition().
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Mouse.hpp