Techstorm-rivalry: toml::v3::path Class Reference
toml::v3::path Class Reference
#include <toml.h>
Public Types
using iterator = std::vector<path_component>::iterator
using const_iterator = std::vector<path_component>::const_iterator
Public Member Functions
path () noexcept=default
path (std::string_view)
~path () noexcept=default
path (const path &)=default
path (path &&) noexcept=default
size_t size () const noexcept
operator bool () const noexcept
bool empty () const noexcept
path_component & operator[] (size_t index) noexcept
const path_component & operator[] (size_t index) const noexcept
path & operator= (const path &)=default
path & operator= (path &&) noexcept=default
path & operator= (std::string_view)
path & assign (const path &p)
path & assign (path &&p) noexcept
path & assign (std::string_view str)
path & operator+= (const path &)
path & operator+= (path &&)
path & operator+= (std::string_view)
path & append (const path &p)
path & append (path &&p)
path & append (std::string_view str)
path & prepend (const path &)
path & prepend (path &&)
path & prepend (std::string_view)
std::string str () const
operator std::string () const
iterator begin () noexcept
iterator end () noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
path & truncate (size_t n)
path truncated (size_t n) const
path parent () const
path leaf (size_t n=1) const
path subpath (const_iterator start, const_iterator end) const
path subpath (size_t start, size_t length) const
Friends
path operator+ (const path &lhs, const path &rhs)
path operator+ (const path &lhs, std::string_view rhs)
path operator+ (std::string_view lhs, const path &rhs)
std::ostream & operator<< (std::ostream &os, const path &rhs)
bool operator== (const path &lhs, const path &rhs) noexcept
bool operator!= (const path &lhs, const path &rhs) noexcept
bool operator== (const path &lhs, std::string_view rhs)
bool operator== (std::string_view lhs, const path &rhs)
bool operator!= (const path &lhs, std::string_view rhs)
bool operator!= (std::string_view lhs, const path &rhs)
Detailed Description
Definition at line 2952 of file toml.h.
Member Typedef Documentation
const_iterator
using toml::v3::path::const_iterator = std::vector<path_component>::const_iterator
Definition at line 3275 of file toml.h.
iterator
using toml::v3::path::iterator = std::vector<path_component>::iterator
Definition at line 3273 of file toml.h.
Constructor & Destructor Documentation
path() [1/4]
toml::v3::path::path () default noexcept
path() [2/4]
toml::v3::path::path (std::string_view str) inline explicit
Definition at line 10972 of file toml.h.
    {
        TOML_ANON_NAMESPACE::parse_path_into(str, components_);
    }
References str().
~path()
toml::v3::path::~path () default noexcept
path() [3/4]
toml::v3::path::path (const path &) default
path() [4/4]
toml::v3::path::path (path &&) default noexcept
Member Function Documentation
append() [1/3]
path & toml::v3::path::append (const path & p) inline
Definition at line 3081 of file toml.h.
        {
            return *this += p;
        }
append() [2/3]
path & toml::v3::path::append (path && p) inline
Definition at line 3087 of file toml.h.
        {
            return *this += std::move(p);
        }
append() [3/3]
path & toml::v3::path::append (std::string_view str) inline
Definition at line 3093 of file toml.h.
        {
            return *this += str;
        }
assign() [1/3]
path & toml::v3::path::assign (const path & p) inline
Definition at line 3037 of file toml.h.
        {
            return *this = p;
        }
assign() [2/3]
path & toml::v3::path::assign (path && p) inline noexcept
Definition at line 3043 of file toml.h.
        {
            return *this = std::move(p);
        }
assign() [3/3]
path & toml::v3::path::assign (std::string_view str) inline
Definition at line 3049 of file toml.h.
        {
            return *this = str;
        }
begin() [1/2]
const_iterator toml::v3::path::begin () const inline noexcept
Definition at line 3290 of file toml.h.
        {
            return components_.begin();
        }
begin() [2/2]
iterator toml::v3::path::begin () inline noexcept
Definition at line 3278 of file toml.h.
        {
            return components_.begin();
        }
cbegin()
const_iterator toml::v3::path::cbegin () const inline noexcept
Definition at line 3302 of file toml.h.
        {
            return components_.begin();
        }
cend()
const_iterator toml::v3::path::cend () const inline noexcept
Definition at line 3308 of file toml.h.
        {
            return components_.end();
        }
clear()
void toml::v3::path::clear () inline noexcept
Definition at line 11091 of file toml.h.
    {
        components_.clear();
    }
empty()
bool toml::v3::path::empty () const inline noexcept
Definition at line 3003 of file toml.h.
        {
            return components_.empty();
        }
end() [1/2]
const_iterator toml::v3::path::end () const inline noexcept
Definition at line 3296 of file toml.h.
        {
            return components_.end();
        }
end() [2/2]
iterator toml::v3::path::end () inline noexcept
Definition at line 3284 of file toml.h.
        {
            return components_.end();
        }
leaf()
path toml::v3::path::leaf (size_t n = 1) const inline
Definition at line 11131 of file toml.h.
    {
        path leaf_path{};
        n = n > components_.size() ? components_.size() : n;
        if (n > 0)
        {
            leaf_path.components_.insert(leaf_path.components_.begin(),
                                         components_.end() - static_cast<int>(n),
                                         components_.end());
        }
        return leaf_path;
    }
operator bool()
toml::v3::path::operator bool () const inline explicit noexcept
Definition at line 2997 of file toml.h.
        {
            return !components_.empty();
        }
operator std::string()
toml::v3::path::operator std::string () const inline explicit
Definition at line 3181 of file toml.h.
        {
            return str();
        }
operator+=() [1/3]
path & toml::v3::path::operator+= (const path & rhs) inline
Definition at line 11005 of file toml.h.
    {
        components_.insert(components_.cend(), rhs.begin(), rhs.end());
        return *this;
    }
References begin(), and end().
operator+=() [2/3]
path & toml::v3::path::operator+= (path && rhs) inline
Definition at line 11012 of file toml.h.
    {
        components_.insert(components_.end(),
                           std::make_move_iterator(rhs.components_.begin()),
                           std::make_move_iterator(rhs.components_.end()));
        return *this;
    }
operator+=() [3/3]
path & toml::v3::path::operator+= (std::string_view str) inline
Definition at line 11021 of file toml.h.
    {
        TOML_ANON_NAMESPACE::parse_path_into(str, components_);
        return *this;
    }
References str().
operator=() [1/3]
path & toml::v3::path::operator= (const path &) default
operator=() [2/3]
path & toml::v3::path::operator= (path &&) default noexcept
operator=() [3/3]
path & toml::v3::path::operator= (std::string_view rhs) inline
Definition at line 10987 of file toml.h.
    {
        components_.clear();
        TOML_ANON_NAMESPACE::parse_path_into(rhs, components_);
        return *this;
    }
operator[]() [1/2]
const path_component & toml::v3::path::operator[] (size_t index) const inline noexcept
Definition at line 3016 of file toml.h.
        {
            TOML_ASSERT(index < size());
            return components_[index];
        }
References TOML_ASSERT.
operator[]() [2/2]
path_component & toml::v3::path::operator[] (size_t index) inline noexcept
Definition at line 3009 of file toml.h.
        {
            TOML_ASSERT(index < size());
            return components_[index];
        }
References TOML_ASSERT.
parent()
path toml::v3::path::parent () const inline
Definition at line 11125 of file toml.h.
    {
        return truncated(1);
    }
References truncated().
prepend() [1/3]
path & toml::v3::path::prepend (const path & source) inline
Definition at line 11038 of file toml.h.
    {
        components_.insert(components_.begin(), source.components_.begin(), source.components_.end());
        return *this;
    }
prepend() [2/3]
path & toml::v3::path::prepend (path && source) inline
Definition at line 11045 of file toml.h.
    {
        components_.insert(components_.begin(),
                           std::make_move_iterator(source.components_.begin()),
                           std::make_move_iterator(source.components_.end()));
        return *this;
    }
prepend() [3/3]
path & toml::v3::path::prepend (std::string_view source) inline
Definition at line 11054 of file toml.h.
    {
        return prepend(path{ source });
    }
References prepend().
size()
size_t toml::v3::path::size () const inline noexcept
Definition at line 2991 of file toml.h.
        {
            return components_.size();
        }
str()
std::string toml::v3::path::str () const inline
Definition at line 11070 of file toml.h.
    {
        if (empty())
            return "";
        std::ostringstream ss;
        print_to(ss);
        return std::move(ss).str();
    }
References empty().
subpath() [1/2]
path toml::v3::path::subpath (const_iterator start, const_iterator end) const
References TOML_ALWAYS_INLINE, and TOML_NODISCARD.
subpath() [2/2]
path toml::v3::path::subpath (size_t start, size_t length) const inline
Definition at line 11160 of file toml.h.
    {
        return subpath(begin() + static_cast<int>(start), begin() + static_cast<int>(start + length));
    }
References begin(), and subpath().
truncate()
path & toml::v3::path::truncate (size_t n) inline
Definition at line 11097 of file toml.h.
    {
        n = n > components_.size() ? components_.size() : n;
        auto it_end = components_.end();
        components_.erase(it_end - static_cast<int>(n), it_end);
        return *this;
    }
truncated()
path toml::v3::path::truncated (size_t n) const inline
Definition at line 11108 of file toml.h.
    {
        path truncated_path{};
        n = n > components_.size() ? components_.size() : n;
        // Copy all components except one
        // Need at least two path components to have a parent, since if there is
        // only one path component, the parent is the root/null path ""
        truncated_path.components_.insert(truncated_path.components_.begin(),
                                          components_.begin(),
                                          components_.end() - static_cast<int>(n));
        return truncated_path;
    }
Friends And Related Symbol Documentation
operator!= [1/3]
bool operator!= (const path & lhs, const path & rhs) friend
Definition at line 3208 of file toml.h.
        {
            return !equal(lhs, rhs);
        }
operator!= [2/3]
bool operator!= (const path & lhs, std::string_view rhs) friend
Definition at line 3229 of file toml.h.
        {
            return lhs != path{ rhs };
        }
operator!= [3/3]
bool operator!= (std::string_view lhs, const path & rhs) friend
Definition at line 3236 of file toml.h.
        {
            return rhs != lhs;
        }
operator+ [1/3]
path operator+ (const path & lhs, const path & rhs) friend
Definition at line 3125 of file toml.h.
        {
            path result = lhs;
            result += rhs;
            return result;
        }
operator+ [2/3]
path operator+ (const path & lhs, std::string_view rhs) friend
Definition at line 3133 of file toml.h.
        {
            path result = lhs;
            result += rhs;
            return result;
        }
operator+ [3/3]
path operator+ (std::string_view lhs, const path & rhs) friend
Definition at line 3141 of file toml.h.
        {
            path result = rhs;
            result.prepend(lhs);
            return result;
        }
operator<<
std::ostream & operator<< (std::ostream & os, const path & rhs) friend
Definition at line 3169 of file toml.h.
        {
            rhs.print_to(os);
            return os;
        }
operator== [1/3]
bool operator== (const path & lhs, const path & rhs) friend
Definition at line 3202 of file toml.h.
        {
            return equal(lhs, rhs);
        }
operator== [2/3]
bool operator== (const path & lhs, std::string_view rhs) friend
Definition at line 3215 of file toml.h.
        {
            return lhs == path{ rhs };
        }
operator== [3/3]
bool operator== (std::string_view lhs, const path & rhs) friend
Definition at line 3222 of file toml.h.
        {
            return rhs == lhs;
        }
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/toml.h