Techstorm-rivalry: raylib::ModelAnimation Class Reference
raylib::ModelAnimation Class Reference
#include <ModelAnimation.hpp>
Public Member Functions
ModelAnimation (const ::ModelAnimation &model)
ModelAnimation (const ModelAnimation &)=delete
ModelAnimation (ModelAnimation &&other)
~ModelAnimation ()
int GetBoneCount () const
void SetBoneCount (int value)
::BoneInfo * GetBones () const
void SetBones (::BoneInfo *value)
int GetFrameCount () const
void SetFrameCount (int value)
::Transform ** GetFramePoses () const
void SetFramePoses (::Transform **value)
ModelAnimation & operator= (const ::ModelAnimation &model)
ModelAnimation & operator= (const ModelAnimation &)=delete
ModelAnimation & operator= (ModelAnimation &&other) noexcept
void Unload ()
ModelAnimation & Update (const ::Model &model, int frame)
bool IsValid (const ::Model &model) const
Static Public Member Functions
static std::vector< ModelAnimation > Load (const std::string &fileName)
Public Attributes
int boneCount
int frameCount
BoneInfo * bones
Transform ** framePoses
char name [32]
Protected Member Functions
void set (const ::ModelAnimation &model)
Detailed Description
Model animation
Definition at line 15 of file ModelAnimation.hpp.
Constructor & Destructor Documentation
ModelAnimation() [1/3]
raylib::ModelAnimation::ModelAnimation (const ::ModelAnimation & model) inline
Definition at line 17 of file ModelAnimation.hpp.
{
        set(model);
    }
References set().
ModelAnimation() [2/3]
raylib::ModelAnimation::ModelAnimation (const ModelAnimation &) delete
ModelAnimation() [3/3]
raylib::ModelAnimation::ModelAnimation (ModelAnimation && other) inline
Definition at line 23 of file ModelAnimation.hpp.
{
        set(other);
        other.boneCount = 0;
        other.frameCount = 0;
        other.bones = nullptr;
        other.framePoses = nullptr;
    }
References set().
~ModelAnimation()
raylib::ModelAnimation::~ModelAnimation () inline
Definition at line 32 of file ModelAnimation.hpp.
                      {
        Unload();
    }
References Unload().
Member Function Documentation
GetBoneCount()
int raylib::ModelAnimation::GetBoneCount () const inline
Retrieves the boneCount value for the object.
Returns
The boneCount value of the object.
Definition at line 49 of file ModelAnimation.hpp.
GetBones()
::BoneInfo * raylib::ModelAnimation::GetBones () const inline
Retrieves the bones value for the object.
Returns
The bones value of the object.
Definition at line 50 of file ModelAnimation.hpp.
GetFrameCount()
int raylib::ModelAnimation::GetFrameCount () const inline
Retrieves the frameCount value for the object.
Returns
The frameCount value of the object.
Definition at line 51 of file ModelAnimation.hpp.
GetFramePoses()
::Transform ** raylib::ModelAnimation::GetFramePoses () const inline
Retrieves the framePoses value for the object.
Returns
The framePoses value of the object.
Definition at line 52 of file ModelAnimation.hpp.
IsValid()
bool raylib::ModelAnimation::IsValid (const ::Model & model) const inline
Check model animation skeleton match
Definition at line 95 of file ModelAnimation.hpp.
{
        return ::IsModelAnimationValid(model, *this);
    }
Load()
static std::vector< ModelAnimation > raylib::ModelAnimation::Load (const std::string & fileName) inline static
Load model animations from file
Definition at line 39 of file ModelAnimation.hpp.
{
        int count = 0;
        ::ModelAnimation* modelAnimations = ::LoadModelAnimations(fileName.c_str(), &count);
        std::vector<ModelAnimation> mats(modelAnimations, modelAnimations + count);
        RL_FREE(modelAnimations);
        return mats;
    }
References LoadModelAnimations(), and RL_FREE.
operator=() [1/3]
ModelAnimation & raylib::ModelAnimation::operator= (const ::ModelAnimation & model) inline
Definition at line 54 of file ModelAnimation.hpp.
{
        set(model);
        return *this;
    }
References set().
operator=() [2/3]
ModelAnimation & raylib::ModelAnimation::operator= (const ModelAnimation &) delete
operator=() [3/3]
ModelAnimation & raylib::ModelAnimation::operator= (ModelAnimation && other) inline noexcept
Definition at line 61 of file ModelAnimation.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.boneCount = 0;
        other.frameCount = 0;
        other.bones = nullptr;
        other.framePoses = nullptr;
        return *this;
    }
References set(), and Unload().
set()
void raylib::ModelAnimation::set (const ::ModelAnimation & model) inline protected
Definition at line 100 of file ModelAnimation.hpp.
{
        boneCount = model.boneCount;
        frameCount = model.frameCount;
        bones = model.bones;
        framePoses = model.framePoses;
    }
References ModelAnimation::boneCount, ModelAnimation::bones, ModelAnimation::frameCount, and ModelAnimation::framePoses.
SetBoneCount()
void raylib::ModelAnimation::SetBoneCount (int value) inline
Sets the boneCount value for the object.
Parameters
value The value of which to set boneCount to.
Definition at line 49 of file ModelAnimation.hpp.
SetBones()
void raylib::ModelAnimation::SetBones (::BoneInfo * value) inline
Sets the bones value for the object.
Parameters
value The value of which to set bones to.
Definition at line 50 of file ModelAnimation.hpp.
SetFrameCount()
void raylib::ModelAnimation::SetFrameCount (int value) inline
Sets the frameCount value for the object.
Parameters
value The value of which to set frameCount to.
Definition at line 51 of file ModelAnimation.hpp.
SetFramePoses()
void raylib::ModelAnimation::SetFramePoses (::Transform ** value) inline
Sets the framePoses value for the object.
Parameters
value The value of which to set framePoses to.
Definition at line 52 of file ModelAnimation.hpp.
Unload()
void raylib::ModelAnimation::Unload () inline
Unload animation data
Definition at line 80 of file ModelAnimation.hpp.
{
        ::UnloadModelAnimation(*this);
    }
References UnloadModelAnimation().
Update()
ModelAnimation & raylib::ModelAnimation::Update (const ::Model & model, int frame) inline
Update model animation pose
Definition at line 87 of file ModelAnimation.hpp.
{
        ::UpdateModelAnimation(model, *this, frame);
        return *this;
    }
References UpdateModelAnimation().
Member Data Documentation
boneCount
int ModelAnimation::boneCount inherited
Definition at line 409 of file raylib.h.
bones
BoneInfo* ModelAnimation::bones inherited
Definition at line 411 of file raylib.h.
frameCount
int ModelAnimation::frameCount inherited
Definition at line 410 of file raylib.h.
framePoses
Transform** ModelAnimation::framePoses inherited
Definition at line 412 of file raylib.h.
name
char ModelAnimation::name[32] inherited
Definition at line 413 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/ModelAnimation.hpp