Techstorm-rivalry: Player Class Reference
Player Class Reference
#include <Player.h>
Public Member Functions
Player (Vector3 StartingPos, int MaxHP, const Model model, int CameraMode)
void onDestroy () const override
void onUpdate () override
void Draw () override
void Drive ()
virtual ~Player ()
Public Attributes
Model model
int cameraMode
bool doDraw = true
PlayerController * controller = new PlayerController(KEY_W, KEY_S, KEY_A, KEY_D, KEY_SPACE, KEY_C, cameraMode)
bool isRunning
PlayerHealthComp * healthComp
Static Public Attributes
static CameraComp * cameraComponent
Detailed Description
Definition at line 228 of file Player.h.
Constructor & Destructor Documentation
Player()
Player::Player (Vector3 StartingPos, int MaxHP, const Model model, int CameraMode) inline
Definition at line 233 of file Player.h.
        : position(StartingPos),
        maxHP(MaxHP),
        model(model),
        cameraMode(CameraMode)
    {
        cameraComponent = new CameraComp(CameraData{
               {0.0f, 0.0f, 4.0f},
               {0.0f, 2.0f, 0.0f},
               {0.0f, 2.0f, 0.0f},
               45.0f,
               CAMERA_PERSPECTIVE });
        healthComp = new PlayerHealthComp(maxHP);
    };
References CAMERA_PERSPECTIVE, cameraComponent, and healthComp.
~Player()
virtual Player::~Player () inline virtual
Definition at line 305 of file Player.h.
    {
        delete cameraComponent;
        delete controller;
        delete this;
    }
References cameraComponent, and controller.
Member Function Documentation
Draw()
void Player::Draw () inline override virtual
Reimplemented from GameObject.
Definition at line 296 of file Player.h.
    {
    }
Drive()
void Player::Drive () inline
Definition at line 300 of file Player.h.
                 {
        CameraMoveForward(cameraComponent->GetSelfCameraPointer(), 0.01f, false);
    }
References cameraComponent, and CameraMoveForward().
onDestroy()
void Player::onDestroy () const inline override virtual
Implements GameObject.
Definition at line 250 of file Player.h.
    {
        delete this;
    };
onUpdate()
void Player::onUpdate () inline override virtual
Reimplemented from GameObject.
Definition at line 255 of file Player.h.
    {
        if (cameraMode != CAMERA_FIRST_PERSON) {
            if (this->doDraw) {
                DrawModel(model, this->cameraComponent->GetPosition(), 0.2f, GREEN);
            }
        }
        if (controller->canMove) {
            controller->Update(cameraComponent->GetSelfCameraPointer());
        }
        if (IsKeyDown(KEY_F)) {
            startDriving = true;
        }
        if (IsKeyDown(KEY_V)) {
            startDriving = false;
        }
        if (!IsKeyDown(KEY_LEFT_SHIFT)) {
            controller->isRunning = false;
            controller->SetSpeed(0.03f); //m/s
        }
        else {
            controller->isRunning = true;
            controller->SetSpeed(1.3f); //m/s
        }
        // View Sway
        if (startDriving) {
            Drive();
        }
    };
References CAMERA_FIRST_PERSON, cameraComponent, cameraMode, PlayerController::canMove, controller, doDraw, DrawModel(), Drive(), GREEN, IsKeyDown(), PlayerController::isRunning, KEY_F, KEY_LEFT_SHIFT, KEY_V, model, PlayerController::SetSpeed(), and PlayerController::Update().
Member Data Documentation
cameraComponent
CameraComp* Player::cameraComponent inline static
Definition at line 318 of file Player.h.
cameraMode
int Player::cameraMode
Definition at line 314 of file Player.h.
controller
PlayerController* Player::controller = new PlayerController(KEY_W, KEY_S, KEY_A, KEY_D, KEY_SPACE, KEY_C, cameraMode)
Definition at line 320 of file Player.h.
doDraw
bool Player::doDraw = true
Definition at line 316 of file Player.h.
healthComp
PlayerHealthComp* Player::healthComp
Definition at line 324 of file Player.h.
isRunning
bool Player::isRunning
Definition at line 323 of file Player.h.
model
Model Player::model
Definition at line 313 of file Player.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Player.h