Techstorm-rivalry: Game Class Reference
Game Class Reference
#include <Game.h>
Classes
class Renderer
Public Member Functions
Game ()
~Game ()
toml::v3::parse_result GetGameConfig ()
void StartGame ()
void EndGame ()
Public Attributes
int windowWidth
int windowHeight
bool isFullscreen = false
bool enableMusic
ConfigMan * configman = new ConfigMan()
Static Public Attributes
static Renderer * renderer
Detailed Description
Definition at line 6 of file Game.h.
Constructor & Destructor Documentation
Game()
Game::Game () inline
Definition at line 112 of file Game.h.
{}
~Game()
Game::~Game () inline
Definition at line 115 of file Game.h.
    {
        delete this;
    }
Member Function Documentation
EndGame()
void Game::EndGame () inline
Definition at line 214 of file Game.h.
    {
        rlglClose();
        CloseWindow(); // Close window and OpenGL context
        CloseAudioDevice();
        delete configman;
        delete this;
    }
References CloseAudioDevice(), CloseWindow(), configman, and rlglClose().
GetGameConfig()
toml::v3::parse_result Game::GetGameConfig () inline
Definition at line 120 of file Game.h.
    {
        return this->optionsConfig;
    }
StartGame()
void Game::StartGame () inline
Definition at line 125 of file Game.h.
    {
        SetTraceLogCallback(Logman::CustomLog);
        SetTargetFPS(60);
        // Read config to decide what to set for the game
        Logman::CustomLog(LOG_INFO, "Initiating Config Manager", NULL);
        optionsConfig = toml::parse_file("Config/options.toml");
        Logman::CustomLog(LOG_INFO, "OptionsConfig file registered", NULL);
        isFullscreen = optionsConfig["Window"]["isFullScreen"].as_boolean();
        Logman::CustomLog(LOG_INFO, TextFormat("IsFullscreen = %i", isFullscreen), NULL);
        enableMusic = optionsConfig["Sound"]["enableMusic"].as_boolean();
        Logman::CustomLog(LOG_INFO, TextFormat("EnableMusic = %i", enableMusic), NULL);
        if (isFullscreen == false)
        {
            windowWidth = ConfigTypeConverter::StrToInt(&optionsConfig["Window"]["windowWidth"].as_string()->operator std::string & ());
            Logman::CustomLog(LOG_INFO, TextFormat("Setting window width to %i", windowWidth), NULL);
            windowHeight = ConfigTypeConverter::StrToInt(&optionsConfig["Window"]["windowHeight"].as_string()->operator std::string & ());
            Logman::CustomLog(LOG_INFO, TextFormat("Setting window height to %i", windowHeight), NULL);
        }
        else
        {
            ToggleFullscreen();
            windowWidth = GetMonitorWidth(0);
            windowHeight = GetMonitorHeight(0);
            // windowfactory->StampFlag(FLAG_WINDOW_MAXIMIZED);
        }
        if (windowHeight == 0 || windowWidth == 0)
        {
            Logman::CustomLog(LOG_ERROR, "WINDOW WIDTH/HEIGHT CANT BE 0! Setting to config data.", NULL);
            if (isFullscreen) {
                windowWidth = GetMonitorWidth(0);
                windowHeight = GetMonitorHeight(0);
            }
            else {
                windowWidth = ConfigTypeConverter::StrToInt(&optionsConfig["Window"]["windowWidth"].as_string()->operator std::string & ());
                Logman::CustomLog(LOG_INFO, TextFormat("Setting window width to %i", windowWidth), NULL);
                windowHeight = ConfigTypeConverter::StrToInt(&optionsConfig["Window"]["windowHeight"].as_string()->operator std::string & ());
                Logman::CustomLog(LOG_INFO, TextFormat("Setting window height to %i", windowHeight), NULL);
            }
        }
        // Stamp window config flags & Manufacture
        Logman::CustomLog(LOG_INFO, "Starting Game", NULL);
        if (isFullscreen == true) {
            SetConfigFlags(FLAG_WINDOW_MAXIMIZED || FLAG_MSAA_4X_HINT);
        }
        else {
            SetConfigFlags(FLAG_MSAA_4X_HINT);
        }
        InitWindow(windowWidth, windowHeight, "TechStorm-Rivalry");
        InitAudioDevice(); // starts the audio driver(s).
        DisableEventWaiting();
        SetExitKey(KEY_BACKSPACE); // In event of your fuck up press this.
        // Setting the window icon in task bar
        Image icon = LoadImage("resources/images/icon.png");
        ImageFormat(&icon, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8);
        SetWindowIcon(icon);
        renderer = new Renderer();
        renderer->CreateRenderTexture(windowWidth, windowHeight);
        renderer->bloomShader = LoadShader(0, "resources/shaders/bloom.fs");
        // rlSetCullFace(RL_CULL_FACE_BACK);
    }
References Game::Renderer::bloomShader, Game::Renderer::CreateRenderTexture(), Logman::CustomLog(), DisableEventWaiting(), enableMusic, FLAG_MSAA_4X_HINT, FLAG_WINDOW_MAXIMIZED, GetMonitorHeight(), GetMonitorWidth(), ImageFormat(), InitAudioDevice(), InitWindow(), isFullscreen, KEY_BACKSPACE, LoadImage(), LoadShader(), LOG_ERROR, LOG_INFO, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, renderer, SetConfigFlags(), SetExitKey(), SetTargetFPS(), SetTraceLogCallback(), SetWindowIcon(), ConfigTypeConverter::StrToInt(), TextFormat(), ToggleFullscreen(), windowHeight, and windowWidth.
Member Data Documentation
configman
ConfigMan* Game::configman = new ConfigMan()
Definition at line 107 of file Game.h.
enableMusic
bool Game::enableMusic
Definition at line 104 of file Game.h.
isFullscreen
bool Game::isFullscreen = false
Definition at line 103 of file Game.h.
renderer
Renderer* Game::renderer inline static
Definition at line 110 of file Game.h.
windowHeight
int Game::windowHeight
Definition at line 101 of file Game.h.
windowWidth
int Game::windowWidth
Definition at line 100 of file Game.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Game.h