Techstorm-rivalry: raylib::Vector2 Class Reference
raylib::Vector2 Class Reference
#include <Vector2.hpp>
Public Member Functions
Vector2 (const ::Vector2 &vec)
Vector2 (float x, float y)
Vector2 (float x)
Vector2 ()
float GetX () const
void SetX (float value)
float GetY () const
void SetY (float value)
Vector2 & operator= (const ::Vector2 &vector2)
bool operator== (const ::Vector2 &other) const
bool operator!= (const ::Vector2 &other) const
std::string ToString () const
operator std::string () const
Vector2 Add (const ::Vector2 &vector2) const
Vector2 operator+ (const ::Vector2 &vector2) const
Vector2 & operator+= (const ::Vector2 &vector2)
Vector2 Subtract (const ::Vector2 &vector2) const
Vector2 operator- (const ::Vector2 &vector2) const
Vector2 & operator-= (const ::Vector2 &vector2)
Vector2 Negate () const
Vector2 operator- () const
Vector2 Multiply (const ::Vector2 &vector2) const
Vector2 operator* (const ::Vector2 &vector2) const
Vector2 & operator*= (const ::Vector2 &vector2)
Vector2 Scale (const float scale) const
Vector2 operator* (const float scale) const
Vector2 & operator*= (const float scale)
Vector2 Divide (const ::Vector2 &vector2) const
Vector2 operator/ (const ::Vector2 &vector2) const
Vector2 & operator/= (const ::Vector2 &vector2)
Vector2 Divide (const float div) const
Vector2 operator/ (const float div) const
Vector2 & operator/= (const float div)
Vector2 Normalize () const
Vector2 Transform (::Matrix mat) const
Vector2 Lerp (const ::Vector2 &vector2, float amount) const
Vector2 Reflect (const ::Vector2 &normal) const
Vector2 Rotate (float degrees) const
Vector2 MoveTowards (const ::Vector2 &target, float maxDistance) const
Vector2 Invert () const
Vector2 Clamp (::Vector2 min, ::Vector2 max) const
Vector2 Clamp (float min, float max) const
int Equals (::Vector2 q) const
float Length () const
float LengthSqr () const
float DotProduct (const ::Vector2 &vector2) const
float Distance (const ::Vector2 &vector2) const
float DistanceSqr (::Vector2 v2) const
float Angle (const ::Vector2 &vector2) const
void DrawPixel (::Color color={0, 0, 0, 255}) const
void DrawLine (::Vector2 endPos, ::Color color={0, 0, 0, 255}) const
void DrawLine (::Vector2 endPos, float thick, ::Color color={0, 0, 0, 255}) const
void DrawLineBezier (::Vector2 endPos, float thick, ::Color color={0, 0, 0, 255}) const
void DrawCircle (float radius, ::Color color={0, 0, 0, 255}) const
void DrawRectangle (::Vector2 size, ::Color color={0, 0, 0, 255}) const
void DrawPoly (int sides, float radius, float rotation, ::Color color={0, 0, 0, 255}) const
bool CheckCollisionCircle (float radius1, ::Vector2 center2, float radius2) const
bool CheckCollisionCircle (float radius, ::Rectangle rec) const
bool CheckCollision (::Rectangle rec) const
bool CheckCollision (::Vector2 center, float radius) const
bool CheckCollision (::Vector2 p1, ::Vector2 p2, ::Vector2 p3) const
bool CheckCollisionLines (::Vector2 endPos1, ::Vector2 startPos2, ::Vector2 endPos2, ::Vector2 *collisionPoint) const
bool CheckCollisionPointLine (::Vector2 p1, ::Vector2 p2, int threshold=1) const
Static Public Member Functions
static Vector2 Zero ()
static Vector2 One ()
Public Attributes
float x
float y
Protected Member Functions
void set (const ::Vector2 &vec)
Detailed Description
Vector2 type
Definition at line 18 of file Vector2.hpp.
Constructor & Destructor Documentation
Vector2() [1/4]
raylib::Vector2::Vector2 (const ::Vector2 & vec) inline
Definition at line 20 of file Vector2.hpp.
: ::Vector2{vec.x, vec.y} {}
Vector2() [2/4]
raylib::Vector2::Vector2 (float x, float y) inline
Definition at line 22 of file Vector2.hpp.
: ::Vector2{x, y} {}
Vector2() [3/4]
raylib::Vector2::Vector2 (float x) inline
Definition at line 23 of file Vector2.hpp.
: ::Vector2{x, 0} {}
Vector2() [4/4]
raylib::Vector2::Vector2 () inline
Definition at line 24 of file Vector2.hpp.
: ::Vector2{0, 0} {}
Member Function Documentation
Add()
Vector2 raylib::Vector2::Add (const ::Vector2 & vector2) const inline
Add two vectors (v1 + v2)
Definition at line 64 of file Vector2.hpp.
{
        return Vector2Add(*this, vector2);
    }
References Vector2Add().
Angle()
float raylib::Vector2::Angle (const ::Vector2 & vector2) const inline
Calculate angle from two vectors in X-axis
Definition at line 322 of file Vector2.hpp.
{
        return Vector2Angle(*this, vector2);
    }
References Vector2Angle().
CheckCollision() [1/3]
bool raylib::Vector2::CheckCollision (::Rectangle rec) const inline
Check if point is inside rectangle
Definition at line 389 of file Vector2.hpp.
{
        return ::CheckCollisionPointRec(*this, rec);
    }
CheckCollision() [2/3]
bool raylib::Vector2::CheckCollision (::Vector2 center, float radius) const inline
Check if point is inside circle
Definition at line 396 of file Vector2.hpp.
{
        return ::CheckCollisionPointCircle(*this, center, radius);
    }
CheckCollision() [3/3]
bool raylib::Vector2::CheckCollision (::Vector2 p1, ::Vector2 p2, ::Vector2 p3) const inline
Check if point is inside a triangle
Definition at line 403 of file Vector2.hpp.
{
        return ::CheckCollisionPointTriangle(*this, p1, p2, p3);
    }
CheckCollisionCircle() [1/2]
bool raylib::Vector2::CheckCollisionCircle (float radius, ::Rectangle rec) const inline
Check collision between circle and rectangle
Definition at line 382 of file Vector2.hpp.
{
        return ::CheckCollisionCircleRec(*this, radius, rec);
    }
CheckCollisionCircle() [2/2]
bool raylib::Vector2::CheckCollisionCircle (float radius1, ::Vector2 center2, float radius2) const inline
Check collision between two circles
Definition at line 375 of file Vector2.hpp.
{
        return ::CheckCollisionCircles(*this, radius1, center2, radius2);
    }
CheckCollisionLines()
bool raylib::Vector2::CheckCollisionLines (::Vector2 endPos1, ::Vector2 startPos2, ::Vector2 endPos2, ::Vector2 * collisionPoint) const inline
Check the collision between two lines defined by two points each, returns collision point by reference
Definition at line 410 of file Vector2.hpp.
{
        return ::CheckCollisionLines(*this, endPos1, startPos2, endPos2, collisionPoint);
    }
CheckCollisionPointLine()
bool raylib::Vector2::CheckCollisionPointLine (::Vector2 p1, ::Vector2 p2, int threshold = 1) const inline
Check if point belongs to line created between two points [p1] and [p2] with defined margin in pixels [threshold]
Definition at line 420 of file Vector2.hpp.
{
        return ::CheckCollisionPointLine(*this, p1, p2, threshold);
    }
Clamp() [1/2]
Vector2 raylib::Vector2::Clamp (::Vector2 min, ::Vector2 max) const inline
Clamp the components of the vector between
Definition at line 266 of file Vector2.hpp.
{
        return ::Vector2Clamp(*this, min, max);
    }
Clamp() [2/2]
Vector2 raylib::Vector2::Clamp (float min, float max) const inline
// Clamp the magnitude of the vector between two min and max values
Definition at line 273 of file Vector2.hpp.
{
        return ::Vector2ClampValue(*this, min, max);
    }
Distance()
float raylib::Vector2::Distance (const ::Vector2 & vector2) const inline
Calculate distance between two vectors
Definition at line 308 of file Vector2.hpp.
{
        return Vector2Distance(*this, vector2);
    }
References Vector2Distance().
DistanceSqr()
float raylib::Vector2::DistanceSqr (::Vector2 v2) const inline
Calculate square distance between two vectors
Definition at line 315 of file Vector2.hpp.
{
        return ::Vector2DistanceSqr(*this, v2);
    }
Divide() [1/2]
Vector2 raylib::Vector2::Divide (const ::Vector2 & vector2) const inline
Divide vector by vector
Definition at line 170 of file Vector2.hpp.
{
        return Vector2Divide(*this, vector2);
    }
References Vector2Divide().
Divide() [2/2]
Vector2 raylib::Vector2::Divide (const float div) const inline
Divide vector by value
Definition at line 193 of file Vector2.hpp.
{
        return ::Vector2{x / div, y / div};
    }
References Vector2::x, and Vector2::y.
DotProduct()
float raylib::Vector2::DotProduct (const ::Vector2 & vector2) const inline
Calculate two vectors dot product
Definition at line 301 of file Vector2.hpp.
{
        return Vector2DotProduct(*this, vector2);
    }
References Vector2DotProduct().
DrawCircle()
void raylib::Vector2::DrawCircle (float radius, ::Color color = {0, 0, 0, 255}) const inline
Draw a color-filled circle (Vector version)
Definition at line 360 of file Vector2.hpp.
                                                       {0, 0, 0, 255}) const {
        ::DrawCircleV(*this, radius, color);
    }
DrawLine() [1/2]
void raylib::Vector2::DrawLine (::Vector2 endPos, ::Color color = {0, 0, 0, 255}) const inline
Definition at line 345 of file Vector2.hpp.
                                                       {0, 0, 0, 255}) const {
        ::DrawLineV(*this, endPos, color);
    }
DrawLine() [2/2]
void raylib::Vector2::DrawLine (::Vector2 endPos, float thick, ::Color color = {0, 0, 0, 255}) const inline
Definition at line 349 of file Vector2.hpp.
                                                                    {0, 0, 0, 255}) const {
        ::DrawLineEx(*this, endPos, thick, color);
    }
DrawLineBezier()
void raylib::Vector2::DrawLineBezier (::Vector2 endPos, float thick, ::Color color = {0, 0, 0, 255}) const inline
Definition at line 353 of file Vector2.hpp.
                                                                          {0, 0, 0, 255}) const {
        ::DrawLineBezier(*this, endPos, thick, color);
    }
DrawPixel()
void raylib::Vector2::DrawPixel (::Color color = {0, 0, 0, 255}) const inline
Definition at line 341 of file Vector2.hpp.
                                        {0, 0, 0, 255}) const {
        ::DrawPixelV(*this, color);
    }
DrawPoly()
void raylib::Vector2::DrawPoly (int sides, float radius, float rotation, ::Color color = {0, 0, 0, 255}) const inline
Definition at line 368 of file Vector2.hpp.
                                                                                {0, 0, 0, 255}) const {
        ::DrawPoly(*this, sides, radius, rotation, color);
    }
DrawRectangle()
void raylib::Vector2::DrawRectangle (::Vector2 size, ::Color color = {0, 0, 0, 255}) const inline
Definition at line 364 of file Vector2.hpp.
                                                          {0, 0, 0, 255}) const {
        ::DrawRectangleV(*this, size, color);
    }
Equals()
int raylib::Vector2::Equals (::Vector2 q) const inline
Check whether two given vectors are almost equal
Definition at line 280 of file Vector2.hpp.
{
        return ::Vector2Equals(*this, q);
    }
GetX()
float raylib::Vector2::GetX () const inline
Retrieves the x value for the object.
Returns
The x value of the object.
Definition at line 26 of file Vector2.hpp.
GetY()
float raylib::Vector2::GetY () const inline
Retrieves the y value for the object.
Returns
The y value of the object.
Definition at line 27 of file Vector2.hpp.
Invert()
Vector2 raylib::Vector2::Invert () const inline
Invert the given vector
Definition at line 259 of file Vector2.hpp.
{
        return ::Vector2Invert(*this);
    }
Length()
float raylib::Vector2::Length () const inline
Calculate vector length
Definition at line 287 of file Vector2.hpp.
{
        return Vector2Length(*this);
    }
References Vector2Length().
LengthSqr()
float raylib::Vector2::LengthSqr () const inline
Calculate vector square length
Definition at line 294 of file Vector2.hpp.
{
        return Vector2LengthSqr(*this);
    }
References Vector2LengthSqr().
Lerp()
Vector2 raylib::Vector2::Lerp (const ::Vector2 & vector2, float amount) const inline
Calculate linear interpolation between two vectors
Definition at line 231 of file Vector2.hpp.
{
        return Vector2Lerp(*this, vector2, amount);
    }
References Vector2Lerp().
MoveTowards()
Vector2 raylib::Vector2::MoveTowards (const ::Vector2 & target, float maxDistance) const inline
Move Vector towards target
Definition at line 252 of file Vector2.hpp.
{
        return Vector2MoveTowards(*this, target, maxDistance);
    }
References Vector2MoveTowards().
Multiply()
Vector2 raylib::Vector2::Multiply (const ::Vector2 & vector2) const inline
Multiply vector by vector
Definition at line 124 of file Vector2.hpp.
{
        return Vector2Multiply(*this, vector2);
    }
References Vector2Multiply().
Negate()
Vector2 raylib::Vector2::Negate () const inline
Negate vector
Definition at line 110 of file Vector2.hpp.
{
        return Vector2Negate(*this);
    }
References Vector2Negate().
Normalize()
Vector2 raylib::Vector2::Normalize () const inline
Normalize provided vector
Definition at line 217 of file Vector2.hpp.
{
        return Vector2Normalize(*this);
    }
References Vector2Normalize().
One()
static Vector2 raylib::Vector2::One () inline static
Vector with components value 1.0f
Definition at line 336 of file Vector2.hpp.
{
        return Vector2One();
    }
References Vector2One().
operator std::string()
raylib::Vector2::operator std::string () const inline
Definition at line 56 of file Vector2.hpp.
{
        return ToString();
    }
References ToString().
operator!=()
bool raylib::Vector2::operator!= (const ::Vector2 & other) const inline
Determines if the vectors are not equal.
Definition at line 48 of file Vector2.hpp.
{
        return !(*this == other);
    }
operator*() [1/2]
Vector2 raylib::Vector2::operator* (const ::Vector2 & vector2) const inline
Multiply vector by vector
Definition at line 131 of file Vector2.hpp.
{
        return Vector2Multiply(*this, vector2);
    }
References Vector2Multiply().
operator*() [2/2]
Vector2 raylib::Vector2::operator* (const float scale) const inline
Scale vector (multiply by value)
Definition at line 154 of file Vector2.hpp.
{
        return Vector2Scale(*this, scale);
    }
References Vector2Scale().
operator*=() [1/2]
Vector2 & raylib::Vector2::operator*= (const ::Vector2 & vector2) inline
Multiply vector by vector
Definition at line 138 of file Vector2.hpp.
{
        set(Vector2Multiply(*this, vector2));
        return *this;
    }
References set(), and Vector2Multiply().
operator*=() [2/2]
Vector2 & raylib::Vector2::operator*= (const float scale) inline
Scale vector (multiply by value)
Definition at line 161 of file Vector2.hpp.
{
        set(Vector2Scale(*this, scale));
        return *this;
    }
References set(), and Vector2Scale().
operator+()
Vector2 raylib::Vector2::operator+ (const ::Vector2 & vector2) const inline
Add two vectors (v1 + v2)
Definition at line 71 of file Vector2.hpp.
{
        return Vector2Add(*this, vector2);
    }
References Vector2Add().
operator+=()
Vector2 & raylib::Vector2::operator+= (const ::Vector2 & vector2) inline
Add two vectors (v1 + v2)
Definition at line 78 of file Vector2.hpp.
{
        set(Vector2Add(*this, vector2));
        return *this;
    }
References set(), and Vector2Add().
operator-() [1/2]
Vector2 raylib::Vector2::operator- () const inline
Negate vector
Definition at line 117 of file Vector2.hpp.
{
        return Vector2Negate(*this);
    }
References Vector2Negate().
operator-() [2/2]
Vector2 raylib::Vector2::operator- (const ::Vector2 & vector2) const inline
Subtract two vectors (v1 - v2)
Definition at line 94 of file Vector2.hpp.
{
        return Vector2Subtract(*this, vector2);
    }
References Vector2Subtract().
operator-=()
Vector2 & raylib::Vector2::operator-= (const ::Vector2 & vector2) inline
Add two vectors (v1 + v2)
Definition at line 101 of file Vector2.hpp.
{
        set(Vector2Subtract(*this, vector2));
        return *this;
    }
References set(), and Vector2Subtract().
operator/() [1/2]
Vector2 raylib::Vector2::operator/ (const ::Vector2 & vector2) const inline
Divide vector by vector
Definition at line 177 of file Vector2.hpp.
{
        return Vector2Divide(*this, vector2);
    }
References Vector2Divide().
operator/() [2/2]
Vector2 raylib::Vector2::operator/ (const float div) const inline
Divide vector by value
Definition at line 200 of file Vector2.hpp.
{
        return Divide(div);
    }
References Divide().
operator/=() [1/2]
Vector2 & raylib::Vector2::operator/= (const ::Vector2 & vector2) inline
Divide vector by vector
Definition at line 184 of file Vector2.hpp.
{
        set(Vector2Divide(*this, vector2));
        return *this;
    }
References set(), and Vector2Divide().
operator/=() [2/2]
Vector2 & raylib::Vector2::operator/= (const float div) inline
Divide vector by value
Definition at line 207 of file Vector2.hpp.
{
        this->x /= div;
        this->y /= div;
        return *this;
    }
References Vector2::x, and Vector2::y.
operator=()
Vector2 & raylib::Vector2::operator= (const ::Vector2 & vector2) inline
Set the Vector2 to the same as the given Vector2.
Definition at line 32 of file Vector2.hpp.
{
        set(vector2);
        return *this;
    }
References set().
operator==()
bool raylib::Vector2::operator== (const ::Vector2 & other) const inline
Determine whether or not the vectors are equal.
Definition at line 40 of file Vector2.hpp.
{
        return x == other.x
            && y == other.y;
    }
References Vector2::x, and Vector2::y.
Reflect()
Vector2 raylib::Vector2::Reflect (const ::Vector2 & normal) const inline
Calculate reflected vector to normal
Definition at line 238 of file Vector2.hpp.
{
        return Vector2Reflect(*this, normal);
    }
References Vector2Reflect().
Rotate()
Vector2 raylib::Vector2::Rotate (float degrees) const inline
Rotate Vector by float in Degrees
Definition at line 245 of file Vector2.hpp.
{
        return Vector2Rotate(*this, degrees);
    }
References Vector2Rotate().
Scale()
Vector2 raylib::Vector2::Scale (const float scale) const inline
Scale vector (multiply by value)
Definition at line 147 of file Vector2.hpp.
{
        return Vector2Scale(*this, scale);
    }
References Vector2Scale().
set()
void raylib::Vector2::set (const ::Vector2 & vec) inline protected
Definition at line 425 of file Vector2.hpp.
{
        x = vec.x;
        y = vec.y;
    }
References Vector2::x, and Vector2::y.
SetX()
void raylib::Vector2::SetX (float value) inline
Sets the x value for the object.
Parameters
value The value of which to set x to.
Definition at line 26 of file Vector2.hpp.
SetY()
void raylib::Vector2::SetY (float value) inline
Sets the y value for the object.
Parameters
value The value of which to set y to.
Definition at line 27 of file Vector2.hpp.
Subtract()
Vector2 raylib::Vector2::Subtract (const ::Vector2 & vector2) const inline
Subtract two vectors (v1 - v2)
Definition at line 87 of file Vector2.hpp.
{
        return Vector2Subtract(*this, vector2);
    }
References Vector2Subtract().
ToString()
std::string raylib::Vector2::ToString () const inline
Definition at line 52 of file Vector2.hpp.
{
        return TextFormat("Vector2(%f, %f)", x, y);
    }
References TextFormat(), Vector2::x, and Vector2::y.
Transform()
Vector2 raylib::Vector2::Transform (::Matrix mat) const inline
Transforms a Vector2 by a given Matrix
Definition at line 224 of file Vector2.hpp.
{
        return ::Vector2Transform(*this, mat);
    }
Zero()
static Vector2 raylib::Vector2::Zero () inline static
Vector with components value 0.0f
Definition at line 329 of file Vector2.hpp.
{
        return Vector2Zero();
    }
References Vector2Zero().
Member Data Documentation
x
float Vector2::x inherited
Definition at line 205 of file raylib.h.
y
float Vector2::y inherited
Definition at line 206 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Vector2.hpp