Techstorm-rivalry: raylib::Wave Class Reference
raylib::Wave Class Reference
#include <Wave.hpp>
Public Member Functions
Wave (const ::Wave &wave)
Wave (unsigned int frameCount=0, unsigned int sampleRate=0, unsigned int sampleSize=0, unsigned int channels=0, void *data=nullptr)
Wave (const std::string &fileName)
Wave (const std::string &fileType, const unsigned char *fileData, int dataSize)
Wave (const Wave &other)
Wave (Wave &&other)
~Wave ()
unsigned int GetFrameCount () const
void SetFrameCount (unsigned int value)
unsigned int GetSampleRate () const
void SetSampleRate (unsigned int value)
unsigned int GetSampleSize () const
void SetSampleSize (unsigned int value)
unsigned int GetChannels () const
void SetChannels (unsigned int value)
void * GetData () const
void SetData (void *value)
Wave & operator= (const ::Wave &wave)
Wave & operator= (const Wave &other)
Wave & operator= (Wave &&other) noexcept
inline ::Wave Copy () const
Wave & Crop (int initSample, int finalSample)
Wave & Format (int SampleRate, int SampleSize, int Channels=2)
float * LoadSamples ()
bool Export (const std::string &fileName)
bool ExportAsCode (const std::string &fileName)
void Unload ()
inline ::Sound LoadSound ()
operator::Sound ()
void Load (const std::string &fileName)
void Load (const std::string &fileType, const unsigned char *fileData, int dataSize)
bool IsReady () const
Static Public Member Functions
static void UnloadSamples (float *samples)
Public Attributes
unsigned int frameCount
unsigned int sampleRate
unsigned int sampleSize
unsigned int channels
void * data
Protected Member Functions
void set (const ::Wave &wave)
Detailed Description
Wave type, defines audio wave data
Definition at line 14 of file Wave.hpp.
Constructor & Destructor Documentation
Wave() [1/6]
raylib::Wave::Wave (const ::Wave & wave) inline
Definition at line 16 of file Wave.hpp.
{
        set(wave);
    }
References set().
Wave() [2/6]
raylib::Wave::Wave (unsigned int frameCount = 0, unsigned int sampleRate = 0, unsigned int sampleSize = 0, unsigned int channels = 0, void * data = nullptr) inline
Definition at line 20 of file Wave.hpp.
                                  : ::Wave{frameCount, sampleRate, sampleSize, channels, data} {
        // Nothing.
    }
Wave() [3/6]
raylib::Wave::Wave (const std::string & fileName) inline
Load wave data from file
Exceptions
raylib::RaylibException Throws if the Wave failed to load.
Definition at line 34 of file Wave.hpp.
{
        Load(fileName);
    }
References Load().
Wave() [4/6]
raylib::Wave::Wave (const std::string & fileType, const unsigned char * fileData, int dataSize) inline
Load wave from memory buffer, fileType refers to extension: i.e. "wav"
Exceptions
raylib::RaylibException Throws if the Wave failed to load.
Definition at line 43 of file Wave.hpp.
{
        Load(fileType, fileData, dataSize);
    }
References Load().
Wave() [5/6]
raylib::Wave::Wave (const Wave & other) inline
Definition at line 47 of file Wave.hpp.
{
        set(other.Copy());
    }
References Copy(), and set().
Wave() [6/6]
raylib::Wave::Wave (Wave && other) inline
Definition at line 51 of file Wave.hpp.
                       {
        set(other);
        other.frameCount = 0;
        other.sampleRate = 0;
        other.sampleSize = 0;
        other.channels = 0;
        other.data = nullptr;
    }
References set().
~Wave()
raylib::Wave::~Wave () inline
Unload wave data
Definition at line 64 of file Wave.hpp.
            {
        Unload();
    }
References Unload().
Member Function Documentation
Copy()
inline ::Wave raylib::Wave::Copy () const inline
Copy a wave to a new wave
Definition at line 110 of file Wave.hpp.
{
        return ::WaveCopy(*this);
    }
Crop()
Wave & raylib::Wave::Crop (int initSample, int finalSample) inline
Crop a wave to defined samples range
Definition at line 117 of file Wave.hpp.
{
        ::WaveCrop(this, initSample, finalSample);
        return *this;
    }
References WaveCrop().
Export()
bool raylib::Wave::Export (const std::string & fileName) inline
Export wave data to file, returns true on success
Definition at line 147 of file Wave.hpp.
{
        // TODO(RobLoach): Throw exception on error.
        return ::ExportWave(*this, fileName.c_str());
    }
ExportAsCode()
bool raylib::Wave::ExportAsCode (const std::string & fileName) inline
Export wave sample data to code (.h), returns true on success
Definition at line 155 of file Wave.hpp.
{
        // TODO(RobLoach): Throw exception on error.
        return ::ExportWaveAsCode(*this, fileName.c_str());
    }
Format()
Wave & raylib::Wave::Format (int SampleRate, int SampleSize, int Channels = 2) inline
Convert wave data to desired format
Definition at line 125 of file Wave.hpp.
{
        ::WaveFormat(this, SampleRate, SampleSize, Channels);
        return *this;
    }
References WaveFormat().
GetChannels()
unsigned int raylib::Wave::GetChannels () const inline
Retrieves the channels value for the object.
Returns
The channels value of the object.
Definition at line 71 of file Wave.hpp.
GetData()
void * raylib::Wave::GetData () const inline
Retrieves the data value for the object.
Returns
The data value of the object.
Definition at line 72 of file Wave.hpp.
GetFrameCount()
unsigned int raylib::Wave::GetFrameCount () const inline
Retrieves the frameCount value for the object.
Returns
The frameCount value of the object.
Definition at line 68 of file Wave.hpp.
GetSampleRate()
unsigned int raylib::Wave::GetSampleRate () const inline
Retrieves the sampleRate value for the object.
Returns
The sampleRate value of the object.
Definition at line 69 of file Wave.hpp.
GetSampleSize()
unsigned int raylib::Wave::GetSampleSize () const inline
Retrieves the sampleSize value for the object.
Returns
The sampleSize value of the object.
Definition at line 70 of file Wave.hpp.
IsReady()
bool raylib::Wave::IsReady () const inline
Retrieve whether or not the Wave data has been loaded.
Returns
True or false depending on whether the wave data has been loaded.
Definition at line 214 of file Wave.hpp.
{
        return ::IsWaveReady(*this);
    }
Load() [1/2]
void raylib::Wave::Load (const std::string & fileName) inline
Load wave data from file.
Exceptions
raylib::RaylibException Throws if the Wave failed to load.
Definition at line 190 of file Wave.hpp.
{
        set(::LoadWave(fileName.c_str()));
        if (!IsReady()) {
            throw RaylibException("Failed to load Wave from file: " + fileName);
        }
    }
References IsReady(), LoadWave(), and set().
Load() [2/2]
void raylib::Wave::Load (const std::string & fileType, const unsigned char * fileData, int dataSize) inline
Load wave from memory buffer, fileType refers to extension: i.e. "wav"
Exceptions
raylib::RaylibException Throws if the Wave failed to load.
Definition at line 202 of file Wave.hpp.
{
        set(::LoadWaveFromMemory(fileType.c_str(), fileData, dataSize));
        if (!IsReady()) {
            throw RaylibException("Failed to load Wave from file data of type: " + fileType);
        }
    }
References IsReady(), LoadWaveFromMemory(), and set().
LoadSamples()
float * raylib::Wave::LoadSamples () inline
Load samples data from wave as a floats array
Definition at line 133 of file Wave.hpp.
{
        return ::LoadWaveSamples(*this);
    }
LoadSound()
inline ::Sound raylib::Wave::LoadSound () inline
Load sound from wave data
Definition at line 174 of file Wave.hpp.
{
        return ::LoadSoundFromWave(*this);
    }
operator::Sound()
raylib::Wave::operator::Sound () inline
Load sound from wave data
Definition at line 181 of file Wave.hpp.
{
        return LoadSound();
    }
References LoadSound().
operator=() [1/3]
Wave & raylib::Wave::operator= (const ::Wave & wave) inline
Definition at line 74 of file Wave.hpp.
{
        set(wave);
        return *this;
    }
References set().
operator=() [2/3]
Wave & raylib::Wave::operator= (const Wave & other) inline
Definition at line 79 of file Wave.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other.Copy());
        return *this;
    }
References Copy(), set(), and Unload().
operator=() [3/3]
Wave & raylib::Wave::operator= (Wave && other) inline noexcept
Definition at line 90 of file Wave.hpp.
{
        if (this != &other) {
            return *this;
        }
        Unload();
        set(other);
        other.frameCount = 0;
        other.sampleRate = 0;
        other.sampleSize = 0;
        other.channels = 0;
        other.data = nullptr;
        return *this;
    }
References set(), and Unload().
set()
void raylib::Wave::set (const ::Wave & wave) inline protected
Definition at line 219 of file Wave.hpp.
{
        frameCount = wave.frameCount;
        sampleRate = wave.sampleRate;
        sampleSize = wave.sampleSize;
        channels = wave.channels;
        data = wave.data;
    }
References Wave::channels, Wave::data, Wave::frameCount, Wave::sampleRate, and Wave::sampleSize.
SetChannels()
void raylib::Wave::SetChannels (unsigned int value) inline
Sets the channels value for the object.
Parameters
value The value of which to set channels to.
Definition at line 71 of file Wave.hpp.
SetData()
void raylib::Wave::SetData (void * value) inline
Sets the data value for the object.
Parameters
value The value of which to set data to.
Definition at line 72 of file Wave.hpp.
SetFrameCount()
void raylib::Wave::SetFrameCount (unsigned int value) inline
Sets the frameCount value for the object.
Parameters
value The value of which to set frameCount to.
Definition at line 68 of file Wave.hpp.
SetSampleRate()
void raylib::Wave::SetSampleRate (unsigned int value) inline
Sets the sampleRate value for the object.
Parameters
value The value of which to set sampleRate to.
Definition at line 69 of file Wave.hpp.
SetSampleSize()
void raylib::Wave::SetSampleSize (unsigned int value) inline
Sets the sampleSize value for the object.
Parameters
value The value of which to set sampleSize to.
Definition at line 70 of file Wave.hpp.
Unload()
void raylib::Wave::Unload () inline
Unload wave data
Definition at line 163 of file Wave.hpp.
                  {
        // Protect against calling UnloadWave() twice.
        if (data != nullptr) {
            ::UnloadWave(*this);
            data = nullptr;
        }
    }
References Wave::data, and UnloadWave().
UnloadSamples()
static void raylib::Wave::UnloadSamples (float * samples) inline static
Unload samples data loaded with LoadWaveSamples()
Definition at line 140 of file Wave.hpp.
{
        ::UnloadWaveSamples(samples);
    }
References UnloadWaveSamples().
Member Data Documentation
channels
unsigned int Wave::channels inherited
Definition at line 441 of file raylib.h.
data
void* Wave::data inherited
Definition at line 442 of file raylib.h.
frameCount
unsigned int Wave::frameCount inherited
Definition at line 438 of file raylib.h.
sampleRate
unsigned int Wave::sampleRate inherited
Definition at line 439 of file raylib.h.
sampleSize
unsigned int Wave::sampleSize inherited
Definition at line 440 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Wave.hpp