Techstorm-rivalry: raylib::Camera2D Class Reference
raylib::Camera2D Class Reference
#include <Camera2D.hpp>
Public Member Functions
Camera2D (const ::Camera2D &camera)
Camera2D ()
Camera2D (::Vector2 offset, ::Vector2 target, float rotation=0.0f, float zoom=1.0f)
Camera2D & BeginMode ()
Camera2D & EndMode ()
::Vector2 GetOffset () const
void SetOffset (::Vector2 value)
::Vector2 GetTarget () const
void SetTarget (::Vector2 value)
float GetRotation () const
void SetRotation (float value)
float GetZoom () const
void SetZoom (float value)
Camera2D & operator= (const ::Camera2D &camera)
Matrix GetMatrix () const
Vector2 GetScreenToWorld (::Vector2 position) const
Vector2 GetWorldToScreen (::Vector2 position) const
Public Attributes
Vector2 offset
Vector2 target
float rotation
float zoom
Protected Member Functions
void set (const ::Camera2D &camera)
Detailed Description
Camera2D type, defines a 2d camera
Definition at line 12 of file Camera2D.hpp.
Constructor & Destructor Documentation
Camera2D() [1/3]
raylib::Camera2D::Camera2D (const ::Camera2D & camera) inline
Definition at line 14 of file Camera2D.hpp.
{
        set(camera);
    }
References set().
Camera2D() [2/3]
raylib::Camera2D::Camera2D () inline
Definition at line 18 of file Camera2D.hpp.
{}
Camera2D() [3/3]
raylib::Camera2D::Camera2D (::Vector2 offset, ::Vector2 target, float rotation = 0.0f, float zoom = 1.0f) inline
Definition at line 19 of file Camera2D.hpp.
                                                      : ::Camera2D{offset, target, rotation, zoom} {}
Member Function Documentation
BeginMode()
Camera2D & raylib::Camera2D::BeginMode () inline
Definition at line 22 of file Camera2D.hpp.
{
        ::BeginMode2D(*this);
        return *this;
    }
References BeginMode2D().
EndMode()
Camera2D & raylib::Camera2D::EndMode () inline
Definition at line 27 of file Camera2D.hpp.
{
        ::EndMode2D();
        return *this;
    }
References EndMode2D().
GetMatrix()
Matrix raylib::Camera2D::GetMatrix () const inline
Returns camera 2d transform matrix
Definition at line 45 of file Camera2D.hpp.
{
        return ::GetCameraMatrix2D(*this);
    }
GetOffset()
::Vector2 raylib::Camera2D::GetOffset () const inline
Retrieves the offset value for the object.
Returns
The offset value of the object.
Definition at line 32 of file Camera2D.hpp.
GetRotation()
float raylib::Camera2D::GetRotation () const inline
Retrieves the rotation value for the object.
Returns
The rotation value of the object.
Definition at line 34 of file Camera2D.hpp.
GetScreenToWorld()
Vector2 raylib::Camera2D::GetScreenToWorld (::Vector2 position) const inline
Returns the world space position for a 2d camera screen space position
Definition at line 52 of file Camera2D.hpp.
{
        return ::GetScreenToWorld2D(position, *this);
    }
GetTarget()
::Vector2 raylib::Camera2D::GetTarget () const inline
Retrieves the target value for the object.
Returns
The target value of the object.
Definition at line 33 of file Camera2D.hpp.
GetWorldToScreen()
Vector2 raylib::Camera2D::GetWorldToScreen (::Vector2 position) const inline
Returns the screen space position for a 3d world space position
Definition at line 59 of file Camera2D.hpp.
{
        return ::GetWorldToScreen2D(position, *this);
    }
GetZoom()
float raylib::Camera2D::GetZoom () const inline
Retrieves the zoom value for the object.
Returns
The zoom value of the object.
Definition at line 35 of file Camera2D.hpp.
operator=()
Camera2D & raylib::Camera2D::operator= (const ::Camera2D & camera) inline
Definition at line 37 of file Camera2D.hpp.
{
        set(camera);
        return *this;
    }
References set().
set()
void raylib::Camera2D::set (const ::Camera2D & camera) inline protected
Definition at line 64 of file Camera2D.hpp.
{
        offset = camera.offset;
        target = camera.target;
        rotation = camera.rotation;
        zoom = camera.zoom;
    }
References Camera2D::offset, Camera2D::rotation, Camera2D::target, and Camera2D::zoom.
SetOffset()
void raylib::Camera2D::SetOffset (::Vector2 value) inline
Sets the offset value for the object.
Parameters
value The value of which to set offset to.
Definition at line 32 of file Camera2D.hpp.
SetRotation()
void raylib::Camera2D::SetRotation (float value) inline
Sets the rotation value for the object.
Parameters
value The value of which to set rotation to.
Definition at line 34 of file Camera2D.hpp.
SetTarget()
void raylib::Camera2D::SetTarget (::Vector2 value) inline
Sets the target value for the object.
Parameters
value The value of which to set target to.
Definition at line 33 of file Camera2D.hpp.
SetZoom()
void raylib::Camera2D::SetZoom (float value) inline
Sets the zoom value for the object.
Parameters
value The value of which to set zoom to.
Definition at line 35 of file Camera2D.hpp.
Member Data Documentation
offset
Vector2 Camera2D::offset inherited
Definition at line 327 of file raylib.h.
rotation
float Camera2D::rotation inherited
Definition at line 329 of file raylib.h.
target
Vector2 Camera2D::target inherited
Definition at line 328 of file raylib.h.
zoom
float Camera2D::zoom inherited
Definition at line 330 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Camera2D.hpp