Techstorm-rivalry: ConfigMan Class Reference
ConfigMan Class Reference
#include <Configman.h>
Public Member Functions
ConfigMan ()
~ConfigMan ()
Static Public Member Functions
static void Innit ()
static ConfigFile FindFile (std::vector< ConfigFile > &Dataset, const char *TargetFile)
Find a ConfigFile in the Dataset by TargetFile.
static bool DoesFileExist (std::vector< ConfigFile > &Dataset, const char *TargetFile)
Check if a file exists in the Dataset.
static int CharToInt (const char *value)
Converts a char pointer to an integer value.
static int StrToInt (std::string *value)
Converts a string to an integer.
static int Int64ToInt (int64_t *value)
Converts a 64-bit integer to a 16-bit integer value.
Static Public Attributes
static ConfigRegistry * Registry
Detailed Description
Definition at line 307 of file Configman.h.
Constructor & Destructor Documentation
ConfigMan()
ConfigMan::ConfigMan () inline
Definition at line 311 of file Configman.h.
                {
        Logman::CustomLog(LOG_INFO, "New Config Manager instance created successfully!", NULL);
    };
References Logman::CustomLog(), and LOG_INFO.
~ConfigMan()
ConfigMan::~ConfigMan () inline
Definition at line 316 of file Configman.h.
                 {
        delete this;
    }
Member Function Documentation
CharToInt()
static int ConfigTypeConverter::CharToInt (const char * value) inline static inherited
Converts a char pointer to an integer value.
Parameters
value The input char pointer.
Returns
The converted integer value.
Definition at line 50 of file Configman.h.
{
        return TextToInteger(value);
    }
References TextToInteger().
DoesFileExist()
static bool ConfigRegistrySecretary::DoesFileExist (std::vector< ConfigFile > & Dataset, const char * TargetFile) inline static inherited
Check if a file exists in the Dataset.
Parameters
Dataset The vector of ConfigFiles to search
TargetFile The file to search for
Returns
true if the file exists, false otherwise
Definition at line 229 of file Configman.h.
{
        bool found = false;
        for (int i = 0; i < Dataset.size(); i++) {
            if (Dataset[i].file.entry.FilePath == TargetFile) {
                found = true;
            }
        }
        return found;
    }
FindFile()
static ConfigFile ConfigRegistrySecretary::FindFile (std::vector< ConfigFile > & Dataset, const char * TargetFile) inline static inherited
Find a ConfigFile in the Dataset by TargetFile.
Parameters
Dataset The vector of ConfigFiles to search
TargetFile The file to search for
Returns
The found ConfigFile, or an empty ConfigFile if not found
Definition at line 210 of file Configman.h.
{
        ConfigFile file;
        if (DoesFileExist(Dataset, TargetFile)) {
            for (int i = 0; i < Dataset.size(); i++) {
                if (Dataset[i].file.entry.FilePath == TargetFile) {
                    file = Dataset[i];
                }
            }
        }
        return file;
    }
References ConfigRegistrySecretary::DoesFileExist().
Innit()
static void ConfigMan::Innit () inline static
Definition at line 321 of file Configman.h.
{
        Registry = new ConfigRegistry();
        ConfigFile::Innit();
        Logman::CustomLog(LOG_INFO, "Loading TOML files from Config folder...", NULL);
        // TODO : Make this automatic.
        Registry->RegisterFile("Config/Engine.toml");
        Registry->RegisterFile("Config/options.toml");
        Logman::CustomLog(LOG_INFO, "Loaded TOML files from Config folder", NULL);
    }
References Logman::CustomLog(), ConfigFile::Innit(), LOG_INFO, ConfigRegistry::RegisterFile(), and Registry.
Int64ToInt()
static int ConfigTypeConverter::Int64ToInt (int64_t * value) inline static inherited
Converts a 64-bit integer to a 16-bit integer value.
Parameters
value The input 64-bit integer pointer.
Returns
The converted 16-bit integer value.
Definition at line 80 of file Configman.h.
{
        return *value;
    }
StrToInt()
static int ConfigTypeConverter::StrToInt (std::string * value) inline static inherited
Converts a string to an integer.
This function converts the input string to an integer. If the string is "true", it returns 1; if the string is "false", it returns 0; otherwise, it converts the string to an integer using TextToInteger function.
Parameters
value The input string.
Returns
The converted integer value.
Definition at line 62 of file Configman.h.
{
        if (value->c_str() == "true") {
            return 1;
        }
        else if (value->c_str() == "false") {
            return 0;
        }
        else {
            const char* charconversion = value->c_str();
            return TextToInteger(charconversion);
        }
    }
References TextToInteger().
Member Data Documentation
Registry
ConfigRegistry* ConfigMan::Registry static
Definition at line 334 of file Configman.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Configman.h