Techstorm-rivalry: PlayerController Class Reference
PlayerController Class Reference
#include <Player.h>
Public Member Functions
PlayerController (KeyboardKey Forward, KeyboardKey Backward, KeyboardKey Left, KeyboardKey Right, KeyboardKey Jump, KeyboardKey Crouch, int mode)
void SetSpeed (float speed)
void Update (Camera *camera)
Public Attributes
bool isRunning = false
bool canMove = true
bool isGrounded = false
Detailed Description
Definition at line 11 of file Player.h.
Constructor & Destructor Documentation
PlayerController()
PlayerController::PlayerController (KeyboardKey Forward, KeyboardKey Backward, KeyboardKey Left, KeyboardKey Right, KeyboardKey Jump, KeyboardKey Crouch, int mode) inline
Definition at line 40 of file Player.h.
                                                                                                                                                     : forward(Forward), backward(Backward), left(Left), right(Right), jump(Jump), crouch(Crouch), mode(mode)
    {
#ifndef tiltLeft
        tiltLeft = KEY_Q;
#endif // !tiltLeft
#ifndef tiltRight
        tiltRight = KEY_E;
#endif // !tiltRight
    }
References KEY_E, and KEY_Q.
Member Function Documentation
SetSpeed()
void PlayerController::SetSpeed (float speed) inline
Definition at line 50 of file Player.h.
{
        this->speed = speed;
    }
Update()
void PlayerController::Update (Camera * camera) inline
Definition at line 54 of file Player.h.
    {
        // Camera PRO usage example (EXPERIMENTAL)
        // This new camera function allows custom movement/rotation values to be directly provided
        // as input parameters, with this approach, rcamera module is internally independent of raylib inputs
        UpdateCameraPro(camera,
            Vector3{
                (IsKeyDown(forward) || IsKeyDown(KEY_UP)) * speed -      // Move forward-backward
                (IsKeyDown(backward) || IsKeyDown(KEY_DOWN)) * speed,
                (IsKeyDown(right) || IsKeyDown(KEY_RIGHT)) * speed -   // Move right-left
                (IsKeyDown(left) || IsKeyDown(KEY_LEFT)) * speed,
                (IsKeyDown(jump)) * speed -                                                 // Move up-down
                (IsKeyDown(crouch)) * speed
            },
            Vector3{
                GetMouseDelta().x * mouseSensitivity,                            // Rotation: yaw
                GetMouseDelta().y * mouseSensitivity,                            // Rotation: pitch
                CalculateCameraTilt()                // Rotation: roll
            },
            GetMouseWheelMove() * 2.0f);                              // Move to target (zoom)
    }
References GetMouseDelta(), GetMouseWheelMove(), IsKeyDown(), KEY_DOWN, KEY_LEFT, KEY_RIGHT, KEY_UP, UpdateCameraPro(), Vector2::x, and Vector2::y.
Member Data Documentation
canMove
bool PlayerController::canMove = true
Definition at line 37 of file Player.h.
isGrounded
bool PlayerController::isGrounded = false
Definition at line 38 of file Player.h.
isRunning
bool PlayerController::isRunning = false
Definition at line 36 of file Player.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Player.h