Techstorm-rivalry: raylib::Vector3 Class Reference
raylib::Vector3 Class Reference
#include <Vector3.hpp>
Public Member Functions
Vector3 (const ::Vector3 &vec)
Vector3 (float x, float y, float z)
Vector3 (float x, float y)
Vector3 (float x)
Vector3 ()
Vector3 (::Color color)
float GetX () const
void SetX (float value)
float GetY () const
void SetY (float value)
float GetZ () const
void SetZ (float value)
Vector3 & operator= (const ::Vector3 &vector3)
bool operator== (const ::Vector3 &other) const
bool operator!= (const ::Vector3 &other) const
std::string ToString () const
operator std::string () const
Vector3 Add (const ::Vector3 &vector3) const
Vector3 operator+ (const ::Vector3 &vector3) const
Vector3 & operator+= (const ::Vector3 &vector3)
Vector3 Subtract (const ::Vector3 &vector3) const
Vector3 operator- (const ::Vector3 &vector3) const
Vector3 & operator-= (const ::Vector3 &vector3)
Vector3 Negate () const
Vector3 operator- () const
Vector3 Multiply (const ::Vector3 &vector3) const
Vector3 operator* (const ::Vector3 &vector3) const
Vector3 & operator*= (const ::Vector3 &vector3)
Vector3 Scale (const float scaler) const
Vector3 operator* (const float scaler) const
Vector3 & operator*= (const float scaler)
Vector3 Divide (const ::Vector3 &vector3) const
Vector3 operator/ (const ::Vector3 &vector3) const
Vector3 & operator/= (const ::Vector3 &vector3)
Vector3 Divide (const float div) const
Vector3 operator/ (const float div) const
Vector3 & operator/= (const float div)
float Length () const
Vector3 Normalize () const
float DotProduct (const ::Vector3 &vector3) const
float Distance (const ::Vector3 &vector3) const
Vector3 Lerp (const ::Vector3 &vector3, const float amount) const
Vector3 CrossProduct (const ::Vector3 &vector3) const
Vector3 Perpendicular () const
void OrthoNormalize (::Vector3 *vector3)
Vector3 Transform (const ::Matrix &matrix) const
Vector3 RotateByQuaternion (const ::Quaternion &quaternion) const
Vector3 Reflect (const ::Vector3 &normal) const
Vector3 Min (const ::Vector3 &vector3) const
Vector3 Max (const ::Vector3 &vector3) const
Vector3 Barycenter (const ::Vector3 &a, const ::Vector3 &b, const ::Vector3 &c) const
void DrawLine3D (const ::Vector3 &endPos, ::Color color) const
void DrawPoint3D (::Color color) const
void DrawCircle3D (float radius, const ::Vector3 &rotationAxis, float rotationAngle, Color color) const
void DrawCube (float width, float height, float length, ::Color color) const
void DrawCube (const ::Vector3 &size, ::Color color) const
void DrawCubeWires (float width, float height, float length, ::Color color) const
void DrawCubeWires (const ::Vector3 &size, ::Color color) const
void DrawSphere (float radius, ::Color color) const
void DrawSphere (float radius, int rings, int slices, ::Color color) const
void DrawSphereWires (float radius, int rings, int slices, ::Color color) const
void DrawCylinder (float radiusTop, float radiusBottom, float height, int slices, ::Color color) const
void DrawCylinderWires (float radiusTop, float radiusBottom, float height, int slices, ::Color color) const
void DrawPlane (const ::Vector2 &size, ::Color color) const
bool CheckCollision (float radius1, const ::Vector3 &center2, float radius2) const
Static Public Member Functions
static Vector3 Zero ()
static Vector3 One ()
Public Attributes
float x
float y
float z
Protected Member Functions
void set (const ::Vector3 &vec)
Detailed Description
Vector3 type
Definition at line 18 of file Vector3.hpp.
Constructor & Destructor Documentation
Vector3() [1/6]
raylib::Vector3::Vector3 (const ::Vector3 & vec) inline
Definition at line 20 of file Vector3.hpp.
: ::Vector3{vec.x, vec.y, vec.z} {}
Vector3() [2/6]
raylib::Vector3::Vector3 (float x, float y, float z) inline
Definition at line 22 of file Vector3.hpp.
: ::Vector3{x, y, z} {}
Vector3() [3/6]
raylib::Vector3::Vector3 (float x, float y) inline
Definition at line 23 of file Vector3.hpp.
: ::Vector3{x, y, 0} {}
Vector3() [4/6]
raylib::Vector3::Vector3 (float x) inline
Definition at line 24 of file Vector3.hpp.
: ::Vector3{x, 0, 0} {}
Vector3() [5/6]
raylib::Vector3::Vector3 () inline
Definition at line 25 of file Vector3.hpp.
{}
Vector3() [6/6]
raylib::Vector3::Vector3 (::Color color) inline
Definition at line 27 of file Vector3.hpp.
{
        set(ColorToHSV(color));
    }
References ColorToHSV(), and set().
Member Function Documentation
Add()
Vector3 raylib::Vector3::Add (const ::Vector3 & vector3) const inline
Add two vectors
Definition at line 62 of file Vector3.hpp.
{
        return Vector3Add(*this, vector3);
    }
References Vector3Add().
Barycenter()
Vector3 raylib::Vector3::Barycenter (const ::Vector3 & a, const ::Vector3 & b, const ::Vector3 & c) const inline
Definition at line 264 of file Vector3.hpp.
{
        return Vector3Barycenter(*this, a, b, c);
    }
References Vector3Barycenter().
CheckCollision()
bool raylib::Vector3::CheckCollision (float radius1, const ::Vector3 & center2, float radius2) const inline
Detect collision between two spheres
Definition at line 338 of file Vector3.hpp.
{
        return CheckCollisionSpheres(*this, radius1, center2, radius2);
    }
References CheckCollisionSpheres().
CrossProduct()
Vector3 raylib::Vector3::CrossProduct (const ::Vector3 & vector3) const inline
Definition at line 232 of file Vector3.hpp.
{
        return Vector3CrossProduct(*this, vector3);
    }
References Vector3CrossProduct().
Distance()
float raylib::Vector3::Distance (const ::Vector3 & vector3) const inline
Definition at line 224 of file Vector3.hpp.
{
        return Vector3Distance(*this, vector3);
    }
References Vector3Distance().
Divide() [1/2]
Vector3 raylib::Vector3::Divide (const ::Vector3 & vector3) const inline
Divide vector by vector
Definition at line 162 of file Vector3.hpp.
{
        return Vector3Divide(*this, vector3);
    }
References Vector3Divide().
Divide() [2/2]
Vector3 raylib::Vector3::Divide (const float div) const inline
Divide a vector by a value.
Definition at line 187 of file Vector3.hpp.
{
        return ::Vector3{x / div, y / div, z / div};
    }
References Vector3::x, Vector3::y, and Vector3::z.
DotProduct()
float raylib::Vector3::DotProduct (const ::Vector3 & vector3) const inline
Definition at line 220 of file Vector3.hpp.
{
        return Vector3DotProduct(*this, vector3);
    }
References Vector3DotProduct().
DrawCircle3D()
void raylib::Vector3::DrawCircle3D (float radius, const ::Vector3 & rotationAxis, float rotationAngle, Color color) const inline
Definition at line 285 of file Vector3.hpp.
{
        ::DrawCircle3D(*this, radius, rotationAxis, rotationAngle, color);
    }
References DrawCircle3D().
DrawCube() [1/2]
void raylib::Vector3::DrawCube (const ::Vector3 & size, ::Color color) const inline
Definition at line 297 of file Vector3.hpp.
{
        ::DrawCubeV(*this, size, color);
    }
References DrawCubeV().
DrawCube() [2/2]
void raylib::Vector3::DrawCube (float width, float height, float length, ::Color color) const inline
Definition at line 293 of file Vector3.hpp.
{
        ::DrawCube(*this, width, height, length, color);
    }
References DrawCube().
DrawCubeWires() [1/2]
void raylib::Vector3::DrawCubeWires (const ::Vector3 & size, ::Color color) const inline
Definition at line 305 of file Vector3.hpp.
{
        ::DrawCubeWiresV(*this, size, color);
    }
References DrawCubeWiresV().
DrawCubeWires() [2/2]
void raylib::Vector3::DrawCubeWires (float width, float height, float length, ::Color color) const inline
Definition at line 301 of file Vector3.hpp.
{
        ::DrawCubeWires(*this, width, height, length, color);
    }
References DrawCubeWires().
DrawCylinder()
void raylib::Vector3::DrawCylinder (float radiusTop, float radiusBottom, float height, int slices, ::Color color) const inline
Definition at line 321 of file Vector3.hpp.
{
        ::DrawCylinder(*this, radiusTop, radiusBottom, height, slices, color);
    }
References DrawCylinder().
DrawCylinderWires()
void raylib::Vector3::DrawCylinderWires (float radiusTop, float radiusBottom, float height, int slices, ::Color color) const inline
Definition at line 326 of file Vector3.hpp.
{
        ::DrawCylinderWires(*this, radiusTop, radiusBottom, height, slices, color);
    }
References DrawCylinderWires().
DrawLine3D()
void raylib::Vector3::DrawLine3D (const ::Vector3 & endPos, ::Color color) const inline
Definition at line 277 of file Vector3.hpp.
{
        ::DrawLine3D(*this, endPos, color);
    }
References DrawLine3D().
DrawPlane()
void raylib::Vector3::DrawPlane (const ::Vector2 & size, ::Color color) const inline
Definition at line 331 of file Vector3.hpp.
{
        ::DrawPlane(*this, size, color);
    }
References DrawPlane().
DrawPoint3D()
void raylib::Vector3::DrawPoint3D (::Color color) const inline
Definition at line 281 of file Vector3.hpp.
{
        ::DrawPoint3D(*this, color);
    }
References DrawPoint3D().
DrawSphere() [1/2]
void raylib::Vector3::DrawSphere (float radius, ::Color color) const inline
Definition at line 309 of file Vector3.hpp.
{
        ::DrawSphere(*this, radius, color);
    }
References DrawSphere().
DrawSphere() [2/2]
void raylib::Vector3::DrawSphere (float radius, int rings, int slices, ::Color color) const inline
Definition at line 313 of file Vector3.hpp.
{
        ::DrawSphereEx(*this, radius, rings, slices, color);
    }
References DrawSphereEx().
DrawSphereWires()
void raylib::Vector3::DrawSphereWires (float radius, int rings, int slices, ::Color color) const inline
Definition at line 317 of file Vector3.hpp.
{
        ::DrawSphereWires(*this, radius, rings, slices, color);
    }
References DrawSphereWires().
GetX()
float raylib::Vector3::GetX () const inline
Retrieves the x value for the object.
Returns
The x value of the object.
Definition at line 31 of file Vector3.hpp.
GetY()
float raylib::Vector3::GetY () const inline
Retrieves the y value for the object.
Returns
The y value of the object.
Definition at line 32 of file Vector3.hpp.
GetZ()
float raylib::Vector3::GetZ () const inline
Retrieves the z value for the object.
Returns
The z value of the object.
Definition at line 33 of file Vector3.hpp.
Length()
float raylib::Vector3::Length () const inline
Calculate vector length
Definition at line 212 of file Vector3.hpp.
{
        return Vector3Length(*this);
    }
References Vector3Length().
Lerp()
Vector3 raylib::Vector3::Lerp (const ::Vector3 & vector3, const float amount) const inline
Definition at line 228 of file Vector3.hpp.
{
        return Vector3Lerp(*this, vector3, amount);
    }
References Vector3Lerp().
Max()
Vector3 raylib::Vector3::Max (const ::Vector3 & vector3) const inline
Definition at line 260 of file Vector3.hpp.
{
        return Vector3Max(*this, vector3);
    }
References Vector3Max().
Min()
Vector3 raylib::Vector3::Min (const ::Vector3 & vector3) const inline
Definition at line 256 of file Vector3.hpp.
{
        return Vector3Min(*this, vector3);
    }
References Vector3Min().
Multiply()
Vector3 raylib::Vector3::Multiply (const ::Vector3 & vector3) const inline
Multiply vector by vector
Definition at line 116 of file Vector3.hpp.
{
        return Vector3Multiply(*this, vector3);
    }
References Vector3Multiply().
Negate()
Vector3 raylib::Vector3::Negate () const inline
Negate provided vector (invert direction)
Definition at line 102 of file Vector3.hpp.
{
        return Vector3Negate(*this);
    }
References Vector3Negate().
Normalize()
Vector3 raylib::Vector3::Normalize () const inline
Definition at line 216 of file Vector3.hpp.
{
        return Vector3Normalize(*this);
    }
References Vector3Normalize().
One()
static Vector3 raylib::Vector3::One () inline static
Definition at line 272 of file Vector3.hpp.
{
        return Vector3One();
    }
References Vector3One().
operator std::string()
raylib::Vector3::operator std::string () const inline
Definition at line 54 of file Vector3.hpp.
{
        return ToString();
    }
References ToString().
operator!=()
bool raylib::Vector3::operator!= (const ::Vector3 & other) const inline
Definition at line 46 of file Vector3.hpp.
{
        return !(*this == other);
    }
operator*() [1/2]
Vector3 raylib::Vector3::operator* (const ::Vector3 & vector3) const inline
Multiply vector by vector
Definition at line 123 of file Vector3.hpp.
{
        return Vector3Multiply(*this, vector3);
    }
References Vector3Multiply().
operator*() [2/2]
Vector3 raylib::Vector3::operator* (const float scaler) const inline
Multiply vector by scalar
Definition at line 146 of file Vector3.hpp.
{
        return Vector3Scale(*this, scaler);
    }
References Vector3Scale().
operator*=() [1/2]
Vector3 & raylib::Vector3::operator*= (const ::Vector3 & vector3) inline
Multiply vector by vector
Definition at line 130 of file Vector3.hpp.
{
        set(Vector3Multiply(*this, vector3));
        return *this;
    }
References set(), and Vector3Multiply().
operator*=() [2/2]
Vector3 & raylib::Vector3::operator*= (const float scaler) inline
Multiply vector by scalar
Definition at line 153 of file Vector3.hpp.
{
        set(Vector3Scale(*this, scaler));
        return *this;
    }
References set(), and Vector3Scale().
operator+()
Vector3 raylib::Vector3::operator+ (const ::Vector3 & vector3) const inline
Add two vectors
Definition at line 69 of file Vector3.hpp.
{
        return Vector3Add(*this, vector3);
    }
References Vector3Add().
operator+=()
Vector3 & raylib::Vector3::operator+= (const ::Vector3 & vector3) inline
Definition at line 73 of file Vector3.hpp.
{
        set(Vector3Add(*this, vector3));
        return *this;
    }
References set(), and Vector3Add().
operator-() [1/2]
Vector3 raylib::Vector3::operator- () const inline
Negate provided vector (invert direction)
Definition at line 109 of file Vector3.hpp.
{
        return Vector3Negate(*this);
    }
References Vector3Negate().
operator-() [2/2]
Vector3 raylib::Vector3::operator- (const ::Vector3 & vector3) const inline
Subtract two vectors.
Definition at line 89 of file Vector3.hpp.
{
        return Vector3Subtract(*this, vector3);
    }
References Vector3Subtract().
operator-=()
Vector3 & raylib::Vector3::operator-= (const ::Vector3 & vector3) inline
Definition at line 93 of file Vector3.hpp.
{
        set(Vector3Subtract(*this, vector3));
        return *this;
    }
References set(), and Vector3Subtract().
operator/() [1/2]
Vector3 raylib::Vector3::operator/ (const ::Vector3 & vector3) const inline
Divide vector by vector
Definition at line 169 of file Vector3.hpp.
{
        return Vector3Divide(*this, vector3);
    }
References Vector3Divide().
operator/() [2/2]
Vector3 raylib::Vector3::operator/ (const float div) const inline
Divide a vector by a value.
Definition at line 194 of file Vector3.hpp.
{
        return Divide(div);
    }
References Divide().
operator/=() [1/2]
Vector3 & raylib::Vector3::operator/= (const ::Vector3 & vector3) inline
Divide vector by vector
Definition at line 176 of file Vector3.hpp.
{
        x /= vector3.x;
        y /= vector3.y;
        z /= vector3.z;
        return *this;
    }
References Vector3::x, Vector3::y, and Vector3::z.
operator/=() [2/2]
Vector3 & raylib::Vector3::operator/= (const float div) inline
Divide a vector by a value.
Definition at line 201 of file Vector3.hpp.
{
        x /= div;
        y /= div;
        z /= div;
        return *this;
    }
References Vector3::x, Vector3::y, and Vector3::z.
operator=()
Vector3 & raylib::Vector3::operator= (const ::Vector3 & vector3) inline
Definition at line 35 of file Vector3.hpp.
{
        set(vector3);
        return *this;
    }
References set().
operator==()
bool raylib::Vector3::operator== (const ::Vector3 & other) const inline
Definition at line 40 of file Vector3.hpp.
{
        return x == other.x
            && y == other.y
            && z == other.z;
    }
References Vector3::x, Vector3::y, and Vector3::z.
OrthoNormalize()
void raylib::Vector3::OrthoNormalize (::Vector3 * vector3) inline
Definition at line 240 of file Vector3.hpp.
{
        Vector3OrthoNormalize(this, vector3);
    }
References Vector3OrthoNormalize().
Perpendicular()
Vector3 raylib::Vector3::Perpendicular () const inline
Definition at line 236 of file Vector3.hpp.
{
        return Vector3Perpendicular(*this);
    }
References Vector3Perpendicular().
Reflect()
Vector3 raylib::Vector3::Reflect (const ::Vector3 & normal) const inline
Definition at line 252 of file Vector3.hpp.
{
        return Vector3Reflect(*this, normal);
    }
References Vector3Reflect().
RotateByQuaternion()
Vector3 raylib::Vector3::RotateByQuaternion (const ::Quaternion & quaternion) const inline
Definition at line 248 of file Vector3.hpp.
{
        return Vector3RotateByQuaternion(*this, quaternion);
    }
References Vector3RotateByQuaternion().
Scale()
Vector3 raylib::Vector3::Scale (const float scaler) const inline
Multiply vector by scalar
Definition at line 139 of file Vector3.hpp.
{
        return Vector3Scale(*this, scaler);
    }
References Vector3Scale().
set()
void raylib::Vector3::set (const ::Vector3 & vec) inline protected
Definition at line 343 of file Vector3.hpp.
{
        x = vec.x;
        y = vec.y;
        z = vec.z;
    }
References Vector3::x, Vector3::y, and Vector3::z.
SetX()
void raylib::Vector3::SetX (float value) inline
Sets the x value for the object.
Parameters
value The value of which to set x to.
Definition at line 31 of file Vector3.hpp.
SetY()
void raylib::Vector3::SetY (float value) inline
Sets the y value for the object.
Parameters
value The value of which to set y to.
Definition at line 32 of file Vector3.hpp.
SetZ()
void raylib::Vector3::SetZ (float value) inline
Sets the z value for the object.
Parameters
value The value of which to set z to.
Definition at line 33 of file Vector3.hpp.
Subtract()
Vector3 raylib::Vector3::Subtract (const ::Vector3 & vector3) const inline
Subtract two vectors.
Definition at line 82 of file Vector3.hpp.
{
        return Vector3Subtract(*this, vector3);
    }
References Vector3Subtract().
ToString()
std::string raylib::Vector3::ToString () const inline
Definition at line 50 of file Vector3.hpp.
{
        return TextFormat("Vector3(%f, %f, %f)", x, y, z);
    }
References TextFormat(), Vector3::x, Vector3::y, and Vector3::z.
Transform()
Vector3 raylib::Vector3::Transform (const ::Matrix & matrix) const inline
Definition at line 244 of file Vector3.hpp.
{
        return Vector3Transform(*this, matrix);
    }
References Vector3Transform().
Zero()
static Vector3 raylib::Vector3::Zero () inline static
Definition at line 268 of file Vector3.hpp.
{
        return Vector3Zero();
    }
References Vector3Zero().
Member Data Documentation
x
float Vector3::x inherited
Definition at line 211 of file raylib.h.
y
float Vector3::y inherited
Definition at line 212 of file raylib.h.
z
float Vector3::z inherited
Definition at line 213 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Vector3.hpp