Techstorm-rivalry: toml::v3::table Class Reference
toml::v3::table Class Reference
#include <toml.h>
Public Types
using iterator = toml::table_iterator
using const_iterator = toml::const_table_iterator
Public Member Functions
table () noexcept
~table () noexcept
table (const table &)
table (table &&other) noexcept
table (std::initializer_list< impl::table_init_pair > kvps)
table & operator= (const table &)
table & operator= (table &&rhs) noexcept
node_type type () const noexcept final
bool is_homogeneous (node_type ntype) const noexcept final
bool is_homogeneous (node_type ntype, node *&first_nonmatch) noexcept final
bool is_homogeneous (node_type ntype, const node *&first_nonmatch) const noexcept final
template<typename ElemType = void>
bool is_homogeneous () const noexcept
bool is_table () const noexcept final
bool is_array () const noexcept final
bool is_array_of_tables () const noexcept final
bool is_value () const noexcept final
bool is_string () const noexcept final
bool is_integer () const noexcept final
bool is_floating_point () const noexcept final
bool is_number () const noexcept final
bool is_boolean () const noexcept final
bool is_date () const noexcept final
bool is_time () const noexcept final
bool is_date_time () const noexcept final
table * as_table () noexcept final
array * as_array () noexcept final
toml::value< std::string > * as_string () noexcept final
toml::value< int64_t > * as_integer () noexcept final
toml::value< double > * as_floating_point () noexcept final
toml::value< bool > * as_boolean () noexcept final
toml::value< date > * as_date () noexcept final
toml::value< time > * as_time () noexcept final
toml::value< date_time > * as_date_time () noexcept final
const table * as_table () const noexcept final
const array * as_array () const noexcept final
const toml::value< std::string > * as_string () const noexcept final
const toml::value< int64_t > * as_integer () const noexcept final
const toml::value< double > * as_floating_point () const noexcept final
const toml::value< bool > * as_boolean () const noexcept final
const toml::value< date > * as_date () const noexcept final
const toml::value< time > * as_time () const noexcept final
const toml::value< date_time > * as_date_time () const noexcept final
bool is_inline () const noexcept
void is_inline (bool val) noexcept
node * get (std::string_view key) noexcept
const node * get (std::string_view key) const noexcept
template<typename T >
impl::wrap_node< T > * get_as (std::string_view key) noexcept
template<typename T >
const impl::wrap_node< T > * get_as (std::string_view key) const noexcept
node & at (std::string_view key)
const node & at (std::string_view key) const
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cend () const noexcept
template<typename Func >
table & for_each (Func &&visitor) &noexcept(for_each_is_nothrow< Func &&, table & >)
template<typename Func >
table && for_each (Func &&visitor) &&noexcept(for_each_is_nothrow< Func &&, table && >)
template<typename Func >
const table & for_each (Func &&visitor) const &noexcept(for_each_is_nothrow< Func &&, const table & >)
template<typename Func >
const table && for_each (Func &&visitor) const &&noexcept(for_each_is_nothrow< Func &&, const table && >)
bool empty () const noexcept
size_t size () const noexcept
iterator lower_bound (std::string_view key) noexcept
const_iterator lower_bound (std::string_view key) const noexcept
iterator find (std::string_view key) noexcept
const_iterator find (std::string_view key) const noexcept
bool contains (std::string_view key) const noexcept
iterator erase (iterator pos) noexcept
iterator erase (const_iterator pos) noexcept
iterator erase (const_iterator begin, const_iterator end) noexcept
size_t erase (std::string_view key) noexcept
table & prune (bool recursive=true) &noexcept
table && prune (bool recursive=true) &&noexcept
void clear () noexcept
template<typename ValueType = void, typename KeyType , typename... ValueArgs, typename std::enable_if<((is_key_or_convertible< KeyType && >||impl::is_wide_string< KeyType >)), int >::type = 0>
iterator emplace_hint (const_iterator hint, KeyType &&key, ValueArgs &&... args)
template<typename KeyType , typename ValueType , typename std::enable_if<((is_key_or_convertible< KeyType && >||impl::is_wide_string< KeyType >)), int >::type = 0>
std::pair< iterator, bool > insert (KeyType &&key, ValueType &&val, value_flags flags=preserve_source_value_flags)
template<typename Iter , typename std::enable_if<((!is_key_or_convertible< Iter > &&!impl::is_wide_string< Iter >)), int >::type = 0>
void insert (Iter begin, Iter end, value_flags flags=preserve_source_value_flags)
template<typename KeyType , typename ValueType , typename std::enable_if<((is_key_or_convertible< KeyType && >||impl::is_wide_string< KeyType >)), int >::type = 0>
std::pair< iterator, bool > insert_or_assign (KeyType &&key, ValueType &&val, value_flags flags=preserve_source_value_flags)
template<typename ValueType = void, typename KeyType , typename... ValueArgs, typename std::enable_if<((is_key_or_convertible< KeyType && >||impl::is_wide_string< KeyType >)), int >::type = 0>
std::pair< iterator, bool > emplace (KeyType &&key, ValueArgs &&... args)
node_view< node > operator[] (std::string_view key) noexcept
node_view< const node > operator[] (std::string_view key) const noexcept
template<typename T >
bool is () const noexcept
template<typename T >
impl::wrap_node< T > * as () noexcept
template<typename T >
const impl::wrap_node< T > * as () const noexcept
template<typename T >
optional< T > value_exact () const noexcept(impl::value_retrieval_is_nothrow< T >)
template<typename T >
optional< T > value () const noexcept(impl::value_retrieval_is_nothrow< T >)
template<typename T >
auto value_or (T &&default_value) const noexcept(impl::value_retrieval_is_nothrow< T >)
template<typename T >
decltype(auto) ref () &noexcept
template<typename T >
decltype(auto) ref () &&noexcept
template<typename T >
decltype(auto) ref () const &noexcept
template<typename T >
decltype(auto) ref () const &&noexcept
const source_region & source () const noexcept
template<typename Func >
decltype(auto) visit (Func &&visitor) &noexcept(visit_is_nothrow< Func &&, node & >)
template<typename Func >
decltype(auto) visit (Func &&visitor) &&noexcept(visit_is_nothrow< Func &&, node && >)
template<typename Func >
decltype(auto) visit (Func &&visitor) const &noexcept(visit_is_nothrow< Func &&, const node & >)
template<typename Func >
decltype(auto) visit (Func &&visitor) const &&noexcept(visit_is_nothrow< Func &&, const node && >)
operator node_view< node > () noexcept
operator node_view< const node > () const noexcept
node_view< node > at_path (std::string_view path) noexcept
node_view< const node > at_path (std::string_view path) const noexcept
node_view< node > at_path (const toml::path &path) noexcept
node_view< const node > at_path (const toml::path &path) const noexcept
node_view< node > operator[] (const toml::path &path) noexcept
node_view< const node > operator[] (const toml::path &path) const noexcept
Protected Types
template<typename T , typename N >
using ref_cast_type_
template<typename T , typename N >
using ref_cast_type
Protected Member Functions
template<typename T >
ref_cast_type< T, node & > ref_cast () &noexcept
template<typename T >
ref_cast_type< T, node && > ref_cast () &&noexcept
template<typename T >
ref_cast_type< T, const node & > ref_cast () const &noexcept
template<typename T >
ref_cast_type< T, const node && > ref_cast () const &&noexcept
Friends
bool operator== (const table &lhs, const table &rhs) noexcept
bool operator!= (const table &lhs, const table &rhs) noexcept
std::ostream & operator<< (std::ostream &lhs, const table &rhs)
Detailed Description
Definition at line 7291 of file toml.h.
Member Typedef Documentation
const_iterator
using toml::v3::table::const_iterator = toml::const_table_iterator
Definition at line 7649 of file toml.h.
iterator
using toml::v3::table::iterator = toml::table_iterator
Definition at line 7647 of file toml.h.
ref_cast_type
template<typename T , typename N > using toml::v3::node::ref_cast_type protected inherited
Initial value:
 std::conditional_t<
            std::is_reference_v<N>,
            ref_cast_type_<T, N>,
            ref_cast_type_<T, std::add_lvalue_reference_t<N>>
            >
Definition at line 3458 of file toml.h.
ref_cast_type_
template<typename T , typename N > using toml::v3::node::ref_cast_type_ protected inherited
Initial value:
 std::conditional_t<
            std::is_reference_v<T>,
            impl::copy_ref<impl::copy_cv<impl::wrap_node<T>, std::remove_reference_t<N>>, T>,
            impl::copy_cvref<impl::wrap_node<T>, N>
            >
Definition at line 3451 of file toml.h.
Constructor & Destructor Documentation
table() [1/4]
toml::v3::table::table () inline noexcept
Definition at line 11626 of file toml.h.
    {
#if TOML_LIFETIME_HOOKS
        TOML_TABLE_CREATED;
#endif
    }
~table()
toml::v3::table::~table () inline noexcept
Definition at line 11634 of file toml.h.
    {
#if TOML_LIFETIME_HOOKS
        TOML_TABLE_DESTROYED;
#endif
    }
table() [2/4]
toml::v3::table::table (const table & other) inline
Definition at line 11665 of file toml.h.
        : node(other),
          inline_{ other.inline_ }
    {
        for (auto&& [k, v] : other.map_)
            map_.emplace_hint(map_.end(), k, impl::make_node(*v));
#if TOML_LIFETIME_HOOKS
        TOML_TABLE_CREATED;
#endif
    }
References emplace_hint(), and toml::v3::impl::make_node().
table() [3/4]
toml::v3::table::table (table && other) inline noexcept
Definition at line 11678 of file toml.h.
        : node(std::move(other)),
          map_{ std::move(other.map_) },
          inline_{ other.inline_ }
    {
#if TOML_LIFETIME_HOOKS
        TOML_TABLE_CREATED;
#endif
    }
table() [4/4]
toml::v3::table::table (std::initializer_list< impl::table_init_pair > kvps) inline explicit
Definition at line 7326 of file toml.h.
            : table(kvps.begin(), kvps.end())
        {}
Member Function Documentation
as() [1/2]
template<typename T > const impl::wrap_node< T > * toml::v3::node::as () const inline noexcept inherited
Definition at line 3676 of file toml.h.
        {
            using unwrapped_type = impl::unwrap_node<impl::remove_cvref<T>>;
            static_assert(toml::is_value<unwrapped_type> || toml::is_container<unwrapped_type>,
                          "The template type argument of node::as() must be one of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
            if constexpr (std::is_same_v<unwrapped_type, table>)
                return as_table();
            else if constexpr (std::is_same_v<unwrapped_type, array>)
                return as_array();
            else if constexpr (std::is_same_v<unwrapped_type, std::string>)
                return as_string();
            else if constexpr (std::is_same_v<unwrapped_type, int64_t>)
                return as_integer();
            else if constexpr (std::is_same_v<unwrapped_type, double>)
                return as_floating_point();
            else if constexpr (std::is_same_v<unwrapped_type, bool>)
                return as_boolean();
            else if constexpr (std::is_same_v<unwrapped_type, date>)
                return as_date();
            else if constexpr (std::is_same_v<unwrapped_type, time>)
                return as_time();
            else if constexpr (std::is_same_v<unwrapped_type, date_time>)
                return as_date_time();
        }
References TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
as() [2/2]
template<typename T > impl::wrap_node< T > * toml::v3::node::as () inline noexcept inherited
Definition at line 3648 of file toml.h.
        {
            using unwrapped_type = impl::unwrap_node<impl::remove_cvref<T>>;
            static_assert(toml::is_value<unwrapped_type> || toml::is_container<unwrapped_type>,
                          "The template type argument of node::as() must be one of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
            if constexpr (std::is_same_v<unwrapped_type, table>)
                return as_table();
            else if constexpr (std::is_same_v<unwrapped_type, array>)
                return as_array();
            else if constexpr (std::is_same_v<unwrapped_type, std::string>)
                return as_string();
            else if constexpr (std::is_same_v<unwrapped_type, int64_t>)
                return as_integer();
            else if constexpr (std::is_same_v<unwrapped_type, double>)
                return as_floating_point();
            else if constexpr (std::is_same_v<unwrapped_type, bool>)
                return as_boolean();
            else if constexpr (std::is_same_v<unwrapped_type, date>)
                return as_date();
            else if constexpr (std::is_same_v<unwrapped_type, time>)
                return as_time();
            else if constexpr (std::is_same_v<unwrapped_type, date_time>)
                return as_date_time();
        }
References TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
as_array() [1/2]
const array * toml::v3::table::as_array () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7498 of file toml.h.
        {
            return nullptr;
        }
as_array() [2/2]
array * toml::v3::table::as_array () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7444 of file toml.h.
        {
            return nullptr;
        }
as_boolean() [1/2]
const toml::value< bool > * toml::v3::table::as_boolean () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7522 of file toml.h.
        {
            return nullptr;
        }
as_boolean() [2/2]
toml::value< bool > * toml::v3::table::as_boolean () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7468 of file toml.h.
        {
            return nullptr;
        }
as_date() [1/2]
const toml::value< date > * toml::v3::table::as_date () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7528 of file toml.h.
        {
            return nullptr;
        }
as_date() [2/2]
toml::value< date > * toml::v3::table::as_date () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7474 of file toml.h.
        {
            return nullptr;
        }
as_date_time() [1/2]
const toml::value< date_time > * toml::v3::table::as_date_time () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7540 of file toml.h.
        {
            return nullptr;
        }
as_date_time() [2/2]
toml::value< date_time > * toml::v3::table::as_date_time () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7486 of file toml.h.
        {
            return nullptr;
        }
as_floating_point() [1/2]
const toml::value< double > * toml::v3::table::as_floating_point () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7516 of file toml.h.
        {
            return nullptr;
        }
as_floating_point() [2/2]
toml::value< double > * toml::v3::table::as_floating_point () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7462 of file toml.h.
        {
            return nullptr;
        }
as_integer() [1/2]
const toml::value< int64_t > * toml::v3::table::as_integer () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7510 of file toml.h.
        {
            return nullptr;
        }
as_integer() [2/2]
toml::value< int64_t > * toml::v3::table::as_integer () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7456 of file toml.h.
        {
            return nullptr;
        }
as_string() [1/2]
const toml::value< std::string > * toml::v3::table::as_string () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7504 of file toml.h.
        {
            return nullptr;
        }
as_string() [2/2]
toml::value< std::string > * toml::v3::table::as_string () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7450 of file toml.h.
        {
            return nullptr;
        }
as_table() [1/2]
const table * toml::v3::table::as_table () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7492 of file toml.h.
        {
            return this;
        }
as_table() [2/2]
table * toml::v3::table::as_table () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7438 of file toml.h.
        {
            return this;
        }
as_time() [1/2]
const toml::value< time > * toml::v3::table::as_time () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7534 of file toml.h.
        {
            return nullptr;
        }
as_time() [2/2]
toml::value< time > * toml::v3::table::as_time () inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7480 of file toml.h.
        {
            return nullptr;
        }
at() [1/2]
node & toml::v3::table::at (std::string_view key) inline
Definition at line 11777 of file toml.h.
    {
        auto n = get(key);
#if TOML_COMPILER_HAS_EXCEPTIONS
        if (!n)
        {
            auto err = "key '"s;
            err.append(key);
            err.append("' not found in table"sv);
            throw std::out_of_range{ err };
        }
#else
        TOML_ASSERT_ASSUME(n && "key not found in table!");
#endif
        return *n;
    }
References get(), and TOML_ASSERT_ASSUME.
at() [2/2]
const node & toml::v3::table::at (std::string_view key) const inline
Definition at line 7626 of file toml.h.
        {
            return const_cast<table&>(*this).at(key);
        }
References at().
at_path() [1/4]
node_view< const node > toml::v3::node::at_path (const toml::path & path) const noexcept inherited
at_path() [2/4]
node_view< node > toml::v3::node::at_path (const toml::path & path) noexcept inherited
at_path() [3/4]
node_view< const node > toml::v3::node::at_path (std::string_view path) const inline noexcept inherited
Definition at line 10363 of file toml.h.
    {
        return toml::at_path(*this, path);
    }
at_path() [4/4]
node_view< node > toml::v3::node::at_path (std::string_view path) inline noexcept inherited
Definition at line 10357 of file toml.h.
    {
        return toml::at_path(*this, path);
    }
begin() [1/2]
const_iterator toml::v3::table::begin () const inline noexcept
Definition at line 7658 of file toml.h.
        {
            return const_iterator{ map_.cbegin() };
        }
begin() [2/2]
iterator toml::v3::table::begin () inline noexcept
Definition at line 7652 of file toml.h.
        {
            return iterator{ map_.begin() };
        }
cbegin()
const_iterator toml::v3::table::cbegin () const inline noexcept
Definition at line 7664 of file toml.h.
        {
            return const_iterator{ map_.cbegin() };
        }
cend()
const_iterator toml::v3::table::cend () const inline noexcept
Definition at line 7682 of file toml.h.
        {
            return const_iterator{ map_.cend() };
        }
clear()
void toml::v3::table::clear () inline noexcept
Definition at line 11881 of file toml.h.
    {
        map_.clear();
    }
contains()
bool toml::v3::table::contains (std::string_view key) const inline noexcept
Definition at line 7896 of file toml.h.
          {
              return get(key) != nullptr;
          }
emplace()
template<typename ValueType = void, typename KeyType , typename... ValueArgs, typename std::enable_if<((is_key_or_convertible< KeyType && >||impl::is_wide_string< KeyType >)), int >::type = 0> std::pair< iterator, bool > toml::v3::table::emplace (KeyType && key, ValueArgs &&... args) inline
Definition at line 8155 of file toml.h.
          {
              static_assert(!impl::is_wide_string<KeyType> || TOML_ENABLE_WINDOWS_COMPAT,
                            "Emplacement using wide-character keys is only supported on Windows with "
                            "TOML_ENABLE_WINDOWS_COMPAT enabled.");
              using raw_value_type = impl::remove_cvref<ValueType>;
              using value_type = std::
                  conditional_t<std::is_void_v<raw_value_type>, impl::emplaced_type_of<ValueArgs&&...>, raw_value_type>;
              if constexpr (impl::is_wide_string<KeyType>)
              {
  #if TOML_ENABLE_WINDOWS_COMPAT
                  return emplace<value_type>(impl::narrow(static_cast<KeyType&&>(key)),
                                             static_cast<ValueArgs&&>(args)...);
  #else
                  static_assert(impl::dependent_false<KeyType>, "Evaluated unreachable branch!");
  #endif
              }
              else
              {
                  using unwrapped_type = impl::remove_cvref<impl::unwrap_node<value_type>>;
                  static_assert((impl::is_native<unwrapped_type> || impl::is_one_of<unwrapped_type, table, array>),
                                "ValueType argument of table::emplace() must be one "
                                "of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
                  const auto key_view = std::string_view{ key };
                  auto ipos = get_lower_bound(key_view);
                  if (ipos == map_.end() || ipos->first != key_view)
                  {
                      ipos = insert_with_hint(
                          const_iterator{ ipos },
                          toml::key{ static_cast<KeyType&&>(key) },
                          impl::node_ptr{ new impl::wrap_node<unwrapped_type>{ static_cast<ValueArgs&&>(args)... } });
                      return { iterator{ ipos }, true };
                  }
                  return { iterator{ ipos }, false };
              }
          }
References TOML_ENABLE_WINDOWS_COMPAT, and TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
emplace_hint()
template<typename ValueType = void, typename KeyType , typename... ValueArgs, typename std::enable_if<((is_key_or_convertible< KeyType && >||impl::is_wide_string< KeyType >)), int >::type = 0> iterator toml::v3::table::emplace_hint (const_iterator hint, KeyType && key, ValueArgs &&... args) inline
Definition at line 7988 of file toml.h.
          {
              static_assert(!impl::is_wide_string<KeyType> || TOML_ENABLE_WINDOWS_COMPAT,
                            "Emplacement using wide-character keys is only supported on Windows with "
                            "TOML_ENABLE_WINDOWS_COMPAT enabled.");
              using raw_value_type = impl::remove_cvref<ValueType>;
              using value_type = std::
                  conditional_t<std::is_void_v<raw_value_type>, impl::emplaced_type_of<ValueArgs&&...>, raw_value_type>;
              if constexpr (impl::is_wide_string<KeyType>)
              {
  #if TOML_ENABLE_WINDOWS_COMPAT
                  return emplace_hint<value_type>(hint,
                                                  impl::narrow(static_cast<KeyType&&>(key)),
                                                  static_cast<ValueArgs&&>(args)...);
  #else
                  static_assert(impl::dependent_false<KeyType>, "Evaluated unreachable branch!");
  #endif
              }
              else
              {
                  static constexpr auto moving_node_ptr = std::is_same_v<value_type, impl::node_ptr> //
                                                       && sizeof...(ValueArgs) == 1u                   //
                                                       && impl::first_is_same<impl::node_ptr&&, ValueArgs&&...>;
                  using unwrapped_type = impl::remove_cvref<impl::unwrap_node<value_type>>;
                  static_assert(moving_node_ptr                                     //
                                    || impl::is_native<unwrapped_type>              //
                                    || impl::is_one_of<unwrapped_type, table, array>, //
                                "ValueType argument of table::emplace_hint() must be one "
                                "of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
                  map_iterator ipos = insert_with_hint(hint, toml::key{ static_cast<KeyType&&>(key) }, nullptr);
                  // if second is nullptr then we successully claimed the key and inserted the empty sentinel,
                  // so now we have to construct the actual value
                  if (!ipos->second)
                  {
                      if constexpr (moving_node_ptr)
                          ipos->second = std::move(static_cast<ValueArgs&&>(args)...);
                      else
                      {
  #if TOML_COMPILER_HAS_EXCEPTIONS
                          try
{
  #endif
                              ipos->second.reset(
                                  new impl::wrap_node<unwrapped_type>{ static_cast<ValueArgs&&>(args)... });
  #if TOML_COMPILER_HAS_EXCEPTIONS
                          }
                          catch (...)
{
                              erase(const_map_iterator{ ipos }); // strong exception guarantee
                              throw;
                          }
  #endif
                      }
                  }
                  return iterator{ ipos };
              }
          }
References TOML_ENABLE_WINDOWS_COMPAT, and TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
empty()
bool toml::v3::table::empty () const inline noexcept
Definition at line 7834 of file toml.h.
          {
              return map_.empty();
          }
end() [1/2]
const_iterator toml::v3::table::end () const inline noexcept
Definition at line 7676 of file toml.h.
        {
            return const_iterator{ map_.cend() };
        }
end() [2/2]
iterator toml::v3::table::end () inline noexcept
Definition at line 7670 of file toml.h.
        {
            return iterator{ map_.end() };
        }
erase() [1/4]
iterator toml::v3::table::erase (const_iterator begin, const_iterator end) inline noexcept
Definition at line 7946 of file toml.h.
          {
              return iterator{ erase(const_map_iterator{ begin }, const_map_iterator{ end }) };
          }
erase() [2/4]
iterator toml::v3::table::erase (const_iterator pos) inline noexcept
Definition at line 7941 of file toml.h.
          {
              return iterator{ erase(const_map_iterator{ pos }) };
          }
erase() [3/4]
iterator toml::v3::table::erase (iterator pos) inline noexcept
Definition at line 7936 of file toml.h.
          {
              return iterator{ erase(const_map_iterator{ pos }) };
          }
erase() [4/4]
size_t toml::v3::table::erase (std::string_view key) inline noexcept
Definition at line 11834 of file toml.h.
    {
        if (auto it = map_.find(key); it != map_.end())
        {
            map_.erase(it);
            return size_t{ 1 };
        }
        return size_t{};
    }
find() [1/2]
table::const_iterator toml::v3::table::find (std::string_view key) const inline noexcept
Definition at line 11816 of file toml.h.
    {
        return const_iterator{ map_.find(key) };
    }
find() [2/2]
table::iterator toml::v3::table::find (std::string_view key) inline noexcept
Definition at line 11809 of file toml.h.
    {
        return iterator{ map_.find(key) };
    }
for_each() [1/4]
template<typename Func > table && toml::v3::table::for_each (Func && visitor) && inline noexcept
Definition at line 7813 of file toml.h.
          {
              do_for_each(static_cast<Func&&>(visitor), static_cast<table&&>(*this));
              return static_cast<table&&>(*this);
          }
for_each() [2/4]
template<typename Func > table & toml::v3::table::for_each (Func && visitor) & inline noexcept
Definition at line 7806 of file toml.h.
          {
              do_for_each(static_cast<Func&&>(visitor), *this);
              return *this;
          }
for_each() [3/4]
template<typename Func > const table && toml::v3::table::for_each (Func && visitor) const && inline noexcept
Definition at line 7827 of file toml.h.
          {
              do_for_each(static_cast<Func&&>(visitor), static_cast<const table&&>(*this));
              return static_cast<const table&&>(*this);
          }
for_each() [4/4]
template<typename Func > const table & toml::v3::table::for_each (Func && visitor) const & inline noexcept
Definition at line 7820 of file toml.h.
          {
              do_for_each(static_cast<Func&&>(visitor), *this);
              return *this;
          }
get() [1/2]
const node * toml::v3::table::get (std::string_view key) const inline noexcept
Definition at line 7561 of file toml.h.
        {
            return const_cast<table&>(*this).get(key);
        }
References get().
get() [2/2]
node * toml::v3::table::get (std::string_view key) inline noexcept
Definition at line 11769 of file toml.h.
    {
        if (auto it = map_.find(key); it != map_.end())
            return it->second.get();
        return nullptr;
    }
get_as() [1/2]
template<typename T > const impl::wrap_node< T > * toml::v3::table::get_as (std::string_view key) const inline noexcept
Definition at line 7595 of file toml.h.
        {
            return const_cast<table&>(*this).template get_as<T>(key);
        }
get_as() [2/2]
template<typename T > impl::wrap_node< T > * toml::v3::table::get_as (std::string_view key) inline noexcept
Definition at line 7587 of file toml.h.
        {
            const auto n = this->get(key);
            return n ? n->template as<T>() : nullptr;
        }
insert() [1/2]
template<typename Iter , typename std::enable_if<((!is_key_or_convertible< Iter > &&!impl::is_wide_string< Iter >)), int >::type = 0> void toml::v3::table::insert (Iter begin, Iter end, value_flags flags = preserve_source_value_flags) inline
Definition at line 8092 of file toml.h.
          {
              if (begin == end)
                  return;
              for (auto it = begin; it != end; it++)
              {
                  if constexpr (std::is_rvalue_reference_v<decltype(*it)>)
                      insert(std::move((*it).first), std::move((*it).second), flags);
                  else
                      insert((*it).first, (*it).second, flags);
              }
          }
insert() [2/2]
template<typename KeyType , typename ValueType , typename std::enable_if<((is_key_or_convertible< KeyType && >||impl::is_wide_string< KeyType >)), int >::type = 0> std::pair< iterator, bool > toml::v3::table::insert (KeyType && key, ValueType && val, value_flags flags = preserve_source_value_flags) inline
Definition at line 8054 of file toml.h.
          {
              static_assert(!impl::is_wide_string<KeyType> || TOML_ENABLE_WINDOWS_COMPAT,
                            "Insertion using wide-character keys is only supported on Windows with "
                            "TOML_ENABLE_WINDOWS_COMPAT enabled.");
              if constexpr (is_node_view<ValueType>)
              {
                  if (!val)
                      return { end(), false };
              }
              if constexpr (impl::is_wide_string<KeyType>)
              {
  #if TOML_ENABLE_WINDOWS_COMPAT
                  return insert(impl::narrow(static_cast<KeyType&&>(key)), static_cast<ValueType&&>(val), flags);
  #else
                  static_assert(impl::dependent_false<KeyType>, "Evaluated unreachable branch!");
  #endif
              }
              else
              {
                  const auto key_view = std::string_view{ key };
                  map_iterator ipos = get_lower_bound(key_view);
                  if (ipos == map_.end() || ipos->first != key_view)
                  {
                      ipos = insert_with_hint(const_iterator{ ipos },
                                              toml::key{ static_cast<KeyType&&>(key) },
                                              impl::make_node(static_cast<ValueType&&>(val), flags));
                      return { iterator{ ipos }, true };
                  }
                  return { iterator{ ipos }, false };
              }
          }
References TOML_ENABLE_WINDOWS_COMPAT.
insert_or_assign()
template<typename KeyType , typename ValueType , typename std::enable_if<((is_key_or_convertible< KeyType && >||impl::is_wide_string< KeyType >)), int >::type = 0> std::pair< iterator, bool > toml::v3::table::insert_or_assign (KeyType && key, ValueType && val, value_flags flags = preserve_source_value_flags) inline
Definition at line 8108 of file toml.h.
          {
              static_assert(!impl::is_wide_string<KeyType> || TOML_ENABLE_WINDOWS_COMPAT,
                            "Insertion using wide-character keys is only supported on Windows with "
                            "TOML_ENABLE_WINDOWS_COMPAT enabled.");
              if constexpr (is_node_view<ValueType>)
              {
                  if (!val)
                      return { end(), false };
              }
              if constexpr (impl::is_wide_string<KeyType>)
              {
  #if TOML_ENABLE_WINDOWS_COMPAT
                  return insert_or_assign(impl::narrow(static_cast<KeyType&&>(key)),
                                          static_cast<ValueType&&>(val),
                                          flags);
  #else
                  static_assert(impl::dependent_false<KeyType>, "Evaluated unreachable branch!");
  #endif
              }
              else
              {
                  const auto key_view = std::string_view{ key };
                  map_iterator ipos = get_lower_bound(key_view);
                  if (ipos == map_.end() || ipos->first != key_view)
                  {
                      ipos = insert_with_hint(const_iterator{ ipos },
                                              toml::key{ static_cast<KeyType&&>(key) },
                                              impl::make_node(static_cast<ValueType&&>(val), flags));
                      return { iterator{ ipos }, true };
                  }
                  else
                  {
                      (*ipos).second = impl::make_node(static_cast<ValueType&&>(val), flags);
                      return { iterator{ ipos }, false };
                  }
              }
          }
References TOML_ENABLE_WINDOWS_COMPAT.
is()
template<typename T > bool toml::v3::node::is () const inline noexcept inherited
Definition at line 3566 of file toml.h.
        {
            using type = impl::remove_cvref<impl::unwrap_node<T>>;
            static_assert(toml::is_value<type> || toml::is_container<type>,
                          "The template type argument of node::is() must be one of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
            if constexpr (std::is_same_v<type, table>)
                return is_table();
            else if constexpr (std::is_same_v<type, array>)
                return is_array();
            else if constexpr (std::is_same_v<type, std::string>)
                return is_string();
            else if constexpr (std::is_same_v<type, int64_t>)
                return is_integer();
            else if constexpr (std::is_same_v<type, double>)
                return is_floating_point();
            else if constexpr (std::is_same_v<type, bool>)
                return is_boolean();
            else if constexpr (std::is_same_v<type, date>)
                return is_date();
            else if constexpr (std::is_same_v<type, time>)
                return is_time();
            else if constexpr (std::is_same_v<type, date_time>)
                return is_date_time();
        }
References TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
is_array()
bool toml::v3::table::is_array () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7372 of file toml.h.
        {
            return false;
        }
is_array_of_tables()
bool toml::v3::table::is_array_of_tables () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7378 of file toml.h.
        {
            return false;
        }
is_boolean()
bool toml::v3::table::is_boolean () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7414 of file toml.h.
        {
            return false;
        }
is_date()
bool toml::v3::table::is_date () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7420 of file toml.h.
        {
            return false;
        }
is_date_time()
bool toml::v3::table::is_date_time () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7432 of file toml.h.
        {
            return false;
        }
is_floating_point()
bool toml::v3::table::is_floating_point () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7402 of file toml.h.
        {
            return false;
        }
is_homogeneous() [1/4]
template<typename ElemType = void> bool toml::v3::table::is_homogeneous () const inline noexcept
Definition at line 7356 of file toml.h.
        {
            using type = impl::remove_cvref<impl::unwrap_node<ElemType>>;
            static_assert(std::is_void_v<type> || toml::is_value<type> || toml::is_container<type>,
                          "The template type argument of table::is_homogeneous() must be void or one "
                          "of:" TOML_SA_UNWRAPPED_NODE_TYPE_LIST);
            return is_homogeneous(impl::node_type_of<type>);
        }
References TOML_SA_UNWRAPPED_NODE_TYPE_LIST.
is_homogeneous() [2/4]
bool toml::v3::table::is_homogeneous (node_type ntype) const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 11716 of file toml.h.
    {
        if (map_.empty())
            return false;
        if (ntype == node_type::none)
            ntype = map_.cbegin()->second->type();
        for (auto&& [k, v] : map_)
        {
            TOML_UNUSED(k);
            if (v->type() != ntype)
                return false;
        }
        return true;
    }
References toml::v3::none, and TOML_UNUSED.
is_homogeneous() [3/4]
bool toml::v3::table::is_homogeneous (node_type ntype, const node *& first_nonmatch) const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 11759 of file toml.h.
    {
        node* fnm = nullptr;
        const auto result = const_cast<table&>(*this).is_homogeneous(ntype, fnm);
        first_nonmatch = fnm;
        return result;
    }
References is_homogeneous().
is_homogeneous() [4/4]
bool toml::v3::table::is_homogeneous (node_type ntype, node *& first_nonmatch) inline final virtual noexcept
Implements toml::v3::node.
Definition at line 11736 of file toml.h.
    {
        if (map_.empty())
        {
            first_nonmatch = {};
            return false;
        }
        if (ntype == node_type::none)
            ntype = map_.cbegin()->second->type();
        for (const auto& [k, v] : map_)
        {
            TOML_UNUSED(k);
            if (v->type() != ntype)
            {
                first_nonmatch = v.get();
                return false;
            }
        }
        return true;
    }
References toml::v3::none, and TOML_UNUSED.
is_inline() [1/2]
bool toml::v3::table::is_inline () const inline noexcept
Definition at line 7546 of file toml.h.
        {
            return inline_;
        }
is_inline() [2/2]
void toml::v3::table::is_inline (bool val) inline noexcept
Definition at line 7551 of file toml.h.
        {
            inline_ = val;
        }
is_integer()
bool toml::v3::table::is_integer () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7396 of file toml.h.
        {
            return false;
        }
is_number()
bool toml::v3::table::is_number () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7408 of file toml.h.
        {
            return false;
        }
is_string()
bool toml::v3::table::is_string () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7390 of file toml.h.
        {
            return false;
        }
is_table()
bool toml::v3::table::is_table () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7366 of file toml.h.
        {
            return true;
        }
is_time()
bool toml::v3::table::is_time () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7426 of file toml.h.
        {
            return false;
        }
is_value()
bool toml::v3::table::is_value () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7384 of file toml.h.
        {
            return false;
        }
lower_bound() [1/2]
const_iterator toml::v3::table::lower_bound (std::string_view key) const inline noexcept
Definition at line 7860 of file toml.h.
          {
              return const_iterator{ const_cast<table&>(*this).get_lower_bound(key) };
          }
lower_bound() [2/2]
iterator toml::v3::table::lower_bound (std::string_view key) inline noexcept
Definition at line 7854 of file toml.h.
          {
              return iterator{ get_lower_bound(key) };
          }
operator node_view< const node >()
toml::v3::node::operator node_view< const node > () const inline explicit noexcept inherited
Definition at line 4489 of file toml.h.
    {
        return node_view<const node>{ this };
    }
operator node_view< node >()
toml::v3::node::operator node_view< node > () inline explicit noexcept inherited
Definition at line 4484 of file toml.h.
    {
        return node_view<node>{ this };
    }
operator=() [1/2]
table & toml::v3::table::operator= (const table & rhs) inline
Definition at line 11689 of file toml.h.
    {
        if (&rhs != this)
        {
            node::operator=(rhs);
            map_.clear();
            for (auto&& [k, v] : rhs.map_)
                map_.emplace_hint(map_.end(), k, impl::make_node(*v));
            inline_ = rhs.inline_;
        }
        return *this;
    }
References toml::v3::impl::make_node(), and toml::v3::node::operator=().
operator=() [2/2]
table & toml::v3::table::operator= (table && rhs) inline noexcept
Definition at line 11703 of file toml.h.
    {
        if (&rhs != this)
        {
            node::operator=(std::move(rhs));
            map_ = std::move(rhs.map_);
            inline_ = rhs.inline_;
        }
        return *this;
    }
References toml::v3::node::operator=().
operator[]() [1/4]
node_view< const node > toml::v3::node::operator[] (const toml::path & path) const noexcept inherited
operator[]() [2/4]
node_view< node > toml::v3::node::operator[] (const toml::path & path) noexcept inherited
operator[]() [3/4]
node_view< const node > toml::v3::table::operator[] (std::string_view key) const inline noexcept
Definition at line 8204 of file toml.h.
          {
              return node_view<const node>{ get(key) };
          }
operator[]() [4/4]
node_view< node > toml::v3::table::operator[] (std::string_view key) inline noexcept
Definition at line 8198 of file toml.h.
          {
              return node_view<node>{ get(key) };
          }
prune() [1/2]
table && toml::v3::table::prune (bool recursive = true) && inline noexcept
Definition at line 7969 of file toml.h.
          {
              return static_cast<toml::table&&>(this->prune(recursive));
          }
prune() [2/2]
table & toml::v3::table::prune (bool recursive = true) & inline noexcept
Definition at line 11845 of file toml.h.
    {
        if (map_.empty())
            return *this;
        for (auto it = map_.begin(); it != map_.end();)
        {
            if (auto arr = it->second->as_array())
            {
                if (recursive)
                    arr->prune(true);
                if (arr->empty())
                {
                    it = map_.erase(it);
                    continue;
                }
            }
            else if (auto tbl = it->second->as_table())
            {
                if (recursive)
                    tbl->prune(true);
                if (tbl->empty())
                {
                    it = map_.erase(it);
                    continue;
                }
            }
            it++;
        }
        return *this;
    }
References prune().
ref() [1/4]
template<typename T > decltype(auto) toml::v3::node::ref () && inline noexcept inherited
Definition at line 3723 of file toml.h.
        {
            return do_ref<T>(std::move(*this));
        }
ref() [2/4]
template<typename T > decltype(auto) toml::v3::node::ref () & inline noexcept inherited
Definition at line 3716 of file toml.h.
        {
            return do_ref<T>(*this);
        }
ref() [3/4]
template<typename T > decltype(auto) toml::v3::node::ref () const && inline noexcept inherited
Definition at line 3737 of file toml.h.
        {
            return do_ref<T>(std::move(*this));
        }
ref() [4/4]
template<typename T > decltype(auto) toml::v3::node::ref () const & inline noexcept inherited
Definition at line 3730 of file toml.h.
        {
            return do_ref<T>(*this);
        }
ref_cast() [1/4]
template<typename T > ref_cast_type< T, node && > toml::v3::node::ref_cast () && inline protected noexcept inherited
Definition at line 3475 of file toml.h.
        {
            using out_ref = ref_cast_type<T, node&&>;
            using out_type = std::remove_reference_t<out_ref>;
            return static_cast<out_ref>(*reinterpret_cast<out_type*>(this));
        }
ref_cast() [2/4]
template<typename T > ref_cast_type< T, node & > toml::v3::node::ref_cast () & inline protected noexcept inherited
Definition at line 3466 of file toml.h.
        {
            using out_ref = ref_cast_type<T, node&>;
            using out_type = std::remove_reference_t<out_ref>;
            return static_cast<out_ref>(*reinterpret_cast<out_type*>(this));
        }
ref_cast() [3/4]
template<typename T > ref_cast_type< T, const node && > toml::v3::node::ref_cast () const && inline protected noexcept inherited
Definition at line 3493 of file toml.h.
        {
            using out_ref = ref_cast_type<T, const node&&>;
            using out_type = std::remove_reference_t<out_ref>;
            return static_cast<out_ref>(*reinterpret_cast<out_type*>(this));
        }
ref_cast() [4/4]
template<typename T > ref_cast_type< T, const node & > toml::v3::node::ref_cast () const & inline protected noexcept inherited
Definition at line 3484 of file toml.h.
        {
            using out_ref = ref_cast_type<T, const node&>;
            using out_type = std::remove_reference_t<out_ref>;
            return static_cast<out_ref>(*reinterpret_cast<out_type*>(this));
        }
size()
size_t toml::v3::table::size () const inline noexcept
Definition at line 7840 of file toml.h.
          {
              return map_.size();
          }
source()
const source_region & toml::v3::node::source () const inline noexcept inherited
Definition at line 3743 of file toml.h.
        {
            return source_;
        }
type()
node_type toml::v3::table::type () const inline final virtual noexcept
Implements toml::v3::node.
Definition at line 7337 of file toml.h.
        {
            return node_type::table;
        }
value()
template<typename T > optional< T > toml::v3::node::value () const inline noexcept inherited
Definition at line 5363 of file toml.h.
    {
        using namespace impl;
        static_assert(!is_wide_string<T> || TOML_ENABLE_WINDOWS_COMPAT,
                      "Retrieving values as wide-character strings with node::value() is only "
                      "supported on Windows with TOML_ENABLE_WINDOWS_COMPAT enabled.");
        static_assert((is_native<T> || can_represent_native<T> || can_partially_represent_native<T>) && !is_cvref<T>,
                      TOML_SA_VALUE_FUNC_MESSAGE("return type of node::value()"));
        // when asking for strings, dates, times and date_times there's no 'fuzzy' conversion
        // semantics to be mindful of so the exact retrieval is enough.
        if constexpr (is_natively_one_of<T, std::string, time, date, date_time>)
        {
            if (type() == node_type_of<T>)
                return { this->get_value_exact<T>() };
            else
                return {};
        }
        // everything else requires a bit of logicking.
        else
        {
            switch (type())
            {
                // int -> *
                case node_type::integer:
                {
                    // int -> int
                    if constexpr (is_natively_one_of<T, int64_t>)
                    {
                        if constexpr (is_native<T> || can_represent_native<T>)
                            return static_cast<T>(*ref_cast<int64_t>());
                        else
                            return node_integer_cast<T>(*ref_cast<int64_t>());
                    }
                    // int -> float
                    else if constexpr (is_natively_one_of<T, double>)
                    {
                        const int64_t val = *ref_cast<int64_t>();
                        if constexpr (std::numeric_limits<T>::digits < 64)
{
                            constexpr auto largest_whole_float = (int64_t{ 1 } << std::numeric_limits<T>::digits);
                            if (val < -largest_whole_float || val > largest_whole_float)
                                return {};
                        }
                        return static_cast<T>(val);
                    }
                    // int -> bool
                    else if constexpr (is_natively_one_of<T, bool>)
                        return static_cast<bool>(*ref_cast<int64_t>());
                    // int -> anything else
                    else
                        return {};
                }
                // float -> *
                case node_type::floating_point:
                {
                    // float -> float
                    if constexpr (is_natively_one_of<T, double>)
                    {
                        if constexpr (is_native<T> || can_represent_native<T>)
                            return { static_cast<T>(*ref_cast<double>()) };
                        else
{
                            const double val = *ref_cast<double>();
                            if (impl::fpclassify(val) == fp_class::ok
                                && (val < (std::numeric_limits<T>::lowest)() || val >(std::numeric_limits<T>::max)()))
                                return {};
                            return { static_cast<T>(val) };
                        }
                    }
                    // float -> int
                    else if constexpr (is_natively_one_of<T, int64_t>)
                    {
                        const double val = *ref_cast<double>();
                        if (impl::fpclassify(val) == fp_class::ok
                            && static_cast<double>(static_cast<int64_t>(val)) == val)
                            return node_integer_cast<T>(static_cast<int64_t>(val));
                        else
                            return {};
                    }
                    // float -> anything else
                    else
                        return {};
                }
                // bool -> *
                case node_type::boolean:
                {
                    // bool -> bool
                    if constexpr (is_natively_one_of<T, bool>)
                        return { *ref_cast<bool>() };
                    // bool -> int
                    else if constexpr (is_natively_one_of<T, int64_t>)
                        return { static_cast<T>(*ref_cast<bool>()) };
                    // bool -> anything else
                    else
                        return {};
                }
            }
            // non-values, or 'exact' types covered above
            return {};
        }
    }
References TOML_ENABLE_WINDOWS_COMPAT, and TOML_SA_VALUE_FUNC_MESSAGE.
value_exact()
template<typename T > optional< T > toml::v3::node::value_exact () const inline noexcept inherited
Definition at line 5340 of file toml.h.
    {
        using namespace impl;
        static_assert(!is_wide_string<T> || TOML_ENABLE_WINDOWS_COMPAT,
                      "Retrieving values as wide-character strings with node::value_exact() is only "
                      "supported on Windows with TOML_ENABLE_WINDOWS_COMPAT enabled.");
        static_assert((is_native<T> || can_represent_native<T>) && !is_cvref<T>,
                      TOML_SA_VALUE_EXACT_FUNC_MESSAGE("return type of node::value_exact()"));
        // prevent additional compiler error spam when the static_assert fails by gating behind if constexpr
        if constexpr ((is_native<T> || can_represent_native<T>) && !is_cvref<T>)
        {
            if (type() == node_type_of<T>)
                return { this->get_value_exact<T>() };
            else
                return {};
        }
    }
References TOML_ENABLE_WINDOWS_COMPAT, and TOML_SA_VALUE_EXACT_FUNC_MESSAGE.
value_or()
template<typename T > auto toml::v3::node::value_or (T && default_value) const inline noexcept inherited
Definition at line 5480 of file toml.h.
    {
        using namespace impl;
        static_assert(!is_wide_string<T> || TOML_ENABLE_WINDOWS_COMPAT,
                      "Retrieving values as wide-character strings with node::value_or() is only "
                      "supported on Windows with TOML_ENABLE_WINDOWS_COMPAT enabled.");
        if constexpr (is_wide_string<T>)
        {
#if TOML_ENABLE_WINDOWS_COMPAT
            if (type() == node_type::string)
                return widen(*ref_cast<std::string>());
            return std::wstring{ static_cast<T&&>(default_value) };
#else
            static_assert(dependent_false<T>, "Evaluated unreachable branch!");
#endif
        }
        else
        {
            using value_type =
                std::conditional_t<std::is_pointer_v<std::decay_t<T>>,
                                   std::add_pointer_t<std::add_const_t<std::remove_pointer_t<std::decay_t<T>>>>,
                                   std::decay_t<T>>;
            using traits = value_traits<value_type>;
            // clang-format off
            static_assert(
                traits::is_native || traits::can_represent_native || traits::can_partially_represent_native,
                "The default value type of node::value_or() must be one of:"
                TOML_SA_LIST_NEW "A native TOML value type"
                TOML_SA_NATIVE_VALUE_TYPE_LIST
                TOML_SA_LIST_NXT "A non-view type capable of losslessly representing a native TOML value type"
                TOML_SA_LIST_BEG "std::string"
                #if TOML_ENABLE_WINDOWS_COMPAT
                TOML_SA_LIST_SEP "std::wstring"
                #endif
                TOML_SA_LIST_SEP "any signed integer type >= 64 bits"
                TOML_SA_LIST_SEP "any floating-point type >= 64 bits"
                TOML_SA_LIST_END
                TOML_SA_LIST_NXT "A non-view type capable of (reasonably) representing a native TOML value type"
                TOML_SA_LIST_BEG "any other integer type"
                TOML_SA_LIST_SEP "any floating-point type"
                TOML_SA_LIST_END
                TOML_SA_LIST_NXT "A compatible view type"
                TOML_SA_LIST_BEG "std::string_view"
                #if TOML_HAS_CHAR8
                TOML_SA_LIST_SEP "std::u8string_view"
                #endif
                #if TOML_ENABLE_WINDOWS_COMPAT
                TOML_SA_LIST_SEP "std::wstring_view"
                #endif
                TOML_SA_LIST_SEP "const char*"
                #if TOML_HAS_CHAR8
                TOML_SA_LIST_SEP "const char8_t*"
                #endif
                #if TOML_ENABLE_WINDOWS_COMPAT
                TOML_SA_LIST_SEP "const wchar_t*"
                #endif
                TOML_SA_LIST_END
            );
            // clang-format on
            // prevent additional compiler error spam when the static_assert fails by gating behind if constexpr
            if constexpr (traits::is_native || traits::can_represent_native || traits::can_partially_represent_native)
            {
                if constexpr (traits::is_native)
                {
                    if (type() == node_type_of<value_type>)
                        return *ref_cast<typename traits::native_type>();
                }
                if (auto val = this->value<value_type>())
                    return *val;
                if constexpr (std::is_pointer_v<value_type>)
                    return value_type{ default_value };
                else
                    return static_cast<T&&>(default_value);
            }
        }
    }
References TOML_ENABLE_WINDOWS_COMPAT, TOML_SA_LIST_BEG, TOML_SA_LIST_END, TOML_SA_LIST_NEW, TOML_SA_LIST_NXT, TOML_SA_LIST_SEP, and TOML_SA_NATIVE_VALUE_TYPE_LIST.
visit() [1/4]
template<typename Func > decltype(auto) toml::v3::node::visit (Func && visitor) && inline noexcept inherited
Definition at line 3907 of file toml.h.
        {
            return do_visit(static_cast<Func&&>(visitor), static_cast<node&&>(*this));
        }
visit() [2/4]
template<typename Func > decltype(auto) toml::v3::node::visit (Func && visitor) & inline noexcept inherited
Definition at line 3901 of file toml.h.
        {
            return do_visit(static_cast<Func&&>(visitor), *this);
        }
visit() [3/4]
template<typename Func > decltype(auto) toml::v3::node::visit (Func && visitor) const && inline noexcept inherited
Definition at line 3919 of file toml.h.
        {
            return do_visit(static_cast<Func&&>(visitor), static_cast<const node&&>(*this));
        }
visit() [4/4]
template<typename Func > decltype(auto) toml::v3::node::visit (Func && visitor) const & inline noexcept inherited
Definition at line 3913 of file toml.h.
        {
            return do_visit(static_cast<Func&&>(visitor), *this);
        }
Friends And Related Symbol Documentation
operator!=
bool operator!= (const table & lhs, const table & rhs) friend
Definition at line 8240 of file toml.h.
          {
              return !equal(lhs, rhs);
          }
operator<<
std::ostream & operator<< (std::ostream & lhs, const table & rhs) friend
Definition at line 8247 of file toml.h.
          {
              impl::print_to_stream(lhs, rhs);
              return lhs;
          }
operator==
bool operator== (const table & lhs, const table & rhs) friend
Definition at line 8234 of file toml.h.
          {
              return equal(lhs, rhs);
          }
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/toml.h