Techstorm-rivalry: toml::v3::node_view< ViewedType > Class Template Reference
toml::v3::node_view< ViewedType > Class Template Reference
#include <toml.h>
Public Types
using viewed_type = ViewedType
Public Member Functions
node_view () noexcept=default
node_view (viewed_type *node) noexcept
node_view (viewed_type &node) noexcept
node_view (const node_view &) noexcept=default
node_view (node_view &&) noexcept=default
node_view & operator= (const node_view &) &noexcept=default
node_view & operator= (node_view &&) &noexcept=default
operator bool () const noexcept
viewed_type * node () const noexcept
node_type type () const noexcept
bool is_table () const noexcept
bool is_array () const noexcept
bool is_value () const noexcept
bool is_string () const noexcept
bool is_integer () const noexcept
bool is_floating_point () const noexcept
bool is_number () const noexcept
bool is_boolean () const noexcept
bool is_date () const noexcept
bool is_time () const noexcept
bool is_date_time () const noexcept
bool is_array_of_tables () const noexcept
template<typename T >
bool is () const noexcept
bool is_homogeneous (node_type ntype, viewed_type *&first_nonmatch) const noexcept
bool is_homogeneous (node_type ntype) const noexcept
template<typename ElemType = void>
bool is_homogeneous () const noexcept
template<typename T >
auto * as () const noexcept
auto * as_table () const noexcept
auto * as_array () const noexcept
auto * as_string () const noexcept
auto * as_integer () const noexcept
auto * as_floating_point () const noexcept
auto * as_boolean () const noexcept
auto * as_date () const noexcept
auto * as_time () const noexcept
auto * as_date_time () const noexcept
template<typename T >
optional< T > value_exact () const noexcept(impl::value_retrieval_is_nothrow< T >)
template<typename T >
optional< T > value () const noexcept(impl::value_retrieval_is_nothrow< T >)
template<typename T >
auto value_or (T &&default_value) const noexcept(impl::value_retrieval_is_nothrow< T >)
template<typename T >
decltype(auto) ref () const noexcept
template<typename Func >
decltype(auto) visit (Func &&visitor) const noexcept(visit_is_nothrow< Func && >)
node_view operator[] (std::string_view key) const noexcept
node_view operator[] (const toml::path &path) const noexcept
node_view at_path (std::string_view path) const noexcept
node_view at_path (const toml::path &path) const noexcept
node_view operator[] (size_t index) const noexcept
Friends
template<typename T >
class node_view
template<typename T >
bool operator== (const node_view &lhs, const node_view< T > &rhs) noexcept
template<typename T >
bool operator!= (const node_view &lhs, const node_view< T > &rhs) noexcept
bool operator== (const node_view &lhs, const table &rhs) noexcept
bool operator== (const table &rhs, const node_view &lhs) noexcept
bool operator!= (const node_view &lhs, const table &rhs) noexcept
bool operator!= (const table &rhs, const node_view &lhs) noexcept
bool operator== (const node_view &lhs, const array &rhs) noexcept
bool operator== (const array &rhs, const node_view &lhs) noexcept
bool operator!= (const node_view &lhs, const array &rhs) noexcept
bool operator!= (const array &rhs, const node_view &lhs) noexcept
template<typename T >
bool operator== (const node_view &lhs, const toml::value< T > &rhs) noexcept
template<typename T >
bool operator== (const toml::value< T > &rhs, const node_view &lhs) noexcept
template<typename T >
bool operator!= (const node_view &lhs, const toml::value< T > &rhs) noexcept
template<typename T >
bool operator!= (const toml::value< T > &rhs, const node_view &lhs) noexcept
template<typename T , typename std::enable_if<(impl::is_losslessly_convertible_to_native< T >), int >::type = 0>
bool operator== (const node_view &lhs, const T &rhs) noexcept(!impl::is_wide_string< T >)
template<typename T , typename std::enable_if<(impl::is_losslessly_convertible_to_native< T >), int >::type = 0>
bool operator== (const T &rhs, const node_view &lhs) noexcept
template<typename T , typename std::enable_if<(impl::is_losslessly_convertible_to_native< T >), int >::type = 0>
bool operator!= (const node_view &lhs, const T &rhs) noexcept
template<typename T , typename std::enable_if<(impl::is_losslessly_convertible_to_native< T >), int >::type = 0>
bool operator!= (const T &rhs, const node_view &lhs) noexcept
template<typename T >
bool operator== (const node_view &lhs, const std::initializer_list< T > &rhs) noexcept(!impl::is_wide_string< T >)
template<typename T >
bool operator== (const std::initializer_list< T > &rhs, const node_view &lhs) noexcept
template<typename T >
bool operator!= (const node_view &lhs, const std::initializer_list< T > &rhs) noexcept
template<typename T >
bool operator!= (const std::initializer_list< T > &rhs, const node_view &lhs) noexcept
template<typename T >
bool operator== (const node_view &lhs, const std::vector< T > &rhs) noexcept(!impl::is_wide_string< T >)
template<typename T >
bool operator== (const std::vector< T > &rhs, const node_view &lhs) noexcept
template<typename T >
bool operator!= (const node_view &lhs, const std::vector< T > &rhs) noexcept
template<typename T >
bool operator!= (const std::vector< T > &rhs, const node_view &lhs) noexcept
std::ostream & operator<< (std::ostream &os, const node_view &nv)
Detailed Description
template<typename ViewedType>
class toml::v3::node_view< ViewedType >
Definition at line 4006 of file toml.h.
Member Typedef Documentation
viewed_type
template<typename ViewedType > using toml::v3::node_view< ViewedType >::viewed_type = ViewedType
Definition at line 4013 of file toml.h.
Constructor & Destructor Documentation
node_view() [1/5]
template<typename ViewedType > toml::v3::node_view< ViewedType >::node_view () default noexcept
node_view() [2/5]
template<typename ViewedType > toml::v3::node_view< ViewedType >::node_view (viewed_type * node) inline explicit noexcept
Definition at line 4027 of file toml.h.
            : node_{ node }
        {}
node_view() [3/5]
template<typename ViewedType > toml::v3::node_view< ViewedType >::node_view (viewed_type & node) inline explicit noexcept
Definition at line 4032 of file toml.h.
            : node_{ &node }
        {}
node_view() [4/5]
template<typename ViewedType > toml::v3::node_view< ViewedType >::node_view (const node_view< ViewedType > &) default noexcept
node_view() [5/5]
template<typename ViewedType > toml::v3::node_view< ViewedType >::node_view (node_view< ViewedType > &&) default noexcept
Member Function Documentation
as()
template<typename ViewedType > template<typename T > auto * toml::v3::node_view< ViewedType >::as () const inline noexcept
Definition at line 4169 of file toml.h.
        {
            return node_ ? node_->template as<T>() : nullptr;
        }
as_array()
template<typename ViewedType > auto * toml::v3::node_view< ViewedType >::as_array () const inline noexcept
Definition at line 4181 of file toml.h.
        {
            return as<array>();
        }
as_boolean()
template<typename ViewedType > auto * toml::v3::node_view< ViewedType >::as_boolean () const inline noexcept
Definition at line 4205 of file toml.h.
        {
            return as<bool>();
        }
as_date()
template<typename ViewedType > auto * toml::v3::node_view< ViewedType >::as_date () const inline noexcept
Definition at line 4211 of file toml.h.
        {
            return as<date>();
        }
as_date_time()
template<typename ViewedType > auto * toml::v3::node_view< ViewedType >::as_date_time () const inline noexcept
Definition at line 4223 of file toml.h.
        {
            return as<date_time>();
        }
as_floating_point()
template<typename ViewedType > auto * toml::v3::node_view< ViewedType >::as_floating_point () const inline noexcept
Definition at line 4199 of file toml.h.
        {
            return as<double>();
        }
as_integer()
template<typename ViewedType > auto * toml::v3::node_view< ViewedType >::as_integer () const inline noexcept
Definition at line 4193 of file toml.h.
        {
            return as<int64_t>();
        }
as_string()
template<typename ViewedType > auto * toml::v3::node_view< ViewedType >::as_string () const inline noexcept
Definition at line 4187 of file toml.h.
        {
            return as<std::string>();
        }
as_table()
template<typename ViewedType > auto * toml::v3::node_view< ViewedType >::as_table () const inline noexcept
Definition at line 4175 of file toml.h.
        {
            return as<table>();
        }
as_time()
template<typename ViewedType > auto * toml::v3::node_view< ViewedType >::as_time () const inline noexcept
Definition at line 4217 of file toml.h.
        {
            return as<time>();
        }
at_path() [1/2]
template<typename ViewedType > node_view toml::v3::node_view< ViewedType >::at_path (const toml::path & path) const inline noexcept
Definition at line 4425 of file toml.h.
        {
            return node_ ? node_->at_path(path) : node_view{};
        }
References toml::v3::node_view< ViewedType >::at_path().
at_path() [2/2]
template<typename ViewedType > node_view toml::v3::node_view< ViewedType >::at_path (std::string_view path) const inline noexcept
Definition at line 4419 of file toml.h.
        {
            return node_ ? node_->at_path(path) : node_view{};
        }
References toml::v3::node_view< ViewedType >::at_path().
is()
template<typename ViewedType > template<typename T > bool toml::v3::node_view< ViewedType >::is () const inline noexcept
Definition at line 4138 of file toml.h.
        {
            return node_ ? node_->template is<impl::unwrap_node<impl::remove_cvref<T>>>() : false;
        }
is_array()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_array () const inline noexcept
Definition at line 4071 of file toml.h.
        {
            return node_ && node_->is_array();
        }
is_array_of_tables()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_array_of_tables () const inline noexcept
Definition at line 4131 of file toml.h.
        {
            return node_ && node_->is_array_of_tables();
        }
is_boolean()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_boolean () const inline noexcept
Definition at line 4107 of file toml.h.
        {
            return node_ && node_->is_boolean();
        }
is_date()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_date () const inline noexcept
Definition at line 4113 of file toml.h.
        {
            return node_ && node_->is_date();
        }
is_date_time()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_date_time () const inline noexcept
Definition at line 4125 of file toml.h.
        {
            return node_ && node_->is_date_time();
        }
is_floating_point()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_floating_point () const inline noexcept
Definition at line 4095 of file toml.h.
        {
            return node_ && node_->is_floating_point();
        }
is_homogeneous() [1/3]
template<typename ViewedType > template<typename ElemType = void> bool toml::v3::node_view< ViewedType >::is_homogeneous () const inline noexcept
Definition at line 4162 of file toml.h.
        {
            return node_ ? node_->template is_homogeneous<impl::unwrap_node<impl::remove_cvref<ElemType>>>() : false;
        }
is_homogeneous() [2/3]
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_homogeneous (node_type ntype) const inline noexcept
Definition at line 4155 of file toml.h.
        {
            return node_ ? node_->is_homogeneous(ntype) : false;
        }
is_homogeneous() [3/3]
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_homogeneous (node_type ntype, viewed_type *& first_nonmatch) const inline noexcept
Definition at line 4144 of file toml.h.
        {
            if (!node_)
            {
                first_nonmatch = {};
                return false;
            }
            return node_->is_homogeneous(ntype, first_nonmatch);
        }
is_integer()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_integer () const inline noexcept
Definition at line 4089 of file toml.h.
        {
            return node_ && node_->is_integer();
        }
is_number()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_number () const inline noexcept
Definition at line 4101 of file toml.h.
        {
            return node_ && node_->is_number();
        }
is_string()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_string () const inline noexcept
Definition at line 4083 of file toml.h.
        {
            return node_ && node_->is_string();
        }
is_table()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_table () const inline noexcept
Definition at line 4065 of file toml.h.
        {
            return node_ && node_->is_table();
        }
is_time()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_time () const inline noexcept
Definition at line 4119 of file toml.h.
        {
            return node_ && node_->is_time();
        }
is_value()
template<typename ViewedType > bool toml::v3::node_view< ViewedType >::is_value () const inline noexcept
Definition at line 4077 of file toml.h.
        {
            return node_ && node_->is_value();
        }
node()
template<typename ViewedType > viewed_type * toml::v3::node_view< ViewedType >::node () const inline noexcept
Definition at line 4053 of file toml.h.
        {
            return node_;
        }
operator bool()
template<typename ViewedType > toml::v3::node_view< ViewedType >::operator bool () const inline explicit noexcept
Definition at line 4047 of file toml.h.
        {
            return node_ != nullptr;
        }
operator=() [1/2]
template<typename ViewedType > node_view & toml::v3::node_view< ViewedType >::operator= (const node_view< ViewedType > &) & default noexcept
operator=() [2/2]
template<typename ViewedType > node_view & toml::v3::node_view< ViewedType >::operator= (node_view< ViewedType > &&) & default noexcept
operator[]() [1/3]
template<typename ViewedType > node_view toml::v3::node_view< ViewedType >::operator[] (const toml::path & path) const inline noexcept
Definition at line 4413 of file toml.h.
        {
            return node_ ? node_->at_path(path) : node_view{};
        }
References toml::v3::node_view< ViewedType >::at_path().
operator[]() [2/3]
template<typename ViewedType > node_view toml::v3::node_view< ViewedType >::operator[] (size_t index) const inline noexcept
Definition at line 4449 of file toml.h.
        {
            if (auto arr = this->as_array())
                return node_view{ arr->get(index) };
            return {};
        }
operator[]() [3/3]
template<typename ViewedType > node_view toml::v3::node_view< ViewedType >::operator[] (std::string_view key) const inline noexcept
Definition at line 4405 of file toml.h.
        {
            if (auto tbl = this->as_table())
                return node_view{ tbl->get(key) };
            return {};
        }
ref()
template<typename ViewedType > template<typename T > decltype(auto) toml::v3::node_view< ViewedType >::ref () const inline noexcept
Definition at line 4288 of file toml.h.
        {
            TOML_ASSERT_ASSUME(node_ && "toml::node_view::ref() called on a node_view that did not reference a node");
            return node_->template ref<T>();
        }
References TOML_ASSERT_ASSUME.
type()
template<typename ViewedType > node_type toml::v3::node_view< ViewedType >::type () const inline noexcept
Definition at line 4059 of file toml.h.
        {
            return node_ ? node_->type() : node_type::none;
        }
value()
template<typename ViewedType > template<typename T > optional< T > toml::v3::node_view< ViewedType >::value () const inline noexcept
Definition at line 4239 of file toml.h.
        {
            if (node_)
                return node_->template value<T>();
            return {};
        }
value_exact()
template<typename ViewedType > template<typename T > optional< T > toml::v3::node_view< ViewedType >::value_exact () const inline noexcept
Definition at line 4230 of file toml.h.
        {
            if (node_)
                return node_->template value_exact<T>();
            return {};
        }
value_or()
template<typename ViewedType > template<typename T > auto toml::v3::node_view< ViewedType >::value_or (T && default_value) const inline noexcept
Definition at line 4248 of file toml.h.
        {
            using namespace ::toml::impl;
            static_assert(!is_wide_string<T> || TOML_ENABLE_WINDOWS_COMPAT,
                          "Retrieving values as wide-character strings is only "
                          "supported on Windows with TOML_ENABLE_WINDOWS_COMPAT enabled.");
            if constexpr (is_wide_string<T>)
            {
#if TOML_ENABLE_WINDOWS_COMPAT
                if (node_)
                    return node_->value_or(static_cast<T&&>(default_value));
                return std::wstring{ static_cast<T&&>(default_value) };
#else
                static_assert(impl::dependent_false<T>, "Evaluated unreachable branch!");
#endif
            }
            else
            {
                using value_type =
                    std::conditional_t<std::is_pointer_v<std::decay_t<T>>,
                                       std::add_pointer_t<std::add_const_t<std::remove_pointer_t<std::decay_t<T>>>>,
                                       std::decay_t<T>>;
                if (node_)
                    return node_->value_or(static_cast<T&&>(default_value));
                if constexpr (std::is_pointer_v<value_type>)
                    return value_type{ default_value };
                else
                    return static_cast<T&&>(default_value);
            }
        }
References TOML_ENABLE_WINDOWS_COMPAT.
visit()
template<typename ViewedType > template<typename Func > decltype(auto) toml::v3::node_view< ViewedType >::visit (Func && visitor) const inline noexcept
Definition at line 4302 of file toml.h.
        {
            using return_type = decltype(node_->visit(static_cast<Func&&>(visitor)));
            if (node_)
                return node_->visit(static_cast<Func&&>(visitor));
            if constexpr (!std::is_void_v<return_type>)
                return return_type{};
        }
Friends And Related Symbol Documentation
node_view
template<typename ViewedType > template<typename T > friend class node_view friend
Definition at line 4017 of file toml.h.
operator!= [1/13]
template<typename ViewedType > bool operator!= (const array & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4345 of file toml.h.
operator!= [2/13]
template<typename ViewedType > bool operator!= (const node_view< ViewedType > & lhs, const array & rhs) friend
Definition at line 4345 of file toml.h.
operator!= [3/13]
template<typename ViewedType > template<typename T > bool operator!= (const node_view< ViewedType > & lhs, const node_view< T > & rhs) friend
Definition at line 4322 of file toml.h.
        {
            return !impl::node_deep_equality(lhs.node_, rhs.node_);
        }
operator!= [4/13]
template<typename ViewedType > template<typename T > bool operator!= (const node_view< ViewedType > & lhs, const std::initializer_list< T > & rhs) friend
Definition at line 4393 of file toml.h.
operator!= [5/13]
template<typename ViewedType > template<typename T > bool operator!= (const node_view< ViewedType > & lhs, const std::vector< T > & rhs) friend
Definition at line 4402 of file toml.h.
operator!= [6/13]
template<typename ViewedType > template<typename T , typename std::enable_if<(impl::is_losslessly_convertible_to_native< T >), int >::type = 0> bool operator!= (const node_view< ViewedType > & lhs, const T & rhs) friend
Definition at line 4383 of file toml.h.
operator!= [7/13]
template<typename ViewedType > bool operator!= (const node_view< ViewedType > & lhs, const table & rhs) friend
Definition at line 4335 of file toml.h.
operator!= [8/13]
template<typename ViewedType > template<typename T > bool operator!= (const node_view< ViewedType > & lhs, const toml::value< T > & rhs) friend
Definition at line 4356 of file toml.h.
operator!= [9/13]
template<typename ViewedType > template<typename T > bool operator!= (const std::initializer_list< T > & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4393 of file toml.h.
operator!= [10/13]
template<typename ViewedType > template<typename T > bool operator!= (const std::vector< T > & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4402 of file toml.h.
operator!= [11/13]
template<typename ViewedType > template<typename T , typename std::enable_if<(impl::is_losslessly_convertible_to_native< T >), int >::type = 0> bool operator!= (const T & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4383 of file toml.h.
operator!= [12/13]
template<typename ViewedType > bool operator!= (const table & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4335 of file toml.h.
operator!= [13/13]
template<typename ViewedType > template<typename T > bool operator!= (const toml::value< T > & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4356 of file toml.h.
operator<<
template<typename ViewedType > std::ostream & operator<< (std::ostream & os, const node_view< ViewedType > & nv) friend
Definition at line 4458 of file toml.h.
        {
            if (nv.node_)
                nv.node_->visit([&os](const auto& n) { os << n; });
            return os;
        }
operator== [1/13]
template<typename ViewedType > bool operator== (const array & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4345 of file toml.h.
operator== [2/13]
template<typename ViewedType > bool operator== (const node_view< ViewedType > & lhs, const array & rhs) friend
Definition at line 4338 of file toml.h.
        {
            if (lhs.node_ == &rhs)
                return true;
            const auto arr = lhs.as<array>();
            return arr && *arr == rhs;
        }
operator== [3/13]
template<typename ViewedType > template<typename T > bool operator== (const node_view< ViewedType > & lhs, const node_view< T > & rhs) friend
Definition at line 4315 of file toml.h.
        {
            return impl::node_deep_equality(lhs.node_, rhs.node_);
        }
operator== [4/13]
template<typename ViewedType > template<typename T > bool operator== (const node_view< ViewedType > & lhs, const std::initializer_list< T > & rhs) friend
Definition at line 4387 of file toml.h.
        {
            const auto arr = lhs.as<array>();
            return arr && *arr == rhs;
        }
operator== [5/13]
template<typename ViewedType > template<typename T > bool operator== (const node_view< ViewedType > & lhs, const std::vector< T > & rhs) friend
Definition at line 4397 of file toml.h.
        {
            const auto arr = lhs.as<array>();
            return arr && *arr == rhs;
        }
operator== [6/13]
template<typename ViewedType > template<typename T , typename std::enable_if<(impl::is_losslessly_convertible_to_native< T >), int >::type = 0> bool operator== (const node_view< ViewedType > & lhs, const T & rhs) friend
Definition at line 4360 of file toml.h.
        {
            static_assert(!impl::is_wide_string<T> || TOML_ENABLE_WINDOWS_COMPAT,
                          "Comparison with wide-character strings is only "
                          "supported on Windows with TOML_ENABLE_WINDOWS_COMPAT enabled.");
            if constexpr (impl::is_wide_string<T>)
            {
#if TOML_ENABLE_WINDOWS_COMPAT
                return lhs == impl::narrow(rhs);
#else
                static_assert(impl::dependent_false<T>, "Evaluated unreachable branch!");
#endif
            }
            else
            {
                const auto val = lhs.as<impl::native_type_of<T>>();
                return val && *val == rhs;
            }
        }
operator== [7/13]
template<typename ViewedType > bool operator== (const node_view< ViewedType > & lhs, const table & rhs) friend
Definition at line 4328 of file toml.h.
        {
            if (lhs.node_ == &rhs)
                return true;
            const auto tbl = lhs.as<table>();
            return tbl && *tbl == rhs;
        }
operator== [8/13]
template<typename ViewedType > template<typename T > bool operator== (const node_view< ViewedType > & lhs, const toml::value< T > & rhs) friend
Definition at line 4349 of file toml.h.
        {
            if (lhs.node_ == &rhs)
                return true;
            const auto val = lhs.as<T>();
            return val && *val == rhs;
        }
operator== [9/13]
template<typename ViewedType > template<typename T > bool operator== (const std::initializer_list< T > & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4393 of file toml.h.
operator== [10/13]
template<typename ViewedType > template<typename T > bool operator== (const std::vector< T > & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4402 of file toml.h.
operator== [11/13]
template<typename ViewedType > template<typename T , typename std::enable_if<(impl::is_losslessly_convertible_to_native< T >), int >::type = 0> bool operator== (const T & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4383 of file toml.h.
operator== [12/13]
template<typename ViewedType > bool operator== (const table & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4335 of file toml.h.
operator== [13/13]
template<typename ViewedType > template<typename T > bool operator== (const toml::value< T > & rhs, const node_view< ViewedType > & lhs) friend
Definition at line 4356 of file toml.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/toml.h