Techstorm-rivalry: raylib::Music Class Reference
raylib::Music Class Reference
#include <Music.hpp>
Public Member Functions
Music (::AudioStream stream={nullptr, nullptr, 0, 0, 0}, unsigned int frameCount=0, bool looping=false, int ctxType=0, void *ctxData=nullptr)
Music (const ::Music &music)
Music (const std::string &fileName)
Music (const std::string &fileType, unsigned char *data, int dataSize)
Music (const Music &)=delete
Music (Music &&other)
~Music ()
::AudioStream GetStream () const
void SetStream (::AudioStream value)
unsigned int GetFrameCount () const
void SetFrameCount (unsigned int value)
bool GetLooping () const
void SetLooping (bool value)
int GetCtxType () const
void SetCtxType (int value)
void * GetCtxData () const
void SetCtxData (void *value)
Music & operator= (const ::Music &music)
Music & operator= (const Music &)=delete
Music & operator= (Music &&other) noexcept
void Unload ()
Music & Play ()
Music & Update ()
Music & Stop ()
Music & Pause ()
Music & Resume ()
Music & Seek (float position)
bool IsPlaying () const
Music & SetVolume (float volume)
Music & SetPitch (float pitch)
Music & SetPan (float pan=0.5f)
float GetTimeLength () const
float GetTimePlayed () const
void Load (const std::string &fileName)
void Load (const std::string &fileType, unsigned char *data, int dataSize)
bool IsReady () const
Public Attributes
AudioStream stream
unsigned int frameCount
bool looping
int ctxType
void * ctxData
Protected Member Functions
void set (const ::Music &music)
Detailed Description
Music stream type (audio file streaming from memory)
Definition at line 14 of file Music.hpp.
Constructor & Destructor Documentation
Music() [1/6]
raylib::Music::Music (::AudioStream stream = {nullptr, nullptr, 0, 0, 0}, unsigned int frameCount = 0, bool looping = false, int ctxType = 0, void * ctxData = nullptr) inline
Definition at line 16 of file Music.hpp.
                               {nullptr, nullptr, 0, 0, 0},
            unsigned int frameCount = 0,
            bool looping = false,
            int ctxType = 0,
            void *ctxData = nullptr) : ::Music{stream, frameCount, looping, ctxType, ctxData} {}
Music() [2/6]
raylib::Music::Music (const ::Music & music) inline
Definition at line 22 of file Music.hpp.
{
        set(music);
    }
References set().
Music() [3/6]
raylib::Music::Music (const std::string & fileName) inline
Load music stream from file
Exceptions
raylib::RaylibException Throws if the music failed to load.
Definition at line 31 of file Music.hpp.
{
        Load(fileName);
    }
References Load().
Music() [4/6]
raylib::Music::Music (const std::string & fileType, unsigned char * data, int dataSize) inline
Load music stream from memory
Exceptions
raylib::RaylibException Throws if the music failed to load.
Definition at line 40 of file Music.hpp.
{
        Load(fileType, data, dataSize);
    }
References Load().
Music() [5/6]
raylib::Music::Music (const Music &) delete
Music() [6/6]
raylib::Music::Music (Music && other) inline
Definition at line 46 of file Music.hpp.
{
        set(other);
        other.stream = {};
        other.frameCount = 0;
        other.looping = false;
        other.ctxType = 0;
        other.ctxData = nullptr;
    }
References set().
~Music()
raylib::Music::~Music () inline
Unload music stream
Definition at line 59 of file Music.hpp.
             {
        Unload();
    }
References Unload().
Member Function Documentation
GetCtxData()
void * raylib::Music::GetCtxData () const inline
Retrieves the ctxData value for the object.
Returns
The ctxData value of the object.
Definition at line 67 of file Music.hpp.
GetCtxType()
int raylib::Music::GetCtxType () const inline
Retrieves the ctxType value for the object.
Returns
The ctxType value of the object.
Definition at line 66 of file Music.hpp.
GetFrameCount()
unsigned int raylib::Music::GetFrameCount () const inline
Retrieves the frameCount value for the object.
Returns
The frameCount value of the object.
Definition at line 64 of file Music.hpp.
GetLooping()
bool raylib::Music::GetLooping () const inline
Retrieves the looping value for the object.
Returns
The looping value of the object.
Definition at line 65 of file Music.hpp.
GetStream()
::AudioStream raylib::Music::GetStream () const inline
Retrieves the stream value for the object.
Returns
The stream value of the object.
Definition at line 63 of file Music.hpp.
GetTimeLength()
float raylib::Music::GetTimeLength () const inline
Get music time length (in seconds)
Definition at line 182 of file Music.hpp.
{
        return ::GetMusicTimeLength(*this);
    }
GetTimePlayed()
float raylib::Music::GetTimePlayed () const inline
Get current music time played (in seconds)
Definition at line 189 of file Music.hpp.
{
        return ::GetMusicTimePlayed(*this);
    }
IsPlaying()
bool raylib::Music::IsPlaying () const inline
Check if music is playing
Definition at line 151 of file Music.hpp.
{
        return ::IsMusicStreamPlaying(*this);
    }
IsReady()
bool raylib::Music::IsReady () const inline
Retrieve whether or not the Music has been loaded.
Returns
True or false depending on whether the Music has been loaded.
Definition at line 222 of file Music.hpp.
{
        return ::IsMusicReady(*this);
    }
Load() [1/2]
void raylib::Music::Load (const std::string & fileName) inline
Load music stream from file
Exceptions
raylib::RaylibException Throws if the music failed to load.
Definition at line 198 of file Music.hpp.
{
        set(::LoadMusicStream(fileName.c_str()));
        if (!IsReady()) {
            throw RaylibException(TextFormat("Failed to load Music from file: %s", fileName.c_str()));
        }
    }
References IsReady(), LoadMusicStream(), set(), and TextFormat().
Load() [2/2]
void raylib::Music::Load (const std::string & fileType, unsigned char * data, int dataSize) inline
Load music stream from memory
Exceptions
raylib::RaylibException Throws if the music failed to load.
Definition at line 210 of file Music.hpp.
{
        set(::LoadMusicStreamFromMemory(fileType.c_str(), data, dataSize));
        if (!IsReady()) {
            throw RaylibException(TextFormat("Failed to load Music from %s file dat", fileType.c_str()));
        }
    }
References IsReady(), LoadMusicStreamFromMemory(), set(), and TextFormat().
operator=() [1/3]
Music & raylib::Music::operator= (const ::Music & music) inline
Definition at line 69 of file Music.hpp.
{
        set(music);
        return *this;
    }
References set().
operator=() [2/3]
Music & raylib::Music::operator= (const Music &) delete
operator=() [3/3]
Music & raylib::Music::operator= (Music && other) inline noexcept
Definition at line 76 of file Music.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.ctxType = 0;
        other.ctxData = nullptr;
        other.looping = false;
        other.frameCount = 0;
        other.stream = {};
        return *this;
    }
References set(), and Unload().
Pause()
Music & raylib::Music::Pause () inline
Pause music playing
Definition at line 127 of file Music.hpp.
{
        ::PauseMusicStream(*this);
        return *this;
    }
References PauseMusicStream().
Play()
Music & raylib::Music::Play () inline
Start music playing
Definition at line 103 of file Music.hpp.
{
        ::PlayMusicStream(*this);
        return *this;
    }
References PlayMusicStream().
Resume()
Music & raylib::Music::Resume () inline
Resume music playing
Definition at line 135 of file Music.hpp.
{
        ::ResumeMusicStream(*this);
        return *this;
    }
References ResumeMusicStream().
Seek()
Music & raylib::Music::Seek (float position) inline
Seek music to a position (in seconds)
Definition at line 143 of file Music.hpp.
{
        SeekMusicStream(*this, position);
        return *this;
    }
References SeekMusicStream().
set()
void raylib::Music::set (const ::Music & music) inline protected
Definition at line 227 of file Music.hpp.
{
        stream = music.stream;
        frameCount = music.frameCount;
        looping = music.looping;
        ctxType = music.ctxType;
        ctxData = music.ctxData;
    }
References Music::ctxData, Music::ctxType, Music::frameCount, Music::looping, and Music::stream.
SetCtxData()
void raylib::Music::SetCtxData (void * value) inline
Sets the ctxData value for the object.
Parameters
value The value of which to set ctxData to.
Definition at line 67 of file Music.hpp.
SetCtxType()
void raylib::Music::SetCtxType (int value) inline
Sets the ctxType value for the object.
Parameters
value The value of which to set ctxType to.
Definition at line 66 of file Music.hpp.
SetFrameCount()
void raylib::Music::SetFrameCount (unsigned int value) inline
Sets the frameCount value for the object.
Parameters
value The value of which to set frameCount to.
Definition at line 64 of file Music.hpp.
SetLooping()
void raylib::Music::SetLooping (bool value) inline
Sets the looping value for the object.
Parameters
value The value of which to set looping to.
Definition at line 65 of file Music.hpp.
SetPan()
Music & raylib::Music::SetPan (float pan = 0.5f) inline
Set pan for a music (0.5 is center)
Definition at line 174 of file Music.hpp.
{
        ::SetMusicPan(*this, pan);
        return *this;
    }
References SetMusicPan().
SetPitch()
Music & raylib::Music::SetPitch (float pitch) inline
Set pitch for music
Definition at line 166 of file Music.hpp.
{
        ::SetMusicPitch(*this, pitch);
        return *this;
    }
References SetMusicPitch().
SetStream()
void raylib::Music::SetStream (::AudioStream value) inline
Sets the stream value for the object.
Parameters
value The value of which to set stream to.
Definition at line 63 of file Music.hpp.
SetVolume()
Music & raylib::Music::SetVolume (float volume) inline
Set volume for music
Definition at line 158 of file Music.hpp.
{
        ::SetMusicVolume(*this, volume);
        return *this;
    }
References SetMusicVolume().
Stop()
Music & raylib::Music::Stop () inline
Stop music playing
Definition at line 119 of file Music.hpp.
{
        ::StopMusicStream(*this);
        return *this;
    }
References StopMusicStream().
Unload()
void raylib::Music::Unload () inline
Unload music stream
Definition at line 96 of file Music.hpp.
{
        ::UnloadMusicStream(*this);
    }
References UnloadMusicStream().
Update()
Music & raylib::Music::Update () inline
Updates buffers for music streaming
Definition at line 111 of file Music.hpp.
{
        ::UpdateMusicStream(*this);
        return *this;
    }
References UpdateMusicStream().
Member Data Documentation
ctxData
void* Music::ctxData inherited
Definition at line 473 of file raylib.h.
ctxType
int Music::ctxType inherited
Definition at line 472 of file raylib.h.
frameCount
unsigned int Music::frameCount inherited
Definition at line 469 of file raylib.h.
looping
bool Music::looping inherited
Definition at line 470 of file raylib.h.
stream
AudioStream Music::stream inherited
Definition at line 468 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Music.hpp