Techstorm-rivalry: Block Class Reference
Block Class Reference
#include <Block.h>
Public Member Functions
void Draw () override
Block (Vector3 position, const Color color, Shader shader, Model model)
void onUpdate () override
void onDestroy () const override
virtual ~Block ()
Public Attributes
Color color
bool deleteRequested
const Mesh mesh = GenMeshCube(1 , 1 , 1)
Vector3 position
Model model
Static Public Attributes
static Vector2 blockTextureTiling = Vector2{ 0.5f, 0.5f }
Detailed Description
Definition at line 15 of file Block.h.
Constructor & Destructor Documentation
Block()
Block::Block (Vector3 position, const Color color, Shader shader, Model model) inline
Definition at line 25 of file Block.h.
                                                                           : color(color), position(position), model(model)
    {
        Logman::CustomLog(LOG_TRACE, "Block Constructor", NULL);
        this->model = model;
        const static Texture2D Bricks = LoadTexture("resources/textures/Block/Brick/Brick.png");
        this->model.materials[0].shader = shader;
        this->model.materials[0].maps[MATERIAL_MAP_ALBEDO].color = WHITE;
        this->model.materials[0].maps[MATERIAL_MAP_METALNESS].value = 1.0f;
        this->model.materials[0].maps[MATERIAL_MAP_ROUGHNESS].value = 0.0f;
        this->model.materials[0].maps[MATERIAL_MAP_OCCLUSION].value = 1.0f;
        this->model.materials[0].maps[MATERIAL_MAP_EMISSION].color = Color{ 255, 162, 0, 100 };
        //this->model.materials[0].maps[MATERIAL_MAP_DIFFUSE].texture = Bricks;
        this->model.materials[0].maps[MATERIAL_MAP_ALBEDO].texture = Bricks;
        this->model.materials[0].maps[MATERIAL_MAP_METALNESS].texture = LoadTexture("resources/textures/Block/Brick/brickMRAO.png");
        this->model.materials[0].maps[MATERIAL_MAP_NORMAL].texture = LoadTexture("resources/textures/Block/Brick/brick_NORM.png");
        this->model.materials[0].maps[MATERIAL_MAP_HEIGHT].texture = LoadTexture("resources/textures/Block/Brick/brick_DISP.png");
        //this->model.materials[0].maps[MATERIAL_MAP_EMISSION].texture = LoadTexture("resources/textures/Old_Car/old_car_e.png");
        /*
        *
        *
        *
        *
        *
        *         this->model.materials[0].maps[MATERIAL_MAP_ALBEDO].texture = LoadTexture("resources/textures/Old_Car/old_car_d.png");
        this->model.materials[0].maps[MATERIAL_MAP_METALNESS].texture = LoadTexture("resources/textures/Old_Car/old_car_mra.png");
        this->model.materials[0].maps[MATERIAL_MAP_NORMAL].texture = LoadTexture("resources/textures/Old_Car/old_car_n.png");
                // Setup materials[0].maps default parameters
        //
        // Setup materials[0].maps default textures
   //
        // Setup materials[0].maps default textures
    */
    // UnloadTexture(Bricks);
    }
References MaterialMap::color, Logman::CustomLog(), LoadTexture(), LOG_TRACE, Material::maps, MATERIAL_MAP_ALBEDO, MATERIAL_MAP_EMISSION, MATERIAL_MAP_HEIGHT, MATERIAL_MAP_METALNESS, MATERIAL_MAP_NORMAL, MATERIAL_MAP_OCCLUSION, MATERIAL_MAP_ROUGHNESS, Model::materials, model, Material::shader, MaterialMap::texture, MaterialMap::value, and WHITE.
~Block()
virtual Block::~Block () inline virtual
Definition at line 84 of file Block.h.
    {
        deleteRequested = true;
    }
References deleteRequested.
Member Function Documentation
Draw()
void Block::Draw () inline override virtual
Reimplemented from GameObject.
Definition at line 19 of file Block.h.
    {
            DrawModel(model, position, 1.0f, color);
    }
References color, DrawModel(), model, and position.
onDestroy()
void Block::onDestroy () const inline override virtual
Implements GameObject.
Definition at line 77 of file Block.h.
    {
        delete this;
    };
onUpdate()
void Block::onUpdate () inline override virtual
Reimplemented from GameObject.
Definition at line 73 of file Block.h.
    {
    };
Member Data Documentation
blockTextureTiling
Vector2 Block::blockTextureTiling = Vector2{ 0.5f, 0.5f } inline static
Definition at line 93 of file Block.h.
{ 0.5f, 0.5f };
color
Color Block::color
Definition at line 90 of file Block.h.
deleteRequested
bool Block::deleteRequested
Definition at line 92 of file Block.h.
mesh
const Mesh Block::mesh = GenMeshCube(1 , 1 , 1)
Definition at line 95 of file Block.h.
model
Model Block::model
Definition at line 97 of file Block.h.
position
Vector3 Block::position
Definition at line 96 of file Block.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Block.h