Techstorm-rivalry: toml::v3::impl::formatter Class Reference
toml::v3::impl::formatter Class Reference
#include <toml.h>
Protected Member Functions
const node & source () const noexcept
std::ostream & stream () const noexcept
int indent () const noexcept
void indent (int level) noexcept
void increase_indent () noexcept
void decrease_indent () noexcept
size_t indent_columns () const noexcept
bool indent_array_elements () const noexcept
bool indent_sub_tables () const noexcept
bool literal_strings_allowed () const noexcept
bool multi_line_strings_allowed () const noexcept
bool real_tabs_in_strings_allowed () const noexcept
bool unicode_strings_allowed () const noexcept
bool terse_kvps () const noexcept
void attach (std::ostream &stream) noexcept
void detach () noexcept
void print_newline (bool force=false)
void print_indent ()
void print_unformatted (char)
void print_unformatted (std::string_view)
void print_string (std::string_view str, bool allow_multi_line=true, bool allow_bare=false)
void print (const value< std::string > &)
void print (const value< int64_t > &)
void print (const value< double > &)
void print (const value< bool > &)
void print (const value< date > &)
void print (const value< time > &)
void print (const value< date_time > &)
void print_value (const node &, node_type)
bool dump_failed_parse_result ()
formatter (const node *, const parse_result *, const formatter_constants &, const formatter_config &) noexcept
Detailed Description
Definition at line 9275 of file toml.h.
Constructor & Destructor Documentation
formatter()
toml::v3::impl::formatter::formatter (const node * source_node, const parse_result * source_pr, const formatter_constants & constants, const formatter_config & config) inline protected noexcept
Definition at line 15942 of file toml.h.
        : source_{ source_pr && *source_pr ? &source_pr->table() : source_node },
          result_{ source_pr },
#else
        : source_{ source_pr ? source_pr : source_node },
#endif
          constants_{ &constants },
          config_{ config }
    {
        TOML_ASSERT_ASSUME(source_);
        config_.flags = (config_.flags | constants_->mandatory_flags) & ~constants_->ignored_flags;
        indent_columns_ = {};
        for (auto c : config_.indent)
            indent_columns_ += c == '\t' ? 4u : 1u;
        int_format_mask_ = config_.flags
                         & (format_flags::allow_binary_integers | format_flags::allow_octal_integers
                            | format_flags::allow_hexadecimal_integers);
    }
Member Function Documentation
attach()
void toml::v3::impl::formatter::attach (std::ostream & stream) inline protected noexcept
Definition at line 15969 of file toml.h.
    {
        indent_ = {};
        naked_newline_ = true;
        stream_ = &stream;
    }
decrease_indent()
void toml::v3::impl::formatter::decrease_indent () inline protected noexcept
Definition at line 9319 of file toml.h.
        {
            indent_--;
        }
detach()
void toml::v3::impl::formatter::detach () inline protected noexcept
Definition at line 15977 of file toml.h.
    {
        stream_ = nullptr;
    }
dump_failed_parse_result()
bool toml::v3::impl::formatter::dump_failed_parse_result () inline protected
Definition at line 16390 of file toml.h.
    {
        if (result_ && !(*result_))
        {
            stream() << result_->error();
            return true;
        }
        return false;
    }
References toml::v3::noex::parse_result::error().
increase_indent()
void toml::v3::impl::formatter::increase_indent () inline protected noexcept
Definition at line 9314 of file toml.h.
        {
            indent_++;
        }
indent() [1/2]
int toml::v3::impl::formatter::indent () const inline protected noexcept
Definition at line 9304 of file toml.h.
        {
            return indent_;
        }
indent() [2/2]
void toml::v3::impl::formatter::indent (int level) inline protected noexcept
Definition at line 9309 of file toml.h.
        {
            indent_ = level;
        }
indent_array_elements()
bool toml::v3::impl::formatter::indent_array_elements () const inline protected noexcept
Definition at line 9331 of file toml.h.
        {
            return !!(config_.flags & format_flags::indent_array_elements);
        }
References toml::v3::impl::formatter_config::flags.
indent_columns()
size_t toml::v3::impl::formatter::indent_columns () const inline protected noexcept
Definition at line 9325 of file toml.h.
        {
            return indent_columns_;
        }
indent_sub_tables()
bool toml::v3::impl::formatter::indent_sub_tables () const inline protected noexcept
Definition at line 9337 of file toml.h.
        {
            return !!(config_.flags & format_flags::indent_sub_tables);
        }
References toml::v3::impl::formatter_config::flags.
literal_strings_allowed()
bool toml::v3::impl::formatter::literal_strings_allowed () const inline protected noexcept
Definition at line 9343 of file toml.h.
        {
            return !!(config_.flags & format_flags::allow_literal_strings);
        }
References toml::v3::impl::formatter_config::flags.
multi_line_strings_allowed()
bool toml::v3::impl::formatter::multi_line_strings_allowed () const inline protected noexcept
Definition at line 9349 of file toml.h.
        {
            return !!(config_.flags & format_flags::allow_multi_line_strings);
        }
References toml::v3::impl::formatter_config::flags.
print() [1/7]
void toml::v3::impl::formatter::print (const value< bool > & val) inline protected
Definition at line 16335 of file toml.h.
    {
        print_unformatted(*val ? constants_->bool_true : constants_->bool_false);
    }
References toml::v3::impl::formatter_constants::bool_false, and toml::v3::impl::formatter_constants::bool_true.
print() [2/7]
void toml::v3::impl::formatter::print (const value< date > & val) inline protected
Definition at line 16341 of file toml.h.
    {
        if (!!(config_.flags & format_flags::quote_dates_and_times))
            print_to_stream_bookended(*stream_, *val, literal_strings_allowed() ? '\'' : '"');
        else
            print_to_stream(*stream_, *val);
        naked_newline_ = false;
    }
References toml::v3::impl::formatter_config::flags, toml::v3::impl::print_to_stream(), toml::v3::impl::print_to_stream_bookended(), and toml::v3::quote_dates_and_times.
print() [3/7]
void toml::v3::impl::formatter::print (const value< date_time > & val) inline protected
Definition at line 16361 of file toml.h.
    {
        if (!!(config_.flags & format_flags::quote_dates_and_times))
            print_to_stream_bookended(*stream_, *val, literal_strings_allowed() ? '\'' : '"');
        else
            print_to_stream(*stream_, *val);
        naked_newline_ = false;
    }
References toml::v3::impl::formatter_config::flags, toml::v3::impl::print_to_stream(), toml::v3::impl::print_to_stream_bookended(), and toml::v3::quote_dates_and_times.
print() [4/7]
void toml::v3::impl::formatter::print (const value< double > & val) inline protected
Definition at line 16306 of file toml.h.
    {
        const std::string_view* inf_nan = nullptr;
        switch (fpclassify(*val))
        {
            case fp_class::neg_inf: inf_nan = &constants_->float_neg_inf; break;
            case fp_class::pos_inf: inf_nan = &constants_->float_pos_inf; break;
            case fp_class::nan: inf_nan = &constants_->float_nan; break;
            case fp_class::ok:
                print_to_stream(*stream_,
                                *val,
                                value_flags::none,
                                !!(config_.flags & format_flags::relaxed_float_precision));
                break;
            default: TOML_UNREACHABLE;
        }
        if (inf_nan)
        {
            if (!!(config_.flags & format_flags::quote_infinities_and_nans))
                print_to_stream_bookended(*stream_, *inf_nan, '"');
            else
                print_to_stream(*stream_, *inf_nan);
        }
        naked_newline_ = false;
    }
References toml::v3::impl::formatter_config::flags, toml::v3::impl::formatter_constants::float_nan, toml::v3::impl::formatter_constants::float_neg_inf, toml::v3::impl::formatter_constants::float_pos_inf, toml::v3::impl::fpclassify(), toml::v3::none, toml::v3::impl::print_to_stream(), toml::v3::impl::print_to_stream_bookended(), toml::v3::quote_infinities_and_nans, toml::v3::relaxed_float_precision, and TOML_UNREACHABLE.
print() [5/7]
void toml::v3::impl::formatter::print (const value< int64_t > & val) inline protected
Definition at line 16258 of file toml.h.
    {
        naked_newline_ = false;
        if (*val >= 0 && !!int_format_mask_)
        {
            static constexpr auto value_flags_mask =
                value_flags::format_as_binary | value_flags::format_as_octal | value_flags::format_as_hexadecimal;
            const auto fmt = val.flags() & value_flags_mask;
            switch (fmt)
            {
                case value_flags::format_as_binary:
                    if (!!(int_format_mask_ & format_flags::allow_binary_integers))
                    {
                        print_to_stream(*stream_, "0b"sv);
                        print_to_stream(*stream_, *val, fmt);
                        return;
                    }
                    break;
                case value_flags::format_as_octal:
                    if (!!(int_format_mask_ & format_flags::allow_octal_integers))
                    {
                        print_to_stream(*stream_, "0o"sv);
                        print_to_stream(*stream_, *val, fmt);
                        return;
                    }
                    break;
                case value_flags::format_as_hexadecimal:
                    if (!!(int_format_mask_ & format_flags::allow_hexadecimal_integers))
                    {
                        print_to_stream(*stream_, "0x"sv);
                        print_to_stream(*stream_, *val, fmt);
                        return;
                    }
                    break;
                default: break;
            }
        }
        // fallback to decimal
        print_to_stream(*stream_, *val);
    }
References toml::v3::allow_binary_integers, toml::v3::allow_hexadecimal_integers, toml::v3::allow_octal_integers, toml::v3::value< ValueType >::flags(), toml::v3::format_as_binary, toml::v3::format_as_hexadecimal, toml::v3::format_as_octal, and toml::v3::impl::print_to_stream().
print() [6/7]
void toml::v3::impl::formatter::print (const value< std::string > & val) inline protected
Definition at line 16252 of file toml.h.
    {
        print_string(val.get());
    }
References toml::v3::value< ValueType >::get().
print() [7/7]
void toml::v3::impl::formatter::print (const value< time > & val) inline protected
Definition at line 16351 of file toml.h.
    {
        if (!!(config_.flags & format_flags::quote_dates_and_times))
            print_to_stream_bookended(*stream_, *val, literal_strings_allowed() ? '\'' : '"');
        else
            print_to_stream(*stream_, *val);
        naked_newline_ = false;
    }
References toml::v3::impl::formatter_config::flags, toml::v3::impl::print_to_stream(), toml::v3::impl::print_to_stream_bookended(), and toml::v3::quote_dates_and_times.
print_indent()
void toml::v3::impl::formatter::print_indent () inline protected
Definition at line 15993 of file toml.h.
    {
        for (int i = 0; i < indent_; i++)
        {
            print_to_stream(*stream_, config_.indent);
            naked_newline_ = false;
        }
    }
References toml::v3::impl::formatter_config::indent, and toml::v3::impl::print_to_stream().
print_newline()
void toml::v3::impl::formatter::print_newline (bool force = false) inline protected
Definition at line 15983 of file toml.h.
    {
        if (!naked_newline_ || force)
        {
            print_to_stream(*stream_, '\n');
            naked_newline_ = true;
        }
    }
References toml::v3::impl::print_to_stream().
print_string()
void toml::v3::impl::formatter::print_string (std::string_view str, bool allow_multi_line = true, bool allow_bare = false) inline protected
Definition at line 16017 of file toml.h.
    {
        if (str.empty())
        {
            print_unformatted(literal_strings_allowed() ? "''"sv : "\"\""sv);
            return;
        }
        // pre-scan the string to determine how we should output it
        formatted_string_traits traits = {};
        if (!allow_bare)
            traits |= formatted_string_traits::non_bare;
        bool unicode_allowed = unicode_strings_allowed();
        // ascii fast path
        if (is_ascii(str.data(), str.length()))
        {
            for (auto c : str)
            {
                switch (c)
                {
                    case '\n': traits |= formatted_string_traits::line_breaks; break;
                    case '\t': traits |= formatted_string_traits::tabs; break;
                    case '\'': traits |= formatted_string_traits::single_quotes; break;
                    default:
                    {
                        if TOML_UNLIKELY(is_control_character(c))
                            traits |= formatted_string_traits::control_chars;
                        if (!is_ascii_bare_key_character(static_cast<char32_t>(c)))
                            traits |= formatted_string_traits::non_bare;
                        break;
                    }
                }
                static constexpr auto all_ascii_traits =
                    formatted_string_traits::all & ~formatted_string_traits::non_ascii;
                if (traits == all_ascii_traits)
                    break;
            }
        }
        // unicode slow path
        else
        {
            traits |= formatted_string_traits::non_ascii;
            utf8_decoder decoder;
            // if the unicode is malformed just treat the string as a single-line non-literal and
            // escape all non-ascii characters (to ensure round-tripping and help with diagnostics)
            const auto bad_unicode = [&]() noexcept
            {
                traits &= ~formatted_string_traits::line_breaks;
                traits |= formatted_string_traits::control_chars | formatted_string_traits::non_bare;
                unicode_allowed = false;
            };
            for (auto c : str)
            {
                decoder(c);
                if TOML_UNLIKELY(decoder.error())
                {
                    bad_unicode();
                    break;
                }
                if (!decoder.has_code_point())
                    continue;
                switch (decoder.codepoint)
                {
                    case U'\n': traits |= formatted_string_traits::line_breaks; break;
                    case U'\t': traits |= formatted_string_traits::tabs; break;
                    case U'\'': traits |= formatted_string_traits::single_quotes; break;
                    default:
                    {
                        if TOML_UNLIKELY(is_control_character(decoder.codepoint)
                            || is_non_ascii_vertical_whitespace(decoder.codepoint))
                            traits |= formatted_string_traits::control_chars;
                        if (!is_bare_key_character(decoder.codepoint))
                            traits |= formatted_string_traits::non_bare;
                        break;
                    }
                }
            }
            if (decoder.needs_more_input())
                bad_unicode();
        }
        // if the string meets the requirements of being 'bare' we can emit a bare string
        // (bare strings are composed of letters and numbers; no whitespace, control chars, quotes, etc)
        if (!(traits & formatted_string_traits::non_bare)
            && (!(traits & formatted_string_traits::non_ascii) || unicode_allowed))
        {
            print_unformatted(str);
            return;
        }
        // determine if this should be a multi-line string (triple-quotes)
        const auto multi_line = allow_multi_line             //
                             && multi_line_strings_allowed() //
                             && !!(traits & formatted_string_traits::line_breaks);
        // determine if this should be a literal string (single-quotes with no escaping)
        const auto literal = literal_strings_allowed()                                                     //
                          && !(traits & formatted_string_traits::control_chars)                            //
                          && (!(traits & formatted_string_traits::single_quotes) || multi_line)            //
                          && (!(traits & formatted_string_traits::tabs) || real_tabs_in_strings_allowed()) //
                          && (!(traits & formatted_string_traits::non_ascii) || unicode_allowed);
        // literal strings (single quotes, no escape codes)
        if (literal)
        {
            const auto quot = multi_line ? R"(''')"sv : R"(')"sv;
            print_unformatted(quot);
            print_unformatted(str);
            print_unformatted(quot);
            return;
        }
        // anything from here down is a non-literal string, so requires iteration and escaping.
        print_unformatted(multi_line ? R"(""")"sv : R"(")"sv);
        const auto real_tabs_allowed = real_tabs_in_strings_allowed();
        // ascii fast path
        if (!(traits & formatted_string_traits::non_ascii))
        {
            for (auto c : str)
            {
                switch (c)
                {
                    case '"': print_to_stream(*stream_, R"(\")"sv); break;
                    case '\\': print_to_stream(*stream_, R"(\\)"sv); break;
                    case '\x7F': print_to_stream(*stream_, R"(\u007F)"sv); break;
                    case '\t': print_to_stream(*stream_, real_tabs_allowed ? "\t"sv : R"(\t)"sv); break;
                    case '\n': print_to_stream(*stream_, multi_line ? "\n"sv : R"(\n)"sv); break;
                    default:
                    {
                        // control characters from lookup table
                        if TOML_UNLIKELY(c >= '\x00' && c <= '\x1F')
                            print_to_stream(*stream_, control_char_escapes[c]);
                        // regular characters
                        else
                            print_to_stream(*stream_, c);
                    }
                }
            }
        }
        // unicode slow path
        else
        {
            utf8_decoder decoder;
            const char* cp_start = str.data();
            const char* cp_end = cp_start;
            for (auto c : str)
            {
                decoder(c);
                cp_end++;
                // if the decoder encounters malformed unicode just emit raw bytes and
                if (decoder.error())
                {
                    while (cp_start != cp_end)
                    {
                        print_to_stream(*stream_, R"(\u00)"sv);
                        print_to_stream(*stream_,
                                        static_cast<uint8_t>(*cp_start),
                                        value_flags::format_as_hexadecimal,
                                        2);
                        cp_start++;
                    }
                    decoder.reset();
                    continue;
                }
                if (!decoder.has_code_point())
                    continue;
                switch (decoder.codepoint)
                {
                    case U'"': print_to_stream(*stream_, R"(\")"sv); break;
                    case U'\\': print_to_stream(*stream_, R"(\\)"sv); break;
                    case U'\x7F': print_to_stream(*stream_, R"(\u007F)"sv); break;
                    case U'\t': print_to_stream(*stream_, real_tabs_allowed ? "\t"sv : R"(\t)"sv); break;
                    case U'\n': print_to_stream(*stream_, multi_line ? "\n"sv : R"(\n)"sv); break;
                    default:
                    {
                        // control characters from lookup table
                        if TOML_UNLIKELY(decoder.codepoint <= U'\x1F')
                            print_to_stream(*stream_,
                                            control_char_escapes[static_cast<uint_least32_t>(decoder.codepoint)]);
                        // escaped unicode characters
                        else if (decoder.codepoint > U'\x7F'
                                 && (!unicode_allowed || is_non_ascii_vertical_whitespace(decoder.codepoint)))
{
                            if (static_cast<uint_least32_t>(decoder.codepoint) > 0xFFFFu)
{
                                print_to_stream(*stream_, R"(\U)"sv);
                                print_to_stream(*stream_,
                                                static_cast<uint_least32_t>(decoder.codepoint),
                                                value_flags::format_as_hexadecimal,
                                                8);
                            }
                            else
{
                                print_to_stream(*stream_, R"(\u)"sv);
                                print_to_stream(*stream_,
                                                static_cast<uint_least32_t>(decoder.codepoint),
                                                value_flags::format_as_hexadecimal,
                                                4);
                            }
                        }
                        // regular characters
                        else
                            print_to_stream(*stream_, cp_start, static_cast<size_t>(cp_end - cp_start));
                    }
                }
                cp_start = cp_end;
            }
        }
        print_unformatted(multi_line ? R"(""")"sv : R"(")"sv);
    }
References toml::v3::impl::utf8_decoder::codepoint, toml::v3::impl::control_char_escapes, toml::v3::impl::utf8_decoder::error(), toml::v3::format_as_hexadecimal, toml::v3::impl::utf8_decoder::has_code_point(), toml::v3::impl::is_ascii(), toml::v3::impl::is_ascii_bare_key_character(), toml::v3::impl::is_bare_key_character(), toml::v3::impl::is_control_character(), toml::v3::impl::is_non_ascii_vertical_whitespace(), toml::v3::impl::utf8_decoder::needs_more_input(), toml::v3::impl::print_to_stream(), toml::v3::impl::utf8_decoder::reset(), and TOML_UNLIKELY.
print_unformatted() [1/2]
void toml::v3::impl::formatter::print_unformatted (char c) inline protected
Definition at line 16003 of file toml.h.
    {
        print_to_stream(*stream_, c);
        naked_newline_ = false;
    }
References toml::v3::impl::print_to_stream().
print_unformatted() [2/2]
void toml::v3::impl::formatter::print_unformatted (std::string_view str) inline protected
Definition at line 16010 of file toml.h.
    {
        print_to_stream(*stream_, str);
        naked_newline_ = false;
    }
References toml::v3::impl::print_to_stream().
print_value()
void toml::v3::impl::formatter::print_value (const node & val_node, node_type type) inline protected
Definition at line 16371 of file toml.h.
    {
        TOML_ASSUME(type > node_type::array);
        switch (type)
        {
            case node_type::string: print(*reinterpret_cast<const value<std::string>*>(&val_node)); break;
            case node_type::integer: print(*reinterpret_cast<const value<int64_t>*>(&val_node)); break;
            case node_type::floating_point: print(*reinterpret_cast<const value<double>*>(&val_node)); break;
            case node_type::boolean: print(*reinterpret_cast<const value<bool>*>(&val_node)); break;
            case node_type::date: print(*reinterpret_cast<const value<date>*>(&val_node)); break;
            case node_type::time: print(*reinterpret_cast<const value<time>*>(&val_node)); break;
            case node_type::date_time: print(*reinterpret_cast<const value<date_time>*>(&val_node)); break;
            default: TOML_UNREACHABLE;
        }
    }
References toml::v3::array, toml::v3::boolean, toml::v3::date, toml::v3::date_time, toml::v3::floating_point, toml::v3::integer, toml::v3::string, toml::v3::time, TOML_ASSUME, and TOML_UNREACHABLE.
real_tabs_in_strings_allowed()
bool toml::v3::impl::formatter::real_tabs_in_strings_allowed () const inline protected noexcept
Definition at line 9355 of file toml.h.
        {
            return !!(config_.flags & format_flags::allow_real_tabs_in_strings);
        }
References toml::v3::impl::formatter_config::flags.
source()
const node & toml::v3::impl::formatter::source () const inline protected noexcept
Definition at line 9292 of file toml.h.
        {
            return *source_;
        }
stream()
std::ostream & toml::v3::impl::formatter::stream () const inline protected noexcept
Definition at line 9298 of file toml.h.
        {
            return *stream_;
        }
terse_kvps()
bool toml::v3::impl::formatter::terse_kvps () const inline protected noexcept
Definition at line 9367 of file toml.h.
        {
            return !!(config_.flags & format_flags::terse_key_value_pairs);
        }
References toml::v3::impl::formatter_config::flags.
unicode_strings_allowed()
bool toml::v3::impl::formatter::unicode_strings_allowed () const inline protected noexcept
Definition at line 9361 of file toml.h.
        {
            return !!(config_.flags & format_flags::allow_unicode_strings);
        }
References toml::v3::impl::formatter_config::flags.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/toml.h