Techstorm-rivalry: Game::Renderer Class Reference
Game::Renderer Class Reference
#include <Game.h>
Public Member Functions
void StartDraw ()
void EndDraw ()
void Start3D (Camera *camera)
void End3D ()
void StartTexturing ()
void StartDepthMode ()
void StopDepthMode ()
void StopTexturing ()
void CreateRenderTexture (int width, int height)
Public Attributes
RenderTexture2D fbo
RenderTexture2D depthMapFBO
Shader pbrShader
Shader bloomShader
Detailed Description
Definition at line 12 of file Game.h.
Member Function Documentation
CreateRenderTexture()
void Game::Renderer::CreateRenderTexture (int width, int height) inline
Definition at line 81 of file Game.h.
        {
            fbo = LoadRenderTexture(width, height);
            depthMapFBO = LoadRenderTexture(width, height);
        }
References depthMapFBO, fbo, and LoadRenderTexture().
End3D()
void Game::Renderer::End3D () inline
Definition at line 44 of file Game.h.
        {
            if (isIn3DMode && isDrawing)
            {
                EndMode3D();
                isIn3DMode = false;
            }
        }
References EndMode3D().
EndDraw()
void Game::Renderer::EndDraw () inline
Definition at line 23 of file Game.h.
        {
            isDrawing = false;
            EndDrawing();
        }
References EndDrawing().
Start3D()
void Game::Renderer::Start3D (Camera * camera) inline
Definition at line 30 of file Game.h.
        {
            if (!isDrawing)
            {
                StartDraw();
            }
            else
            {
                isIn3DMode = true;
                BeginMode3D(*camera);
            }
        }
References BeginMode3D(), and StartDraw().
StartDepthMode()
void Game::Renderer::StartDepthMode () inline
Definition at line 62 of file Game.h.
        {
            BeginTextureMode(depthMapFBO);
        }
References BeginTextureMode(), and depthMapFBO.
StartDraw()
void Game::Renderer::StartDraw () inline
Definition at line 16 of file Game.h.
        {
            isDrawing = true;
            BeginDrawing();
        }
References BeginDrawing().
StartTexturing()
void Game::Renderer::StartTexturing () inline
Definition at line 54 of file Game.h.
        {
            // StartDraw();
            BeginTextureMode(fbo);
            ClearBackground(BLACK);
        }
References BeginTextureMode(), BLACK, ClearBackground(), and fbo.
StopDepthMode()
void Game::Renderer::StopDepthMode () inline
Definition at line 68 of file Game.h.
        {
            EndTextureMode();
        }
References EndTextureMode().
StopTexturing()
void Game::Renderer::StopTexturing () inline
Definition at line 74 of file Game.h.
        {
            // EndDraw();
            EndTextureMode();
        }
References EndTextureMode().
Member Data Documentation
bloomShader
Shader Game::Renderer::bloomShader
Definition at line 93 of file Game.h.
depthMapFBO
RenderTexture2D Game::Renderer::depthMapFBO
Definition at line 88 of file Game.h.
fbo
RenderTexture2D Game::Renderer::fbo
Definition at line 87 of file Game.h.
pbrShader
Shader Game::Renderer::pbrShader
Definition at line 91 of file Game.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Game.h