Techstorm-rivalry: raylib::AudioStream Class Reference
raylib::AudioStream Class Reference
#include <AudioStream.hpp>
Public Member Functions
AudioStream (const ::AudioStream &music)
AudioStream (rAudioBuffer *buffer=nullptr, rAudioProcessor *processor=nullptr, unsigned int sampleRate=0, unsigned int sampleSize=0, unsigned int channels=0)
AudioStream (unsigned int sampleRate, unsigned int sampleSize, unsigned int channels=2)
AudioStream (const AudioStream &)=delete
AudioStream (AudioStream &&other)
~AudioStream ()
rAudioBuffer * GetBuffer () const
void SetBuffer (rAudioBuffer *value)
rAudioProcessor * GetProcessor () const
void SetProcessor (rAudioProcessor *value)
unsigned int GetSampleRate () const
void SetSampleRate (unsigned int value)
unsigned int GetSampleSize () const
void SetSampleSize (unsigned int value)
unsigned int GetChannels () const
void SetChannels (unsigned int value)
AudioStream & operator= (const ::AudioStream &stream)
AudioStream & operator= (const AudioStream &)=delete
AudioStream & operator= (AudioStream &&other) noexcept
AudioStream & Update (const void *data, int samplesCount)
void Unload ()
bool IsProcessed () const
AudioStream & Play ()
AudioStream & Pause ()
AudioStream & Resume ()
bool IsPlaying () const
AudioStream & Stop ()
AudioStream & SetVolume (float volume=1.0f)
AudioStream & SetPitch (float pitch)
AudioStream & SetPan (float pan=0.5f)
void SetCallback (::AudioCallback callback)
void AttachProcessor (::AudioCallback processor)
void DetachProcessor (::AudioCallback processor)
bool IsReady () const
void Load (unsigned int SampleRate, unsigned int SampleSize, unsigned int Channels=2)
Static Public Member Functions
static void SetBufferSizeDefault (int size)
Public Attributes
rAudioBuffer * buffer
rAudioProcessor * processor
unsigned int sampleRate
unsigned int sampleSize
unsigned int channels
Protected Member Functions
void set (const ::AudioStream &stream)
Detailed Description
AudioStream management functions
Definition at line 12 of file AudioStream.hpp.
Constructor & Destructor Documentation
AudioStream() [1/5]
raylib::AudioStream::AudioStream (const ::AudioStream & music) inline
Definition at line 14 of file AudioStream.hpp.
{
        set(music);
    }
References set().
AudioStream() [2/5]
raylib::AudioStream::AudioStream (rAudioBuffer * buffer = nullptr, rAudioProcessor * processor = nullptr, unsigned int sampleRate = 0, unsigned int sampleSize = 0, unsigned int channels = 0) inline
Definition at line 18 of file AudioStream.hpp.
                                       : ::AudioStream{buffer, processor, sampleRate, sampleSize, channels} {
        // Nothing.
    }
AudioStream() [3/5]
raylib::AudioStream::AudioStream (unsigned int sampleRate, unsigned int sampleSize, unsigned int channels = 2) inline
Init audio stream (to stream raw audio pcm data)
Exceptions
raylib::RaylibException Throws if the AudioStream failed to load.
Definition at line 31 of file AudioStream.hpp.
{
        Load(sampleRate, sampleSize, channels);
    }
References AudioStream::channels, Load(), AudioStream::sampleRate, and AudioStream::sampleSize.
AudioStream() [4/5]
raylib::AudioStream::AudioStream (const AudioStream &) delete
AudioStream() [5/5]
raylib::AudioStream::AudioStream (AudioStream && other) inline
Definition at line 37 of file AudioStream.hpp.
{
        set(other);
        other.buffer = nullptr;
        other.processor = nullptr;
        other.sampleRate = 0;
        other.sampleSize = 0;
        other.channels = 0;
    }
References set().
~AudioStream()
raylib::AudioStream::~AudioStream () inline
Definition at line 47 of file AudioStream.hpp.
                   {
        Unload();
    }
References Unload().
Member Function Documentation
AttachProcessor()
void raylib::AudioStream::AttachProcessor (::AudioCallback processor) inline
Attach audio stream processor to stream
Definition at line 183 of file AudioStream.hpp.
{
        ::SetAudioStreamCallback(*this, processor);
    }
References AudioStream::processor, and SetAudioStreamCallback().
DetachProcessor()
void raylib::AudioStream::DetachProcessor (::AudioCallback processor) inline
Detach audio stream processor from stream
Definition at line 190 of file AudioStream.hpp.
{
        ::SetAudioStreamCallback(*this, processor);
    }
References AudioStream::processor, and SetAudioStreamCallback().
GetBuffer()
rAudioBuffer * raylib::AudioStream::GetBuffer () const inline
Retrieves the buffer value for the object.
Returns
The buffer value of the object.
Definition at line 51 of file AudioStream.hpp.
GetChannels()
unsigned int raylib::AudioStream::GetChannels () const inline
Retrieves the channels value for the object.
Returns
The channels value of the object.
Definition at line 55 of file AudioStream.hpp.
GetProcessor()
rAudioProcessor * raylib::AudioStream::GetProcessor () const inline
Retrieves the processor value for the object.
Returns
The processor value of the object.
Definition at line 52 of file AudioStream.hpp.
GetSampleRate()
unsigned int raylib::AudioStream::GetSampleRate () const inline
Retrieves the sampleRate value for the object.
Returns
The sampleRate value of the object.
Definition at line 53 of file AudioStream.hpp.
GetSampleSize()
unsigned int raylib::AudioStream::GetSampleSize () const inline
Retrieves the sampleSize value for the object.
Returns
The sampleSize value of the object.
Definition at line 54 of file AudioStream.hpp.
IsPlaying()
bool raylib::AudioStream::IsPlaying () const inline
Check if audio stream is playing
Definition at line 130 of file AudioStream.hpp.
{
        return ::IsAudioStreamPlaying(*this);
    }
IsProcessed()
bool raylib::AudioStream::IsProcessed () const inline
Check if any audio stream buffers requires refill
Definition at line 99 of file AudioStream.hpp.
{
        return ::IsAudioStreamProcessed(*this);
    }
IsReady()
bool raylib::AudioStream::IsReady () const inline
Retrieve whether or not the audio stream is ready.
Definition at line 197 of file AudioStream.hpp.
{
        return ::IsAudioStreamReady(*this);
    }
Load()
void raylib::AudioStream::Load (unsigned int SampleRate, unsigned int SampleSize, unsigned int Channels = 2) inline
Load audio stream (to stream raw audio pcm data)
Exceptions
raylib::RaylibException Throws if the AudioStream failed to load.
Definition at line 206 of file AudioStream.hpp.
{
        Unload();
        set(::LoadAudioStream(SampleRate, SampleSize, Channels));
        if (!IsReady()) {
            throw RaylibException("Failed to load audio stream");
        }
    }
References IsReady(), LoadAudioStream(), set(), and Unload().
operator=() [1/3]
AudioStream & raylib::AudioStream::operator= (AudioStream && other) inline noexcept
Definition at line 64 of file AudioStream.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.buffer = nullptr;
        other.processor = nullptr;
        other.sampleRate = 0;
        other.sampleSize = 0;
        other.channels = 0;
        return *this;
    }
References set(), and Unload().
operator=() [2/3]
AudioStream & raylib::AudioStream::operator= (const ::AudioStream & stream) inline
Definition at line 57 of file AudioStream.hpp.
{
        set(stream);
        return *this;
    }
References set().
operator=() [3/3]
AudioStream & raylib::AudioStream::operator= (const AudioStream &) delete
Pause()
AudioStream & raylib::AudioStream::Pause () inline
Pause audio stream
Definition at line 114 of file AudioStream.hpp.
{
        ::PauseAudioStream(*this);
        return *this;
    }
References PauseAudioStream().
Play()
AudioStream & raylib::AudioStream::Play () inline
Play audio stream
Definition at line 106 of file AudioStream.hpp.
{
        ::PlayAudioStream(*this);
        return *this;
    }
References PlayAudioStream().
Resume()
AudioStream & raylib::AudioStream::Resume () inline
Resume audio stream
Definition at line 122 of file AudioStream.hpp.
{
        ::ResumeAudioStream(*this);
        return *this;
    }
References ResumeAudioStream().
set()
void raylib::AudioStream::set (const ::AudioStream & stream) inline protected
Definition at line 215 of file AudioStream.hpp.
{
        buffer = stream.buffer;
        processor = stream.processor;
        sampleRate = stream.sampleRate;
        sampleSize = stream.sampleSize;
        channels = stream.channels;
    }
References AudioStream::buffer, AudioStream::channels, AudioStream::processor, AudioStream::sampleRate, and AudioStream::sampleSize.
SetBuffer()
void raylib::AudioStream::SetBuffer (rAudioBuffer * value) inline
Sets the buffer value for the object.
Parameters
value The value of which to set buffer to.
Definition at line 51 of file AudioStream.hpp.
SetBufferSizeDefault()
static void raylib::AudioStream::SetBufferSizeDefault (int size) inline static
Default size for new audio streams
Definition at line 169 of file AudioStream.hpp.
{
        ::SetAudioStreamBufferSizeDefault(size);
    }
References SetAudioStreamBufferSizeDefault().
SetCallback()
void raylib::AudioStream::SetCallback (::AudioCallback callback) inline
Audio thread callback to request new data
Definition at line 176 of file AudioStream.hpp.
{
        ::SetAudioStreamCallback(*this, callback);
    }
References SetAudioStreamCallback().
SetChannels()
void raylib::AudioStream::SetChannels (unsigned int value) inline
Sets the channels value for the object.
Parameters
value The value of which to set channels to.
Definition at line 55 of file AudioStream.hpp.
SetPan()
AudioStream & raylib::AudioStream::SetPan (float pan = 0.5f) inline
Set pan for audio stream (0.5 is centered)
Definition at line 161 of file AudioStream.hpp.
{
        ::SetAudioStreamPitch(*this, pan);
        return *this;
    }
References SetAudioStreamPitch().
SetPitch()
AudioStream & raylib::AudioStream::SetPitch (float pitch) inline
Set pitch for audio stream (1.0 is base level)
Definition at line 153 of file AudioStream.hpp.
{
        ::SetAudioStreamPitch(*this, pitch);
        return *this;
    }
References SetAudioStreamPitch().
SetProcessor()
void raylib::AudioStream::SetProcessor (rAudioProcessor * value) inline
Sets the processor value for the object.
Parameters
value The value of which to set processor to.
Definition at line 52 of file AudioStream.hpp.
SetSampleRate()
void raylib::AudioStream::SetSampleRate (unsigned int value) inline
Sets the sampleRate value for the object.
Parameters
value The value of which to set sampleRate to.
Definition at line 53 of file AudioStream.hpp.
SetSampleSize()
void raylib::AudioStream::SetSampleSize (unsigned int value) inline
Sets the sampleSize value for the object.
Parameters
value The value of which to set sampleSize to.
Definition at line 54 of file AudioStream.hpp.
SetVolume()
AudioStream & raylib::AudioStream::SetVolume (float volume = 1.0f) inline
Set volume for audio stream (1.0 is max level)
Definition at line 145 of file AudioStream.hpp.
{
        ::SetAudioStreamVolume(*this, volume);
        return *this;
    }
References SetAudioStreamVolume().
Stop()
AudioStream & raylib::AudioStream::Stop () inline
Stop audio stream
Definition at line 137 of file AudioStream.hpp.
{
        ::StopAudioStream(*this);
        return *this;
    }
References StopAudioStream().
Unload()
void raylib::AudioStream::Unload () inline
Unload audio stream and free memory
Definition at line 92 of file AudioStream.hpp.
{
        ::UnloadAudioStream(*this);
    }
References UnloadAudioStream().
Update()
AudioStream & raylib::AudioStream::Update (const void * data, int samplesCount) inline
Update audio stream buffers with data
Definition at line 84 of file AudioStream.hpp.
{
        ::UpdateAudioStream(*this, data, samplesCount);
        return *this;
    }
References UpdateAudioStream().
Member Data Documentation
buffer
rAudioBuffer* AudioStream::buffer inherited
Definition at line 452 of file raylib.h.
channels
unsigned int AudioStream::channels inherited
Definition at line 457 of file raylib.h.
processor
rAudioProcessor* AudioStream::processor inherited
Definition at line 453 of file raylib.h.
sampleRate
unsigned int AudioStream::sampleRate inherited
Definition at line 455 of file raylib.h.
sampleSize
unsigned int AudioStream::sampleSize inherited
Definition at line 456 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/AudioStream.hpp