Techstorm-rivalry: raylib::Camera3D Class Reference
raylib::Camera3D Class Reference
#include <Camera3D.hpp>
Public Member Functions
Camera3D (const ::Camera3D &camera)
Camera3D (::Vector3 position, ::Vector3 target=::Vector3{0.0f, 0.0f, 0.0f}, ::Vector3 up=::Vector3{0.0f, 1.0f, 0.0f}, float fovy=0, int projection=CAMERA_PERSPECTIVE)
Camera3D ()
::Vector3 GetPosition () const
void SetPosition (::Vector3 value)
::Vector3 GetTarget () const
void SetTarget (::Vector3 value)
::Vector3 GetUp () const
void SetUp (::Vector3 value)
float GetFovy () const
void SetFovy (float value)
int GetProjection () const
void SetProjection (int value)
Camera3D & operator= (const ::Camera3D &camera)
Camera3D & BeginMode ()
Camera3D & EndMode ()
Matrix GetMatrix () const
Camera3D & Update (int mode)
Camera3D & Update (::Vector3 movement, ::Vector3 rotation, float zoom=1.0f)
Ray GetMouseRay (::Vector2 mousePosition) const
Vector2 GetWorldToScreen (::Vector3 position) const
void DrawBillboard (const ::Texture2D &texture, ::Vector3 center, float size, ::Color tint={255, 255, 255, 255}) const
void DrawBillboard (const ::Texture2D &texture, ::Rectangle sourceRec, ::Vector3 center, ::Vector2 size, ::Color tint={255, 255, 255, 255}) const
Public Attributes
Vector3 position
Vector3 target
Vector3 up
float fovy
int projection
Protected Member Functions
void set (const ::Camera3D &camera)
Detailed Description
Camera type, defines a camera position/orientation in 3d space
Definition at line 12 of file Camera3D.hpp.
Constructor & Destructor Documentation
Camera3D() [1/3]
raylib::Camera3D::Camera3D (const ::Camera3D & camera) inline
Definition at line 14 of file Camera3D.hpp.
{
        set(camera);
    }
References set().
Camera3D() [2/3]
raylib::Camera3D::Camera3D (::Vector3 position, ::Vector3 target = ::Vector3{0.0f, 0.0f, 0.0f}, ::Vector3 up = ::Vector3{0.0f, 1.0f, 0.0f}, float fovy = 0, int projection = CAMERA_PERSPECTIVE) inline
Create a new Camera3D.
Parameters
position Camera position
target Camera target it looks-at
up Camera up vector (rotation over its axis)
fovy Camera field-of-view apperture in Y (degrees) in perspective, used as near plane width in orthographic
projection Camera projection: CAMERA_PERSPECTIVE or CAMERA_ORTHOGRAPHIC
Definition at line 27 of file Camera3D.hpp.
                                    {0.0f, 0.0f, 0.0f},
            ::Vector3 up = ::Vector3{0.0f, 1.0f, 0.0f},
            float fovy = 0,
            int projection = CAMERA_PERSPECTIVE) : ::Camera3D{position, target, up, fovy, projection} {}
Camera3D() [3/3]
raylib::Camera3D::Camera3D () inline
Definition at line 33 of file Camera3D.hpp.
{}
Member Function Documentation
BeginMode()
Camera3D & raylib::Camera3D::BeginMode () inline
Initializes 3D mode with custom camera (3D)
Definition at line 49 of file Camera3D.hpp.
{
        ::BeginMode3D(*this);
        return *this;
    }
References BeginMode3D().
DrawBillboard() [1/2]
void raylib::Camera3D::DrawBillboard (const ::Texture2D & texture, ::Rectangle sourceRec, ::Vector3 center, ::Vector2 size, ::Color tint = {255, 255, 255, 255}) const inline
Draw a billboard texture defined by source.
Definition at line 113 of file Camera3D.hpp.
                         {255, 255, 255, 255}) const {
        ::DrawBillboardRec(*this, texture, sourceRec, center, size, tint);
    }
DrawBillboard() [2/2]
void raylib::Camera3D::DrawBillboard (const ::Texture2D & texture, ::Vector3 center, float size, ::Color tint = {255, 255, 255, 255}) const inline
Draw a billboard texture.
Definition at line 102 of file Camera3D.hpp.
                         {255, 255, 255, 255}) const {
        ::DrawBillboard(*this, texture, center, size, tint);
    }
EndMode()
Camera3D & raylib::Camera3D::EndMode () inline
Ends 3D mode and returns to default 2D orthographic mode
Definition at line 57 of file Camera3D.hpp.
{
        ::EndMode3D();
        return *this;
    }
References EndMode3D().
GetFovy()
float raylib::Camera3D::GetFovy () const inline
Retrieves the fovy value for the object.
Returns
The fovy value of the object.
Definition at line 38 of file Camera3D.hpp.
GetMatrix()
Matrix raylib::Camera3D::GetMatrix () const inline
Get camera transform matrix (view matrix)
Definition at line 65 of file Camera3D.hpp.
{
        return ::GetCameraMatrix(*this);
    }
GetMouseRay()
Ray raylib::Camera3D::GetMouseRay (::Vector2 mousePosition) const inline
Returns a ray trace from mouse position
Definition at line 88 of file Camera3D.hpp.
{
        return ::GetMouseRay(mousePosition, *this);
    }
GetPosition()
::Vector3 raylib::Camera3D::GetPosition () const inline
Retrieves the position value for the object.
Returns
The position value of the object.
Definition at line 35 of file Camera3D.hpp.
GetProjection()
int raylib::Camera3D::GetProjection () const inline
Retrieves the projection value for the object.
Returns
The projection value of the object.
Definition at line 39 of file Camera3D.hpp.
GetTarget()
::Vector3 raylib::Camera3D::GetTarget () const inline
Retrieves the target value for the object.
Returns
The target value of the object.
Definition at line 36 of file Camera3D.hpp.
GetUp()
::Vector3 raylib::Camera3D::GetUp () const inline
Retrieves the up value for the object.
Returns
The up value of the object.
Definition at line 37 of file Camera3D.hpp.
GetWorldToScreen()
Vector2 raylib::Camera3D::GetWorldToScreen (::Vector3 position) const inline
Returns the screen space position for a 3d world space position
Definition at line 95 of file Camera3D.hpp.
{
        return ::GetWorldToScreen(position, *this);
    }
References Camera3D::position.
operator=()
Camera3D & raylib::Camera3D::operator= (const ::Camera3D & camera) inline
Definition at line 41 of file Camera3D.hpp.
{
        set(camera);
        return *this;
    }
References set().
set()
void raylib::Camera3D::set (const ::Camera3D & camera) inline protected
Definition at line 123 of file Camera3D.hpp.
{
        position = camera.position;
        target = camera.target;
        up = camera.up;
        fovy = camera.fovy;
        projection = camera.projection;
    }
References Camera3D::fovy, Camera3D::position, Camera3D::projection, Camera3D::target, and Camera3D::up.
SetFovy()
void raylib::Camera3D::SetFovy (float value) inline
Sets the fovy value for the object.
Parameters
value The value of which to set fovy to.
Definition at line 38 of file Camera3D.hpp.
SetPosition()
void raylib::Camera3D::SetPosition (::Vector3 value) inline
Sets the position value for the object.
Parameters
value The value of which to set position to.
Definition at line 35 of file Camera3D.hpp.
SetProjection()
void raylib::Camera3D::SetProjection (int value) inline
Sets the projection value for the object.
Parameters
value The value of which to set projection to.
Definition at line 39 of file Camera3D.hpp.
SetTarget()
void raylib::Camera3D::SetTarget (::Vector3 value) inline
Sets the target value for the object.
Parameters
value The value of which to set target to.
Definition at line 36 of file Camera3D.hpp.
SetUp()
void raylib::Camera3D::SetUp (::Vector3 value) inline
Sets the up value for the object.
Parameters
value The value of which to set up to.
Definition at line 37 of file Camera3D.hpp.
Update() [1/2]
Camera3D & raylib::Camera3D::Update (::Vector3 movement, ::Vector3 rotation, float zoom = 1.0f) inline
Update camera movement/rotation
Definition at line 80 of file Camera3D.hpp.
{
        ::UpdateCameraPro(this, movement, rotation, zoom);
        return *this;
    }
References UpdateCameraPro().
Update() [2/2]
Camera3D & raylib::Camera3D::Update (int mode) inline
Update camera position for selected mode
Definition at line 72 of file Camera3D.hpp.
{
        ::UpdateCamera(this, mode);
        return *this;
    }
References UpdateCamera().
Member Data Documentation
fovy
float Camera3D::fovy inherited
Definition at line 319 of file raylib.h.
position
Vector3 Camera3D::position inherited
Definition at line 316 of file raylib.h.
projection
int Camera3D::projection inherited
Definition at line 320 of file raylib.h.
target
Vector3 Camera3D::target inherited
Definition at line 317 of file raylib.h.
up
Vector3 Camera3D::up inherited
Definition at line 318 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Camera3D.hpp