Techstorm-rivalry: raylib::VrStereoConfig Class Reference
raylib::VrStereoConfig Class Reference
#include <VrStereoConfig.hpp>
Public Member Functions
VrStereoConfig (const ::VrDeviceInfo &info)
void Load (const ::VrDeviceInfo &info)
~VrStereoConfig ()
VrStereoConfig & BeginMode ()
VrStereoConfig & EndMode ()
void Unload ()
Public Attributes
Matrix projection [2]
Matrix viewOffset [2]
float leftLensCenter [2]
float rightLensCenter [2]
float leftScreenCenter [2]
float rightScreenCenter [2]
float scale [2]
float scaleIn [2]
Protected Member Functions
void set (const ::VrStereoConfig &config)
Detailed Description
VR stereo config functions for VR simulator
Definition at line 11 of file VrStereoConfig.hpp.
Constructor & Destructor Documentation
VrStereoConfig()
raylib::VrStereoConfig::VrStereoConfig (const ::VrDeviceInfo & info) inline
Definition at line 13 of file VrStereoConfig.hpp.
{
        Load(info);
    }
References Load().
~VrStereoConfig()
raylib::VrStereoConfig::~VrStereoConfig () inline
Unload VR stereo config
Definition at line 27 of file VrStereoConfig.hpp.
                      {
        Unload();
    }
References Unload().
Member Function Documentation
BeginMode()
VrStereoConfig & raylib::VrStereoConfig::BeginMode () inline
Begin stereo rendering
Definition at line 34 of file VrStereoConfig.hpp.
{
        ::BeginVrStereoMode(*this);
        return *this;
    }
References BeginVrStereoMode().
EndMode()
VrStereoConfig & raylib::VrStereoConfig::EndMode () inline
End stereo rendering
Definition at line 42 of file VrStereoConfig.hpp.
{
        ::EndVrStereoMode();
        return *this;
    }
References EndVrStereoMode().
Load()
void raylib::VrStereoConfig::Load (const ::VrDeviceInfo & info) inline
Load VR stereo config for VR simulator device parameters
Definition at line 20 of file VrStereoConfig.hpp.
{
        set(LoadVrStereoConfig(info));
    }
References LoadVrStereoConfig(), and set().
set()
void raylib::VrStereoConfig::set (const ::VrStereoConfig & config) inline protected
Definition at line 55 of file VrStereoConfig.hpp.
{
        projection[0] = config.projection[0];
        projection[1] = config.projection[1];
        viewOffset[0] = config.viewOffset[0];
        viewOffset[1] = config.viewOffset[1];
        leftLensCenter[0] = config.leftLensCenter[0];
        leftLensCenter[1] = config.leftLensCenter[1];
        rightLensCenter[0] = config.rightLensCenter[0];
        rightLensCenter[1] = config.rightLensCenter[1];
        leftScreenCenter[0] = config.leftScreenCenter[0];
        leftScreenCenter[1] = config.leftScreenCenter[1];
        rightScreenCenter[0] = config.rightScreenCenter[0];
        rightScreenCenter[1] = config.rightScreenCenter[1];
        scale[0] = config.scale[0];
        scale[1] = config.scale[1];
        scaleIn[0] = config.scaleIn[0];
        scaleIn[1] = config.scaleIn[1];
    }
References VrStereoConfig::leftLensCenter, VrStereoConfig::leftScreenCenter, VrStereoConfig::projection, VrStereoConfig::rightLensCenter, VrStereoConfig::rightScreenCenter, VrStereoConfig::scale, VrStereoConfig::scaleIn, and VrStereoConfig::viewOffset.
Unload()
void raylib::VrStereoConfig::Unload () inline
Unload VR stereo config
Definition at line 50 of file VrStereoConfig.hpp.
{
        ::UnloadVrStereoConfig(*this);
    }
References UnloadVrStereoConfig().
Member Data Documentation
leftLensCenter
float VrStereoConfig::leftLensCenter[2] inherited
Definition at line 494 of file raylib.h.
leftScreenCenter
float VrStereoConfig::leftScreenCenter[2] inherited
Definition at line 496 of file raylib.h.
projection
Matrix VrStereoConfig::projection[2] inherited
Definition at line 492 of file raylib.h.
rightLensCenter
float VrStereoConfig::rightLensCenter[2] inherited
Definition at line 495 of file raylib.h.
rightScreenCenter
float VrStereoConfig::rightScreenCenter[2] inherited
Definition at line 497 of file raylib.h.
scale
float VrStereoConfig::scale[2] inherited
Definition at line 498 of file raylib.h.
scaleIn
float VrStereoConfig::scaleIn[2] inherited
Definition at line 499 of file raylib.h.
viewOffset
Matrix VrStereoConfig::viewOffset[2] inherited
Definition at line 493 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/VrStereoConfig.hpp