Techstorm-rivalry: HealthBar Class Reference
HealthBar Class Reference
#include <Player.h>
Public Member Functions
float CalculatePercentage (float hp, float max_hp)
void Draw (Vector2 position)
Public Attributes
float hp
float maxHP
Detailed Description
Definition at line 77 of file Player.h.
Member Function Documentation
CalculatePercentage()
float HealthBar::CalculatePercentage (float hp, float max_hp) inline
Definition at line 80 of file Player.h.
    {
        float percentage = (float)hp / (float)max_hp;
        return percentage;
    }
References hp.
Draw()
void HealthBar::Draw (Vector2 position) inline
Definition at line 86 of file Player.h.
    {
        float percentage = CalculatePercentage(hp, maxHP);
        DrawRectangle((int)position.x, (int)position.y, 100, 20, BLACK);
        DrawRectangleLines((int)position.x, (int)position.y, 100, 20, RED);
        DrawRectangle((int)position.x, (int)position.y, 100 * percentage, 20, GREEN);
    };
References BLACK, CalculatePercentage(), DrawRectangle(), DrawRectangleLines(), GREEN, hp, maxHP, RED, Vector2::x, and Vector2::y.
Member Data Documentation
hp
float HealthBar::hp
Definition at line 95 of file Player.h.
maxHP
float HealthBar::maxHP
Definition at line 96 of file Player.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/Player.h