Techstorm-rivalry: toml::v3::impl::utf8_buffered_reader Class Reference
toml::v3::impl::utf8_buffered_reader Class Reference
#include <toml.h>
Public Member Functions
utf8_buffered_reader (utf8_reader_interface &reader) noexcept
const source_path_ptr & source_path () const noexcept
const utf8_codepoint * read_next () noexcept(! 0)
const utf8_codepoint * step_back (size_t count) noexcept
bool peek_eof () const noexcept(! 0)
optional< parse_error > && error () noexcept
Static Public Attributes
static constexpr size_t max_history_length = 128
Detailed Description
Definition at line 12499 of file toml.h.
Constructor & Destructor Documentation
utf8_buffered_reader()
toml::v3::impl::utf8_buffered_reader::utf8_buffered_reader (utf8_reader_interface & reader) inline explicit noexcept
Definition at line 12517 of file toml.h.
            : reader_{ reader }
        {}
Member Function Documentation
error()
optional< parse_error > && toml::v3::impl::utf8_buffered_reader::error () inline noexcept
Definition at line 12590 of file toml.h.
        {
            return reader_.error();
        }
References toml::v3::impl::utf8_reader_interface::error().
peek_eof()
bool toml::v3::impl::utf8_buffered_reader::peek_eof () const inline noexcept
Definition at line 12582 of file toml.h.
        {
            return reader_.peek_eof();
        }
References toml::v3::impl::utf8_reader_interface::peek_eof().
read_next()
const utf8_codepoint * toml::v3::impl::utf8_buffered_reader::read_next () inline noexcept
Definition at line 12528 of file toml.h.
        {
            utf8_buffered_reader_error_check({});
            if (negative_offset_)
            {
                negative_offset_--;
                // an entry negative offset of 1 just means "replay the current head"
                if (!negative_offset_)
                    return head_;
                // otherwise step back into the history buffer
                else
                    return history_.buffer
                         + ((history_.first + history_.count - negative_offset_) % history_buffer_size);
            }
            else
            {
                // first character read from stream
                if TOML_UNLIKELY(!history_.count && !head_)
                    head_ = reader_.read_next();
                // subsequent characters and not eof
                else if (head_)
                {
                    if TOML_UNLIKELY(history_.count < history_buffer_size)
                        history_.buffer[history_.count++] = *head_;
                    else
                        history_.buffer[(history_.first++ + history_buffer_size) % history_buffer_size] = *head_;
                    head_ = reader_.read_next();
                }
                return head_;
            }
        }
References toml::v3::impl::utf8_reader_interface::read_next(), TOML_UNLIKELY, and utf8_buffered_reader_error_check.
source_path()
const source_path_ptr & toml::v3::impl::utf8_buffered_reader::source_path () const inline noexcept
Definition at line 12522 of file toml.h.
        {
            return reader_.source_path();
        }
References toml::v3::impl::utf8_reader_interface::source_path().
step_back()
const utf8_codepoint * toml::v3::impl::utf8_buffered_reader::step_back (size_t count) inline noexcept
Definition at line 12567 of file toml.h.
        {
            utf8_buffered_reader_error_check({});
            TOML_ASSERT_ASSUME(history_.count);
            TOML_ASSERT_ASSUME(negative_offset_ + count <= history_.count);
            negative_offset_ += count;
            return negative_offset_
                     ? history_.buffer + ((history_.first + history_.count - negative_offset_) % history_buffer_size)
                     : head_;
        }
References TOML_ASSERT_ASSUME, and utf8_buffered_reader_error_check.
Member Data Documentation
buffer
utf8_codepoint toml::v3::impl::utf8_buffered_reader::buffer[history_buffer_size]
Definition at line 12509 of file toml.h.
count
size_t toml::v3::impl::utf8_buffered_reader::count
Definition at line 12510 of file toml.h.
first
size_t toml::v3::impl::utf8_buffered_reader::first
Definition at line 12510 of file toml.h.
max_history_length
constexpr size_t toml::v3::impl::utf8_buffered_reader::max_history_length = 128 static constexpr
Definition at line 12502 of file toml.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/toml.h