Techstorm-rivalry: raylib::Material Class Reference
raylib::Material Class Reference
#include <Material.hpp>
Public Member Functions
Material (const ::Material &material)
Material ()
Material (const Material &)=delete
Material (Material &&other)
~Material ()
::Shader GetShader () const
void SetShader (::Shader value)
::MaterialMap * GetMaps () const
void SetMaps (::MaterialMap *value)
Material & operator= (const ::Material &material)
Material & operator= (const Material &)=delete
Material & operator= (Material &&other) noexcept
void Unload ()
Material & SetTexture (int mapType, const ::Texture2D &texture)
void DrawMesh (const ::Mesh &mesh, ::Matrix transform) const
void DrawMesh (const ::Mesh &mesh, ::Matrix *transforms, int instances) const
bool IsReady () const
Static Public Member Functions
static std::vector< Material > Load (const std::string &fileName)
Public Attributes
Shader shader
MaterialMap * maps
float params [4]
Protected Member Functions
void set (const ::Material &material)
Detailed Description
Material type (generic)
Definition at line 14 of file Material.hpp.
Constructor & Destructor Documentation
Material() [1/4]
raylib::Material::Material (const ::Material & material) inline
Definition at line 16 of file Material.hpp.
{
        set(material);
    }
References set().
Material() [2/4]
raylib::Material::Material () inline
Load default material (Supports: DIFFUSE, SPECULAR, NORMAL maps)
Definition at line 23 of file Material.hpp.
               {
        set(LoadMaterialDefault());
    }
References LoadMaterialDefault(), and set().
Material() [3/4]
raylib::Material::Material (const Material &) delete
Material() [4/4]
raylib::Material::Material (Material && other) inline
Definition at line 29 of file Material.hpp.
{
        set(other);
        other.maps = nullptr;
        other.shader = {};
        other.params[0] = 0.0f;
        other.params[1] = 0.0f;
        other.params[2] = 0.0f;
        other.params[3] = 0.0f;
    }
References set().
~Material()
raylib::Material::~Material () inline
Definition at line 40 of file Material.hpp.
                {
        Unload();
    }
References Unload().
Member Function Documentation
DrawMesh() [1/2]
void raylib::Material::DrawMesh (const ::Mesh & mesh, ::Matrix * transforms, int instances) const inline
Draw multiple mesh instances with material and different transforms
Definition at line 108 of file Material.hpp.
{
        ::DrawMeshInstanced(mesh, *this, transforms, instances);
    }
References DrawMeshInstanced().
DrawMesh() [2/2]
void raylib::Material::DrawMesh (const ::Mesh & mesh, ::Matrix transform) const inline
Draw a 3d mesh with material and transform
Definition at line 101 of file Material.hpp.
{
        ::DrawMesh(mesh, *this, transform);
    }
References DrawMesh().
GetMaps()
::MaterialMap * raylib::Material::GetMaps () const inline
Retrieves the maps value for the object.
Returns
The maps value of the object.
Definition at line 55 of file Material.hpp.
GetShader()
::Shader raylib::Material::GetShader () const inline
Retrieves the shader value for the object.
Returns
The shader value of the object.
Definition at line 54 of file Material.hpp.
IsReady()
bool raylib::Material::IsReady () const inline
Check if material is ready
Definition at line 115 of file Material.hpp.
{
        return ::IsMaterialReady(*this);
    }
Load()
static std::vector< Material > raylib::Material::Load (const std::string & fileName) inline static
Load materials from model file
Definition at line 47 of file Material.hpp.
{
        int count = 0;
        // TODO(RobLoach): Material::Load() possibly leaks the materials array.
        ::Material* materials = ::LoadMaterials(fileName.c_str(), &count);
        return std::vector<Material>(materials, materials + count);
    }
References LoadMaterials().
operator=() [1/3]
Material & raylib::Material::operator= (const ::Material & material) inline
Definition at line 59 of file Material.hpp.
{
        set(material);
        return *this;
    }
References set().
operator=() [2/3]
Material & raylib::Material::operator= (const Material &) delete
operator=() [3/3]
Material & raylib::Material::operator= (Material && other) inline noexcept
Definition at line 66 of file Material.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.maps = nullptr;
        other.shader = {};
        return *this;
    }
References set(), and Unload().
set()
void raylib::Material::set (const ::Material & material) inline protected
Definition at line 120 of file Material.hpp.
{
        shader = material.shader;
        maps = material.maps;
        params[0] = material.params[0];
        params[1] = material.params[1];
        params[2] = material.params[2];
        params[3] = material.params[3];
    }
References Material::maps, Material::params, and Material::shader.
SetMaps()
void raylib::Material::SetMaps (::MaterialMap * value) inline
Sets the maps value for the object.
Parameters
value The value of which to set maps to.
Definition at line 55 of file Material.hpp.
SetShader()
void raylib::Material::SetShader (::Shader value) inline
Sets the shader value for the object.
Parameters
value The value of which to set shader to.
Definition at line 54 of file Material.hpp.
SetTexture()
Material & raylib::Material::SetTexture (int mapType, const ::Texture2D & texture) inline
Set texture for a material map type (MAP_DIFFUSE, MAP_SPECULAR...)
Definition at line 93 of file Material.hpp.
{
        ::SetMaterialTexture(this, mapType, texture);
        return *this;
    }
References SetMaterialTexture().
Unload()
void raylib::Material::Unload () inline
Unload material from memory
Definition at line 83 of file Material.hpp.
{
        if (maps != nullptr) {
            ::UnloadMaterial(*this);
            maps = nullptr;
        }
    }
References Material::maps, and UnloadMaterial().
Member Data Documentation
maps
MaterialMap* Material::maps inherited
Definition at line 374 of file raylib.h.
params
float Material::params[4] inherited
Definition at line 375 of file raylib.h.
shader
Shader Material::shader inherited
Definition at line 373 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Material.hpp