Techstorm-rivalry: raylib::Mesh Class Reference
raylib::Mesh Class Reference
#include <Mesh.hpp>
Public Member Functions
Mesh (const ::Mesh &mesh)
Mesh (const Mesh &)=delete
Mesh (Mesh &&other)
int GetVertexCount () const
void SetVertexCount (int value)
int GetTriangleCount () const
void SetTriangleCount (int value)
float * GetVertices () const
void SetVertices (float *value)
float * GetTexCoords () const
void SetTexCoords (float *value)
float * GetTexCoords2 () const
void SetTexCoords2 (float *value)
float * GetNormals () const
void SetNormals (float *value)
float * GetTangents () const
void SetTangents (float *value)
unsigned char * GetColors () const
void SetColors (unsigned char *value)
unsigned short * GetIndices () const
void SetIndices (unsigned short *value)
float * GetAnimVertices () const
void SetAnimVertices (float *value)
float * GetAnimNormals () const
void SetAnimNormals (float *value)
unsigned char * GetBoneIds () const
void SetBoneIds (unsigned char *value)
float * GetBoneWeights () const
void SetBoneWeights (float *value)
unsigned int GetVaoId () const
void SetVaoId (unsigned int value)
unsigned int * GetVboId () const
void SetVboId (unsigned int *value)
Mesh & operator= (const ::Mesh &mesh)
Mesh & operator= (const Mesh &)=delete
Mesh & operator= (Mesh &&other) noexcept
~Mesh ()
void Upload (bool dynamic=false)
void UpdateBuffer (int index, void *data, int dataSize, int offset=0)
void Draw (const ::Material &material, const ::Matrix &transform) const
void Draw (const ::Material &material, ::Matrix *transforms, int instances) const
void Export (const std::string &fileName)
void Unload ()
raylib::BoundingBox BoundingBox () const
operator raylib::BoundingBox ()
Mesh & GenTangents ()
raylib::Model LoadModelFrom () const
operator raylib::Model ()
Static Public Member Functions
::Mesh Poly (int sides, float radius)
::Mesh Plane (float width, float length, int resX, int resZ)
::Mesh Cube (float width, float height, float length)
::Mesh Sphere (float radius, int rings, int slices)
::Mesh HemiSphere (float radius, int rings, int slices)
::Mesh Cylinder (float radius, float height, int slices)
::Mesh Cone (float radius, float height, int slices)
::Mesh Torus (float radius, float size, int radSeg, int sides)
::Mesh Knot (float radius, float size, int radSeg, int sides)
::Mesh Heightmap (const ::Image &heightmap, ::Vector3 size)
::Mesh Cubicmap (const ::Image &cubicmap, ::Vector3 cubeSize)
Public Attributes
int vertexCount
int triangleCount
float * vertices
float * texcoords
float * texcoords2
float * normals
float * tangents
unsigned char * colors
unsigned short * indices
float * animVertices
float * animNormals
unsigned char * boneIds
float * boneWeights
unsigned int vaoId
unsigned int * vboId
Protected Member Functions
void set (const ::Mesh &mesh)
Detailed Description
Vertex data definning a mesh
Definition at line 16 of file Mesh.hpp.
Constructor & Destructor Documentation
Mesh() [1/3]
raylib::Mesh::Mesh (const ::Mesh & mesh) inline
Definition at line 18 of file Mesh.hpp.
{
        set(mesh);
    }
References set().
Mesh() [2/3]
raylib::Mesh::Mesh (const Mesh &) delete
Load meshes from model file
Mesh() [3/3]
raylib::Mesh::Mesh (Mesh && other) inline
Definition at line 33 of file Mesh.hpp.
                       {
        set(other);
        other.vertexCount = 0;
        other.triangleCount = 0;
        other.vertices = nullptr;
        other.texcoords = nullptr;
        other.texcoords2 = nullptr;
        other.normals = nullptr;
        other.tangents = nullptr;
        other.colors = nullptr;
        other.indices = nullptr;
        other.animVertices = nullptr;
        other.animNormals = nullptr;
        other.boneIds = nullptr;
        other.boneWeights = nullptr;
        other.vaoId = 0;
        other.vboId = nullptr;
    }
References set().
~Mesh()
raylib::Mesh::~Mesh () inline
Definition at line 180 of file Mesh.hpp.
            {
        Unload();
    }
References Unload().
Member Function Documentation
BoundingBox()
raylib::BoundingBox raylib::Mesh::BoundingBox () const inline
Compute mesh bounding box limits
Definition at line 236 of file Mesh.hpp.
{
        return ::GetMeshBoundingBox(*this);
    }
Cone()
::Mesh raylib::Mesh::Cone (float radius, float height, int slices) inline static
Generate cone/pyramid mesh
Definition at line 98 of file Mesh.hpp.
{
        return ::GenMeshCone(radius, height, slices);
    }
Cube()
::Mesh raylib::Mesh::Cube (float width, float height, float length) inline static
Generate cuboid mesh
Definition at line 70 of file Mesh.hpp.
{
        return ::GenMeshCube(width, height, length);
    }
Cubicmap()
::Mesh raylib::Mesh::Cubicmap (const ::Image & cubicmap, ::Vector3 cubeSize) inline static
Generate cubes-based map mesh from image data
Definition at line 126 of file Mesh.hpp.
{
        return ::GenMeshCubicmap(cubicmap, cubeSize);
    }
Cylinder()
::Mesh raylib::Mesh::Cylinder (float radius, float height, int slices) inline static
Generate cylinder mesh
Definition at line 91 of file Mesh.hpp.
{
        return ::GenMeshCylinder(radius, height, slices);
    }
Draw() [1/2]
void raylib::Mesh::Draw (const ::Material & material, ::Matrix * transforms, int instances) const inline
Draw multiple mesh instances with material and different transforms
Definition at line 208 of file Mesh.hpp.
{
        ::DrawMeshInstanced(*this, material, transforms, instances);
    }
References DrawMeshInstanced().
Draw() [2/2]
void raylib::Mesh::Draw (const ::Material & material, const ::Matrix & transform) const inline
Draw a 3d mesh with material and transform
Definition at line 201 of file Mesh.hpp.
{
        ::DrawMesh(*this, material, transform);
    }
References DrawMesh().
Export()
void raylib::Mesh::Export (const std::string & fileName) inline
Export mesh data to file
Exceptions
raylib::RaylibException Throws if failed to export the Mesh.
Definition at line 217 of file Mesh.hpp.
{
        if (!::ExportMesh(*this, fileName.c_str())) {
            throw new RaylibException("Failed to export the Mesh");
        }
    }
References ExportMesh().
GenTangents()
Mesh & raylib::Mesh::GenTangents () inline
Compute mesh tangents
Definition at line 250 of file Mesh.hpp.
{
        ::GenMeshTangents(this);
        return *this;
    }
References GenMeshTangents().
GetAnimNormals()
float * raylib::Mesh::GetAnimNormals () const inline
Retrieves the animNormals value for the object.
Returns
The animNormals value of the object.
Definition at line 140 of file Mesh.hpp.
GetAnimVertices()
float * raylib::Mesh::GetAnimVertices () const inline
Retrieves the animVertices value for the object.
Returns
The animVertices value of the object.
Definition at line 139 of file Mesh.hpp.
GetBoneIds()
unsigned char * raylib::Mesh::GetBoneIds () const inline
Retrieves the boneIds value for the object.
Returns
The boneIds value of the object.
Definition at line 141 of file Mesh.hpp.
GetBoneWeights()
float * raylib::Mesh::GetBoneWeights () const inline
Retrieves the boneWeights value for the object.
Returns
The boneWeights value of the object.
Definition at line 142 of file Mesh.hpp.
GetColors()
unsigned char * raylib::Mesh::GetColors () const inline
Retrieves the colors value for the object.
Returns
The colors value of the object.
Definition at line 137 of file Mesh.hpp.
GetIndices()
unsigned short * raylib::Mesh::GetIndices () const inline
Retrieves the indices value for the object.
Returns
The indices value of the object.
Definition at line 138 of file Mesh.hpp.
GetNormals()
float * raylib::Mesh::GetNormals () const inline
Retrieves the normals value for the object.
Returns
The normals value of the object.
Definition at line 135 of file Mesh.hpp.
GetTangents()
float * raylib::Mesh::GetTangents () const inline
Retrieves the tangents value for the object.
Returns
The tangents value of the object.
Definition at line 136 of file Mesh.hpp.
GetTexCoords()
float * raylib::Mesh::GetTexCoords () const inline
Retrieves the texcoords value for the object.
Returns
The texcoords value of the object.
Definition at line 133 of file Mesh.hpp.
GetTexCoords2()
float * raylib::Mesh::GetTexCoords2 () const inline
Retrieves the texcoords2 value for the object.
Returns
The texcoords2 value of the object.
Definition at line 134 of file Mesh.hpp.
GetTriangleCount()
int raylib::Mesh::GetTriangleCount () const inline
Retrieves the triangleCount value for the object.
Returns
The triangleCount value of the object.
Definition at line 131 of file Mesh.hpp.
GetVaoId()
unsigned int raylib::Mesh::GetVaoId () const inline
Retrieves the vaoId value for the object.
Returns
The vaoId value of the object.
Definition at line 143 of file Mesh.hpp.
GetVboId()
unsigned int * raylib::Mesh::GetVboId () const inline
Retrieves the vboId value for the object.
Returns
The vboId value of the object.
Definition at line 144 of file Mesh.hpp.
GetVertexCount()
int raylib::Mesh::GetVertexCount () const inline
Retrieves the vertexCount value for the object.
Returns
The vertexCount value of the object.
Definition at line 130 of file Mesh.hpp.
GetVertices()
float * raylib::Mesh::GetVertices () const inline
Retrieves the vertices value for the object.
Returns
The vertices value of the object.
Definition at line 132 of file Mesh.hpp.
Heightmap()
::Mesh raylib::Mesh::Heightmap (const ::Image & heightmap, ::Vector3 size) inline static
Generate heightmap mesh from image data
Definition at line 119 of file Mesh.hpp.
{
        return ::GenMeshHeightmap(heightmap, size);
    }
HemiSphere()
::Mesh raylib::Mesh::HemiSphere (float radius, int rings, int slices) inline static
Generate half-sphere mesh (no bottom cap)
Definition at line 84 of file Mesh.hpp.
{
        return ::GenMeshHemiSphere(radius, rings, slices);
    }
Knot()
::Mesh raylib::Mesh::Knot (float radius, float size, int radSeg, int sides) inline static
Generate trefoil knot mesh
Definition at line 112 of file Mesh.hpp.
{
        return ::GenMeshKnot(radius, size, radSeg, sides);
    }
LoadModelFrom()
raylib::Model raylib::Mesh::LoadModelFrom () const inline
Load model from generated mesh
Definition at line 258 of file Mesh.hpp.
{
        return ::LoadModelFromMesh(*this);
    }
operator raylib::BoundingBox()
raylib::Mesh::operator raylib::BoundingBox () inline
Compute mesh bounding box limits
Definition at line 243 of file Mesh.hpp.
{
        return BoundingBox();
    }
References BoundingBox().
operator raylib::Model()
raylib::Mesh::operator raylib::Model () inline
Load model from generated mesh
Definition at line 265 of file Mesh.hpp.
{
        return ::LoadModelFromMesh(*this);
    }
operator=() [1/3]
Mesh & raylib::Mesh::operator= (const ::Mesh & mesh) inline
Definition at line 146 of file Mesh.hpp.
{
        set(mesh);
        return *this;
    }
References set().
operator=() [2/3]
Mesh & raylib::Mesh::operator= (const Mesh &) delete
operator=() [3/3]
Mesh & raylib::Mesh::operator= (Mesh && other) inline noexcept
Definition at line 153 of file Mesh.hpp.
{
        if (this == &other) {
            return *this;
        }
        Unload();
        set(other);
        other.vertexCount = 0;
        other.triangleCount = 0;
        other.vertices = nullptr;
        other.texcoords = nullptr;
        other.texcoords2 = nullptr;
        other.normals = nullptr;
        other.tangents = nullptr;
        other.colors = nullptr;
        other.indices = nullptr;
        other.animVertices = nullptr;
        other.animNormals = nullptr;
        other.boneIds = nullptr;
        other.boneWeights = nullptr;
        other.vaoId = 0;
        other.vboId = nullptr;
        return *this;
    }
References set(), and Unload().
Plane()
::Mesh raylib::Mesh::Plane (float width, float length, int resX, int resZ) inline static
Generate plane mesh (with subdivisions)
Definition at line 63 of file Mesh.hpp.
{
        return ::GenMeshPlane(width, length, resX, resZ);
    }
Poly()
::Mesh raylib::Mesh::Poly (int sides, float radius) inline static
Generate polygonal mesh
Definition at line 56 of file Mesh.hpp.
{
        return ::GenMeshPoly(sides, radius);
    }
set()
void raylib::Mesh::set (const ::Mesh & mesh) inline protected
Definition at line 270 of file Mesh.hpp.
{
        vertexCount = mesh.vertexCount;
        triangleCount = mesh.triangleCount;
        vertices = mesh.vertices;
        texcoords = mesh.texcoords;
        texcoords2 = mesh.texcoords2;
        normals = mesh.normals;
        tangents = mesh.tangents;
        colors = mesh.colors;
        indices = mesh.indices;
        animVertices = mesh.animVertices;
        animNormals = mesh.animNormals;
        boneIds = mesh.boneIds;
        boneWeights = mesh.boneWeights;
        vaoId = mesh.vaoId;
        vboId = mesh.vboId;
    }
References Mesh::animNormals, Mesh::animVertices, Mesh::boneIds, Mesh::boneWeights, Mesh::colors, Mesh::indices, Mesh::normals, Mesh::tangents, Mesh::texcoords, Mesh::texcoords2, Mesh::triangleCount, Mesh::vaoId, Mesh::vboId, Mesh::vertexCount, and Mesh::vertices.
SetAnimNormals()
void raylib::Mesh::SetAnimNormals (float * value) inline
Sets the animNormals value for the object.
Parameters
value The value of which to set animNormals to.
Definition at line 140 of file Mesh.hpp.
SetAnimVertices()
void raylib::Mesh::SetAnimVertices (float * value) inline
Sets the animVertices value for the object.
Parameters
value The value of which to set animVertices to.
Definition at line 139 of file Mesh.hpp.
SetBoneIds()
void raylib::Mesh::SetBoneIds (unsigned char * value) inline
Sets the boneIds value for the object.
Parameters
value The value of which to set boneIds to.
Definition at line 141 of file Mesh.hpp.
SetBoneWeights()
void raylib::Mesh::SetBoneWeights (float * value) inline
Sets the boneWeights value for the object.
Parameters
value The value of which to set boneWeights to.
Definition at line 142 of file Mesh.hpp.
SetColors()
void raylib::Mesh::SetColors (unsigned char * value) inline
Sets the colors value for the object.
Parameters
value The value of which to set colors to.
Definition at line 137 of file Mesh.hpp.
SetIndices()
void raylib::Mesh::SetIndices (unsigned short * value) inline
Sets the indices value for the object.
Parameters
value The value of which to set indices to.
Definition at line 138 of file Mesh.hpp.
SetNormals()
void raylib::Mesh::SetNormals (float * value) inline
Sets the normals value for the object.
Parameters
value The value of which to set normals to.
Definition at line 135 of file Mesh.hpp.
SetTangents()
void raylib::Mesh::SetTangents (float * value) inline
Sets the tangents value for the object.
Parameters
value The value of which to set tangents to.
Definition at line 136 of file Mesh.hpp.
SetTexCoords()
void raylib::Mesh::SetTexCoords (float * value) inline
Sets the texcoords value for the object.
Parameters
value The value of which to set texcoords to.
Definition at line 133 of file Mesh.hpp.
SetTexCoords2()
void raylib::Mesh::SetTexCoords2 (float * value) inline
Sets the texcoords2 value for the object.
Parameters
value The value of which to set texcoords2 to.
Definition at line 134 of file Mesh.hpp.
SetTriangleCount()
void raylib::Mesh::SetTriangleCount (int value) inline
Sets the triangleCount value for the object.
Parameters
value The value of which to set triangleCount to.
Definition at line 131 of file Mesh.hpp.
SetVaoId()
void raylib::Mesh::SetVaoId (unsigned int value) inline
Sets the vaoId value for the object.
Parameters
value The value of which to set vaoId to.
Definition at line 143 of file Mesh.hpp.
SetVboId()
void raylib::Mesh::SetVboId (unsigned int * value) inline
Sets the vboId value for the object.
Parameters
value The value of which to set vboId to.
Definition at line 144 of file Mesh.hpp.
SetVertexCount()
void raylib::Mesh::SetVertexCount (int value) inline
Sets the vertexCount value for the object.
Parameters
value The value of which to set vertexCount to.
Definition at line 130 of file Mesh.hpp.
SetVertices()
void raylib::Mesh::SetVertices (float * value) inline
Sets the vertices value for the object.
Parameters
value The value of which to set vertices to.
Definition at line 132 of file Mesh.hpp.
Sphere()
::Mesh raylib::Mesh::Sphere (float radius, int rings, int slices) inline static
Generate sphere mesh (standard sphere)
Definition at line 77 of file Mesh.hpp.
{
        return ::GenMeshSphere(radius, rings, slices);
    }
Torus()
::Mesh raylib::Mesh::Torus (float radius, float size, int radSeg, int sides) inline static
Generate torus mesh
Definition at line 105 of file Mesh.hpp.
{
        return ::GenMeshTorus(radius, size, radSeg, sides);
    }
Unload()
void raylib::Mesh::Unload () inline
Unload mesh from memory (RAM and/or VRAM)
Definition at line 226 of file Mesh.hpp.
{
        if (vboId != nullptr) {
            ::UnloadMesh(*this);
            vboId = nullptr;
        }
    }
References UnloadMesh(), and Mesh::vboId.
UpdateBuffer()
void raylib::Mesh::UpdateBuffer (int index, void * data, int dataSize, int offset = 0) inline
Upload mesh vertex data to GPU (VRAM)
Definition at line 194 of file Mesh.hpp.
{
        ::UpdateMeshBuffer(*this, index, data, dataSize, offset);
    }
References offset, and UpdateMeshBuffer().
Upload()
void raylib::Mesh::Upload (bool dynamic = false) inline
Upload mesh vertex data to GPU (VRAM)
Definition at line 187 of file Mesh.hpp.
{
        ::UploadMesh(this, dynamic);
    }
References UploadMesh().
Member Data Documentation
animNormals
float* Mesh::animNormals inherited
Definition at line 349 of file raylib.h.
animVertices
float* Mesh::animVertices inherited
Definition at line 348 of file raylib.h.
boneIds
unsigned char* Mesh::boneIds inherited
Definition at line 350 of file raylib.h.
boneWeights
float* Mesh::boneWeights inherited
Definition at line 351 of file raylib.h.
colors
unsigned char* Mesh::colors inherited
Definition at line 344 of file raylib.h.
indices
unsigned short* Mesh::indices inherited
Definition at line 345 of file raylib.h.
normals
float* Mesh::normals inherited
Definition at line 342 of file raylib.h.
tangents
float* Mesh::tangents inherited
Definition at line 343 of file raylib.h.
texcoords
float* Mesh::texcoords inherited
Definition at line 340 of file raylib.h.
texcoords2
float* Mesh::texcoords2 inherited
Definition at line 341 of file raylib.h.
triangleCount
int Mesh::triangleCount inherited
Definition at line 336 of file raylib.h.
vaoId
unsigned int Mesh::vaoId inherited
Definition at line 354 of file raylib.h.
vboId
unsigned int* Mesh::vboId inherited
Definition at line 355 of file raylib.h.
vertexCount
int Mesh::vertexCount inherited
Definition at line 335 of file raylib.h.
vertices
float* Mesh::vertices inherited
Definition at line 339 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/Mesh.hpp