Techstorm-rivalry: raylib::BoundingBox Class Reference
raylib::BoundingBox Class Reference
#include <BoundingBox.hpp>
Public Member Functions
BoundingBox (const ::BoundingBox &box)
BoundingBox (const ::Mesh &mesh)
BoundingBox (::Vector3 minMax=::Vector3{0.0f, 0.0f, 0.0f})
BoundingBox (::Vector3 min, ::Vector3 max)
::Vector3 GetMin () const
void SetMin (::Vector3 value)
::Vector3 GetMax () const
void SetMax (::Vector3 value)
BoundingBox & operator= (const ::BoundingBox &box)
void Draw (::Color color={255, 255, 255, 255}) const
bool CheckCollision (const ::BoundingBox &box2) const
bool CheckCollision (::Vector3 center, float radius) const
bool CheckCollision (const ::Ray &ray) const
RayCollision GetCollision (const ::Ray &ray) const
Public Attributes
Vector3 min
Vector3 max
Protected Member Functions
void set (const ::BoundingBox &box)
void set (const ::Vector3 &_min, const ::Vector3 &_max)
Detailed Description
Bounding box type
Definition at line 11 of file BoundingBox.hpp.
Constructor & Destructor Documentation
BoundingBox() [1/4]
raylib::BoundingBox::BoundingBox (const ::BoundingBox & box) inline
Definition at line 16 of file BoundingBox.hpp.
                                        : ::BoundingBox{box.min, box.max} {
        // Nothing.
    }
BoundingBox() [2/4]
raylib::BoundingBox::BoundingBox (const ::Mesh & mesh) inline
Compute mesh bounding box limits
Definition at line 23 of file BoundingBox.hpp.
{
        set(::GetMeshBoundingBox(mesh));
    }
References GetMeshBoundingBox(), and set().
BoundingBox() [3/4]
raylib::BoundingBox::BoundingBox (::Vector3 minMax = ::Vector3{0.0f, 0.0f, 0.0f}) inline
Definition at line 27 of file BoundingBox.hpp.
{0.0f, 0.0f, 0.0f}) : ::BoundingBox{minMax, minMax} {}
BoundingBox() [4/4]
raylib::BoundingBox::BoundingBox (::Vector3 min, ::Vector3 max) inline
Definition at line 28 of file BoundingBox.hpp.
: ::BoundingBox{min, max} {}
Member Function Documentation
CheckCollision() [1/3]
bool raylib::BoundingBox::CheckCollision (::Vector3 center, float radius) const inline
Detect collision between box and sphere
Definition at line 55 of file BoundingBox.hpp.
{
        return CheckCollisionBoxSphere(*this, center, radius);
    }
References CheckCollisionBoxSphere().
CheckCollision() [2/3]
bool raylib::BoundingBox::CheckCollision (const ::BoundingBox & box2) const inline
Detect collision between two boxes
Definition at line 48 of file BoundingBox.hpp.
{
        return CheckCollisionBoxes(*this, box2);
    }
References CheckCollisionBoxes().
CheckCollision() [3/3]
bool raylib::BoundingBox::CheckCollision (const ::Ray & ray) const inline
Detect collision between ray and bounding box
Definition at line 62 of file BoundingBox.hpp.
{
        return GetRayCollisionBox(ray, *this).hit;
    }
References GetRayCollisionBox(), RayCollision::hit, and ray.
Draw()
void raylib::BoundingBox::Draw (::Color color = {255, 255, 255, 255}) const inline
Draw a bounding box with wires
Definition at line 41 of file BoundingBox.hpp.
                                   {255, 255, 255, 255}) const {
        ::DrawBoundingBox(*this, color);
    }
GetCollision()
RayCollision raylib::BoundingBox::GetCollision (const ::Ray & ray) const inline
Get collision information between ray and bounding box
Definition at line 69 of file BoundingBox.hpp.
{
        return GetRayCollisionBox(ray, *this);
    }
References GetRayCollisionBox(), and ray.
GetMax()
::Vector3 raylib::BoundingBox::GetMax () const inline
Retrieves the max value for the object.
Returns
The max value of the object.
Definition at line 31 of file BoundingBox.hpp.
GetMin()
::Vector3 raylib::BoundingBox::GetMin () const inline
Retrieves the min value for the object.
Returns
The min value of the object.
Definition at line 30 of file BoundingBox.hpp.
operator=()
BoundingBox & raylib::BoundingBox::operator= (const ::BoundingBox & box) inline
Definition at line 33 of file BoundingBox.hpp.
{
        set(box);
        return *this;
    }
References set().
set() [1/2]
void raylib::BoundingBox::set (const ::BoundingBox & box) inline protected
Definition at line 74 of file BoundingBox.hpp.
{
        min = box.min;
        max = box.max;
    }
References BoundingBox::max, and BoundingBox::min.
set() [2/2]
void raylib::BoundingBox::set (const ::Vector3 & _min, const ::Vector3 & _max) inline protected
Definition at line 78 of file BoundingBox.hpp.
{
        min = _min;
        max = _max;
    }
References BoundingBox::max, and BoundingBox::min.
SetMax()
void raylib::BoundingBox::SetMax (::Vector3 value) inline
Sets the max value for the object.
Parameters
value The value of which to set max to.
Definition at line 31 of file BoundingBox.hpp.
SetMin()
void raylib::BoundingBox::SetMin (::Vector3 value) inline
Sets the min value for the object.
Parameters
value The value of which to set min to.
Definition at line 30 of file BoundingBox.hpp.
Member Data Documentation
max
Vector3 BoundingBox::max inherited
Definition at line 433 of file raylib.h.
min
Vector3 BoundingBox::min inherited
Definition at line 432 of file raylib.h.
The documentation for this class was generated from the following file:
C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/packages/raylib.5.0.0/build/native/include/BoundingBox.hpp