Techstorm-rivalry: C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/rgui/examples/custom_file_dialog/custom_file_dialog.c File Reference
custom_file_dialog.c File Reference
#include "raylib.h"
#include "../../src/raygui.h"
#include "gui_window_file_dialog.h"
Macros
#define RAYGUI_IMPLEMENTATION
#define GUI_WINDOW_FILE_DIALOG_IMPLEMENTATION
Functions
int main ()
Macro Definition Documentation
GUI_WINDOW_FILE_DIALOG_IMPLEMENTATION
#define GUI_WINDOW_FILE_DIALOG_IMPLEMENTATION
Definition at line 24 of file custom_file_dialog.c.
RAYGUI_IMPLEMENTATION
#define RAYGUI_IMPLEMENTATION
Definition at line 20 of file custom_file_dialog.c.
Function Documentation
main()
int main (void)
Definition at line 30 of file custom_file_dialog.c.
{
    // Initialization
    //---------------------------------------------------------------------------------------
    int screenWidth = 800;
    int screenHeight = 560;
    InitWindow(screenWidth, screenHeight, "raygui - custom modal dialog");
    SetExitKey(0);
    // Custom file dialog
    GuiWindowFileDialogState fileDialogState = InitGuiWindowFileDialog(GetWorkingDirectory());
    bool exitWindow = false;
    char fileNameToLoad[512] = { 0 };
    Texture texture = { 0 };
    SetTargetFPS(60);
    //--------------------------------------------------------------------------------------
    // Main game loop
    while (!exitWindow)    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        exitWindow = WindowShouldClose();
        if (fileDialogState.SelectFilePressed)
        {
            // Load image file (if supported extension)
            if (IsFileExtension(fileDialogState.fileNameText, ".png"))
            {
                strcpy(fileNameToLoad, TextFormat("%s" PATH_SEPERATOR "%s", fileDialogState.dirPathText, fileDialogState.fileNameText));
                UnloadTexture(texture);
                texture = LoadTexture(fileNameToLoad);
            }
            fileDialogState.SelectFilePressed = false;
        }
        //----------------------------------------------------------------------------------
        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();
            ClearBackground(GetColor(GuiGetStyle(DEFAULT, BACKGROUND_COLOR)));
            DrawTexture(texture, GetScreenWidth()/2 - texture.width/2, GetScreenHeight()/2 - texture.height/2 - 5, WHITE);
            DrawRectangleLines(GetScreenWidth()/2 - texture.width/2, GetScreenHeight()/2 - texture.height/2 - 5, texture.width, texture.height, BLACK);
            DrawText(fileNameToLoad, 208, GetScreenHeight() - 20, 10, GRAY);
            // raygui: controls drawing
            //----------------------------------------------------------------------------------
            if (fileDialogState.windowActive) GuiLock();
            if (GuiButton((Rectangle){ 20, 20, 140, 30 }, GuiIconText(ICON_FILE_OPEN, "Open Image"))) fileDialogState.windowActive = true;
            GuiUnlock();
            // GUI: Dialog Window
            //--------------------------------------------------------------------------------
            GuiWindowFileDialog(&fileDialogState);
            //--------------------------------------------------------------------------------
            //----------------------------------------------------------------------------------
        EndDrawing();
        //----------------------------------------------------------------------------------
    }
    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadTexture(texture);     // Unload texture
    CloseWindow();              // Close window and OpenGL context
    //--------------------------------------------------------------------------------------
    return 0;
}
References BACKGROUND_COLOR, BeginDrawing(), BLACK, ClearBackground(), CloseWindow(), DEFAULT, GuiWindowFileDialogState::dirPathText, DrawRectangleLines(), DrawText(), DrawTexture(), EndDrawing(), GuiWindowFileDialogState::fileNameText, GetColor(), GetScreenHeight(), GetScreenWidth(), GetWorkingDirectory(), GRAY, GuiButton(), GuiGetStyle(), GuiIconText(), GuiLock(), GuiUnlock(), GuiWindowFileDialog(), Texture::height, ICON_FILE_OPEN, InitGuiWindowFileDialog(), InitWindow(), IsFileExtension(), LoadTexture(), GuiWindowFileDialogState::SelectFilePressed, SetExitKey(), SetTargetFPS(), TextFormat(), UnloadTexture(), WHITE, Texture::width, GuiWindowFileDialogState::windowActive, and WindowShouldClose().