Techstorm-rivalry: raylib Namespace Reference
raylib Namespace Reference
Classes
class AudioDevice
class AudioStream
class BoundingBox
class Camera2D
class Camera3D
class Color
class Font
class Gamepad
class Image
class Material
class Matrix
class Mesh
class Model
class ModelAnimation
class Mouse
class Music
class Ray
class RayCollision
class RaylibException
class Rectangle
class RenderTexture
class Shader
class Sound
class Text
class Texture
class TextureUnmanaged
class Touch
class Vector2
class Vector3
class Vector4
class VrStereoConfig
class Wave
class Window
Typedefs
typedef Camera3D Camera
typedef RenderTexture RenderTexture2D
typedef Texture Texture2D
typedef Texture TextureCubemap
typedef TextureUnmanaged Texture2DUnmanaged
typedef TextureUnmanaged TextureCubemapUnmanaged
typedef Vector4 Quaternion
Functions
std::string TextSubtext (const std::string &text, int position, int length)
std::string TextReplace (const std::string &text, const std::string &replace, const std::string &by)
std::string TextInsert (const std::string &text, const std::string &insert, int position)
std::vector< std::string > TextSplit (const std::string &text, char delimiter)
int TextFindIndex (const std::string &text, const std::string &find)
std::string TextToUpper (const std::string &text)
std::string TextToLower (const std::string &text)
std::string TextToPascal (const std::string &text)
int TextToInteger (const std::string &text)
Detailed Description
All raylib-cpp classes and functions appear in the raylib namespace.
Typedef Documentation
Camera
typedef Camera3D raylib::Camera
Definition at line 132 of file Camera3D.hpp.
Quaternion
typedef Vector4 raylib::Quaternion
Definition at line 174 of file Vector4.hpp.
RenderTexture2D
typedef RenderTexture raylib::RenderTexture2D
Definition at line 137 of file RenderTexture.hpp.
Texture2D
typedef Texture raylib::Texture2D
Definition at line 70 of file Texture.hpp.
Texture2DUnmanaged
typedef TextureUnmanaged raylib::Texture2DUnmanaged
Definition at line 337 of file TextureUnmanaged.hpp.
TextureCubemap
typedef Texture raylib::TextureCubemap
Definition at line 71 of file Texture.hpp.
TextureCubemapUnmanaged
typedef TextureUnmanaged raylib::TextureCubemapUnmanaged
Definition at line 338 of file TextureUnmanaged.hpp.
Function Documentation
TextFindIndex()
int raylib::TextFindIndex (const std::string & text, const std::string & find) inline
Find first text occurrence within a string
Definition at line 344 of file Functions.hpp.
{
    return ::TextFindIndex(text.c_str(), find.c_str());
}
TextInsert()
std::string raylib::TextInsert (const std::string & text, const std::string & insert, int position) inline
Insert text in a position
Definition at line 322 of file Functions.hpp.
{
    char* output = ::TextInsert(text.c_str(), insert.c_str(), position);
    if (output != NULL) {
        std::string stringOutput(output);
        free(output);
        return stringOutput;
    }
    return "";
}
References TextInsert().
TextReplace()
std::string raylib::TextReplace (const std::string & text, const std::string & replace, const std::string & by) inline
Replace text string
Definition at line 308 of file Functions.hpp.
{
    const char* input = text.c_str();
    char* output = ::TextReplace(const_cast<char*>(input), replace.c_str(), by.c_str());
    if (output != NULL) {
        std::string stringOutput(output);
        free(output);
        return stringOutput;
    }
    return "";
}
References TextReplace().
TextSplit()
std::vector< std::string > raylib::TextSplit (const std::string & text, char delimiter) inline
Split text into multiple strings
Definition at line 335 of file Functions.hpp.
{
    int count;
    const char** split = ::TextSplit(text.c_str(), delimiter, &count);
    return std::vector<std::string>(split, split + count);
}
References TextSplit().
TextSubtext()
std::string raylib::TextSubtext (const std::string & text, int position, int length) inline
Get text length, checks for '\0' ending
Definition at line 301 of file Functions.hpp.
{
    return ::TextSubtext(text.c_str(), position, length);
}
TextToInteger()
int raylib::TextToInteger (const std::string & text) inline
Get integer value from text (negative values not supported)
Definition at line 372 of file Functions.hpp.
{
    return ::TextToInteger(text.c_str());
}
TextToLower()
std::string raylib::TextToLower (const std::string & text) inline
Get lower case version of provided string
Definition at line 358 of file Functions.hpp.
{
    return ::TextToLower(text.c_str());
}
TextToPascal()
std::string raylib::TextToPascal (const std::string & text) inline
Get Pascal case notation version of provided string
Definition at line 365 of file Functions.hpp.
{
    return ::TextToPascal(text.c_str());
}
TextToUpper()
std::string raylib::TextToUpper (const std::string & text) inline
Get upper case version of provided string
Definition at line 351 of file Functions.hpp.
{
    return ::TextToUpper(text.c_str());
}