Techstorm-rivalry: toml::v3::impl Namespace Reference
toml::v3::impl Namespace Reference
Namespaces
namespace impl_noex
Classes
struct array_init_elem
class array_iterator
struct copy_cv_
struct copy_cv_< Dest, const Src >
struct copy_cv_< Dest, const volatile Src >
struct copy_cv_< Dest, volatile Src >
struct copy_ref_
struct copy_ref_< Dest, Src & >
struct copy_ref_< Dest, Src && >
struct depth_counter_scope
struct emplaced_type_of_
struct emplaced_type_of_< inserter< T > >
struct emplaced_type_of_< T >
struct error_builder
struct escaped_codepoint
struct float_traits
struct float_traits_base
class formatter
struct formatter_config
struct formatter_constants
struct inserted_type_of_
struct inserted_type_of_< inserter< T >, false >
struct inserted_type_of_< T, false >
struct integer_limits
struct integer_traits
struct integer_traits< T, false >
struct integer_traits_base
struct native_value_maker
struct native_value_maker< T, T >
struct native_value_traits
struct node_type_getter
struct node_type_getter< array >
struct node_type_getter< table >
struct node_type_getter< void >
struct node_unwrapper
struct node_unwrapper< const value< T > >
struct node_unwrapper< const volatile value< T > >
struct node_unwrapper< value< T > >
struct node_unwrapper< volatile value< T > >
struct node_wrapper
struct node_wrapper< bool >
struct node_wrapper< const T >
struct node_wrapper< const volatile T >
struct node_wrapper< date >
struct node_wrapper< date_time >
struct node_wrapper< double >
struct node_wrapper< int64_t >
struct node_wrapper< std::string >
struct node_wrapper< time >
struct node_wrapper< volatile T >
struct parse_integer_traits
struct parse_integer_traits< 10 >
struct parse_integer_traits< 16 >
struct parse_integer_traits< 2 >
struct parse_integer_traits< 8 >
struct parse_key_buffer
struct parse_scope
struct parsed_string
class parser
struct signed_integer_traits
struct string_traits
struct table_init_pair
class table_iterator
struct table_proxy_pair
struct table_vector_scope
struct unsigned_integer_traits
class utf8_buffered_reader
class utf8_byte_stream
class utf8_byte_stream< std::basic_string_view< Char > >
class utf8_byte_stream< std::istream >
struct utf8_codepoint
struct utf8_decoder
class utf8_reader
struct utf8_reader_interface
struct value_traits
struct value_traits< bool >
struct value_traits< char * >
struct value_traits< char[N]>
struct value_traits< const char * >
struct value_traits< const char[N]>
struct value_traits< const T >
struct value_traits< const volatile T >
struct value_traits< date >
struct value_traits< date_time >
struct value_traits< double >
struct value_traits< float >
struct value_traits< long double >
struct value_traits< signed char >
struct value_traits< signed int >
struct value_traits< signed long >
struct value_traits< signed long long >
struct value_traits< signed short >
struct value_traits< std::string >
struct value_traits< std::string_view >
struct value_traits< T & >
struct value_traits< T && >
struct value_traits< time >
struct value_traits< unsigned char >
struct value_traits< unsigned int >
struct value_traits< unsigned long >
struct value_traits< unsigned long long >
struct value_traits< unsigned short >
struct value_traits< volatile T >
Typedefs
using node_ptr = std::unique_ptr<node>
template<typename T >
using remove_cvref = std::remove_cv_t<std::remove_reference_t<T>>
template<typename... T>
using common_signed_type = std::common_type_t<std::make_signed_t<T>...>
template<typename Dest , typename Src >
using copy_ref = typename copy_ref_<Dest, Src>::type
template<typename Dest , typename Src >
using copy_cv = typename copy_cv_<Dest, Src>::type
template<typename Dest , typename Src >
using copy_cvref
template<typename T >
using native_type_of = typename value_traits<T>::native_type
template<typename T >
using wrap_node = typename node_wrapper<std::remove_reference_t<T>>::type
template<typename T >
using unwrap_node = typename node_unwrapper<std::remove_reference_t<T>>::type
template<typename T >
using parse_path_callback = bool(*)(void*, T)
template<typename... T>
using emplaced_type_of = typename emplaced_type_of_<remove_cvref<T>...>::type
Enumerations
enum class fp_class : unsigned { ok , neg_inf , pos_inf , nan }
enum class formatted_string_traits : unsigned {
none , line_breaks = 1u << 0 , tabs = 1u << 1 , control_chars = 1u << 2 ,
single_quotes = 1u << 3 , non_bare = 1u << 4 , non_ascii = 1u << 5 , all = (non_ascii << 1u) - 1u
}
Functions
template<typename T >
constexpr std::underlying_type_t< T > unwrap_enum (T val) noexcept
fp_class fpclassify (const double &val) noexcept
template<typename Iterator , typename T >
auto find (Iterator start, Iterator end, const T &needle) noexcept -> decltype(&(*start))
template<typename T >
constexpr const T & min (const T &a, const T &b) noexcept
void print_to_stream (std::ostream &, const char *, size_t)
void print_to_stream (std::ostream &, std::string_view)
void print_to_stream (std::ostream &, const std::string &)
void print_to_stream (std::ostream &, char)
void print_to_stream (std::ostream &, signed char, value_flags={}, size_t min_digits=0)
void print_to_stream (std::ostream &, signed short, value_flags={}, size_t min_digits=0)
void print_to_stream (std::ostream &, signed int, value_flags={}, size_t min_digits=0)
void print_to_stream (std::ostream &, signed long, value_flags={}, size_t min_digits=0)
void print_to_stream (std::ostream &, signed long long, value_flags={}, size_t min_digits=0)
void print_to_stream (std::ostream &, unsigned char, value_flags={}, size_t min_digits=0)
void print_to_stream (std::ostream &, unsigned short, value_flags={}, size_t min_digits=0)
void print_to_stream (std::ostream &, unsigned int, value_flags={}, size_t min_digits=0)
void print_to_stream (std::ostream &, unsigned long, value_flags={}, size_t min_digits=0)
void print_to_stream (std::ostream &, unsigned long long, value_flags={}, size_t min_digits=0)
void print_to_stream (std::ostream &, float, value_flags={}, bool relaxed_precision=false)
void print_to_stream (std::ostream &, double, value_flags={}, bool relaxed_precision=false)
void print_to_stream (std::ostream &, bool)
void print_to_stream (std::ostream &, const toml::date &)
void print_to_stream (std::ostream &, const toml::time &)
void print_to_stream (std::ostream &, const toml::time_offset &)
void print_to_stream (std::ostream &, const toml::date_time &)
void print_to_stream (std::ostream &, const source_position &)
void print_to_stream (std::ostream &, const source_region &)
void print_to_stream (std::ostream &, const array &)
void print_to_stream (std::ostream &, const table &)
void print_to_stream (std::ostream &, const value< std::string > &)
void print_to_stream (std::ostream &, const value< int64_t > &)
void print_to_stream (std::ostream &, const value< double > &)
void print_to_stream (std::ostream &, const value< bool > &)
void print_to_stream (std::ostream &, const value< date > &)
void print_to_stream (std::ostream &, const value< time > &)
void print_to_stream (std::ostream &, const value< date_time > &)
template<typename T , typename U >
void print_to_stream_bookended (std::ostream &stream, const T &val, const U &bookend)
bool parse_path (std::string_view, void *, parse_path_callback< std::string_view >, parse_path_callback< size_t >)
bool node_deep_equality (const node *, const node *) noexcept
template<typename T >
optional< T > node_integer_cast (int64_t val) noexcept
template<typename T >
auto * make_node_impl_specialized (T &&val, value_flags flags)
template<typename T >
auto * make_node_impl (T &&val, value_flags flags=preserve_source_value_flags)
template<typename T >
auto * make_node_impl (inserter< T > &&val, value_flags flags=preserve_source_value_flags)
template<typename T >
node_ptr make_node (T &&val, value_flags flags=preserve_source_value_flags)
constexpr bool is_ascii_horizontal_whitespace (char32_t c) noexcept
constexpr bool is_non_ascii_horizontal_whitespace (char32_t c) noexcept
constexpr bool is_ascii_vertical_whitespace (char32_t c) noexcept
constexpr bool is_non_ascii_vertical_whitespace (char32_t c) noexcept
constexpr bool is_ascii_bare_key_character (char32_t c) noexcept
constexpr bool is_string_delimiter (char32_t c) noexcept
constexpr bool is_ascii_letter (char32_t c) noexcept
constexpr bool is_binary_digit (char32_t c) noexcept
constexpr bool is_octal_digit (char32_t c) noexcept
constexpr bool is_decimal_digit (char32_t c) noexcept
constexpr bool is_hexadecimal_digit (char32_t c) noexcept
template<typename T >
constexpr uint_least32_t hex_to_dec (const T c) noexcept
constexpr bool is_horizontal_whitespace (char32_t c) noexcept
constexpr bool is_vertical_whitespace (char32_t c) noexcept
constexpr bool is_whitespace (char32_t c) noexcept
constexpr bool is_bare_key_character (char32_t c) noexcept
constexpr bool is_value_terminator (char32_t c) noexcept
constexpr bool is_control_character (char c) noexcept
constexpr bool is_control_character (char32_t c) noexcept
constexpr bool is_nontab_control_character (char32_t c) noexcept
constexpr bool is_unicode_surrogate (char32_t c) noexcept
bool is_ascii (const char *str, size_t len) noexcept
template<typename T >
void print_integer_to_stream (std::ostream &stream, T val, value_flags format={}, size_t min_digits=0)
template<typename T >
void print_floating_point_to_stream (std::ostream &stream, T val, value_flags format, bool relaxed_precision)
bool parse_path_into (std::string_view path_str, std::vector< path_component > &components)
template<typename Char >
utf8_reader (std::basic_string_view< Char >, std::string_view) -> utf8_reader< std::basic_string_view< Char > >
template<typename Char >
utf8_reader (std::basic_string_view< Char >, std::string &&) -> utf8_reader< std::basic_string_view< Char > >
template<typename Char >
utf8_reader (std::basic_istream< Char > &, std::string_view) -> utf8_reader< std::basic_istream< Char > >
template<typename Char >
utf8_reader (std::basic_istream< Char > &, std::string &&) -> utf8_reader< std::basic_istream< Char > >
template<typename... T>
constexpr bool is_match (char32_t codepoint, T... vals) noexcept
std::string_view to_sv (node_type val) noexcept
std::string_view to_sv (const std::string &str) noexcept
std::string_view to_sv (bool val) noexcept
std::string_view to_sv (const utf8_codepoint &cp) noexcept
std::string_view to_sv (const utf8_codepoint *cp) noexcept
template<typename T >
void concatenate (char *&write_pos, char *const buf_end, const T &arg) noexcept
parse_result do_parse (utf8_reader_interface &&reader)
parse_result do_parse_file (std::string_view file_path)
constexpr formatted_string_traits operator& (formatted_string_traits lhs, formatted_string_traits rhs) noexcept
constexpr formatted_string_traits & operator&= (formatted_string_traits &lhs, formatted_string_traits rhs) noexcept
constexpr formatted_string_traits operator| (formatted_string_traits lhs, formatted_string_traits rhs) noexcept
constexpr formatted_string_traits & operator|= (formatted_string_traits &lhs, formatted_string_traits rhs) noexcept
constexpr formatted_string_traits operator^ (formatted_string_traits lhs, formatted_string_traits rhs) noexcept
constexpr formatted_string_traits & operator^= (formatted_string_traits &lhs, formatted_string_traits rhs) noexcept
constexpr formatted_string_traits operator~ (formatted_string_traits val) noexcept
constexpr bool operator! (formatted_string_traits val) noexcept
size_t toml_formatter_count_inline_columns (const node &node, size_t line_wrap_cols) noexcept
bool toml_formatter_forces_multiline (const node &node, size_t line_wrap_cols, size_t starting_column_bias) noexcept
Variables
constexpr std::string_view control_char_escapes []
constexpr std::string_view node_type_friendly_names []
template<typename T , typename... U>
constexpr bool is_one_of = (false || ... || std::is_same_v<T, U>)
template<typename... T>
constexpr bool all_integral = (std::is_integral_v<T> && ...)
template<typename T >
constexpr bool is_cvref = std::is_reference_v<T> || std::is_const_v<T> || std::is_volatile_v<T>
template<typename T >
constexpr bool is_wide_string
template<typename T >
constexpr bool value_retrieval_is_nothrow
template<typename T >
constexpr bool dependent_false = false
template<typename T , typename... U>
constexpr bool first_is_same = false
template<typename T , typename... U>
constexpr bool first_is_same< T, T, U... > = true
template<typename T >
constexpr bool is_native = value_traits<T>::is_native
template<typename T >
constexpr bool can_represent_native = value_traits<T>::can_represent_native
template<typename T >
constexpr bool can_partially_represent_native = value_traits<T>::can_partially_represent_native
template<typename T >
constexpr bool is_losslessly_convertible_to_native = value_traits<T>::is_losslessly_convertible_to_native
template<typename T , typename... U>
constexpr bool is_natively_one_of = is_one_of<native_type_of<T>, U...>
template<typename T >
constexpr node_type node_type_of = node_type_getter<unwrap_node<remove_cvref<T>>>::value
template<typename T , typename ConvertFrom >
constexpr bool is_constructible_or_convertible
template<typename T >
constexpr size_t charconv_buffer_length = 0
template<>
constexpr size_t charconv_buffer_length< int8_t > = 4
template<>
constexpr size_t charconv_buffer_length< int16_t > = 6
template<>
constexpr size_t charconv_buffer_length< int32_t > = 11
template<>
constexpr size_t charconv_buffer_length< int64_t > = 20
template<>
constexpr size_t charconv_buffer_length< uint8_t > = 3
template<>
constexpr size_t charconv_buffer_length< uint16_t > = 5
template<>
constexpr size_t charconv_buffer_length< uint32_t > = 10
template<>
constexpr size_t charconv_buffer_length< uint64_t > = 20
template<>
constexpr size_t charconv_buffer_length< float > = 64
template<>
constexpr size_t charconv_buffer_length< double > = 64
constexpr auto utf8_byte_order_mark = "\xEF\xBB\xBF"sv
Typedef Documentation
common_signed_type
template<typename... T> using toml::v3::impl::common_signed_type = std::common_type_t<std::make_signed_t<T>...>
Definition at line 1481 of file toml.h.
copy_cv
template<typename Dest , typename Src > using toml::v3::impl::copy_cv = typename copy_cv_<Dest, Src>::type
Definition at line 1530 of file toml.h.
copy_cvref
template<typename Dest , typename Src > using toml::v3::impl::copy_cvref
Initial value:
        copy_ref<copy_ref<copy_cv<std::remove_reference_t<Dest>, std::remove_reference_t<Src>>, Dest>, Src>
Definition at line 1557 of file toml.h.
copy_ref
template<typename Dest , typename Src > using toml::v3::impl::copy_ref = typename copy_ref_<Dest, Src>::type
Definition at line 1507 of file toml.h.
emplaced_type_of
template<typename... T> using toml::v3::impl::emplaced_type_of = typename emplaced_type_of_<remove_cvref<T>...>::type
Definition at line 5737 of file toml.h.
native_type_of
template<typename T > using toml::v3::impl::native_type_of = typename value_traits<T>::native_type
Definition at line 1875 of file toml.h.
node_ptr
using toml::v3::impl::node_ptr = std::unique_ptr<node>
Definition at line 1315 of file toml.h.
parse_path_callback
template<typename T > using toml::v3::impl::parse_path_callback = bool(*)(void*, T)
Definition at line 2737 of file toml.h.
remove_cvref
template<typename T > using toml::v3::impl::remove_cvref = std::remove_cv_t<std::remove_reference_t<T>>
Definition at line 1478 of file toml.h.
unwrap_node
template<typename T > using toml::v3::impl::unwrap_node = typename node_unwrapper<std::remove_reference_t<T>>::type
Definition at line 1973 of file toml.h.
wrap_node
template<typename T > using toml::v3::impl::wrap_node = typename node_wrapper<std::remove_reference_t<T>>::type
Definition at line 1944 of file toml.h.
Enumeration Type Documentation
formatted_string_traits
enum class toml::v3::impl::formatted_string_traits : unsigned strong
Enumerator
none
line_breaks
tabs
control_chars
single_quotes
non_bare
non_ascii
all
Definition at line 15927 of file toml.h.
    {
        none,
        line_breaks = 1u << 0, // \n
        tabs = 1u << 1, // \t
        control_chars = 1u << 2, // also includes non-ascii vertical whitespace
        single_quotes = 1u << 3,
        non_bare = 1u << 4, // anything not satisfying "is bare key character"
        non_ascii = 1u << 5, // any codepoint >= 128
        all = (non_ascii << 1u) - 1u
    };
fp_class
enum class toml::v3::impl::fp_class : unsigned strong
Enumerator
ok
neg_inf
pos_inf
nan
Definition at line 2079 of file toml.h.
    {
        ok,
        neg_inf,
        pos_inf,
        nan
    };
Function Documentation
concatenate()
template<typename T > void toml::v3::impl::concatenate (char *& write_pos, char *const buf_end, const T & arg) inline noexcept
Definition at line 12714 of file toml.h.
    {
        if TOML_UNLIKELY(write_pos >= buf_end)
            return;
        using arg_type = impl::remove_cvref<T>;
        // string views
        if constexpr (std::is_same_v<arg_type, std::string_view>)
        {
            const auto max_chars = static_cast<size_t>(buf_end - write_pos);
            const auto len = max_chars < arg.length() ? max_chars : arg.length();
            std::memcpy(write_pos, arg.data(), len);
            write_pos += len;
        }
        // doubles
        else if constexpr (std::is_same_v<arg_type, double>)
        {
#if TOML_FLOAT_CHARCONV
            const auto result = std::to_chars(write_pos, buf_end, arg);
            write_pos = result.ptr;
#else
            std::ostringstream ss;
            ss.imbue(std::locale::classic());
            ss.precision(std::numeric_limits<arg_type>::max_digits10);
            ss << arg;
            concatenate(write_pos, buf_end, to_sv(std::move(ss).str()));
#endif
        }
        // 64-bit integers
        else if constexpr (impl::is_one_of<arg_type, int64_t, uint64_t>)
        {
#if TOML_INT_CHARCONV
            const auto result = std::to_chars(write_pos, buf_end, arg);
            write_pos = result.ptr;
#else
            std::ostringstream ss;
            ss.imbue(std::locale::classic());
            using cast_type = std::conditional_t<std::is_signed_v<arg_type>, int64_t, uint64_t>;
            ss << static_cast<cast_type>(arg);
            concatenate(write_pos, buf_end, to_sv(std::move(ss).str()));
#endif
        }
        // escaped_codepoint
        else if constexpr (std::is_same_v<arg_type, escaped_codepoint>)
        {
            if (arg.cp.value <= U'\x7F')
                concatenate(write_pos, buf_end, to_sv(arg.cp));
            else
            {
                auto val = static_cast<uint_least32_t>(arg.cp.value);
                const auto digits = val > 0xFFFFu ? 8u : 4u;
                constexpr auto mask = uint_least32_t{ 0xFu };
                char buf[10] = { '\\', digits > 4 ? 'U' : 'u' };
                for (auto i = 2u + digits; i-- > 2u;)
                {
                    const auto hexdig = val & mask;
                    buf[i] = static_cast<char>(hexdig >= 0xAu ? ('A' + (hexdig - 0xAu)) : ('0' + hexdig));
                    val >>= 4;
                }
                concatenate(write_pos, buf_end, std::string_view{ buf, digits + 2u });
            }
        }
        // all other floats (fallback - coerce to double)
        else if constexpr (std::is_floating_point_v<arg_type>)
            concatenate(write_pos, buf_end, static_cast<double>(arg));
        // all other integers (fallback - coerce to (u)int64_t)
        else if constexpr (std::is_arithmetic_v<arg_type> && std::is_integral_v<arg_type>)
        {
            using cast_type = std::conditional_t<std::is_unsigned_v<arg_type>, uint64_t, int64_t>;
            concatenate(write_pos, buf_end, static_cast<cast_type>(arg));
        }
        else
        {
            static_assert(
                impl::dependent_false<T>,
                "concatenate() inputs are limited to std::string_views, integers, floats, and escaped_codepoint");
        }
    }
References concatenate(), to_sv(), and TOML_UNLIKELY.
do_parse()
parse_result toml::v3::impl::do_parse (utf8_reader_interface && reader) inline
Definition at line 15744 of file toml.h.
    {
        return impl::parser{ std::move(reader) };
    }
References do_parse().
do_parse_file()
parse_result toml::v3::impl::do_parse_file (std::string_view file_path) inline
Definition at line 15751 of file toml.h.
    {
#if TOML_EXCEPTIONS
#define TOML_PARSE_FILE_ERROR(msg, path)                                                                               \
    throw parse_error{ msg, source_position{}, std::make_shared<const std::string>(std::move(path)) }
#else
#define TOML_PARSE_FILE_ERROR(msg, path)                                                                               \
    return parse_result                                                                                                \
    {                                                                                                                  \
        parse_error                                                                                                    \
        {                                                                                                              \
            msg, source_position{}, std::make_shared<const std::string>(std::move(path))                               \
        }                                                                                                              \
    }
#endif
        std::string file_path_str(file_path);
        // open file with a custom-sized stack buffer
        std::ifstream file;
        TOML_OVERALIGNED char file_buffer[sizeof(void*) * 1024u];
        file.rdbuf()->pubsetbuf(file_buffer, sizeof(file_buffer));
#if TOML_WINDOWS
        file.open(impl::widen(file_path_str).c_str(), std::ifstream::in | std::ifstream::binary | std::ifstream::ate);
#else
        file.open(file_path_str, std::ifstream::in | std::ifstream::binary | std::ifstream::ate);
#endif
        if (!file.is_open())
            TOML_PARSE_FILE_ERROR("File could not be opened for reading", file_path_str);
        // get size
        const auto file_size = file.tellg();
        if (file_size == -1)
            TOML_PARSE_FILE_ERROR("Could not determine file size", file_path_str);
        file.seekg(0, std::ifstream::beg);
        // read the whole file into memory first if the file isn't too large
        constexpr auto large_file_threshold = 1024 * 1024 * 2; // 2 MB
        if (file_size <= large_file_threshold)
        {
            std::vector<char> file_data;
            file_data.resize(static_cast<size_t>(file_size));
            file.read(file_data.data(), static_cast<std::streamsize>(file_size));
            return parse(std::string_view{ file_data.data(), file_data.size() }, std::move(file_path_str));
        }
        // otherwise parse it using the streams
        else
            return parse(file, std::move(file_path_str));
#undef TOML_PARSE_FILE_ERROR
    }
References do_parse_file(), TOML_OVERALIGNED, and TOML_PARSE_FILE_ERROR.
find()
template<typename Iterator , typename T > auto toml::v3::impl::find (Iterator start, Iterator end, const T & needle) -> decltype(&(*start)) inline noexcept
Definition at line 2111 of file toml.h.
    {
        for (; start != end; start++)
            if (*start == needle)
                return &(*start);
        return nullptr;
    }
References find().
fpclassify()
fp_class toml::v3::impl::fpclassify (const double & val) inline noexcept
Definition at line 2088 of file toml.h.
    {
        static_assert(sizeof(uint64_t) == sizeof(double));
        static constexpr uint64_t sign = 0b1000000000000000000000000000000000000000000000000000000000000000ull;
        static constexpr uint64_t exponent = 0b0111111111110000000000000000000000000000000000000000000000000000ull;
        static constexpr uint64_t mantissa = 0b0000000000001111111111111111111111111111111111111111111111111111ull;
        uint64_t val_bits;
        std::memcpy(&val_bits, &val, sizeof(val));
        if ((val_bits & exponent) != exponent)
            return fp_class::ok;
        if ((val_bits & mantissa))
            return fp_class::nan;
        return (val_bits & sign) ? fp_class::neg_inf : fp_class::pos_inf;
    }
References fpclassify().
hex_to_dec()
template<typename T > constexpr uint_least32_t toml::v3::impl::hex_to_dec (const T c) constexpr noexcept
Definition at line 8504 of file toml.h.
    {
        if constexpr (std::is_same_v<remove_cvref<T>, uint_least32_t>)
            return c >= 0x41u                    // >= 'A'
                     ? 10u + (c | 0x20u) - 0x61u // - 'a'
                     : c - 0x30u                 // - '0'
                ;
        else
            return hex_to_dec(static_cast<uint_least32_t>(c));
    }
References hex_to_dec().
is_ascii()
bool toml::v3::impl::is_ascii (const char * str, size_t len) inline noexcept
Definition at line 11976 of file toml.h.
    {
        const char* const end = str + len;
#if TOML_HAS_SSE2 && (128 % CHAR_BIT) == 0
        {
            constexpr size_t chars_per_vector = 128u / CHAR_BIT;
            if (const size_t simdable = len - (len % chars_per_vector))
            {
                __m128i mask = _mm_setzero_si128();
                for (const char* const e = str + simdable; str < e; str += chars_per_vector)
                {
                    const __m128i current_bytes = _mm_loadu_si128(reinterpret_cast<const __m128i*>(str));
                    mask = _mm_or_si128(mask, current_bytes);
                }
                const __m128i has_error = _mm_cmpgt_epi8(_mm_setzero_si128(), mask);
#if TOML_HAS_SSE4_1
                if (!_mm_testz_si128(has_error, has_error))
                    return false;
#else
                if (_mm_movemask_epi8(_mm_cmpeq_epi8(has_error, _mm_setzero_si128())) != 0xFFFF)
                    return false;
#endif
            }
        }
#endif
        for (; str < end; str++)
            if (static_cast<unsigned char>(*str) > 127u)
                return false;
        return true;
    }
References is_ascii().
is_ascii_bare_key_character()
constexpr bool toml::v3::impl::is_ascii_bare_key_character (char32_t c) constexpr noexcept
Definition at line 8328 of file toml.h.
    {
#if TOML_LANG_UNRELEASED // toml/issues/644 ('+' in bare keys)
        if TOML_UNLIKELY(c == U'+')
            return true;
#endif
        // 64 code units from 5 ranges (spanning a search area of 78)
        if (c < U'-' || c > U'z')
            return false;
        return (((static_cast<uint_least64_t>(c) - 0x2Dull) / 0x40ull) != 0ull)
            || ((1ull << (static_cast<uint_least64_t>(c) - 0x2Dull)) & 0xFFF43FFFFFF01FF9ull);
    }
References is_ascii_bare_key_character(), and TOML_UNLIKELY.
is_ascii_horizontal_whitespace()
constexpr bool toml::v3::impl::is_ascii_horizontal_whitespace (char32_t c) constexpr noexcept
Definition at line 8286 of file toml.h.
    {
        return c == U'\t' || c == U' ';
    }
References is_ascii_horizontal_whitespace().
is_ascii_letter()
constexpr bool toml::v3::impl::is_ascii_letter (char32_t c) constexpr noexcept
Definition at line 8473 of file toml.h.
    {
        return (c >= U'a' && c <= U'z') || (c >= U'A' && c <= U'Z');
    }
References is_ascii_letter().
is_ascii_vertical_whitespace()
constexpr bool toml::v3::impl::is_ascii_vertical_whitespace (char32_t c) constexpr noexcept
Definition at line 8316 of file toml.h.
    {
        return c >= U'\n' && c <= U'\r';
    }
References is_ascii_vertical_whitespace().
is_bare_key_character()
constexpr bool toml::v3::impl::is_bare_key_character (char32_t c) constexpr noexcept
Definition at line 8534 of file toml.h.
    {
        return is_ascii_bare_key_character(c)
#if TOML_LANG_UNRELEASED // toml/pull/891 (unicode bare keys)
            || is_non_ascii_bare_key_character(c)
#endif
            ;
    }
References is_ascii_bare_key_character(), and is_bare_key_character().
is_binary_digit()
constexpr bool toml::v3::impl::is_binary_digit (char32_t c) constexpr noexcept
Definition at line 8479 of file toml.h.
    {
        return c == U'0' || c == U'1';
    }
References is_binary_digit().
is_control_character() [1/2]
constexpr bool toml::v3::impl::is_control_character (char c) constexpr noexcept
Definition at line 8550 of file toml.h.
    {
        return c <= '\u001F' || c == '\u007F';
    }
References is_control_character().
is_control_character() [2/2]
constexpr bool toml::v3::impl::is_control_character (char32_t c) constexpr noexcept
Definition at line 8556 of file toml.h.
    {
        return c <= U'\u001F' || c == U'\u007F';
    }
References is_control_character().
is_decimal_digit()
constexpr bool toml::v3::impl::is_decimal_digit (char32_t c) constexpr noexcept
Definition at line 8491 of file toml.h.
    {
        return (c >= U'0' && c <= U'9');
    }
References is_decimal_digit().
is_hexadecimal_digit()
constexpr bool toml::v3::impl::is_hexadecimal_digit (char32_t c) constexpr noexcept
Definition at line 8497 of file toml.h.
    {
        return U'0' <= c && c <= U'f' && (1ull << (static_cast<uint_least64_t>(c) - 0x30u)) & 0x7E0000007E03FFull;
    }
References is_hexadecimal_digit().
is_horizontal_whitespace()
constexpr bool toml::v3::impl::is_horizontal_whitespace (char32_t c) constexpr noexcept
Definition at line 8516 of file toml.h.
    {
        return is_ascii_horizontal_whitespace(c) || is_non_ascii_horizontal_whitespace(c);
    }
References is_ascii_horizontal_whitespace(), is_horizontal_whitespace(), and is_non_ascii_horizontal_whitespace().
is_match()
template<typename... T> constexpr bool toml::v3::impl::is_match (char32_t codepoint, T... vals) inline constexpr noexcept
Definition at line 12611 of file toml.h.
    {
        static_assert((std::is_same_v<char32_t, T> && ...));
        return ((codepoint == vals) || ...);
    }
References is_match().
is_non_ascii_horizontal_whitespace()
constexpr bool toml::v3::impl::is_non_ascii_horizontal_whitespace (char32_t c) constexpr noexcept
Definition at line 8292 of file toml.h.
    {
        // 20 code units from 8 ranges (spanning a search area of 65120)
        if (c < U'\xA0' || c > U'\uFEFF')
            return false;
        const auto child_index_0 = (static_cast<uint_least64_t>(c) - 0xA0ull) / 0x3FAull;
        if ((1ull << child_index_0) & 0x7FFFFFFFFFFFF75Eull)
            return false;
        if (c == U'\xA0' || c == U'\u3000' || c == U'\uFEFF')
            return true;
        switch (child_index_0)
        {
            case 0x05: return c == U'\u1680' || c == U'\u180E';
            case 0x07:
                return (U'\u2000' <= c && c <= U'\u200B') || (U'\u205F' <= c && c <= U'\u2060') || c == U'\u202F';
            default: TOML_UNREACHABLE;
        }
        TOML_UNREACHABLE;
    }
References is_non_ascii_horizontal_whitespace(), and TOML_UNREACHABLE.
is_non_ascii_vertical_whitespace()
constexpr bool toml::v3::impl::is_non_ascii_vertical_whitespace (char32_t c) constexpr noexcept
Definition at line 8322 of file toml.h.
    {
        return (U'\u2028' <= c && c <= U'\u2029') || c == U'\x85';
    }
References is_non_ascii_vertical_whitespace().
is_nontab_control_character()
constexpr bool toml::v3::impl::is_nontab_control_character (char32_t c) constexpr noexcept
Definition at line 8562 of file toml.h.
    {
        return c <= U'\u0008' || (c >= U'\u000A' && c <= U'\u001F') || c == U'\u007F';
    }
References is_nontab_control_character().
is_octal_digit()
constexpr bool toml::v3::impl::is_octal_digit (char32_t c) constexpr noexcept
Definition at line 8485 of file toml.h.
    {
        return (c >= U'0' && c <= U'7');
    }
References is_octal_digit().
is_string_delimiter()
constexpr bool toml::v3::impl::is_string_delimiter (char32_t c) constexpr noexcept
Definition at line 8467 of file toml.h.
    {
        return c == U'"' || c == U'\'';
    }
References is_string_delimiter().
is_unicode_surrogate()
constexpr bool toml::v3::impl::is_unicode_surrogate (char32_t c) constexpr noexcept
Definition at line 8568 of file toml.h.
    {
        return c >= 0xD800u && c <= 0xDFFF;
    }
References is_unicode_surrogate().
is_value_terminator()
constexpr bool toml::v3::impl::is_value_terminator (char32_t c) constexpr noexcept
Definition at line 8544 of file toml.h.
    {
        return is_whitespace(c) || c == U']' || c == U'}' || c == U',' || c == U'#';
    }
References is_value_terminator(), and is_whitespace().
is_vertical_whitespace()
constexpr bool toml::v3::impl::is_vertical_whitespace (char32_t c) constexpr noexcept
Definition at line 8522 of file toml.h.
    {
        return is_ascii_vertical_whitespace(c) || is_non_ascii_vertical_whitespace(c);
    }
References is_ascii_vertical_whitespace(), is_non_ascii_vertical_whitespace(), and is_vertical_whitespace().
is_whitespace()
constexpr bool toml::v3::impl::is_whitespace (char32_t c) constexpr noexcept
Definition at line 8528 of file toml.h.
    {
        return is_horizontal_whitespace(c) || is_vertical_whitespace(c);
    }
References is_horizontal_whitespace(), is_vertical_whitespace(), and is_whitespace().
make_node()
template<typename T > node_ptr toml::v3::impl::make_node (T && val, value_flags flags = preserve_source_value_flags)
Definition at line 5711 of file toml.h.
    {
        return node_ptr{ make_node_impl(static_cast<T&&>(val), flags) };
    }
References make_node(), and make_node_impl().
make_node_impl() [1/2]
template<typename T > auto * toml::v3::impl::make_node_impl (inserter< T > && val, value_flags flags = preserve_source_value_flags)
Definition at line 5686 of file toml.h.
    {
        return make_node_impl(static_cast<T&&>(val.value), flags);
    }
References make_node_impl().
make_node_impl() [2/2]
template<typename T > auto * toml::v3::impl::make_node_impl (T && val, value_flags flags = preserve_source_value_flags)
Definition at line 5663 of file toml.h.
    {
        using unwrapped_type = unwrap_node<remove_cvref<T>>;
        if constexpr (std::is_same_v<unwrapped_type, node> || is_node_view<unwrapped_type>)
        {
            if constexpr (is_node_view<unwrapped_type>)
            {
                if (!val)
                    return static_cast<toml::node*>(nullptr);
            }
            return static_cast<T&&>(val).visit(
                [flags](auto&& concrete) {
                    return static_cast<toml::node*>(
                        make_node_impl_specialized(static_cast<decltype(concrete)&&>(concrete), flags));
                });
        }
        else
            return make_node_impl_specialized(static_cast<T&&>(val), flags);
    }
References make_node_impl(), and make_node_impl_specialized().
make_node_impl_specialized()
template<typename T > auto * toml::v3::impl::make_node_impl_specialized (T && val, value_flags flags)
Definition at line 5595 of file toml.h.
    {
        using unwrapped_type = unwrap_node<remove_cvref<T>>;
        static_assert(!std::is_same_v<unwrapped_type, node>);
        static_assert(!is_node_view<unwrapped_type>);
        // arrays + tables - invoke copy/move ctor
        if constexpr (is_one_of<unwrapped_type, array, table>)
        {
            return new unwrapped_type(static_cast<T&&>(val));
        }
        // values
        else
        {
            using native_type = native_type_of<unwrapped_type>;
            using value_type = value<native_type>;
            value_type* out;
            // copy/move ctor
            if constexpr (std::is_same_v<remove_cvref<T>, value_type>)
            {
                out = new value_type{ static_cast<T&&>(val) };
            }
            // creating from raw value
            else
            {
                static_assert(!is_wide_string<T> || TOML_ENABLE_WINDOWS_COMPAT,
                              "Instantiating values from wide-character strings is only "
                              "supported on Windows with TOML_ENABLE_WINDOWS_COMPAT enabled.");
                if constexpr (!is_losslessly_convertible_to_native<unwrapped_type>)
                {
                    if constexpr (std::is_same_v<native_type, int64_t>)
                        static_assert(dependent_false<T>,
                                      "Integral value initializers must be losslessly convertible to int64_t");
                    else if constexpr (std::is_same_v<native_type, double>)
                        static_assert(dependent_false<T>,
                                      "Floating-point value initializers must be losslessly convertible to double");
                    else
                        static_assert(
                            dependent_false<T>,
                            "Value initializers must be losslessly convertible to one of the TOML value types");
                }
                if constexpr (is_wide_string<T>)
                {
#if TOML_ENABLE_WINDOWS_COMPAT
                    out = new value_type{ narrow(static_cast<T&&>(val)) };
#else
                    static_assert(dependent_false<T>, "Evaluated unreachable branch!");
#endif
                }
                else
                    out = new value_type{ static_cast<T&&>(val) };
            }
            if (flags != preserve_source_value_flags)
                out->flags(flags);
            return out;
        }
    }
References toml::v3::value< ValueType >::flags(), and TOML_ENABLE_WINDOWS_COMPAT.
min()
template<typename T > constexpr const T & toml::v3::impl::min (const T & a, const T & b) inline constexpr noexcept
Definition at line 2122 of file toml.h.
    {
        return a < b ? a : b;
    }
References min().
node_deep_equality()
bool toml::v3::impl::node_deep_equality (const node * lhs, const node * rhs) inline noexcept
Definition at line 10414 of file toml.h.
    {
    // both same or both null
    if (lhs == rhs)
        return true;
    // lhs null != rhs null or different types
    if ((!lhs != !rhs) || lhs->type() != rhs->type())
        return false;
    return lhs->visit(
        [=](auto& l) noexcept
        {
            using concrete_type = remove_cvref<decltype(l)>;
            return l == *(rhs->as<concrete_type>());
        });
}
References node_deep_equality().
node_integer_cast()
template<typename T > optional< T > toml::v3::impl::node_integer_cast (int64_t val) inline noexcept
Definition at line 4667 of file toml.h.
    {
        static_assert(node_type_of<T> == node_type::integer);
        static_assert(!is_cvref<T>);
        using traits = value_traits<T>;
        if constexpr (!traits::is_signed)
        {
            if constexpr ((sizeof(T) * CHAR_BIT) < 63) // 63 bits == int64_max
            {
                using common_t = decltype(int64_t{} + T{});
                if (val < int64_t{} || static_cast<common_t>(val) > static_cast<common_t>(traits::max))
                    return {};
            }
            else
            {
                if (val < int64_t{})
                    return {};
            }
        }
        else
        {
            if (val < traits::min || val > traits::max)
                return {};
        }
        return { static_cast<T>(val) };
    }
References node_integer_cast().
operator!()
constexpr bool toml::v3::impl::operator! (formatted_string_traits val) inline constexpr noexcept
Definition at line 15939 of file toml.h.
operator&()
constexpr formatted_string_traits toml::v3::impl::operator& (formatted_string_traits lhs, formatted_string_traits rhs) inline constexpr noexcept
Definition at line 15939 of file toml.h.
operator&=()
constexpr formatted_string_traits & toml::v3::impl::operator&= (formatted_string_traits & lhs, formatted_string_traits rhs) constexpr noexcept
Definition at line 15939 of file toml.h.
operator^()
constexpr formatted_string_traits toml::v3::impl::operator^ (formatted_string_traits lhs, formatted_string_traits rhs) inline constexpr noexcept
Definition at line 15939 of file toml.h.
operator^=()
constexpr formatted_string_traits & toml::v3::impl::operator^= (formatted_string_traits & lhs, formatted_string_traits rhs) constexpr noexcept
Definition at line 15939 of file toml.h.
operator|()
constexpr formatted_string_traits toml::v3::impl::operator| (formatted_string_traits lhs, formatted_string_traits rhs) inline constexpr noexcept
Definition at line 15939 of file toml.h.
operator|=()
constexpr formatted_string_traits & toml::v3::impl::operator|= (formatted_string_traits & lhs, formatted_string_traits rhs) constexpr noexcept
Definition at line 15939 of file toml.h.
operator~()
constexpr formatted_string_traits toml::v3::impl::operator~ (formatted_string_traits val) inline constexpr noexcept
Definition at line 15939 of file toml.h.
parse_path()
bool toml::v3::impl::parse_path (std::string_view path, void * data, parse_path_callback< std::string_view > on_key, parse_path_callback< size_t > on_index) inline
Definition at line 10463 of file toml.h.
    {
    // a blank string is a valid path; it's just one component representing the "" key
    if (path.empty())
        return on_key(data, ""sv);
    size_t pos = 0;
    const auto end = path.length();
    bool prev_was_array_indexer = false;
    bool prev_was_dot = true; // invisible root 'dot'
    while (pos < end)
    {
        // start of an array indexer
        if (path[pos] == '[')
        {
            // find first digit in index
            size_t index_start = pos + 1u;
            while (true)
            {
                if TOML_UNLIKELY(index_start >= path.length())
                    return false;
                const auto c = path[index_start];
                if TOML_LIKELY(c >= '0' && c <= '9')
                    break;
                else if (c == ' ' || c == '\t')
                    index_start++;
                else
                    return false;
            }
            TOML_ASSERT(path[index_start] >= '0');
            TOML_ASSERT(path[index_start] <= '9');
            // find end of index (first non-digit character)
            size_t index_end = index_start + 1u;
            while (true)
            {
                // if an array indexer is missing the trailing ']' at the end of the string, permissively accept it
                if TOML_UNLIKELY(index_end >= path.length())
                    break;
                const auto c = path[index_end];
                if (c >= '0' && c <= '9')
                    index_end++;
                else if (c == ']' || c == ' ' || c == '\t' || c == '.' || c == '[')
                    break;
                else
                    return false;
            }
            TOML_ASSERT(path[index_end - 1u] >= '0');
            TOML_ASSERT(path[index_end - 1u] <= '9');
            // move pos to after indexer (char after closing ']' or permissively EOL/subkey '.'/next opening '[')
            pos = index_end;
            while (true)
            {
                if TOML_UNLIKELY(pos >= path.length())
                    break;
                const auto c = path[pos];
                if (c == ']')
                {
                    pos++;
                    break;
                }
                else if TOML_UNLIKELY(c == '.' || c == '[')
                    break;
                else if (c == '\t' || c == ' ')
                    pos++;
                else
                    return false;
            }
            // get array index substring
            auto index_str = path.substr(index_start, index_end - index_start);
            // parse the actual array index to an integer type
            size_t index;
            if (index_str.length() == 1u)
                index = static_cast<size_t>(index_str[0] - '0');
            else
            {
#if TOML_INT_CHARCONV
                    auto fc_result = std::from_chars(index_str.data(), index_str.data() + index_str.length(), index);
                    if (fc_result.ec != std::errc{})
                        return false;
#else
                    std::stringstream ss;
                    ss.imbue(std::locale::classic());
                    ss.write(index_str.data(), static_cast<std::streamsize>(index_str.length()));
                    if (!(ss >> index))
                        return false;
#endif
                }
                prev_was_dot = false;
                prev_was_array_indexer = true;
                if (!on_index(data, index))
                    return false;
            }
        // start of a new table child
        else if (path[pos] == '.')
        {
            // a dot immediately following another dot (or at the beginning of the string) is as if we'd asked
            // for an empty child in between, e.g.
            //
            //     foo..bar
            //
            // is equivalent to
            //
            //     "foo".""."bar"
            //
            if (prev_was_dot && !on_key(data, ""sv))
                return false;
            pos++;
            prev_was_dot = true;
            prev_was_array_indexer = false;
        }
        // an errant closing ']'
        else if TOML_UNLIKELY(path[pos] == ']')
            return false;
        // some regular subkey
        else
        {
            const auto subkey_start = pos;
            const auto subkey_len =
                impl::min(path.find_first_of(".[]"sv, subkey_start + 1u), path.length()) - subkey_start;
            const auto subkey = path.substr(subkey_start, subkey_len);
            // a regular subkey segment immediately after an array indexer is OK if it was all whitespace, e.g.:
            //
            //     "foo[0]  .bar"
            //            ^^ skip this
            //
            // otherwise its an error (since it would have to be preceeded by a dot)
            if (prev_was_array_indexer)
            {
                auto non_ws = subkey.find_first_not_of(" \t");
                if (non_ws == std::string_view::npos)
                {
                    pos += subkey_len;
                    prev_was_dot = false;
                    prev_was_array_indexer = false;
                    continue;
                }
                else
                    return false;
            }
            pos += subkey_len;
            prev_was_dot = false;
            prev_was_array_indexer = false;
            if (!on_key(data, subkey))
                return false;
        }
    }
    // Last character was a '.', which implies an empty string key at the end of the path
    if (prev_was_dot && !on_key(data, ""sv))
        return false;
    return true;
}
References toml::v3::path::empty(), parse_path(), TOML_ASSERT, TOML_LIKELY, and TOML_UNLIKELY.
parse_path_into()
bool toml::v3::impl::parse_path_into (std::string_view path_str, std::vector< path_component > & components) inline
Definition at line 10909 of file toml.h.
    {
        using components_type = std::remove_reference_t<decltype(components)>;
        const auto original_size = components.size();
        static constexpr auto on_key = [](void* data, std::string_view key) -> bool
        {
            auto& comps = *static_cast<components_type*>(data);
            comps.emplace_back(key);
            return true;
        };
        static constexpr auto on_index = [](void* data, size_t index) -> bool
        {
            auto& comps = *static_cast<components_type*>(data);
            comps.emplace_back(index);
            return true;
        };
        if (!impl::parse_path(path_str, &components, on_key, on_index))
        {
            components.resize(original_size);
            return false;
        }
        return true;
    }
References toml::v3::key, parse_path(), and parse_path_into().
print_floating_point_to_stream()
template<typename T > void toml::v3::impl::print_floating_point_to_stream (std::ostream & stream, T val, value_flags format, bool relaxed_precision) inline
Definition at line 9967 of file toml.h.
    {
        switch (impl::fpclassify(val))
        {
            case impl::fp_class::neg_inf: impl::print_to_stream(stream, "-inf"sv); break;
            case impl::fp_class::pos_inf: impl::print_to_stream(stream, "inf"sv); break;
            case impl::fp_class::nan: impl::print_to_stream(stream, "nan"sv); break;
            case impl::fp_class::ok:
            {
                static constexpr auto needs_decimal_point = [](auto&& s) noexcept
                {
                    for (auto c : s)
                        if (c == '.' || c == 'E' || c == 'e')
                            return false;
                    return true;
                };
#if TOML_FLOAT_CHARCONV
                const auto hex = !!(format & value_flags::format_as_hexadecimal);
                char buf[charconv_buffer_length<T>];
                auto res = hex ? std::to_chars(buf, buf + sizeof(buf), val, std::chars_format::hex)
                               : std::to_chars(buf, buf + sizeof(buf), val);
                auto str = std::string_view{ buf, static_cast<size_t>(res.ptr - buf) };
                char buf2[charconv_buffer_length<T>];
                if (!hex && relaxed_precision)
                {
                    res = std::to_chars(buf2, buf2 + sizeof(buf2), val, std::chars_format::general, 6);
                    const auto str2 = std::string_view{ buf2, static_cast<size_t>(res.ptr - buf2) };
                    if (str2.length() < str.length())
                        str = str2;
                }
                impl::print_to_stream(stream, str);
                if (!hex && needs_decimal_point(str))
                    toml::impl::print_to_stream(stream, ".0"sv);
#else
                std::ostringstream ss;
                ss.imbue(std::locale::classic());
                if (!relaxed_precision)
                    ss.precision(std::numeric_limits<T>::max_digits10);
                if (!!(format & value_flags::format_as_hexadecimal))
                    ss << std::hexfloat;
                ss << val;
                const auto str = std::move(ss).str();
                impl::print_to_stream(stream, str);
                if (!(format & value_flags::format_as_hexadecimal) && needs_decimal_point(str))
                    impl::print_to_stream(stream, ".0"sv);
#endif
            }
            break;
            default: TOML_UNREACHABLE;
        }
    }
References print_floating_point_to_stream(), print_to_stream(), and TOML_UNREACHABLE.
print_integer_to_stream()
template<typename T > void toml::v3::impl::print_integer_to_stream (std::ostream & stream, T val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 9880 of file toml.h.
                                                                                 {}, size_t min_digits = 0)
    {
        if (!val)
        {
            if (!min_digits)
                min_digits = 1;
            for (size_t i = 0; i < min_digits; i++)
                stream.put('0');
            return;
        }
        static constexpr auto value_flags_mask =
            value_flags::format_as_binary | value_flags::format_as_octal | value_flags::format_as_hexadecimal;
        format &= value_flags_mask;
        int base = 10;
        if (format != value_flags::none && val > T{})
        {
            switch (format)
            {
                case value_flags::format_as_binary: base = 2; break;
                case value_flags::format_as_octal: base = 8; break;
                case value_flags::format_as_hexadecimal: base = 16; break;
                default: break;
            }
        }
#if TOML_INT_CHARCONV
        char buf[(sizeof(T) * CHAR_BIT)];
        const auto res = std::to_chars(buf, buf + sizeof(buf), val, base);
        const auto len = static_cast<size_t>(res.ptr - buf);
        for (size_t i = len; i < min_digits; i++)
            stream.put('0');
        if (base == 16)
        {
            for (size_t i = 0; i < len; i++)
                if (buf[i] >= 'a')
                    buf[i] -= 32;
        }
        impl::print_to_stream(stream, buf, len);
#else
        using unsigned_type = std::conditional_t<(sizeof(T) > sizeof(unsigned)), std::make_unsigned_t<T>, unsigned>;
        using cast_type = std::conditional_t<std::is_signed_v<T>, std::make_signed_t<unsigned_type>, unsigned_type>;
        if (base == 2)
        {
            const auto len = sizeof(T) * CHAR_BIT;
            for (size_t i = len; i < min_digits; i++)
                stream.put('0');
            bool found_one = false;
            const auto v = static_cast<unsigned_type>(val);
            unsigned_type mask = unsigned_type{ 1 } << (len - 1u);
            for (size_t i = 0; i < len; i++)
            {
                if ((v & mask))
                {
                    stream.put('1');
                    found_one = true;
                }
                else if (found_one)
                    stream.put('0');
                mask >>= 1;
            }
        }
        else
        {
            std::ostringstream ss;
            ss.imbue(std::locale::classic());
            ss << std::uppercase << std::setbase(base);
            if (min_digits)
                ss << std::setfill('0') << std::setw(static_cast<int>(min_digits));
            ss << static_cast<cast_type>(val);
            const auto str = std::move(ss).str();
            impl::print_to_stream(stream, str);
        }
#endif
    }
References print_integer_to_stream().
print_to_stream() [1/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, bool val) inline
Definition at line 10141 of file toml.h.
    {
        print_to_stream(stream, val ? "true"sv : "false"sv);
    }
References print_to_stream().
print_to_stream() [2/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, char val) inline
Definition at line 10057 of file toml.h.
    {
        stream.put(val);
    }
References print_to_stream().
print_to_stream() [3/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const array & arr) inline
Definition at line 10241 of file toml.h.
    {
        stream << toml_formatter{ arr };
    }
References print_to_stream().
print_to_stream() [4/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const char * val, size_t len) inline
Definition at line 10039 of file toml.h.
    {
        stream.write(val, static_cast<std::streamsize>(len));
    }
print_to_stream() [5/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const source_position & val) inline
Definition at line 10218 of file toml.h.
    {
        print_to_stream(stream, "line "sv);
        print_to_stream(stream, val.line);
        print_to_stream(stream, ", column "sv);
        print_to_stream(stream, val.column);
    }
References toml::v3::source_position::column, toml::v3::source_position::line, and print_to_stream().
print_to_stream() [6/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const source_region & val) inline
Definition at line 10227 of file toml.h.
    {
        print_to_stream(stream, val.begin);
        if (val.path)
        {
            print_to_stream(stream, " of '"sv);
            print_to_stream(stream, *val.path);
            stream.put('\'');
        }
    }
References toml::v3::source_region::begin, toml::v3::source_region::path, and print_to_stream().
print_to_stream() [7/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const std::string & val) inline
Definition at line 10051 of file toml.h.
    {
        stream.write(val.data(), static_cast<std::streamsize>(val.length()));
    }
References print_to_stream().
print_to_stream() [8/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const table & tbl) inline
Definition at line 10247 of file toml.h.
    {
        stream << toml_formatter{ tbl };
    }
References print_to_stream().
print_to_stream() [9/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const toml::date & val) inline
Definition at line 10147 of file toml.h.
    {
        print_to_stream(stream, val.year, {}, 4);
        stream.put('-');
        print_to_stream(stream, val.month, {}, 2);
        stream.put('-');
        print_to_stream(stream, val.day, {}, 2);
    }
References toml::v3::date::day, toml::v3::date::month, print_to_stream(), and toml::v3::date::year.
print_to_stream() [10/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const toml::date_time & val) inline
Definition at line 10208 of file toml.h.
    {
        print_to_stream(stream, val.date);
        stream.put('T');
        print_to_stream(stream, val.time);
        if (val.offset)
            print_to_stream(stream, *val.offset);
    }
References toml::v3::stdopt::date_time::date, toml::v3::stdopt::date_time::offset, print_to_stream(), and toml::v3::stdopt::date_time::time.
print_to_stream() [11/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const toml::time & val) inline
Definition at line 10157 of file toml.h.
    {
        print_to_stream(stream, val.hour, {}, 2);
        stream.put(':');
        print_to_stream(stream, val.minute, {}, 2);
        stream.put(':');
        print_to_stream(stream, val.second, {}, 2);
        if (val.nanosecond && val.nanosecond <= 999999999u)
        {
            stream.put('.');
            auto ns = val.nanosecond;
            size_t digits = 9u;
            while (ns % 10u == 0u)
            {
                ns /= 10u;
                digits--;
            }
            print_to_stream(stream, ns, {}, digits);
        }
    }
References toml::v3::time::hour, toml::v3::time::minute, toml::v3::time::nanosecond, print_to_stream(), and toml::v3::time::second.
print_to_stream() [12/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const toml::time_offset & val) inline
Definition at line 10179 of file toml.h.
    {
        if (!val.minutes)
        {
            stream.put('Z');
            return;
        }
        auto mins = static_cast<int>(val.minutes);
        if (mins < 0)
        {
            stream.put('-');
            mins = -mins;
        }
        else
            stream.put('+');
        const auto hours = mins / 60;
        if (hours)
        {
            print_to_stream(stream, static_cast<unsigned int>(hours), {}, 2);
            mins -= hours * 60;
        }
        else
            print_to_stream(stream, "00"sv);
        stream.put(':');
        print_to_stream(stream, static_cast<unsigned int>(mins), {}, 2);
    }
References toml::v3::time_offset::minutes, and print_to_stream().
print_to_stream() [13/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const value< bool > & val) inline
Definition at line 10271 of file toml.h.
    {
        stream << toml_formatter{ val };
    }
References print_to_stream().
print_to_stream() [14/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const value< date > & val) inline
Definition at line 10277 of file toml.h.
    {
        stream << toml_formatter{ val };
    }
References print_to_stream().
print_to_stream() [15/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const value< date_time > & val) inline
Definition at line 10289 of file toml.h.
    {
        stream << toml_formatter{ val };
    }
References print_to_stream().
print_to_stream() [16/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const value< double > & val) inline
Definition at line 10265 of file toml.h.
    {
        stream << toml_formatter{ val };
    }
References print_to_stream().
print_to_stream() [17/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const value< int64_t > & val) inline
Definition at line 10259 of file toml.h.
    {
        stream << toml_formatter{ val };
    }
References print_to_stream().
print_to_stream() [18/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const value< std::string > & val) inline
Definition at line 10253 of file toml.h.
    {
        stream << toml_formatter{ val };
    }
References print_to_stream().
print_to_stream() [19/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, const value< time > & val) inline
Definition at line 10283 of file toml.h.
    {
        stream << toml_formatter{ val };
    }
References print_to_stream().
print_to_stream() [20/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, double val, value_flags format = {}, bool relaxed_precision = false) inline
Definition at line 10135 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_floating_point_to_stream(stream, val, format, relaxed_precision);
    }
References print_to_stream().
print_to_stream() [21/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, float val, value_flags format = {}, bool relaxed_precision = false) inline
Definition at line 10129 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_floating_point_to_stream(stream, val, format, relaxed_precision);
    }
References print_to_stream().
print_to_stream() [22/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, signed char val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 10063 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_integer_to_stream(stream, val, format, min_digits);
    }
References print_to_stream().
print_to_stream() [23/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, signed int val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 10075 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_integer_to_stream(stream, val, format, min_digits);
    }
References print_to_stream().
print_to_stream() [24/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, signed long long val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 10087 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_integer_to_stream(stream, val, format, min_digits);
    }
References print_to_stream().
print_to_stream() [25/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, signed long val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 10081 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_integer_to_stream(stream, val, format, min_digits);
    }
References print_to_stream().
print_to_stream() [26/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, signed short val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 10069 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_integer_to_stream(stream, val, format, min_digits);
    }
References print_to_stream().
print_to_stream() [27/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, std::string_view val) inline
Definition at line 10045 of file toml.h.
    {
        stream.write(val.data(), static_cast<std::streamsize>(val.length()));
    }
References print_to_stream().
print_to_stream() [28/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, unsigned char val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 10096 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_integer_to_stream(stream, val, format, min_digits);
    }
References print_to_stream().
print_to_stream() [29/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, unsigned int val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 10108 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_integer_to_stream(stream, val, format, min_digits);
    }
References print_to_stream().
print_to_stream() [30/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, unsigned long long val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 10120 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_integer_to_stream(stream, val, format, min_digits);
    }
References print_to_stream().
print_to_stream() [31/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, unsigned long val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 10114 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_integer_to_stream(stream, val, format, min_digits);
    }
References print_to_stream().
print_to_stream() [32/32]
void toml::v3::impl::print_to_stream (std::ostream & stream, unsigned short val, value_flags format = {}, size_t min_digits = 0) inline
Definition at line 10102 of file toml.h.
    {
        TOML_ANON_NAMESPACE::print_integer_to_stream(stream, val, format, min_digits);
    }
References print_to_stream().
print_to_stream_bookended()
template<typename T , typename U > void toml::v3::impl::print_to_stream_bookended (std::ostream & stream, const T & val, const U & bookend) inline
Definition at line 2256 of file toml.h.
    {
        print_to_stream(stream, bookend);
        print_to_stream(stream, val);
        print_to_stream(stream, bookend);
    }
References print_to_stream(), and print_to_stream_bookended().
to_sv() [1/5]
std::string_view toml::v3::impl::to_sv (bool val) inline noexcept
Definition at line 12678 of file toml.h.
    {
        using namespace std::string_view_literals;
        return val ? "true"sv : "false"sv;
    }
References to_sv().
to_sv() [2/5]
std::string_view toml::v3::impl::to_sv (const std::string & str) inline noexcept
Definition at line 12671 of file toml.h.
    {
        return std::string_view{ str };
    }
References to_sv().
to_sv() [3/5]
std::string_view toml::v3::impl::to_sv (const utf8_codepoint & cp) inline noexcept
Definition at line 12687 of file toml.h.
    {
        if (cp.value <= U'\x1F')
            return impl::control_char_escapes[cp.value];
        else if (cp.value == U'\x7F')
            return "\\u007F"sv;
        else
            return std::string_view{ cp.bytes, cp.count };
    }
References control_char_escapes, and to_sv().
to_sv() [4/5]
std::string_view toml::v3::impl::to_sv (const utf8_codepoint * cp) inline noexcept
Definition at line 12699 of file toml.h.
    {
        if (cp)
            return to_sv(*cp);
        return ""sv;
    }
References to_sv().
to_sv() [5/5]
std::string_view toml::v3::impl::to_sv (node_type val) inline noexcept
Definition at line 12664 of file toml.h.
    {
        return impl::node_type_friendly_names[impl::unwrap_enum(val)];
    }
References node_type_friendly_names, to_sv(), and unwrap_enum().
toml_formatter_count_inline_columns()
size_t toml::v3::impl::toml_formatter_count_inline_columns (const node & node, size_t line_wrap_cols) inline noexcept
Definition at line 16440 of file toml.h.
    {
        switch (node.type())
        {
            case node_type::table:
            {
                auto& tbl = *reinterpret_cast<const table*>(&node);
                if (tbl.empty())
                    return 2u;      // "{}"
                size_t weight = 3u; // "{ }"
                for (auto&& [k, v] : tbl)
                {
                    weight += k.length() + toml_formatter_count_inline_columns(v, line_wrap_cols) + 2u; // +  ", "
                    if (weight >= line_wrap_cols)
                        break;
                }
                return weight;
            }
            case node_type::array:
            {
                auto& arr = *reinterpret_cast<const array*>(&node);
                if (arr.empty())
                    return 2u;      // "[]"
                size_t weight = 3u; // "[ ]"
                for (auto& elem : arr)
                {
                    weight += toml_formatter_count_inline_columns(elem, line_wrap_cols) + 2u; // +  ", "
                    if (weight >= line_wrap_cols)
                        break;
                }
                return weight;
            }
            case node_type::string:
            {
                // todo: proper utf8 decoding?
                // todo: tab awareness?
                auto& str = (*reinterpret_cast<const value<std::string>*>(&node)).get();
                return str.length() + 2u; // + ""
            }
            case node_type::integer:
            {
                auto val = (*reinterpret_cast<const value<int64_t>*>(&node)).get();
                if (!val)
                    return 1u;
                size_t weight = {};
                if (val < 0)
                {
                    weight += 1u;
                    val *= -1;
                }
                return weight + static_cast<size_t>(log10(static_cast<double>(val))) + 1u;
            }
            case node_type::floating_point:
            {
                auto val = (*reinterpret_cast<const value<double>*>(&node)).get();
                if (val == 0.0)
                    return 3u;      // "0.0"
                size_t weight = 2u; // ".0"
                if (val < 0.0)
                {
                    weight += 1u;
                    val *= -1.0;
                }
                return weight + static_cast<size_t>(log10(val)) + 1u;
                break;
            }
            case node_type::boolean: return 5u;
            case node_type::date: [[fallthrough]];
            case node_type::time: return 10u;
            case node_type::date_time: return 30u;
            case node_type::none: TOML_UNREACHABLE;
            default: TOML_UNREACHABLE;
        }
        TOML_UNREACHABLE;
    }
References toml::v3::array, toml::v3::boolean, toml::v3::date, toml::v3::date_time, toml::v3::floating_point, toml::v3::integer, toml::v3::none, toml::v3::string, toml::v3::table, toml::v3::time, toml_formatter_count_inline_columns(), TOML_UNREACHABLE, and toml::v3::node::type().
toml_formatter_forces_multiline()
bool toml::v3::impl::toml_formatter_forces_multiline (const node & node, size_t line_wrap_cols, size_t starting_column_bias) inline noexcept
Definition at line 16523 of file toml.h.
    {
        return (toml_formatter_count_inline_columns(node, line_wrap_cols) + starting_column_bias) >= line_wrap_cols;
    }
References toml_formatter_count_inline_columns(), and toml_formatter_forces_multiline().
unwrap_enum()
template<typename T > constexpr std::underlying_type_t< T > toml::v3::impl::unwrap_enum (T val) inline constexpr noexcept
Definition at line 2072 of file toml.h.
    {
        return static_cast<std::underlying_type_t<T>>(val);
    }
References unwrap_enum().
utf8_reader() [1/4]
template<typename Char > toml::v3::impl::utf8_reader (std::basic_istream< Char > & , std::string &&) -> utf8_reader< std::basic_istream< Char > >
utf8_reader() [2/4]
template<typename Char > toml::v3::impl::utf8_reader (std::basic_istream< Char > & , std::string_view) -> utf8_reader< std::basic_istream< Char > >
utf8_reader() [3/4]
template<typename Char > toml::v3::impl::utf8_reader (std::basic_string_view< Char > , std::string &&) -> utf8_reader< std::basic_string_view< Char > >
utf8_reader() [4/4]
template<typename Char > toml::v3::impl::utf8_reader (std::basic_string_view< Char > , std::string_view) -> utf8_reader< std::basic_string_view< Char > >
Variable Documentation
all_integral
template<typename... T> constexpr bool toml::v3::impl::all_integral = (std::is_integral_v<T> && ...) inline constexpr
Definition at line 1487 of file toml.h.
can_partially_represent_native
template<typename T > constexpr bool toml::v3::impl::can_partially_represent_native = value_traits<T>::can_partially_represent_native inline constexpr
Definition at line 1881 of file toml.h.
can_represent_native
template<typename T > constexpr bool toml::v3::impl::can_represent_native = value_traits<T>::can_represent_native inline constexpr
Definition at line 1879 of file toml.h.
charconv_buffer_length
template<typename T > constexpr size_t toml::v3::impl::charconv_buffer_length = 0 inline constexpr
Definition at line 9846 of file toml.h.
charconv_buffer_length< double >
template<> constexpr size_t toml::v3::impl::charconv_buffer_length< double > = 64 inline constexpr
Definition at line 9876 of file toml.h.
charconv_buffer_length< float >
template<> constexpr size_t toml::v3::impl::charconv_buffer_length< float > = 64 inline constexpr
Definition at line 9873 of file toml.h.
charconv_buffer_length< int16_t >
template<> constexpr size_t toml::v3::impl::charconv_buffer_length< int16_t > = 6 inline constexpr
Definition at line 9852 of file toml.h.
charconv_buffer_length< int32_t >
template<> constexpr size_t toml::v3::impl::charconv_buffer_length< int32_t > = 11 inline constexpr
Definition at line 9855 of file toml.h.
charconv_buffer_length< int64_t >
template<> constexpr size_t toml::v3::impl::charconv_buffer_length< int64_t > = 20 inline constexpr
Definition at line 9858 of file toml.h.
charconv_buffer_length< int8_t >
template<> constexpr size_t toml::v3::impl::charconv_buffer_length< int8_t > = 4 inline constexpr
Definition at line 9849 of file toml.h.
charconv_buffer_length< uint16_t >
template<> constexpr size_t toml::v3::impl::charconv_buffer_length< uint16_t > = 5 inline constexpr
Definition at line 9864 of file toml.h.
charconv_buffer_length< uint32_t >
template<> constexpr size_t toml::v3::impl::charconv_buffer_length< uint32_t > = 10 inline constexpr
Definition at line 9867 of file toml.h.
charconv_buffer_length< uint64_t >
template<> constexpr size_t toml::v3::impl::charconv_buffer_length< uint64_t > = 20 inline constexpr
Definition at line 9870 of file toml.h.
charconv_buffer_length< uint8_t >
template<> constexpr size_t toml::v3::impl::charconv_buffer_length< uint8_t > = 3 inline constexpr
Definition at line 9861 of file toml.h.
control_char_escapes
constexpr std::string_view toml::v3::impl::control_char_escapes[] inline constexpr
Definition at line 1323 of file toml.h.
    {
        "\\u0000"sv,
        "\\u0001"sv,
        "\\u0002"sv,
        "\\u0003"sv,
        "\\u0004"sv,
        "\\u0005"sv,
        "\\u0006"sv,
        "\\u0007"sv,
        "\\b"sv,
        "\\t"sv,
        "\\n"sv,
        "\\u000B"sv,
        "\\f"sv,
        "\\r"sv,
        "\\u000E"sv,
        "\\u000F"sv,
        "\\u0010"sv,
        "\\u0011"sv,
        "\\u0012"sv,
        "\\u0013"sv,
        "\\u0014"sv,
        "\\u0015"sv,
        "\\u0016"sv,
        "\\u0017"sv,
        "\\u0018"sv,
        "\\u0019"sv,
        "\\u001A"sv,
        "\\u001B"sv,
        "\\u001C"sv,
        "\\u001D"sv,
        "\\u001E"sv,
        "\\u001F"sv,
    };
dependent_false
template<typename T > constexpr bool toml::v3::impl::dependent_false = false inline constexpr
Definition at line 1561 of file toml.h.
first_is_same
template<typename T , typename... U> constexpr bool toml::v3::impl::first_is_same = false inline constexpr
Definition at line 1564 of file toml.h.
first_is_same< T, T, U... >
template<typename T , typename... U> constexpr bool toml::v3::impl::first_is_same< T, T, U... > = true inline constexpr
Definition at line 1566 of file toml.h.
is_constructible_or_convertible
template<typename T , typename ConvertFrom > constexpr bool toml::v3::impl::is_constructible_or_convertible inline constexpr
Initial value:
= std::is_constructible_v<T, ConvertFrom>
                                                         || std::is_convertible_v<ConvertFrom, T>
Definition at line 1999 of file toml.h.
is_cvref
template<typename T > constexpr bool toml::v3::impl::is_cvref = std::is_reference_v<T> || std::is_const_v<T> || std::is_volatile_v<T> inline constexpr
Definition at line 1490 of file toml.h.
is_losslessly_convertible_to_native
template<typename T > constexpr bool toml::v3::impl::is_losslessly_convertible_to_native = value_traits<T>::is_losslessly_convertible_to_native inline constexpr
Definition at line 1883 of file toml.h.
is_native
template<typename T > constexpr bool toml::v3::impl::is_native = value_traits<T>::is_native inline constexpr
Definition at line 1877 of file toml.h.
is_natively_one_of
template<typename T , typename... U> constexpr bool toml::v3::impl::is_natively_one_of = is_one_of<native_type_of<T>, U...> inline constexpr
Definition at line 1885 of file toml.h.
is_one_of
template<typename T , typename... U> constexpr bool toml::v3::impl::is_one_of = (false || ... || std::is_same_v<T, U>) inline constexpr
Definition at line 1484 of file toml.h.
is_wide_string
template<typename T > constexpr bool toml::v3::impl::is_wide_string inline constexpr
Initial value:
=
        is_one_of<std::decay_t<T>, const wchar_t*, wchar_t*, std::wstring_view, std::wstring>
Definition at line 1493 of file toml.h.
node_type_friendly_names
constexpr std::string_view toml::v3::impl::node_type_friendly_names[] inline constexpr
Initial value:
=
    {
        "none"sv,
        "table"sv,
        "array"sv,
        "string"sv,
        "integer"sv,
        "floating-point"sv,
        "boolean"sv,
        "date"sv,
        "time"sv,
        "date-time"sv
    }
Definition at line 1359 of file toml.h.
    {
        "none"sv,
        "table"sv,
        "array"sv,
        "string"sv,
        "integer"sv,
        "floating-point"sv,
        "boolean"sv,
        "date"sv,
        "time"sv,
        "date-time"sv
    };
node_type_of
template<typename T > constexpr node_type toml::v3::impl::node_type_of = node_type_getter<unwrap_node<remove_cvref<T>>>::value inline constexpr
Definition at line 1996 of file toml.h.
utf8_byte_order_mark
constexpr auto toml::v3::impl::utf8_byte_order_mark = "\xEF\xBB\xBF"sv inline constexpr
Definition at line 12053 of file toml.h.
value_retrieval_is_nothrow
template<typename T > constexpr bool toml::v3::impl::value_retrieval_is_nothrow inline constexpr
Initial value:
= !std::is_same_v<remove_cvref<T>, std::string>
                                                    && !is_wide_string<T>
Definition at line 1497 of file toml.h.