Techstorm-rivalry: C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/rgui/examples/portable_window/portable_window.c File Reference
portable_window.c File Reference
#include "raylib.h"
#include "../../src/raygui.h"
Macros
#define RAYGUI_IMPLEMENTATION
Functions
int main ()
Macro Definition Documentation
RAYGUI_IMPLEMENTATION
#define RAYGUI_IMPLEMENTATION
Definition at line 20 of file portable_window.c.
Function Documentation
main()
int main (void)
Definition at line 26 of file portable_window.c.
{
    // Initialization
    //---------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 600;
    SetConfigFlags(FLAG_WINDOW_UNDECORATED);
    InitWindow(screenWidth, screenHeight, "raygui - portable window");
    // General variables
    Vector2 mousePosition = { 0 };
    Vector2 windowPosition = { 500, 200 };
    Vector2 panOffset = mousePosition;
    bool dragWindow = false;
    SetWindowPosition(windowPosition.x, windowPosition.y);
    bool exitWindow = false;
    SetTargetFPS(60);
    //--------------------------------------------------------------------------------------
    // Main game loop
    while (!exitWindow && !WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        mousePosition = GetMousePosition();
        if (IsMouseButtonPressed(MOUSE_LEFT_BUTTON) && !dragWindow)
        {
            if (CheckCollisionPointRec(mousePosition, (Rectangle){ 0, 0, screenWidth, 20 }))
            {
                dragWindow = true;
                panOffset = mousePosition;
            }
        }
        if (dragWindow)
        {
            windowPosition.x += (mousePosition.x - panOffset.x);
            windowPosition.y += (mousePosition.y - panOffset.y);
            SetWindowPosition((int)windowPosition.x, (int)windowPosition.y);
            if (IsMouseButtonReleased(MOUSE_LEFT_BUTTON)) dragWindow = false;
        }
        //----------------------------------------------------------------------------------
        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();
            ClearBackground(RAYWHITE);
            exitWindow = GuiWindowBox((Rectangle){ 0, 0, screenWidth, screenHeight }, "#198# PORTABLE WINDOW");
            DrawText(TextFormat("Mouse Position: [ %.0f, %.0f ]", mousePosition.x, mousePosition.y), 10, 40, 10, DARKGRAY);
            DrawText(TextFormat("Window Position: [ %.0f, %.0f ]", windowPosition.x, windowPosition.y), 10, 60, 10, DARKGRAY);
        EndDrawing();
        //----------------------------------------------------------------------------------
    }
    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------
    return 0;
}
References BeginDrawing(), CheckCollisionPointRec(), ClearBackground(), CloseWindow(), DARKGRAY, DrawText(), EndDrawing(), FLAG_WINDOW_UNDECORATED, GetMousePosition(), GuiWindowBox(), InitWindow(), IsMouseButtonPressed(), IsMouseButtonReleased(), MOUSE_LEFT_BUTTON, RAYWHITE, SetConfigFlags(), SetTargetFPS(), SetWindowPosition(), TextFormat(), WindowShouldClose(), Vector2::x, and Vector2::y.