Techstorm-rivalry: C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/rgui/examples/scroll_panel/scroll_panel.c File Reference
scroll_panel.c File Reference
#include "raylib.h"
#include "../../src/raygui.h"
Macros
#define RAYGUI_IMPLEMENTATION
Functions
int main ()
Macro Definition Documentation
RAYGUI_IMPLEMENTATION
#define RAYGUI_IMPLEMENTATION
Definition at line 26 of file scroll_panel.c.
Function Documentation
main()
int main (void)
Definition at line 35 of file scroll_panel.c.
{
    // Initialization
    //---------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;
    InitWindow(screenWidth, screenHeight, "raygui - GuiScrollPanel()");
    Rectangle panelRec = { 20, 40, 200, 150 };
    Rectangle panelContentRec = {0, 0, 340, 340 };
    Rectangle panelView = { 0 };
    Vector2 panelScroll = { 99, -20 };
    bool showContentArea = true;
    SetTargetFPS(60);
    //---------------------------------------------------------------------------------------
    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        // TODO: Implement required update logic
        //----------------------------------------------------------------------------------
        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawText(TextFormat("[%f, %f]", panelScroll.x, panelScroll.y), 4, 4, 20, RED);
            GuiScrollPanel(panelRec, NULL, panelContentRec, &panelScroll, &panelView);
            BeginScissorMode(panelView.x, panelView.y, panelView.width, panelView.height);
                GuiGrid((Rectangle){panelRec.x + panelScroll.x, panelRec.y + panelScroll.y, panelContentRec.width, panelContentRec.height}, NULL, 16, 3, NULL);
            EndScissorMode();
            if (showContentArea) DrawRectangle(panelRec.x + panelScroll.x, panelRec.y + panelScroll.y, panelContentRec.width, panelContentRec.height, Fade(RED, 0.1));
            DrawStyleEditControls();
            GuiCheckBox((Rectangle){ 565, 80, 20, 20 }, "SHOW CONTENT AREA", &showContentArea);
            GuiSliderBar((Rectangle){ 590, 385, 145, 15}, "WIDTH", TextFormat("%i", (int)panelContentRec.width), &panelContentRec.width, 1, 600);
            GuiSliderBar((Rectangle){ 590, 410, 145, 15 }, "HEIGHT", TextFormat("%i", (int)panelContentRec.height), &panelContentRec.height, 1, 400);
        EndDrawing();
        //----------------------------------------------------------------------------------
    }
    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------
    return 0;
}
References BeginDrawing(), BeginScissorMode(), ClearBackground(), CloseWindow(), DrawRectangle(), DrawText(), EndDrawing(), EndScissorMode(), Fade(), GuiCheckBox(), GuiGrid(), GuiScrollPanel(), GuiSliderBar(), Rectangle::height, InitWindow(), RAYWHITE, RED, SetTargetFPS(), TextFormat(), Rectangle::width, WindowShouldClose(), Vector2::x, Rectangle::x, Vector2::y, and Rectangle::y.