Techstorm-rivalry: C:/Dev/TechStorm-Rivalry/TechStorm-Rivalry/rgui/examples/style_selector/style_selector.c File Reference
style_selector.c File Reference
#include "raylib.h"
#include "../../src/raygui.h"
#include "../styles/style_cyber.h"
#include "../styles/style_jungle.h"
#include "../styles/style_lavanda.h"
#include "../styles/style_dark.h"
#include "../styles/style_bluish.h"
#include "../styles/style_terminal.h"
#include <string.h>
Macros
#define RAYGUI_IMPLEMENTATION
Functions
int main ()
Macro Definition Documentation
RAYGUI_IMPLEMENTATION
#define RAYGUI_IMPLEMENTATION
Definition at line 20 of file style_selector.c.
Function Documentation
main()
int main (void)
Definition at line 38 of file style_selector.c.
{
    // Initialization
    //---------------------------------------------------------------------------------------
    const int screenWidth = 690;
    const int screenHeight = 560;
    InitWindow(screenWidth, screenHeight, "raygui - controls test suite");
    SetExitKey(0);
    // Custom GUI font loading
    //Font font = LoadFontEx("fonts/custom_font.ttf", 12, 0, 0);
    //GuiSetFont(font);
    bool exitWindow = false;
    bool showMessageBox = false;
    char textInput[256] = { 0 };
    bool showTextInputBox = false;
    char textInputFileName[256] = { 0 };
    // Load default style
    GuiLoadStyleBluish();
    int visualStyleActive = 4;
    int prevVisualStyleActive = 4;
    SetTargetFPS(60);
    //--------------------------------------------------------------------------------------
    // Main game loop
    while (!exitWindow)    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        exitWindow = WindowShouldClose();
        if (IsKeyPressed(KEY_ESCAPE)) showMessageBox = !showMessageBox;
        if (IsKeyDown(KEY_LEFT_CONTROL) && IsKeyPressed(KEY_S)) showTextInputBox = true;
        if (IsFileDropped())
        {
            FilePathList droppedFiles = LoadDroppedFiles();
            if ((droppedFiles.count > 0) && IsFileExtension(droppedFiles.paths[0], ".rgs")) GuiLoadStyle(droppedFiles.paths[0]);
            UnloadDroppedFiles(droppedFiles);    // Clear internal buffers
        }
        if (visualStyleActive != prevVisualStyleActive)
        {
            GuiLoadStyleDefault();
            switch (visualStyleActive)
            {
                case 0: break;      // Default style
                case 1: GuiLoadStyleJungle(); break;
                case 2: GuiLoadStyleLavanda(); break;
                case 3: GuiLoadStyleDark(); break;
                case 4: GuiLoadStyleBluish(); break;
                case 5: GuiLoadStyleCyber(); break;
                case 6: GuiLoadStyleTerminal(); break;
                default: break;
            }
            GuiSetStyle(LABEL, TEXT_ALIGNMENT, TEXT_ALIGN_LEFT);
            prevVisualStyleActive = visualStyleActive;
        }
        //----------------------------------------------------------------------------------
        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();
            ClearBackground(GetColor(GuiGetStyle(DEFAULT, BACKGROUND_COLOR)));
            // Visuals options
            GuiLabel((Rectangle){ 10, 10, 60, 24 }, "Style:");
            GuiComboBox((Rectangle){ 60,10, 120, 24 }, "default;Jungle;Lavanda;Dark;Bluish;Cyber;Terminal", &visualStyleActive);
            GuiSetIconScale(2);
            GuiSetStyle(BUTTON, TEXT_ALIGNMENT, TEXT_ALIGN_RIGHT);
            GuiButton((Rectangle){ 25, 255, 300, 30 }, GuiIconText(ICON_FILE_SAVE, "Save File"));
            GuiSetStyle(BUTTON, TEXT_ALIGNMENT, TEXT_ALIGN_CENTER);
            //----------------------------------------------------------------------------------
        EndDrawing();
        //----------------------------------------------------------------------------------
    }
    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------
    return 0;
}
References BACKGROUND_COLOR, BeginDrawing(), BUTTON, ClearBackground(), CloseWindow(), FilePathList::count, DEFAULT, EndDrawing(), GetColor(), GuiButton(), GuiComboBox(), GuiGetStyle(), GuiIconText(), GuiLabel(), GuiLoadStyle(), GuiLoadStyleDefault(), GuiSetIconScale(), GuiSetStyle(), ICON_FILE_SAVE, InitWindow(), IsFileDropped(), IsFileExtension(), IsKeyDown(), IsKeyPressed(), KEY_ESCAPE, KEY_LEFT_CONTROL, KEY_S, LABEL, LoadDroppedFiles(), FilePathList::paths, SetExitKey(), SetTargetFPS(), TEXT_ALIGN_CENTER, TEXT_ALIGN_LEFT, TEXT_ALIGN_RIGHT, TEXT_ALIGNMENT, UnloadDroppedFiles(), and WindowShouldClose().