var topics =
[
    [ "Context reference", "group__context.html", "group__context" ],
    [ "Vulkan support reference", "group__vulkan.html", "group__vulkan" ],
    [ "Initialization, version and error reference", "group__init.html", "group__init" ],
    [ "Input reference", "group__input.html", "group__input" ],
    [ "Monitor reference", "group__monitor.html", "group__monitor" ],
    [ "Window reference", "group__window.html", "group__window" ],
    [ "Native access", "group__native.html", null ],
    [ "Core features", "group__core.html", "group__core" ],
    [ "Stable extensions", "group__ext.html", "group__ext" ],
    [ "Recommended extensions", "group__gtc.html", "group__gtc" ],
    [ "Experimental extensions", "group__gtx.html", "group__gtx" ],
    [ "Algorithms", "group__algorithms.html", "group__algorithms" ],
    [ "Atomics", "group__atomics.html", null ],
    [ "Exceptions", "group__exceptions.html", "group__exceptions" ],
    [ "Locales", "group__locales.html", "group__locales" ],
    [ "Random Number Generation", "group__random.html", "group__random" ],
    [ "Regular Expressions", "group__regex.html", "group__regex" ],
    [ "Mathematical Special Functions", "group__mathsf.html", null ],
    [ "Iterators", "group__iterators.html", null ],
    [ "Iterator Tags", "group__iterator__tags.html", null ],
    [ "Strings", "group__strings.html", "group__strings" ],
    [ "Policy-Based Data Structures", "group__pbds.html", "group__pbds" ],
    [ "Library Configuration", "group__configuration.html", "group__configuration" ],
    [ "Ext_matrix_uint2x3", "group__ext__matrix__uint2x3.html", "group__ext__matrix__uint2x3" ],
    [ "Ext_matrix_uint3x2", "group__ext__matrix__uint3x2.html", "group__ext__matrix__uint3x2" ],
    [ "Numeric_arrays", "group__numeric__arrays.html", null ],
    [ "Utilities", "group__utilities.html", "group__utilities" ],
    [ "Pointer_abstractions", "group__pointer__abstractions.html", null ],
    [ "Memory", "group__memory.html", "group__memory" ],
    [ "Random Number Generation", "group__tr1__random.html", "group__tr1__random" ]
];