[Debug]
logverbatim = false
shadersEnabled = true

[General]
useMultiThreading = false 
useMSAA = true
maxShaders = "10"
objectDespawnDistance = "1000"
useApplicationBuffer = false

[World]
woldSize = "100"


[Objects]
blockSize = "1.0"


