[Window]
isFullScreen = false
windowWidth = "800"
windowHeight = "600"
lockTo60FPS = false
lockFPS = false

[Game]
skipMenu = false

[Sound]
enableMusic = true
masterVolume = "100"


[Misc]
debugMode = true