<?xml version="1.0" encoding="utf-8"?>
<file>
	<types>
		<!--Textures-->
		<type ext=".png">true</type>
		<type ext=".hdr">false</type>
		<type ext=".jpg">true</type>
		<type ext=".jpeg">true</type>
		<!--Config-->
		<type ext=".toml">true</type>
		<type ext=".tsr">true</type>
		<type ext=".xml">false</type>
		<!--Models-->
		<type ext=".glb">true</type>
		<!--Audio-->
		<type ext=".ogg">true</type>
		<type ext=".mp3">true</type>
		<type ext=".wav">true</type>
	</types>
</file>
